### ISSUE TITLE
Disk Manipulator doesn't update model properly

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage#1673]

**Comment by ineternet** [comment]
Can we get a description?

**Comment by raoulvdberge** [comment]
If you put in disks in the disk manipulator, or move them, sometimes, the disks on the rendered block don't update.

**Comment by Fungie2134** [comment]
I have already experienced that, primarily on servers, and happens more often when more disks manipulator / drives in the same area (loaded).
