### ISSUE TITLE
Scrolling in processing matrix yields unexpected behaviour

### ISSUE THREAD

**Issue by Cydhra** [refinedmods/refinedstorage#1903]
#### What happens:
When scrolling down while hovering an item in the Processing matrix of the pattern grid, the item quanitity is reduced (when above one) but at the same time the item list is scrolled down and, if present, items of the same type in the inventory are partially filled into the currently hold stack (the stack on your mouse). When scrolling up while hovering an item, the quantity is NOT increased. The view nevertheless scrolls up. Items currently held with the mouse are filled back into the inventory if there is a stack of the same item type. 

#### What you expected to happen:
I would expect only one of those behaviours but consistently. I think it would be most convenient and the best experience, if the stack size of the ghost stack would decrease or increase, the item list would not scroll up and down, and especially no items would be transferred between inventory and mouse.

Of course the item list should still scroll, if no item is hovered and items between grid and inventory (or mouse?) should still be moveable when explicitily hovered.

#### Steps to reproduce:
1. Place a stack of more than one item in Processing matrix of the pattern grid GUI. Then hover the stack and scroll down. 
2. Additionally the original stack (that was copied to the ghost stack in the Processing matrix) can be placed in the inventory to see the last part of the bug review.

#### Version (make sure you are on the latest version before reporting):
Forge: 14.23.4.2739
Minecraft: 1.12.2
RS: 1.6

**Comment by raoulvdberge** [comment]
are you using some item scroller mod that changes the quantity when scrolling?

**Comment by Cydhra** [comment]
Uh yes, I did not think about that. I am using Mouse Tweaks. Gonna have to check without it.

**Comment by raoulvdberge** [comment]
Any update on this @Cydhra ?

**Comment by Cydhra** [comment]
Jup. Turns out, it is totally a crossmod issue with Mouse Tweaks. Without MT, nothing happens (except the scrolling in the grid) Would be a could feature though, if you could adjust the stack size in the processing matrix this way
