### ISSUE TITLE
Baubles for wireless items

### ISSUE THREAD

**Issue by FallenRecruit** [refinedmods/refinedstorage#1919]
#### Feature description: 
I have recently been using mod {wireless crafting terminal 2} with AE2 and really like the fact that the terminals are a bauble and that i can open it on a keybind i.e. C

#### What you would like to happen:
I would like it if the wireless grids could go into the bauble slots and be able to open them upon pressing a key

**Comment by raoulvdberge** [comment]
No

**Comment by FallenRecruit** [comment]
any reason as to why?

**Comment by raoulvdberge** [comment]
Let's do this anyway!

**Comment by raoulvdberge** [comment]
We might want Curios support too.

**Comment by raoulvdberge** [comment]
Added in 1.9.14/1.9.15
