### ISSUE TITLE
Bulk crafting blocks lags client

### ISSUE THREAD

**Issue by newlogan** [refinedmods/refinedstorage#2104]
#### Issue description:
When bulk crafting blocks from ingot/gems, the game stutters and lags. Issue appears to exist in RS but not AE2. Has remarkable resemblance to #151.

#### What happens:
Game excessively lags when crafting blocks of material

#### What you expected to happen:
No stuttering, fast item movement to inventory

#### Steps to reproduce:
1. Fill storage with any number of ingots/gems, larger amounts cause greater lag (>10k)
2. Use crafting grid to make blocks of said ingots/gems, shift clicking to receive 64 stacks of blocks

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.10

Does this issue occur on a server?

Yes

[crafting.zip](https://github.com/raoulvdberge/refinedstorage/files/2612664/crafting.zip)

**Comment by EGGS0RZIST** [comment]
Bulk crafting actually caused all of my items to not get shown anymore.
Had to drag them from the disks to new ones with my brothers account.

**Comment by newlogan** [comment]
Had same issue @EGGS0RZIST. Restarting game fixed it.

**Comment by tth05** [comment]
Can confirm this issue. From looking at the code, it seems like RS crafts the block/item 64 times in a while loop, instead of crafting 64 at once. I'm guessing this really slows things down here.

**Comment by raoulvdberge** [comment]
Fixed with the new autocrafting system

**Comment by raoulvdberge** [comment]
This has been fixed for the next version. Thank you @Darkere
