### ISSUE TITLE
FPS drop JEI/RS

### ISSUE THREAD

**Issue by mtdudek** [refinedmods/refinedstorage#2129]
#### Issue description and What happens:
When searching for RS in JEI FPS drops form over 70 to low 20s.
Same issue happened in Applied Energistics 2, caching covers
helped.

#### What you expected to happen:
FPS shouldn't take such hit.

#### Steps to reproduce:
1. Open inventory 
2. Search in JEI for RS cover
3. See how much FPS drop

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.11
- JEI: 4.14.0

Does this issue occur on a server? Don't know

**Comment by Tahakk** [comment]
you can hide covers via JEI or in RS config and see if it helps

**Comment by ospis12** [comment]
When they are not displayed, just different page, FPS is not affected.
looks like render is not optimized.
