### ISSUE TITLE
Performance issue with Crafting Monitor

### ISSUE THREAD

**Issue by Sir-Will** [refinedmods/refinedstorage#2132]
Not 100% sure what exactly triggers this as this doesn't always happen but it seems to be a combination of a large "ingredient" list and fast changing of stored and crafting values.

refinedstorage-1.6.11
![](https://i.imgur.com/REdvWks.jpg)

**Comment by tenten8401** [comment]
I've been seeing this too when crafting things with huge ingredient lists, any system with the crafting monitor just locks up the entire server, and without it it's like 5 TPS

**Comment by resinate** [comment]
from what ive seen this is bug that cant be fixed, its been around since 1.7.10 days.

**Comment by FluffyDiscord** [comment]
to be honest, I get about 1 tick per second when I want to crafting something big and also tps starts to drop like mad with full discs once you hit about 20mil of different items in your storage, it starts to lose its purpose as one big storage unit and you have to make more, smaller ones and far away from each other, something needs to be done
