### ISSUE TITLE
Exporter crafting task gets stuck

### ISSUE THREAD

**Issue by notcake** [refinedmods/refinedstorage#2155]
#### Issue description:

I have \*two* exporters set to export Diamond Chisels, with the Crafting Upgrade. After enough time, the crafting task for a Diamond Chisel will jam, with either a diamond, stick or oak wood planks missing in the Crafting Monitor. Manually crafting the missing item unjams the crafting task.

#### What happens:
Exporter crafting gets stuck

#### What you expected to happen:
Exporter crafting should not get stuck

#### Steps to reproduce:
1. Install Chisel and Extra Utilities 2 (useful for demonstrating the bug)
2. Set up an RS network with lots of oak wood, diamond blocks and nothing else
3. Set up the following crafting recipes:
* 1 Oak Wood -> 4 Oak Wood Planks
* 2 Oak Wood Planks -> 4 Sticks
* 1 Diamond Block -> 9 Diamonds
* 1 Stick and 1 Diamond -> 1 Diamond chisel
4. Set up two Exporters for Diamond chisels, each with a Crafting Upgrade
5. Point the Exporters at a Trash Can or something to absorb the items
6. Wait long enough

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768
- Refined Storage: 1.6.11

Does this issue occur on a server? yes

**Comment by notcake** [comment]
It looks like `CraftingTask.calculate()` doesn't lock or reserve items in any way, so if two crafting tasks which used the same ingredients were to start on the exact same tick, they may both decide not to run crafting sub-tasks. One of them may then get stuck when trying to extract ingredients which the other task took that aren't there anymore.

**Comment by raoulvdberge** [comment]
this has been fixed for the next version.
