### ISSUE TITLE
Sync items bug on start system

### ISSUE THREAD

**Issue by yaroslav4167** [refinedmods/refinedstorage#2166]
#### Steps to reproduce:
Reproduce: [link](https://youtu.be/tRDQV0eqnY0)
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2805
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no] - Yes

**Comment by Darkere** [comment]
Already fixed.
