### ISSUE TITLE
Crafter Stays locked after canceling crafting task.

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#2170]
#### Issue description: 
When using the pulse locking feature and the craft gets canceled via the crafting monitor the crafter stays locked for future recipes.

#### What happens:
Crafter still locked after new craft.

#### What you expected to happen: 
Crafter unlocks when crafting recipe is canceled.

#### Steps to reproduce:
1.Make a processing recipe.
2.Set Crafter to pulse mode
3.Start recipe and cancel before finishing
4. Start another recipe using the same crafter.

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12
- Forge:2795
- Refined Storage:1.6.12

Does this issue occur on a server? [yes/no]
yes

**Comment by raoulvdberge** [comment]
If you cancel a request, wouldn't the in-progress items still be transferred to your detection system, which would trigger the pulse?

**Comment by Darkere** [comment]
If everything was working correctly yes. However usually when I'm canceling a task it's because something went wrong. In my case, the detection mechanism was accidentally set to the wrong crafter causing a lot of confusion.
Canceling a task resetting everything seems more intuitive to me.
