### ISSUE TITLE
Detector state is incorrect after reloading world

### ISSUE THREAD

**Issue by davidthehat** [refinedmods/refinedstorage#2179]
#### Issue description:
When I reload my world, detectors turn on when they should be off.  This is fixed by rebooting the RS system through the controller.  Also note that the items in question are stored in external storage, although I haven't tested if this issue exists if the items are stored on drives.
#### What happens:
Detector incorrectly turns on when I reload the world.
#### What you expected to happen:
Detector should always reflect the items in the system, even through a reload
#### Steps to reproduce:
1. Create RS system
2. Place detector
3. Configure detector to emit signal when under an amount
4. Place more than that amount in system (detector should be off)
5. Reload the world
6. Detector should be on

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2 (Stoneblock)
- Forge: 14.23.5.2772
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]
Only tested on singleplayer.

**Comment by raoulvdberge** [comment]
I can't reproduce this
