### ISSUE TITLE
Portable Grid block doesn't consume energy

### ISSUE THREAD

**Issue by Encharrion** [refinedmods/refinedstorage#2182]
#### Issue description:
When a Portable Grid is placed in the world, and then used, opening the grid and moving items in or out does not consume energy from the grid.
#### What happens:
As above
#### What you expected to happen:
Using the Portable Grid when placed in the world would consume energy from the grid in the same way that using it as an item does.
#### Steps to reproduce:
1. Place Portable Grid
2. Right click to open, or take items in or out.
3. Portable Grid contains the same amount of energy as before.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2811
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]
Yes

**Comment by Darkere** [comment]
already fixed.
