### ISSUE TITLE
Portable Grid loses Storage Disk, howto

### ISSUE THREAD

**Issue by NoX-programer** [refinedmods/refinedstorage#2190]
#### Issue description:
Few clicks leads to Storage Disk lost with it's content.
#### What happens:
Player can manage to loose Storage Disk and all his stuff in it.
#### What you expected to happen:
It must not happen! ;-)
#### Steps to reproduce:
1. Have a Storage Disk in Portable Grid maybe with important stuff.
2. Have a fully stuffed own inventory with no sigle empty slot.
3. Open Portable Grid (no matter how - on the ground or in hands) interface.
4. (with crazy face!) Shift-click the Storage Disk there.
5. Aaaand it's gone! Ok, seriously: Storage Disk disappeared, all it's contents lost.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2781
- Refined Storage: 1.6.12

Does this issue occur on a server?  yes

#### If a (crash)log is relevant for this issue, link it here:
No crashlog (not a crash), nor error line in all logs.

**Comment by Darkere** [comment]
Does this happen consistently for you? I tried and could not make it happen. If it does you possibly have a mod incompatibility or maybe some storage permission issues (onedrive is a common one). 

Or it only happened one time then you probably have an entirely different issue at hand.

**Comment by NoX-programer** [comment]
It happen on custom modpack for another player and confirmed by me. I was taken from newly/fresh storage disk and portable grid; another player crafted this things without any access tweaks. Ok, I'll try to reproduce this with minimum mods...

**Comment by NoX-programer** [comment]
Checked again in singleplayer with only Refined Storage and deleted/fresh config. **It happens.** Are you sure you checked generic item storage disk and portable grid exactly?

**Comment by Darkere** [comment]
Do you mean like this? https://gfycat.com/CelebratedHarmlessJenny

**Comment by NoX-programer** [comment]
Yes, almost. But you ignored step#2 - before you shift+click storage disk in the portable grid, fill your inventory so have no free space. I know - stupid move, but player of my server was managed to make it so lost everything >_<. He was so gladly it was backup :-)

**Comment by Darkere** [comment]
Rereading your issue and things suddenly make sense! 

Shift-clicking the storage disk from a portable grid into a full player inventory deletes it instead of blocking the action.

Yes, obviously a problem thank you for the report.

Video: https://gfycat.com/BleakDampCatfish
