### ISSUE TITLE
Resource Packs breaks textures

### ISSUE THREAD

**Issue by NewAgeLink** [refinedmods/refinedstorage#2205]
Issue description:
I was testing out some stuff in creative mode and noticed that certain texture break when enabling a resource pack, as far as i know through my testing this only happens when enabling a resource pack in an open world, if i enable a pack before entering a world then it seems fine

Version:
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.14

**Comment by Darkere** [comment]
![image](https://user-images.githubusercontent.com/4283717/58249987-93b5ac00-7d60-11e9-8962-9990d6955f97.png)
Restarting the game will fix the issue.

**Comment by Jeppeskovsgaard** [comment]
I can confirm that restarting the game fixes the rendering issue.

**Comment by Darkere** [comment]
I believe this is still an issue. At least I remember some fairly recent complaints about this.

**Comment by raoulvdberge** [comment]
On 1.16?

**Comment by Darkere** [comment]
Yeah. Gonna do a quick test in a bit.

**Comment by Darkere** [comment]
Yep sure still a thing 
![image](https://user-images.githubusercontent.com/4283717/96304709-dd113600-0ffc-11eb-85be-e97081b61a5b.png)

**Comment by iTaeyeonKim** [comment]
On 1.12.2 too. Not sure if you still supporting that version, but it would be nice, since 95% mods stills last version is 1.12.2

**Comment by raoulvdberge** [comment]
Fixed for v1.9.10
