### ISSUE TITLE
Crash when scrolling mouse wheel while Mouse Tweaks is installed

### ISSUE THREAD

**Issue by ghost** [refinedmods/refinedstorage#2247]
#### Issue description:
The game crashes when you're interacting with an RS block that holds a stack of items, and you scroll the mouse wheel over that item stack (should increase or decrease the amount of items in that slot, Mouse Tweaks feature). I tested this on Pattern Grid processing mode, and Interface's Export Bus. The mechanic works fine with vanilla blocks like Crafting Table and Chest, so I presume this is an RS issue.

#### What happens:
The game freezes for a couple of seconds, then goes into a loading screen that says "Shutting down internal server..." and exits to desktop.

#### What you expected to happen:
The amount of items in the slot your mouse is over to increase or decrease.

#### Steps to reproduce:
1. Place down a Controller and a Pattern Grid
2. Tick the processing box on
3. Put some items in the input grid
4. Hover your mouse over the items and scroll up or down with your mouse. 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838 (latest available as of writing this), 2825 (used in All The Mods 3: Remix 1.3.0) and 2768 (recommended by MultiMC)
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no]
I only tried in single player.

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/HN8tCQfS this log is from a little while ago when I first encountered it while playing ATM3: Remix.

https://pastebin.com/UfCF8qsv this is while testing to confirm on a fresh instance with only RS, MT and JEI installed just a moment ago.

**Comment by thewalkerberry** [comment]
I can confirm this is happening, same atm remix version et all.

**Comment by raoulvdberge** [comment]
Probably related to #1903 ?

**Comment by raoulvdberge** [comment]
Can no longer reproduce on 1.16.x, closing.
