### ISSUE TITLE
Autocrafting "Keep items in stock" loop

### ISSUE THREAD

**Issue by derdotte** [refinedmods/refinedstorage#2270]
#### Issue description:
When you want to keep items in stock by autocrafting it (for further autocrafting) automatically through interface or exporter and use a crafting upgrade, it becomes a loop of export and import, never actually crafting it. Even After setting a higher priority on external storage block.
#### What happens:
Auto loop of insert and extract.
#### What you expected to happen:
To prioritize filling up the inventory through crafting and not taking items from the system. If i use an exporter/interface, i expect it to only handle autocrafting and not also export that item from already existing refined storage source to the container.
#### Steps to reproduce:
1. Make a simple autocrafting setup of any item
2. Get any type of chest, put an exporter on it, put a crafting card inside, put item inside
3. have said item already once in your RS system
4. Observe how it never autocrafts said item but only keep exporting and importing

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2836 (Base modpack is enigmatica 2 but self-modded to include refined storage)
- Refined Storage: 1.6.14

Does this issue occur on a server? [yes/no]
yes, singleplayer too

------

IMO, there should be an option to never export from your already existing system once you use a crafting upgrade in either exporter or interface.
This behavior completely defeats the purpose of "keep items in stock".

**Comment by Darkere** [comment]
Instead of an exporter use an interface with crafting card and external storage.

Or check out the addon mod Requestify.

**Comment by derdotte** [comment]
> Instead of an exporter use an interface with crafting card and external storage.
Thats also something i tested, very much the same behavior. It does not craft and auto loops if i use the RS interface together with a crafting upgrade in it. Telling it to export, in this case, glass to an external storage connected by an extern storage connector. While the external storage has high priority and the interface doesnt.

> Or check out the addon mod Requestify.
I check that one out too but i would rather have this also fixed in the base mod as this really goes against the idea (and wiki page) of "Keep items in stock".

**Comment by Darkere** [comment]
You need an Interface with crafting card. In that interface, you specify the items you want to keep in stock.
Then you add an External Storage onto that interface.

**Comment by derdotte** [comment]
That only gives access to a single stack or max 9 stacks, not even enough to autocraft anything in an expert modpack like enigmatica 2. Sure it wont do the input loop because of that but also isnt any practical.
Issue persists.

**Comment by derdotte** [comment]
Why would this be invalid? After all this should be basic functionality when using a crafting card.

**Comment by raoulvdberge** [comment]
Because you are using the mod wrong. Please follow Darkere's instructions.

**Comment by raoulvdberge** [comment]
Did you connect a importer (or external storage) AND exporter to the chest in question?

**Comment by derdotte** [comment]
I used an exporter to export an item with crafting functionality enabled. It crafted the item if there wasnt already one in the system. If an item existed already it would just export it. If i want to keep items in stock using an external storage block on the chest it would just keep exporting into said chest. As the exporter does not have the functionality (with crafting card) to already ignore content in your RS system.

**Comment by derdotte** [comment]
Considering that this mod is used in modpacks where you have recipes that usually take forever but need lots of, its a very limiting intended feature. In fact its so limiting that somebody made an addon mod (requestify) to fix this.
AE2 has this functionality when using an export bus and a crafting card, i am not a fan of AE2 but thats one of the things i like there.

**Comment by aMannus** [comment]
Would it be possible at all to make a toggable button on export busses with a crafting card where you can toggle between "craft only" or "export existing items and craft if neccesary"? This would fix all these issues.

This is how the export bus in AE2 works, and I'm kinda similar to derdotte, it's one of the things I really miss in RS compared to AE2, while I do prefer RS for basically anything else.

**Comment by raoulvdberge** [comment]
Yes, I'm going to try to implement this for mc 1.15. This feature is mentioned in the mc 1.15 tracking issue.
