### ISSUE TITLE
Interface transforms metadata when set to ignore damage

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#2297]
#### Issue description:
Interface stacks items of different metadata if it is in ignore damage mode.

#### Steps to reproduce:
1. Basic setup, 1 interface + some storage.
2. Set the interface to export item with metadata. (needs to have at least one in output slot)
3.Add item with different metadata to the system
4. Set interface to ignore damage

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12
- Forge:2838
- Refined Storage:1.6.15

Demonstration: https://gfycat.com/BlaringPiercingGoitered

**Comment by raoulvdberge** [comment]
this has been fixed for 1.15
