### ISSUE TITLE
Crash related to EnderIO's Glowstone nanoparticles

### ISSUE THREAD

**Issue by S4NDW1CH** [refinedmods/refinedstorage#2319]
#### Issue description:
When playing on ATM3 lite a weird crash appeared. When breaking Tinkers' Construct's seared tank which had some glowstone particles inside. From crash report I deduced that there was some weird interaction between external storage block and particles. 

#### What happens:
Server crashes with IllegalArgumentException.

#### What you expected to happen:
No crash

#### Steps to reproduce:
Currently I am unable to reproduce the crash outside the world on which I play. I can provide a copy of the world where crash happens.
From limited investigation the crash appears to be semi-random.
The setup required to reproduce the crash involves having RS network that connects to TCon's seared tank with external storage and drain. Likely these have to be located on the bottom of the tank. The tank has to have EnderIO's glowstone nano-particles inside of it.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.15

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/S4NDW1CH/a3ce71c1dd7a1d9482ea3c972c0e920e

**Comment by raoulvdberge** [comment]
This has been fixed for 1.15
