### ISSUE TITLE
Creative portable grid loses its name when placed down.

### ISSUE THREAD

**Issue by Tuchevery** [refinedmods/refinedstorage#2324]
Creative portable grid loses its name when placed down.

I can change the name of a creative portable grid using an anvil.  It retains the name as long as I do not set it down.  Once it is placed in the world the name reverts to "Creative Portable Grid".

#### What you expected to happen:
I expect it to retain the name I gave it on the anvil.

#### Steps to reproduce:
1. Rename a creative portable grid with a disk in it
2. Note the new name is on the grid
3. Place the grid down in the world
4. The new name is gone.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no] Don't know, playing single player.

#### If a (crash)log is relevant for this issue, link it here: 

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Closing this for #2948, it's a more global issue.
