### ISSUE TITLE
scrolling with mouse to pick and put items

### ISSUE THREAD

**Issue by Dessp1** [refinedmods/refinedstorage#2332]
#### Issue description:
want to pick up and restore items with mouse scroll (like regular chests)
#### What happens:
nothing
#### What you expected to happen:
want to pick up and restore items with mouse scroll (like regular chests)
#### Steps to reproduce:
just use scroll and nothing will happen :)))
#### Version (make sure you are on the latest version before reporting):

- Minecraft: dont know, playing on DDSS modpack
- Forge: dont know, playing on DDSS modpack
- Refined Storage: dont know, playing on DDSS modpack

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
This is not a vanilla feature. This feature is added by mousetweaks or Inventory sorter.

The problem with adding it is that the scroll wheel is already needed to scroll inside the grid.

It might be possible to add such a feature by adding a keybind? Shift scrolling to put items into the inventory maybe.

**Comment by raoulvdberge** [comment]
Shift scrolling is kind of a good idea, actually.

**Comment by raoulvdberge** [comment]
Not going to implement this as it's already possible with SHIFT + middle click.

**Comment by raoulvdberge** [comment]
But maybe we can remove middle click and do some kind of scrolling to select one item or multiple..

**Comment by Spongman** [comment]
+1 for mouse wheel.

**Comment by raoulvdberge** [comment]
Implemented

**Comment by GrantGryczan** [comment]
Was the ability to middle click to take out one item actually removed? Because that is much more convenient than holding `ctrl` and scrolling down by a precise angle. It's just taking out a whole stack for me.
