### ISSUE TITLE
The exporter cannot export all items with Ore Dictionnary

### ISSUE THREAD

**Issue by ExDomino** [refinedmods/refinedstorage#2335]
#### Issue description:

We have RefinedStorage, ImmersiveEngineering, InstustrialCraft, Mekanism installed with UniDict. ImmersiveEngineering extracts uranium, Mekanism makes this uranium ore uranium ingot, but the ingots is from ImmersiveEngineering. Uranium is automaticly imported inside RefinedStorage. UniDict converts these ingot into IndustrialCraft ones automaticly when we pick them out of the RefinedStorage.

The exporter cannot (I don't know why) export all items that correspond to an Ore Dictionnary so only one kind of uranium can be set. We need to configure it to export all kind of uranium, not only one kind.

#### What happens:

Only uranium from IndustrialCraft (the one I set into the exporter) is exported
There is no button in order to set the exporter to work with Ore Dictionnary.

#### What you expected to happen:

Having a button to allow the exporter to export all kind of uranium.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 2847
- Refined Storage: 1.6.15

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
For 1.12 this is wontfix.

For 1.14 I might implement this.

**Comment by ExDomino** [comment]
Author always leave the old versions behind ...
Please fix that for 1.12 as well.

**Comment by raoulvdberge** [comment]
Moving this to #2372
