### ISSUE TITLE
Can't autocraft rockets.

### ISSUE THREAD

**Issue by Tuchevery** [refinedmods/refinedstorage#2342]
#### Issue description:
Several Issues with auto crafting rockets:
1. JEI won't fill in the rocket recipe in the pattern grid.  Understandable I guess since there are 3 recipes.  I suggest filling in the one gun powder recipe at least.
2. I manually set the recipe of one paper and one gun powder and the grid correctly showed it would make 3 rockets.  I made the pattern but it showed as Invalid Pattern.  I turned off the ore dictionary option and made the pattern again and it was valid.  I put it in a crafter and tried to make various quantities but after I press the Start the dialog just sits there.  The only thing I can do is press Cancel.

#### What happens:
See above

#### What you expected to happen:
See above

#### Steps to reproduce:
See above

#### Version (make sure you are on the latest version before reporting): 

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no] 
Don't know.  Tested on single player world.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Got fixed at some point
