### ISSUE TITLE
Crafting tweaks buttons in incorrect position after switching grid size

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#2348]
![image](https://user-images.githubusercontent.com/4283717/68549495-d0ea2500-03f8-11ea-891a-89c0c8bf13f7.png)

Forge: 28.1.69
RS: 1.7

**Comment by Darkere** [comment]
:/ Nvm Only when changing the size. Reopening the grid puts them in the right spot.

**Comment by raoulvdberge** [comment]
This is a bug though
