### ISSUE TITLE
All nodes reverting when leaving the nether without causing a save

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#2394]
#### Issue description:
All nodes revert to default or a previous state when leaving through a nether portal. 
#### What happens:
Disk drives empty, importer settings gone. Disk data itself seems fine. 

#### Steps to reproduce:
1. Create RS system in the Nether
2. Leave through portal before a save happens
3. come back couple seconds later. 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.109
- Refined Storage: 1.7.3

**Comment by zedekblue** [comment]
Just had this issue occur on my world. 64k disk from the drive I had is gone.
Left the nether via an rftools teleporter.

**Comment by Darkere** [comment]
Fixed in 1.16
