### ISSUE TITLE
Buttons on the craftingpreview screen moved

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#2431]
- Refined Storage:1.8.1

Probably not intentional. Putting it here so it doesn't get forgotten.

1.8.0:
![image](https://user-images.githubusercontent.com/4283717/74607343-7a1b7800-50d8-11ea-97c3-26c119c74076.png)

1.8.1: 
![image](https://user-images.githubusercontent.com/4283717/74607348-8dc6de80-50d8-11ea-80b7-4caed539177d.png)

**Comment by raoulvdberge** [comment]
This was intentional. It was to make space for the crafting task identifier

**Comment by Darkere** [comment]
hmm ok. The thing I don't like about it is that you have to move across the entire screen from the top right on the amount screen:
![image](https://user-images.githubusercontent.com/4283717/74608581-a20fd900-50e2-11ea-84cf-e4e86141c6cb.png)

to the bottom left on the preview screen.

Also not a fan of the full ResourceLocation. Not only does it look a bit unfinished it also really doesn't mean anything to a player. Been thinking of what to put there. 

The best idea I had was `AEv5` for "Autocrafting Engine" but that might be a bit problematic :) Definitely needs a tooltip though.

**Comment by raoulvdberge** [comment]
I'll probably just end up removing the identifier.
