### ISSUE TITLE
External Storage

### ISSUE THREAD

**Issue by closeshot** [refinedmods/refinedstorage#2438]
Using Importer with external storage:

When having a storage connected to an external storage and using an importer to import items and also having filters it goes straight into the storage disks even with lower priority and higher priority on the external storage:

Imported items going into the connected storage on the external storage:

#### Steps to reproduce:
1. connect external storage to a chest
2. connect importer to a furnace for smelted items 
3. smelted items go into the storage disks instead of connected storage to external storage
...

Version 1.8.1:

- Minecraft: 1.15.2
- Forge: 31.1.9
- Refined Storage:

Does this issue occur on a server? [yes/no] Havent tested

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by closeshot** [comment]
Forgot to mention the external storage is connected to a dank storage

**Comment by Darkere** [comment]
Unrelated to RS. Probably dank storage not working properly. 

1.15 is also unsupported.
