### ISSUE TITLE
[feature] ComputerCraft API

### ISSUE THREAD

**Issue by za3k** [refinedmods/refinedstorage#2453]
Requesting a ComputerCraft API--it looks like there's already an OpenComputers one, so #153 was closed. AFAICT this API doesn't work with CC.
OpenComputers hasn't been updated since 1.12 so it's no longer available in newer modpacks, most of the ones I see use CC:Tweaked

**Comment by uecasm** [comment]
I've just created an [addon mod](https://github.com/uecasm/rs4cc/releases/tag/1.0.0) that provides a ComputerCraft (or actually CC:Tweaked) API for MC 1.16.4.  (I've made a CurseForge page for it as well but it's awaiting moderator approval.)

Let me know if there are any issues with it.

**Comment by uecasm** [comment]
The [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/refined-storage-for-computercraft) is up now.

**Comment by Emyrk** [comment]
> The [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/refined-storage-for-computercraft) is up now.

Can you also upload this for 1.16.3? Would it be compatible with that version of MC?

**Comment by Darkere** [comment]
From what I'm hearing this is working well. Thanks
