### ISSUE TITLE
Click issue when trying to search for items in GUI

### ISSUE THREAD

**Issue by Frogwisard1984** [refinedmods/refinedstorage#2463]
#### Steps to reproduce:
1.open the crafting block
2.click search nox
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no] not sure, playing solo world

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/Frogwisard1984/573d073f52cee8b835857aa363068384

[pastebin/gist/etc link here]

**Comment by HowardRoark2016** [comment]
I have the same issue. Crash the moment I left-click the search bar in both the Refined Storage controller and wireless controller.  I am playing All The Mods 5 v1.18b. I will post the link to my crash log below.

#### Issue description: Crash upon left-clicking the search bar in the controller's GUI

#### What happens: Crash

#### What you expected to happen: Type to search for items in storage

#### Steps to reproduce:
1. Open GUI of either Controller or Wireless Controller
2. Left-click the search bar
3. Crash
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.47
- Refined Storage: 1.8.1

Does this issue occur on a server? [yes/no] Unknown

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/pwJLWaDR

**Comment by raoulvdberge** [comment]
I don't think this is an issue in mc 1.16.
