### ISSUE TITLE
Items have wrong quantities and "Lock up"

### ISSUE THREAD

**Issue by enderface36** [refinedmods/refinedstorage#2475]
**EDIT**
everything in this issue _also_ applies to fluids

#### Issue description:
Items inserted into storage system in any way will have weird numbers (often multiples of 8) and often cant be retrieved after inserting them.
#### What happens:
lets say I put 64 cobblestone in a crafting grid. The grid will say I have 8 cobblestone and the cobblestone cant be retrieved after.
#### What you expected to happen:
I expected to get 64 cobblestone on screen and be able to take 64 cobblestone back out.
#### Steps to reproduce:
1. build RS system.
2. Insert item.
3. close grid.
4. Re-enter grid and see your wacky numbers and vanished items.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.37
- Refined Storage: 1.8.1

Does this issue occur on a server? [yes/**no**]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![2020-04-05_20 29 34](https://user-images.githubusercontent.com/27897624/78513813-35c56380-777c-11ea-9cf0-e408fe488e5a.png)

**Comment by Darkere** [comment]
What are you storing your items in?

**Comment by enderface36** [comment]
The issue occurs when i store them in a wireless terminal or crafting grid

**Comment by Darkere** [comment]
I meant what the items are stored in. Inside a chest or in disks...

**Comment by enderface36** [comment]
disks

**Comment by raoulvdberge** [comment]
Can't reproduce this
