### ISSUE TITLE
[1.15.2]Japanese translation

### ISSUE THREAD

**Issue by KusozakoAtama10k** [refinedmods/refinedstorage#2501]
https://gist.github.com/KusozakoAtama10k/8a95357ee96358416b1f8f59e77fe878
I've created a Japanese translation file for 1.6.16 , but I don't know how to do a pull request, so I'm posting it here.

**Comment by raoulvdberge** [comment]
1.12 is not getting these updates anymore. Can you modify it for 1.15?

**Comment by KusozakoAtama10k** [comment]
https://gist.github.com/KusozakoAtama10k/8a95357ee96358416b1f8f59e77fe878
Corrected for 1.15 (ja_jo.json). But some of the sentences may be wrong because I didn't know what situation they would appear in.

**Comment by raoulvdberge** [comment]
Thank you, this has been merged.
