### ISSUE TITLE
[1.15.2] Controller wasting energy (FE) when offline

### ISSUE THREAD

**Issue by darkwerr** [refinedmods/refinedstorage#2505]
#### Issue description:

Other components from Refined Storage (e.g. Grids, Exporters/Importers) continue to consume energy (FE) when the Controller is offline, wasting energy buffer from the Controller. But if you turn off a Grid or such, the energy for that component stops being wasted.

#### What happens:

Controller is letting energy flow to components connected to it when offline and wasting energy (FE).

#### What you expected to happen:

When the Controller is offline, the energy (FE) should stop being wasted since the whole system is offline too.

#### Steps to reproduce:

1. Place a Controller down and fill with some energy (FE).
2. Place any component from Refined Storage which waste some energy, e.g. a Grid, next to the Controller.
3. Turn off the Controller via redstone signal config.
4. Optional: Remove any energy connection from the Controller to see the buffer energy going down.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.49
- Refined Storage: 1.8.3

**Comment by kylania** [comment]
I can replicate this issue as well.  It first was happening for me with 1.8.1, then still happening in 1.8.3.

If you have the Controller set to Only Work With Redstone Signal with no redstone signal active, upon game load the Controller will be offline and not using any power.  As soon as it's activated it starts to draw power.  Turning off the redstone signal will turn off the Controller and all attached devices but power drain will continue until all other devices are removed from the network.
