### ISSUE TITLE
Refined Storage Crafters interfaced with hoppers will result in recipes being removed

### ISSUE THREAD

**Issue by utoc** [refinedmods/refinedstorage#2512]
#### Issue description:
Crafter interfaced with a hopper.  Hopper interfaced with some machine (Pneumaticcraft's Pressure Chamber in this example as the crafter will not work with the chamber).  The hopper pulls the recipes from the crafter.  Tada!
#### What happens:
The hopper is doing what it thinks is best but truly it doesn't know whats best.
#### What you expected to happen:
The hopper should not remove recipes from a crafter on the interfaced side.
#### Steps to reproduce:
1. Place a chest
2.Place a hopperpointing into said chest
3.Place a crafter, interface side down, on top of the hopper.
4.Place patterns into the crafter
5.Observe the chest: it has patterns
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.15.2
- Forge:31.1.74
- Refined Storage:1.8.3

Does this issue occur on a server? [yes/no] Yes (but also tested in SSP)

#### If a (crash)log is relevant for this issue, link it here:
Nein

Here are some pretty pictures if you need to duplicate this for testing:

![javaw_ljN93TNGna](https://user-images.githubusercontent.com/11995956/81297503-f1f2a200-9038-11ea-9ff3-a6683c51726d.png)

Oh also, V6 autocrafting appears to be much friendlier (so far) on servers, thank you!

**Comment by utoc** [comment]
Actually, this probably isn't a bug since the crafter can point to ANY other side of a hopper and still work.  Please close this ticket if it is intended behavior and not a bug.

**Comment by raoulvdberge** [comment]
This behavior could be changed, a pattern inventory shouldn't be exposed to the side the crafter is facing, probably.
