### ISSUE TITLE
The liquid "milk" won't go in to some items

### ISSUE THREAD

**Issue by seals55** [refinedmods/refinedstorage#2516]
#### Steps to reproduce:
1. Try to make a detector emit a redstone signal when you have 1 MB of milk
2. Try to create a pattern to put 1 B of milk + 1 bucket for 1 bucket of milk 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.74
- Refined Storage: 1.8.3

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

https://github.com/ValhelsiaTeam/Valhelsia/issues/16

**Comment by Darkere** [comment]
The vanilla milk bucket does not extend ItemBucket. As such Forge's fluidhandler cannot get the fluid that is inside the bucket. 

Industrial Foregoing by defaul replaces the Milk Bucket but that one is missing the FLUID_HANDLER_ITEM_CAPABILITY.
