### ISSUE TITLE
Item quantity in exporter (for regulator) is forgotten on reboot

### ISSUE THREAD

**Issue by seals55** [refinedmods/refinedstorage#2517]
#### Steps to reproduce:
1. Attach exporter with regulator card to storage
2. Add stack of 64 of something to export section. 
3. Restart server, look at exporter and see that stack is set to 1 of the item, NOT 64
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.74
- Refined Storage: 1.8.3

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Can you reproduce this on 1.8.6?

**Comment by raoulvdberge** [comment]
Fixed, thx for the report (cute cat by the way!)
