### ISSUE TITLE
[1.12.2] Storage Drawers over 100k items bug

### ISSUE THREAD

**Issue by rasm685p** [refinedmods/refinedstorage#2518]
#### Issue description and what happens:
(This issue happens with the mod "Storage Drawers")
If I have 100k or more in my Storage Drawer then it just "magically" disappears and starts over and counts from 0. So if I for example have 101k items in my Storage Drawer, then I'll only see 1k of the items in my Grid. This isn't just a visual bug because I can't use any items besides the 1k I'm able to see. So if I really wanted to use the 100k items I would have to extract the items from the Storage Drawers manually without Refined Storage.

#### What you expected to happen:
If I have 101k items in my Storage Drawer then I'll only see 1k of the items even through I should be able to see all 101k in my Grid. I can't use the 100k either. They can't be seen or extracted from the system. I would have to manually extract the items by finding the drawer and clicking on it.

#### Steps to reproduce:
1. Fill a Storage Drawer with 101k items.
2. Link a Drawer Controller to the Storage Drawer.
3. Connect a external storage cable to the Drawer Controller
4. Open the grid and you should only see 1k of the 101k items.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.16
- Storage Drawers: 5.4.2

Does this issue occur on a server? [yes/no]
Yes. The issue is found on a server.

**Comment by Darkere** [comment]
Cannot reproduce. Mod Pack issue or are you maybe on a broken version of Storage Drawers?
