### ISSUE TITLE
Wireless Crafting Monitor Dupe Bug

### ISSUE THREAD

**Issue by CoolDCB** [refinedmods/refinedstorage#2521]
#### Issue description: When you shift click items into the refined storages system it puts the item into the System but doesnt take it from your inventory
What happens: The item dupes
What you expected to happen: No dupe preferably
Steps to reproduce: (Not completely certain but it seems to be something to do with the wireless transmittor)

#### Steps to reproduce:
1. Connect a wireless crafting monitor to the System
2. Open main system
3. When you attempt to shift click an item into the system the item will appear in the system but will not leave your inventory
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.5.2854
- Refined Storage: refinedstorage-1.6.16

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/9aDfM1mP

**Comment by Darkere** [comment]
The wireless crafting monitor is for seeing currently auto crafting tasks. Did you mean something else?

**Comment by CoolDCB** [comment]
Look at the Null Pointer Error in the Pastebin

**Comment by raoulvdberge** [comment]
Fixed for 1.15
