### ISSUE TITLE
[1.12.2] External Storage stops to see attached container

### ISSUE THREAD

**Issue by LuciusV** [refinedmods/refinedstorage#2524]
#### Issue description & What happens:
Singleplayer world
External storage is attached to Storage Drawers Controller set with high priority.
Chunk has chunkloaders.
After some time things supposed to be in Storage Drawers go to in Disk Storage. (The are automatically imported with Importer from farms).
Drawers are upgraded and have voiding excess, so it isn't overflow.
Same can happen with big chests or any external storage

#### What you expected to happen:
Thinng go to controller with External Storage
#### Steps to reproduce:
1. Create system of Storage drawers and controller connected to RS External Storage
2. Direct some resources into it automatically by Importer
3. Go around change dimensions/logout/login, after some time items start to go to Disk Storage

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847 
- Refined Storage: 1.6.16

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.12 is no longer maintained. This bug should be gone in mc1.15.

**Comment by LuciusV** [comment]
I understand that you are focused on 1.15 now, but could you please fix it if you have time?
Many modpacks are on 1.12 because many mods have not been updated, and this bug ruins crafting automation to unplayable (or forces to use unefficient storage methods)

**Comment by Darkere** [comment]
See https://github.com/refinedmods/refinedstorage/issues/2120 

It seems to be a special case with FTBU loading. Try a different chunkloader. 
There are no plans to make any mor updates to 1.12.
