### ISSUE TITLE
[1.12.2] Shift click storage disk deletes it when inventory full in portable grid

### ISSUE THREAD

**Issue by Lithium941** [refinedmods/refinedstorage#2528]
#### Steps to reproduce:
1. Open portable grid with a full inventory
2. Shift-click the storage disk out
3. The disk will be gone (I tried it again to make sure)
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Refined Storage: 1.6.15

Does this issue occur on a server? [**yes**/no] > YES, it occurs on servers 

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by tth05** [comment]
What happens here is that the disk gets inserted into itself. Fixed this in my fork for 1.12.
