### ISSUE TITLE
Feature Request: Drive LIFO mode for priority

### ISSUE THREAD

**Issue by xannor** [refinedmods/refinedstorage#2531]
This is similar to #2419 but instead of on all bi-directional interfaces, I would like it just for drives. My main idea for this is with drives you usually use them as a catch all, and most people set them at the lowest priority on their network. This has the side effect of the drives accumulating items that have proper storage, but may overflow, which means these items will never get used or even discovered until the other storage is completely empty. 

What I suggest is a LIFO mode for drives that alters their priority, and this mode would be in the list for  the direction (i.e. in, out, bi, and lifo). What this could do is either a fixed subtractor to the priority for inserts, an inverted priority for inserts, or any method you feel is implementable to split the priority between inserts and extracts.

I feel this would be a low impact QOL addition, and not as "cheaty" as dual priorty on all interfaces, since for external storages, you can just use two to achieve the the same result. Drives you have no practical way to split like that.

**Comment by raoulvdberge** [comment]
I think this idea is too complicated.
