### ISSUE TITLE
Server crash on player logon (Null pointer exception)

### ISSUE THREAD

**Issue by jrnvnjk** [refinedmods/refinedstorage#2539]
#### Issue description:
server crashes after a player logs on
#### What happens:
the server crashes

#### What you expected to happen:
The server not to crash
#### Steps to reproduce:
1. start the server
2. logon to the server
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2847
- Refined Storage:1.6.16
- Modpack: Dungeons Dragons and Spaceshuttles 7.4.1a

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://pastebin.com/iDL9nhjk

**Comment by raoulvdberge** [comment]
Should no longer exist on mc1.15
