### ISSUE TITLE
CPU's not recognizing each other

### ISSUE THREAD

**Issue by keebster** [refinedmods/refinedstorage#2542]
The CPU's Item number 5933/0 /1 and /2 Do not see the tier below it within the system.

We are using a Refined Storage computer system. I can create the 5933/0 Item as it doesnt require another cpu. But the 5933/1 does not recognize the pattern or the item of 5933/0 in the computer. and the 5933/2 does not recognize the pattern or the item 5933/2

I have tried to make different items that require those CPU's and none of them seem to work.

I have also sent this issue to OpenComputers just encase its an issue with their system.

**Comment by raoulvdberge** [comment]
Follow the issue template. And explain what you mean with CPUs, RS doesn't have those.
