### ISSUE TITLE
[1.12.2] Fluid Grid Resets fluid quantity on open

### ISSUE THREAD

**Issue by vedalken254** [refinedmods/refinedstorage#2543]
#### Issue description:
Fluid Grid resets quantity on every open of the grid.
#### What happens:
Upon opening the fluid grid, if the stored value for a given fluid is greater than 2.1B mB, the grid will reset to 0 and count up on every open.
#### What you expected to happen:
Actual Quantity display of fluid in the system
#### Steps to reproduce:
1. Fill fluid disks up to over 2.1B mB worth
2. Open Fluid Grid
3. Observe it climb from 0.
4. Close grid and re-open.
5. Repeat step 3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.16
- DW20 1.12.2 pack v2.7.0
Does this issue occur on a server? Yes

After looking over the code, this appears to be because of the variable type for the amount. As it is an int variable, once it exceeds the max value of int (2,147,483,647 mB), it resets. I am unable to tell if this will also impact exporting, but importing seems unaffected as more drives are still filling up so I would assume it is merely a display issue and not a functionality issue. A note that the disks used were from RebornStorage which makes the cap of int far easier to reach.

**Comment by raoulvdberge** [comment]
Yes, your analysis is correct. However, this won't be fixed for 1.12 anymore.
