### ISSUE TITLE
CPU's not recognizing each other

### ISSUE THREAD

**Issue by keebster** [refinedmods/refinedstorage#2544]
#### Issue description:
Creating CPU 5933/0 works without issue. 
Creating CPU 5933/1 doesn't work
Creating CPU 5933/2 doesn't work
#### What happens:
Creating CPU 5933/1 It can't see the item or the pattern for CPU 5833/0 within the refinedstorage computer system. 
Creating CPU 5933/2 It can't see  the item or the pattern for CPU 5833/1 within the refinedstorage computer system. 
#### What you expected to happen:
It to work.
#### Steps to reproduce:
1.Create a pattern for, or just use the GUI and pull the pattern into the crafting window
2.Try to make the pattern it shows items 5933/1 and 5933/2 at missing.
3.It don't work.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:
I know the item is from OpenComputers and I sent them the issue also. I sent this one to you because I dont know if it's an issue with the item or the refined storages system
[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
I remember there being a case of https://github.com/refinedmods/refinedstorage/issues/2064 in Open Computers too. 

Try creating the pattern by hand instead of with JEI. (and turn off oredict).

**Comment by keebster** [comment]
Ok that worked thanks
