### ISSUE TITLE
Feature request: auto-clear crafting grid

### ISSUE THREAD

**Issue by charliegc4** [refinedmods/refinedstorage#2545]
What would be so useful is to have the Crafting Grid clear after some time. That way, if you leave the grid for months, it does not keep items in it's inventory.

**Comment by Darkere** [comment]
The code to make this work would be ugly, complicated. It's also not possible to determine when people would want to have their cleared. 

There is a button and a keybind to clear the crafting grid. Use those.

**Comment by charliegc4** [comment]
There are so many other crafter types in Minecraft where the inventory is cleared after the craft is complete. Guess they all use complicated and ugly code, but it works just fine.

**Comment by Darkere** [comment]
They work fundamentally different. With that approach it is not possible to have multiple people interact with the same crafting grid or keep any items inside it. 

>Crafting Grid clear after some time

The code to accomplish this ^ would be ugly :). Making it clear upon leaving would be easy.

**Comment by charliegc4** [comment]
That's hopeful. So, is there some way we can have it clear on leaving that would not involve any rewrite? Like say some config file change?

**Comment by Darkere** [comment]
I doubt it's going to happen but you should already be able to accomplish this by bindind the clear crafting matrix key to the same key you use to close the grid.

**Comment by charliegc4** [comment]
To exit the grid, I use Esc, which, as far as I know, can't be assigned as a key in Controls as it is used to assign a NONE value to the key.

Thanks anyway.

**Comment by raoulvdberge** [comment]
This won't be implemented since it's impossible to determine when a grid should be cleared. It could be cleared if you close the grid, but that could lead to annoyances and we generally don't put things behind config options.

**Comment by charliegc4** [comment]
I guess that annoyances because it is not being cleared are not as important as annoyances that it might be cleared!

Why not provide an option by config so that we can choose for ourselves?

**Comment by raoulvdberge** [comment]
Read the FAQ for an answer to that: refinedstorage.raoulvdberge.com/wiki/faq

**Comment by charliegc4** [comment]
That is a lame excuse as many mods allow the player a more personalized experience through config options, and it is not confusing at all. 

In the mean time I have found a solution; use another mod. I was only using Refined Storage for the Crafting Grid anyway, 

Sorry guys.

**Comment by raoulvdberge** [comment]
That is your opinion. I don't think it's an excuse but something I believe in personally. 

But thank you for the encouraging words anyway; very happy we were able to spend time on this issue for you today.
