### ISSUE TITLE
Game Crash and Empty Block when moving Crafter with Sticky Piston

### ISSUE THREAD

**Issue by GatorSpear** [refinedmods/refinedstorage#2551]
#### Issue description:

 I have the need to move some crafters over using sticky pistons and slime blocks.  Moving a single crafter as a test, the game (client and server) crashed.  Upon reconnecting, the crafter is gone (along with all of its recipes and upgrades.  In the place of where it was being moved to (not the original location) is an empty block that cannot be removed and nothing can be placed here.  I can walk through it, but liquids flow around/over it.  Happens for crafters that are connects to network and disconnected.

#### What happens:

Server crash.  From the log:

> Description: Watching Server
> 
> java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
> 	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:39) [?:?] {re:classloading}
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

#### What you expected to happen:

Crafter should move one space without breaking or losing its recipes or upgrades.

#### Steps to reproduce:
1. Place sticky piston 1 block away from crafter, facing it.
2. Power sticky piston with torch.
3. Break the torch

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.0
- Refined Storage: 1.8.4

Does this issue occur on a server? **YES**

#### If a (crash)log is relevant for this issue, link it here:

https://www.dropbox.com/s/t8zl9x97orvy526/crash-2020-06-04_14.19.08-server.txt?dl=0

**Comment by GatorSpear** [comment]
FYI - the only way I found to fix the blank spaces is to use the "/fill" command on the coordinates.  WorldEdit crashed the game when trying to use the "/regen" command.

**Comment by Darkere** [comment]
Pistons are not able to push tile entities by default. You probably have Quark installed which allows for this to happen. 

I don't know how much effort it would be to make this work but I'm sure it is possible.

**Comment by GatorSpear** [comment]
Thanks for the response.  I do have Quark installed.

I am going t move it manually.  It won't be a problem.  The bigger problem for me was the blank block that wouldn't allow me to use the area I had laid-out.

If you did make it moveable via Quark, this would make for a different way to disconnect than the Relay.  Or, perhaps a way to switch to crafters with different recipes.

**Comment by Darkere** [comment]
Being able to make moving RS systems using vanilla flying machines is a much more interesting application I imagine.

**Comment by raoulvdberge** [comment]
Don't move RS blocks!
