### ISSUE TITLE
Network system bug

### ISSUE THREAD

**Issue by HireSLH** [refinedmods/refinedstorage#2553]
###  Issue description:
I can't set a Network.

### What happens:
When I place the Network Card inside the Network Transmitter the Network Receiver always breaks and the Network Receiver item its on the ground and I had to place it again but then Network doesn't work.

### Version:

- Minecraft: 1.15.2
- Forge: 31.2.0
- Refined Storage: 1.8.4

### Does this issue occur on a server?
Yes

**Comment by Darkere** [comment]
The network system is for extending a single network. NOT for combining 2 networks together. A network can never have more than 1 controller.

**Comment by HireSLH** [comment]
> The network system is for extending a single network. NOT for combining 2 networks together. A network can never have more than 1 controller.

So how i give energy to the Transmitter because without controller its off and doenst work  even i plug directly a Flux Point (I use Flux Networks)

**Comment by Darkere** [comment]
You power the controller on the transmitters side. The receiver will get powered when the transmitter connects to it.

**Comment by HireSLH** [comment]
Can i place more than one Network Transmitter  to collect on my central storage the items from different farms?

**Comment by Darkere** [comment]
You create as many Network Transmitter, Network Receiver combinations as you want.

**Comment by HireSLH** [comment]
Humm i am trying it but second receiver doesnt turn on when i place the card. I have a 2 chest with importers, cable and the receiber
