### ISSUE TITLE
Can't put any item !

### ISSUE THREAD

**Issue by Lukeskyf** [refinedmods/refinedstorage#2562]
#### Issue description: Hello !
This little message to report what I think is a bug or somekind because its simply weird : I've done just a simple installation with Refined Storage to replace my Simple Storage Network. 
![installation](https://user-images.githubusercontent.com/66335516/83979860-bb4ac880-a911-11ea-9853-ecd089c14639.png)
I've made the controller, fully powered ; a crafting grid, a simple grid, a fluid grid, a disk manipulator and a disk drive with 3x 16k disk in it.
![disk drive](https://user-images.githubusercontent.com/66335516/83979897-f3520b80-a911-11ea-91cc-120b8171d83b.png)
The controller is seeing well the network
![controller](https://user-images.githubusercontent.com/66335516/83979907-01079100-a912-11ea-9828-dac6d9e5a4f4.png)
But, I wanted to extract a simple vanilla double chest into the disk drive, so I made an importer. Didn't work. I thought "whatever, I'm not doing this well, I'll do it by hand".
I can't even put just a simple stack of stone in the system !
![crafting grid](https://user-images.githubusercontent.com/66335516/83979955-4e83fe00-a912-11ea-8a2c-7bdd2eedd63f.png)
That's just a simple as that : I just can't use the mod !

#### What happens:
I can't put any items in the network, by hand or with an importer

#### What you expected to happen:
Simply use the abilities of this mod by improve my storage !

#### Steps to reproduce:
If I only had the beggining of an idea for that...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.0
- Refined Storage: 1.8.4

Does this issue occur on a server? [yes/no] No

**Comment by Darkere** [comment]
In the disk drive on the left you have set the filter to whitelist. An empty whitelist means no items may go inside.
