### ISSUE TITLE
A version for fabric?

### ISSUE THREAD

**Issue by magic0whi** [refinedmods/refinedstorage#2563]
Current there is lack of a network-based storage system on fabric platform.
It would be nice if refinedstorage support it.

**Comment by magic0whi** [comment]
The close of this issue was out of my expected.
First of all thank you for taking the time to read this issue.
I'm sorry if I have any unclear expressions, English is not my native language.

**Comment by raoulvdberge** [comment]
Sorry, looks like my message didn't get through.

No, I don't have any plans for a Fabric version.

**Comment by magic0whi** [comment]
> Sorry, looks like my message didn't get through.
> 
> No, I don't have any plans for a Fabric version.

Acknowledge, thank you for your rapidly reply.
