### ISSUE TITLE
Unable to play on LAN

### ISSUE THREAD

**Issue by Occhioverde** [refinedmods/refinedstorage#2569]
#### Issue description:
It is impossible to connect to a world hosted on another client on the LAN.

#### What happens:
Once you wait a few seconds after pressing the "Join server" button, the connection stops on the "Encryting" phase without showing any error message (The only text that appears is "Disconnected").

#### What you expected to happen:
The multiplayer game should start without any problem.

#### Steps to reproduce:
1. Create/open a world on Minecraft 1.15.2 with RS enabled
2. Start a local server by pressing ESC and clicking the "Open to LAN" option
3. Connect to this world using another computer

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.15.2
- Forge: 31.2.9
- Refined Storage: 1.8.5 (Note that the problem occurs with each version made for Minecraft 1.15.2)

#### Does this issue occur on a server?
The problem only affects a local multiplayer game (LAN)

#### If a (crash)log is relevant for this issue, link it here:
The only log entry that is shown after this problem occurs is a message that says `lost connection: Took too long to log in`

**Comment by Darkere** [comment]
Is RS the only mod installed?

**Comment by Occhioverde** [comment]
No, I also installed:
- Security Craft (1.8.18.1)
- CC: Tweaked (1.88.1)
- Open Block Elevator (1.7.1)
- Mekanism (9.10.7.420)
- Optifine (1.15.2 HD PRE23)

Obviously I tried to disable one mod at a time and I noticed that the problem is solved when I disable Refined Storage.

**Comment by Occhioverde** [comment]
After some additional research it seems that the problem occurs when the Refined Storage is loaded together with the CC: Tweaked.

**Comment by raoulvdberge** [comment]
Do you have any logs?

**Comment by Occhioverde** [comment]
No.
As I wrote in the first message, I tried to access the world in LAN leaving the logs of both devices open but the only error that appeared was `lost connection: Took too long to login` on the log of the computer that hosted the local server.

**Comment by Darkere** [comment]
The debug log should have more information. 
(Unless you are using twitch. It breaks that log).

**Comment by Occhioverde** [comment]
> The debug log should have more information. 
Do you mean to say that I have to tick the "Debug" filter or that I have to read a particular log somewhere else?

> (Unless you are using twitch. It breaks that log).
No, I don't use the Twitch client.
Both PCs have Manjaro Linux and, as far as I know, Twitch is not yet available for that system.

**Comment by Darkere** [comment]
You are looking at the log inside the Minecraft launcher. The debug option in there unfortunately doesn't work for forge. You will need to go into your logs folder and grab the debug.log file from there.

**Comment by Occhioverde** [comment]
As you asked me, here you find the integral logs of both computers at the time of the connection start (excluding some sensitive information, obviously): https://gist.github.com/Occhioverde/63c632c6f0b7d1a88c299e207bbcecbd

Personally, I don't see anything interesting, but I hope they can help you.
Of course, in case the problem wasn't due to your mod but to CC: Tweaked please let me know so that I can open an issue in their repo.

**Comment by raoulvdberge** [comment]
Thank you for the logs. Indeed, nothing interesting to be seen. I'm closing this issue for now.
