### ISSUE TITLE
Can't force a autocrafting recipe to start in 1.12.2

### ISSUE THREAD

**Issue by CorneliusCornbread** [refinedmods/refinedstorage#2570]
#### Issue description:
In 1.10.2 I was able to force autocrafting recipes to start by ctrl+shift clicking the start button in the autocraft info dialogue, regardless of whether or not I have the materials necessary to craft the item. This isn't possible in 1.12.2

#### What you expected to happen:
I should be able to force a crafting recipe to start through the grid in some form or another.

#### Steps to reproduce:
1. Create an autocraft recipe
2. Attempt to queue an item that you lack the resources for
3. Hold ctrl+shift and try to hit start. Nothing happens

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Refined Storage: MC1.12.1-1.5.3

Does this issue occur on a server? Yes

**Comment by raoulvdberge** [comment]
That feature was removed
