### ISSUE TITLE
[1.15.2] Crash upon enabling shaders in multiplayer world

### ISSUE THREAD

**Issue by kurisubrooks** [refinedmods/refinedstorage#2572]
#### Issue description:

Game crashes when loading the world with OptiFine shaders enabled.
Even after disabling shaders, it still appears to crash, requiring OptiFine to be uninstalled completely.

#### What happens:

The game crashes under certain circumstances to do with OptiFine

#### What you expected to happen:

It to not crash

#### Steps to reproduce:
1. Load up a world with OptiFine enabled
2. Whilst in-game, enable a shader pack (I was using Sildur's Vibrant Extreme)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.9
- Refined Storage: 1.8.4

Does this issue occur on a server? **yes**

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/kurisubrooks/0b6a4f2694764f8795d7d2aba6399126

**Comment by raoulvdberge** [comment]
This looks like an optifine issue
