### ISSUE TITLE
1.10.2 auto crafting not working 

### ISSUE THREAD

**Issue by disduke** [refinedmods/refinedstorage#2577]
#### What happens:
when trying to auto craft large amounts of items or long and complicated recipes the crafting monitor says machine in use when it's not.
#### Steps to reproduce:
1.set up all patterns for items that craft into  the 512k fluid storage disk  all the way down to the crafting recipe for the 64k fluid storage disk
2.then craft the 512k fluid storage disk using the auto craft feature. (does the same thing for any complicated recipe)
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by disduke** [comment]
it's happening with basic recipes like the basic processer too (sometimes it works and sometimes it doesn't.it doesn't work most of the time)

**Comment by disduke** [comment]
why was this made invalid

**Comment by Tahakk** [comment]
1.10.2 is not supported anymore
