### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by emanuele246gi** [refinedmods/refinedstorage#2578]
#### Issue description:
Crash Report

#### What happens:
Crash when starting the game

#### What you expected to happen:
Normally opening the game

#### Steps to reproduce:
1.Open the game
2.Waiting for the loading screen
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.20
- Refined Storage: 1.8.5

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/8hRGPKyE

**Comment by Darkere** [comment]
Report to https://www.curseforge.com/minecraft/mc-mods/rslargepatterns .

The latest update has changed things and every addon will need an update to work with it.

**Comment by emanuele246gi** [comment]
But I updated the addon too

**Comment by Darkere** [comment]
You might have updated RSaddons mod. You did not update rslargepatterns (as there is no update for that).

**Comment by emanuele246gi** [comment]
Oh I see, thanks anyway :D
