### ISSUE TITLE
[1.15.2] crash on start Failed to load hierarchy member com/raoulvdberge/refinedstorage/tile/NetworkNodeTile

### ISSUE THREAD

**Issue by IchigoGames** [refinedmods/refinedstorage#2580]
#### Steps to reproduce:
1.updated mod in modpack
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.21
- Refined Storage: refinedstorage-1.8.5

Does this issue occur on a server? [yes/no] 

not sure

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/dRDC2ays

**Comment by Darkere** [comment]
With version 1.8.5 all add ons need to be updated. Not sure which sddon you are using in this case but it is likely the cause of this crash.

**Comment by IchigoGames** [comment]
ok looks like its StorageTech
