### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Blackcomet** [refinedmods/refinedstorage#2583]
#### Issue description:
Game crashed on load. Forge Devs said to contact you.
#### What happens:
crash
#### What you expected to happen:
Game to load
#### Steps to reproduce:
1.download mod
2.start game

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:1.12.2.14.23.4.2725
- Refined Storage:1.6.16

Does this issue occur on a server? [yes/no]
don't know

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/yeRYSpcZ

**Comment by Darkere** [comment]
You are 100+ Forge versions behind. Update.

**Comment by Blackcomet** [comment]
It's for a mod pack and many mods aren't updated to 1.15.

**Comment by Darkere** [comment]
You are 100 versions behind for forge 1.12.2.
Latest version for 1.12.2 is something like 2870. You are on 2725
