### ISSUE TITLE
Refined storage mekanism autocrafting

### ISSUE THREAD

**Issue by TheKnight1993** [refinedmods/refinedstorage#2595]
#### Issue description:
When I try to create a autocrafting recipe for basic energy cubes (mekanism) my system doesn't recognise the cubes, even after I manually insert the cubes into the pattern, the energy tablets work fine but the energy cubes don't
#### What happens:
When I try to ask for an energy cube craft my system doesn't want to work.
#### What you expected to happen:
That the autocraft works after I insert the cubes manually
#### Steps to reproduce:
1. have mekanism and refined storage
2. make 2 patterns, one for the basic cube and one for the advanced
3. have all the prerequisites for the basic cube and the advanced
4. request an advanced cube, if it says that it doesn't know the basic cube then go and request a basic cube
5a. if you requested a basic cube then replace the basic cube in the advanced cube recipe
5b. if the craft was valid use a crafting monitor to monitor the craft and if it sticks at the processing the advanced cube, cancel the craft and replace the basic cube in the advanced cube recipe
6. request another advanced cube, it should say that it's either missing a basic cube or the craft won't complete

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2821 (playing on ftb presents direwolf20 1.12, so I had to stick with an older forge)
- Refined Storage: 1.16.16

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by TheKnight1993** [comment]
Well, after a bit of faffing around it seems ore dictionary seems to screw things over, I think this is a bug and it should be adressed

**Comment by raoulvdberge** [comment]
1.12 is unmaintained.
