### ISSUE TITLE
[1.12.2] Grid optimization

### ISSUE THREAD

**Issue by TechnoMageDevTeam** [refinedmods/refinedstorage#2596]
Refined storage is absolutely wonderful, but one feature i really miss from AE2 is that i can hold space bar and deposit my entire inventory into the system. Inventory Tweaks allows us to deposit our entire inventories into a chest if we hold space bar and click, it would just be a really handy feature. Thanks :D

**Comment by raoulvdberge** [comment]
Thx for the suggestion but not going to add this.
