### ISSUE TITLE
Watchdog when auto crafting many items at once

### ISSUE THREAD

**Issue by Luohuayu** [refinedmods/refinedstorage#2597]
https://paste.ubuntu.com/p/qBV7xsTGkN/

Auto crafting many items at once (14 Quantum Solar Panel), open Crafting Monitor gui, it took more than a minute until Watchdog.
If not open Crafting Monitor, server tps will remain low until craft is complete

![1](https://user-images.githubusercontent.com/29095770/86805962-fb38d300-c0aa-11ea-8153-a397bcd721a5.png)

**Comment by Darkere** [comment]
Use the Issue Template!!!

Going to save you the time and say that this is fixed for 1.15. There are currently no plans to backport the changes.

**Comment by Luohuayu** [comment]
Ok. Thanks
