### ISSUE TITLE
[1.15.2] Login timeout

### ISSUE THREAD

**Issue by bloodyraoul** [refinedmods/refinedstorage#2598]
#### Issue description:
When joining my server, 95% of the time, i have a timeout on login :
Encrypting... screen, then timeout occurs and I have cant join server, disconnected
server side, the only log is : 
```
[08Jul2020 09:44:55.900] [User Authenticator #28/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player bloodyraoul is b1f7b606-9889-49c9-91a8-edc5c7477947
[08Jul2020 09:45:27.668] [Server thread/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: com.mojang.authlib.GameProfile@46cf5046[id=b1f7b606-9889-49c9-91a8-edc5c7477947,name=bloodyraoul,properties={textures=[com.mojang.authlib.properties.Property@7755670a]},legacy=false] (/XX.XXX.XX.XX:24914) lost connection: Timed out
```

I am looking for the reason of this issue for weeks  but cant find any error log telling me why
It is not because of slow connection, I have fiber
I have first thought it was my server provider, but I can reproduce it with a local server
I have tried to add RandomPatches mod to change the login timeout and  read timeout

it is not map related because i have the same problem on a new map

I have remarked it happens more often on a slow computer or if other programs are running
It seems to be a clientside problem

I use RaoulTech modpack : https://www.curseforge.com/minecraft/modpacks/raoultech 
So I have tried to remove mods one at a time to find the one causing this.
I have remove refined storage, login is long but I can connect 100% of the time.
Do you have an idea ?
Do you do lot of stuff during the login phase that cannot be done later ?

- Minecraft: 1.15.2
- Forge: 31.2.31
- Refined Storage: Refined Storage 1.8.6

maybe it is not related to refined storage but please have a look at it
thanks

**Comment by raoulvdberge** [comment]
Can you reproduce this issue with just RS?

**Comment by raoulvdberge** [comment]
RS does nothing during login.

**Comment by Darkere** [comment]
For some reason Voxel math is happening when you are joining a server. 
Before I assumed this was an issue with Cyclic https://github.com/Lothrazar/Cyclic/issues/1437

However, a quick test with just RS shows that we are also doing that. 
![image](https://user-images.githubusercontent.com/4283717/87088799-ad040b00-c235-11ea-98ad-51d184721c30.png)
[Profiling Snapshot](https://github.com/refinedmods/refinedstorage/files/4899424/RSjoinVoxel.zip)

**Comment by raoulvdberge** [comment]
The voxelshape stuff is really expensive. RS needs proper caching, like Refined Pipes has.

**Comment by Darkere** [comment]
Just did a separate test in a large modpack. RS and cyclic both appear the same way while Refined Pipes doesn't. 

So I think you might just be correct on that one.

**Comment by bloodyraoul** [comment]
I cannot reproduce it with only refined storage
it is a sum of lot of mods + refined storage that cause the issue
can you do something about that or I just have to change my computer for a better one ? :)

**Comment by raoulvdberge** [comment]
Closing this in favor of #2599 

It is an issue with RS. We can fix that.

**Comment by raoulvdberge** [comment]
Fixed for next version

**Comment by bloodyraoul** [comment]
wahoo, thank you so much for having fixed this issue ! it was so difficult to connect to my server for months !
really thank you

**Comment by DiabolosMan** [comment]
Thanks for this fix !!!! It was a nightmare to connect and now it works !

**Comment by raoulvdberge** [comment]
Nice to hear!
