### ISSUE TITLE
Huge performance issues during rain

### ISSUE THREAD

**Issue by ChloeDawn** [refinedmods/refinedstorage#2599]
#### Issue description:
Performance is impacted significantly during rain
#### What happens:
This line here - and similar lines in the other block classes - causes particle collision to grind to a near halt.
https://github.com/refinedmods/refinedstorage/blob/a0385e2477ebf1e0acfbb6e14bb3b440f2e4380c/src/main/java/com/refinedmods/refinedstorage/block/ConstructorBlock.java#L58
#### What you expected to happen:
I expect performance during rain to be identical to performance during clear weather.
#### Steps to reproduce:
1. Create a storage network with various cables and constructors, exporters, etc.
2. Toggle rain on.
3. Hang around among the cables and devices.
4. Observe performance drop.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 13.2.30
- Refined Storage: 1.8.6

Does this issue occur on a server? Yes

**Comment by Darkere** [comment]
How did you come to this conclusion? Just tried and can't seem to reproduce this.

**Comment by raoulvdberge** [comment]
The collision code could use some caching.

**Comment by ChloeDawn** [comment]
Here is a snapshot of the CPU time @Darkere 
![javaw_09-07-2020_11-45-40](https://user-images.githubusercontent.com/9869940/87030586-ba8ba780-c1d9-11ea-961b-fbd50edd4a1e.png)

**Comment by raoulvdberge** [comment]
Fixed now. The shapes are now being cached during startup.
