### ISSUE TITLE
Regulator Upgrade support for Crafters

### ISSUE THREAD

**Issue by ChloeDawn** [refinedmods/refinedstorage#2600]
It would be great to see this upgrade support crafters for processing recipes that take inputs of strict counts. Say you have a machine that processes 2 of "a" into 1 of "b". If you request a crafting operation for 10 of "b", it would put 20 of "a" into the machine, and that machine may no longer execute its processing. If it could be regulated, the crafter would only allow in the 2 "a" until the input slots were empty again.

**Comment by tth05** [comment]
Sounds like the "Insert next set on pulse" mode

**Comment by raoulvdberge** [comment]
No.
