### ISSUE TITLE
Feature Request: Allow specifying time for processing recipes.

### ISSUE THREAD

**Issue by Megacrafter127** [refinedmods/refinedstorage#2606]
#### Issue description:
Unlike a crafting pattern, processing patterns can take wildly different amounts of time to complete a given job, due to the underlying work being performed by different machines.
So, suppose there are two processing patterns, one for A→B, and another for 9A→9B.
The machine performing A→B takes 2 seconds to complete a cycle, and the machine performing 9A→9B takes 9 seconds to complete a cycle.

As it is right now, RS does not know this timing information, so, assuming there are enough resources for both patterns in storage, it should always choose the same pattern, be it the individual or bulk pattern.
If RS chooses the individual pattern, craft-jobs requiring a lot of B will take twice as long as they otherwise would.
If RS on the other hand chooses the bulk pattern, craft-jobs requiring only 1 of B will consume more of A than necessary, and take a bit more than 4 times as long as necessary.

As such, I suggest that the player should be able to specify a time for processing recipes.
RS can then use that timing information to choose whether or not individual or bulk patterns are appropriate for a given craft-job.

Using the above example patterns:
- A craft job requiring 3B to be crafted should use 3(A→B) [the pattern A→B 3 times]
- A craft job requiring 18B to be crafted should use 2(9A→9B) [the pattern 9A→9B 2 times]
- (optionally) A craft job requiring 28B should use 3(9A→9B)+1(A→B) [pattern 9A→9B 3 times, and pattern A→B once]

Thank you for your time.

**Comment by raoulvdberge** [comment]
Thank you for the feature request. Unfortunately I believe that this makes the auto crafting mechanics too complex and unpredictable. For that reason, your request has been denied.
