### ISSUE TITLE
Crafting is not remembering recipe and duplicating resources

### ISSUE THREAD

**Issue by shanekremer** [refinedmods/refinedstorage#2608]
#### What happens:
1. Using the wireless crafting grid, put in a recipe, Oak Chest, for example. Pull out 1 chest. Now you can't pull out anymore, even though the recipe is correct. You have to reset the recipe to do it again.

2. Shift + clicking will give you a stack of chests, but it won't deplete any resources from the system.

This only started happening on updating to RF 1.8.7
Here is the custom modpack I'm using: https://www.curseforge.com/minecraft/modpacks/noobville/files/all

#### What you expected to happen:
1. The oak chest is still shown on the right and able to be pulled out.

2. Resources in the system are depleted to make the items

#### Steps to reproduce:
1. Open wireless crafting grid
2. Craft something (anything)
3. Single-click to pull out one item
3a. Shift + click to pull out a stack
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.29
- Refined Storage: 1.8.7

Does this issue occur on a server? [yes/no] 
Yes

#### If a (crash)log is relevant for this issue, link it here:

Posted some images of the bug here:
https://imgur.com/a/BfTZRos

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Does the same happen in a stationary crafting grid? Or only in the wireless crafting grid?

**Comment by shanekremer** [comment]
The vanilla crafting grid works as expected. Only happens in the RF crafter.

**Comment by Darkere** [comment]
Ok yep confirmed issue. Hotfix will hopefully be going out soon.

**Comment by raoulvdberge** [comment]
Fixed for v1.8.8

**Comment by shanekremer** [comment]
I tested in 1.8.8 and it's still happening.

**Comment by Darkere** [comment]
Add-ons needs an update too it seems. Although I thought that would produce an error. (it doesn't).

Side note: Seems like you are still shipped the old folders. (just folders nothing inside them)
![image](https://user-images.githubusercontent.com/4283717/87396247-d795f100-c5b2-11ea-911b-da958354a552.png)

**Comment by raoulvdberge** [comment]
That doesn't make sense. RS add-ons should use the RS crafting grid behavior. So if RS updates it's logic, RSA would also be fixed. Also, RSA wasn't updated since your performance fixes to that logic @Darkere

**Comment by Darkere** [comment]
Well the Crafting Grid blocks works as intended while the wireless crafting grid dupes things... 

The error doesn't quite seem the same as the one reported... Weren't there API changes in commit?

**Comment by raoulvdberge** [comment]
Yeah, I would also expect it to crash. The API interface changed.

**Comment by Darkere** [comment]
Do you have the time to look at it?  I would need to set up a workspace for addons first.

**Comment by raoulvdberge** [comment]
It will be for later today.. currently stuck cooking :s

**Comment by raoulvdberge** [comment]
Even then, I would still have to release and test manually.

**Comment by raoulvdberge** [comment]
OK, now fixed for RS addons. Unfortunately my Jenkins is broken, so RSA can't use the new RS dependency. I can only release after that is fixed...
