### ISSUE TITLE
[Request] Tag-based filters

### ISSUE THREAD

**Issue by chimericdream** [refinedmods/refinedstorage#2617]
The server I play on has a couple of mods and datapacks that give more mob heads and microblocks (inspired by/stolen from HermitCraft). These have various different names, but they all have the `forge:heads` or `minecraft:heads` tag. It would be awesome if the filters you can put in a crafting grid had support for filtering based on these tags.

**Comment by raoulvdberge** [comment]
Noted. Moved too #2372
