### ISSUE TITLE
Unable to create a new world with Refined Storage installed

### ISSUE THREAD

**Issue by L0rdLogan** [refinedmods/refinedstorage#2620]
#### Steps to reproduce:
1. Launch Minecraft with Refined Storage & Forge installed
2. Create a new world
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.1
- Forge: 32.0.67
- Refined Storage: 1.9.1

Does this issue occur on a server? yes (internal server for singleplayer)

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/Ldi5Smns

**Comment by Darkere** [comment]
For now, you can downgrade forge 1 version to get it fixed.

**Comment by raoulvdberge** [comment]
Don't close this, downgrading Forge is not a real fix.

Looks like BC was broken. No big deal, since Forge is still beta anyway.

**Comment by L0rdLogan** [comment]
> Don't close this, downgrading Forge is not a real fix.
> 
> Looks like BC was broken. No big deal, since Forge is still beta anyway.

Apologies, downgrading to 32.0.66 did resolve the issue, stuff is definitely broken as you can't get to the JEI config either in game - that is nothing to do with refined storage. I think it'll be in beta a while - I am surprised to see a mod like Refined Storage be updated so quickly

**Comment by raoulvdberge** [comment]
This is fixed for the next version.
