### ISSUE TITLE
Interface Export Slot Scrolling

### ISSUE THREAD

**Issue by wojoeraf** [refinedmods/refinedstorage#2622]
[crash-2020-07-16_16.39.00-client.txt](https://github.com/refinedmods/refinedstorage/files/4932225/crash-2020-07-16_16.39.00-client.txt)
#### Issue description:
Crash while scrolling in Interface slot

#### What happens:
Crash while scrolling in Interface slot

#### What you expected to happen:
No Crash

#### Steps to reproduce:
1. Open interface
2. Place item in export slot
3. Scroll with mouse over item in export slot
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2821
- Refined Storage: 1.6.15 

Does this issue occur on a server? [yes/no]
singleplayer mode

#### If a (crash)log is relevant for this issue, link it here:
see attachment
[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Issue with MouseTweaks.

**Comment by wojoeraf** [comment]
Not sure. Found this on their side: https://github.com/YaLTeR/MouseTweaks/issues/15

**Comment by raoulvdberge** [comment]
1.12 is unsupported.

**Comment by wojoeraf** [comment]
How is 1.12 not supported? Refined storage as well as mouse tweaks have official versions for 1.12?
