### ISSUE TITLE
1.9.1 crashes dedicated server Forge 1.16.1 build 32.0.68

### ISSUE THREAD

**Issue by kreezxil** [refinedmods/refinedstorage#2624]
Notes: NoSuchMethodError caused by Forge changing the command class in build 67
     

crash report: 
https://gist.github.com/297c7529fa9398ec4fb09e88c684183f

fml server latest: 
https://gist.github.com/4e479df996ca66a7d43c4d73ac305376

**Comment by raoulvdberge** [comment]
Yes, this has already been fixed for next release.
