### ISSUE TITLE
Sadly this amazing mod seems incompatible with the new forge 32.0.68

### ISSUE THREAD

**Issue by Fidulus** [refinedmods/refinedstorage#2626]
... and that sums it up. ^^

Sorry i had to disable a lot of mods because of the new forge version and don't know exactly which log file i could provide, but you just need to try to start a new world and it should crash with your mod.
I hope you can fix it.

I love what you did and hope you will keep on maintening it.

**Comment by Darkere** [comment]
Already fixed for next version. Stay on 66 until then if you need the mod.

**Comment by raoulvdberge** [comment]
Thx for the compliment @Fidulus !

As Darkere said, fixed for the next version already.

I doubt it will help, but let me pin this so that we won't end up with even more duplicates.

**Comment by raoulvdberge** [comment]
Fixed in 1.9.2
