### ISSUE TITLE
crashes on newest forge update

### ISSUE THREAD

**Issue by Warbringer12** [refinedmods/refinedstorage#2628]
#### Steps to reproduce:
1. launched single player
2. crashed
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:  1.16.1
- Forge: 32.0.70
- Refined Storage: 1.9.1

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here: 
[crash-2020-07-18_17.32.13-server.txt](https://github.com/refinedmods/refinedstorage/files/4943080/crash-2020-07-18_17.32.13-server.txt)

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
update to latest

Next time, first check if there's a newer version available before reporting.
