### ISSUE TITLE
MysticalAgradditions not able to craft thier recipes 

### ISSUE THREAD

**Issue by bash90** [refinedmods/refinedstorage#2629]
#### Issue description:
MysticalAgradditions

#### What happens: 
trying to carft stuff from MysticalAgradditions and the grid show nothing 

#### What you expected to happen:
crafting 

#### Steps to reproduce:
1. have MysticalAgradditions
2. craft stuff (crating grid)
3. u can't 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2854
- Refined Storage: 1.6.16

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.12 is unsupported.
