### ISSUE TITLE
[1.16] World deadlock with Portable Grid

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#2632]
#### Issue description:
 World locks up and becomes impossible to load (Stuck at 100%)

#### Steps to reproduce:
1. Place down portable grid with disk
2. reload world. 

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.1
- Forge:32.0.75
- Refined Storage:1.9.2

![image](https://user-images.githubusercontent.com/4283717/88463948-f059ad00-ceb6-11ea-870b-cda9cf43fef1.png)

Problematic code at PortableGridTile line 544. 

Can be solved by removing the disk.

**Comment by james58899** [comment]
If anyone run into deadlock can't open server
can workaround by setting openUsage > capacity
