### ISSUE TITLE
Autocrafter can't use the Fluid Tank from EnderIO to fill buckets

### ISSUE THREAD

**Issue by snydej** [refinedmods/refinedstorage#2639]
#### Issue description:
Attempting to use a processing recipe that turns 1 bucket and 1000mb of water into a bucket of water fails. The bucket goes into the Fluid Tank but the water doesn't.

Also it should be noted that my usual stopgap for "difficult" recipes is to have the crafter place everything into an inventory and then I can pipe it where it needs to go to do the craft. I have even automated Draconic Evolution infusion crafting in this way and yet now I'm stuck on buckets because I don't know of anything that serves as an inventory for both items and fluids.

It seems like Refined Storage relies heavily on the player being able to use (or wanting to use) the Fluid Transposer from Thermal Expansion (I don't want to use it because it's slow and takes power). I argue that buckets of water and lava are vanilla items and so should be autocraftable without any additional mods (for instance by placing the liquid in the world and using a dispenser).

Here are some ideas I had on how to solve this more general problem:
1. Provide some kind of buffer inventory block that can hold both items and fluids.
2. Have the crafter hold fluids in an internal tank that can be pumped out of if the block it's pointed at doesn't accept fluids.
3. Allow a recipe to be split up so that one crafter delivers the items and another delivers the fluid. In general being able to split up the items in a recipe would be a fantastic feature since every mod nowadays seems to want some kind of tedious infusion crafting.

#### What happens:
The bucket goes into the Fluid Tank but the water does not. The crafting monitor doesn't show any issue regarding the water not going into the tank.

#### What you expected to happen:
Both the bucket and water should be put into the tank so that the tank can fill the bucket

#### Steps to reproduce:
1. Make the processing pattern described at the top.
2. Place a Fluid Tank and put a Crafter on top pointing down at it 
3. Put the pattern in the Crafter and connect the crafter to the autocrafting system
4. Make sure there is at least 1000mb of water in the autocrafting system.
5. Request that a bucket of water be crafted.
6. Note that the empty bucket was placed in the tank but the tank is still empty.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:
- Refined Storage: 1.6.15

If it matters the pack I'm playing on is: FTBRevelation-3.2.1-1.12.2

Does this issue occur on a server? [yes/no]
I don't have a server to test with.

**Comment by Darkere** [comment]
I assume you are certain the pattern contains water and the water isn't just getting moved somewhere before the tank can use it?

I recall using this setup quite a bit. And the crafting will never insert only half the recipe.

Also check logs when you do this (there is a potential warning about voiding liquids).

**Comment by snydej** [comment]
I found the problem. The pattern got created with the liquid water being set as an output rather than an input; I didn't inspect it too carefully I just looked to see that the water was there, oops. I created the pattern from the Ender IO tank recipe for a water bucket in JEI. It correctly has the empty bucket as an input and the filled as an output, so I didn't use the wrong recipe. Creating the pattern using the Fluid Transposer recipe in JEI makes the correct pattern that can then be used to fill buckets with the Ender IO tank.

I think the pattern grid should show the fluids used in a pattern and there shoud be a way to manually modify them.

**Comment by raoulvdberge** [comment]
There is a way to toggle fluid visibility. Use the side button

**Comment by snydej** [comment]
I think you should at least take care of the bug where the pattern gets filled in wrong. JEI correctly knows that that recipe is a use for liquid water and not a recipe for liquid water.

**Comment by Darkere** [comment]
AFAIK that bug is in JEI
