### ISSUE TITLE
Issue regarding autocrafting

### ISSUE THREAD

**Issue by KrAzYGEEK32** [refinedmods/refinedstorage#2640]
#### Issue description:
Autocrafting seems unreliable with processing
#### What happens:
when bulk requests are made, system seems to get stuck on processing state for some materials, but doesn't actually input the stuff to the relevent machine, I couldn't find a discord to discuss the issue before posting it here, so this is pretty raw 

#### What you expected to happen:
When items are in processing state, they should be in the relevent machine
#### Steps to reproduce:
1.its not 100% reproducible, but here we go
2.attach a crafter to any machine( in my case a mekanism crusher)
3.bulk order 1000 gravel (or an big arbitrary number)
4. System possibly gets stuck in processing state for the last few processes left

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.1
- Forge:32.0.75
- Refined Storage:1.9.2

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by KrAzYGEEK32** [comment]
I was unable to reproduce this effectively in a creative world, so this might be a server specific issue, but the issue is there

**Comment by Darkere** [comment]
Can you post a screenshot of the stuck crafting task?

**Comment by KrAzYGEEK32** [comment]
[https://imgur.com/a/dLJCuCe](url) this is an example, here all of the redstone processing is queued up, but there is no ore going into the machine

**Comment by KrAzYGEEK32** [comment]
but, now that i observed it more, im guessing chunkloading is the issue, because the controller is loaded but the partcular crafter isnt, will that have an effect on the process?

**Comment by raoulvdberge** [comment]
Not necessarily. Is the machine loaded connected to it?

**Comment by KrAzYGEEK32** [comment]
yes it is connected to the controller

**Comment by raoulvdberge** [comment]
The machine that you are using for the processing. Is it chunkloaded?

**Comment by KrAzYGEEK32** [comment]
it is not

**Comment by raoulvdberge** [comment]
Can you try chunkloading it?

**Comment by KrAzYGEEK32** [comment]
i am chunkloading it now and it seems to work fine, i.e. ive not yet noticed any anomalies, i will report back i find any

**Comment by KrAzYGEEK32** [comment]
![2020-07-30_19 42 36](https://user-images.githubusercontent.com/59537798/88933304-d811d580-d29c-11ea-842f-3d77cd5fc3f0.png)
seems like even with chunkloading, the processes are getting stuck, those two processes are stuck in processing state

**Comment by KrAzYGEEK32** [comment]
i think chunkloading doesnt affect this, as for these processes(and few others i did later which also got stuck), although i was babysitting them, they seemed to get stuck in processing state without actually inputting the materials to the relevent machine

**Comment by KrAzYGEEK32** [comment]
![2020-08-06_13 53 06](https://user-images.githubusercontent.com/59537798/89509230-ae9d0080-d7ec-11ea-8a86-28c30d8001b8.png)
umm, this is getting out of hand, it says its processing, and no items were put into the machine.. again!!
this particular crafter points towards a vanilla barrel, and it didnt put in the right amount for the recipe

**Comment by KrAzYGEEK32** [comment]
i play on the official E6 server, and Darkare came in the other day to check the inconsistencies but we couldnt figure out much :(, he worte it off as a mekanism bug that time, but this time its a vanilla barrel

**Comment by KrAzYGEEK32** [comment]
to clarify the above pic, i ordered 10 turbines, 3 got crafted and the rest 7 didnt because of missing gold

**Comment by KrAzYGEEK32** [comment]
i am closing this issue for the time being, will reopen if i find some anomalies sans mekanism
