### ISSUE TITLE
Constructors do not extract blocks when placing them

### ISSUE THREAD

**Issue by ochotonida** [refinedmods/refinedstorage#2641]
#### Issue description:
Constructors do not extract blocks when placing them
#### What happens:
The amount of blocks in the storage system stays the same when constructors places a block
#### What you expected to happen:
When a constructor places a block, the amount of blocks in the storage system should decrease by one
#### Steps to reproduce:
1. Create a storage system
2. Add a constructor and configure it to place a block from the system
3. ????
4. profit

https://streamable.com/engvbr

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.1
- Forge: 32.0.70
- Refined Storage: 1.9.2

Does this issue occur on a server? yes

**Comment by Darkere** [comment]
Fixed in dev
