### ISSUE TITLE
[suggestion] Keep search feature for grids

### ISSUE THREAD

**Issue by KrAzYGEEK32** [refinedmods/refinedstorage#2642]
just a little suggestion, as its pretty annoying to type stuff all the time when switching grids. it doesnt help that, things like crafting monitors exist, as you have to switch grids for sure to monitor crafting progress, and the search resets

**Comment by raoulvdberge** [comment]
Sure, we can add this as a client config. This can't be a per-grid sidebutton config, since the search query isn't persisted to the server, and we don't want to cause conflicts with other players who may open a grid.
