### ISSUE TITLE
Missing recipes of processors

### ISSUE THREAD

**Issue by piesio98** [refinedmods/refinedstorage#2644]
On Forge multiplayer, recipes of raw processors seems to be missing. Recipes are showing on jei but with no outcome.

BUT

ON singleplayer all is fine.

- Minecraft: 1.16.1
- Forge: .98
- Refined Storage: 1.9.2
- refinedstorageaddons-0.7
- extradisks-1.16.1-1.3

Does this issue occur on a server? [yes/no]
 YUP

====
![image](https://user-images.githubusercontent.com/6825486/89111106-26b4a080-d452-11ea-8523-dc5f45cb9c1e.png)

====
![image](https://user-images.githubusercontent.com/6825486/89111097-13093a00-d452-11ea-9710-4063bece7c88.png)

====
![image](https://user-images.githubusercontent.com/6825486/89111163-c5410180-d452-11ea-8b68-f338fa832c94.png)

====

![image](https://user-images.githubusercontent.com/6825486/89111166-cd00a600-d452-11ea-8f92-0faa801bc1c9.png)

**Comment by Darkere** [comment]
Please try to reproduce with just RS, as it does not happen in my test. 

There might be info on which mod is causing it in the latest.log or debug.log

**Comment by SpencerIsSalted** [comment]
having the same issue, as well as my old patterns I made (all the processor types, and importer/exporter, for example) are no longer working in my crafters.

Took them out of the crafter, and the crafter no longer accepts the patterns.

**Comment by piesio98** [comment]
It seems that /reload command fixes recipes

**Comment by raoulvdberge** [comment]
I'm gonna go ahead and assume this isn't an RS issue.
