### ISSUE TITLE
Way to transfer items from item Disks to an other one?

### ISSUE THREAD

**Issue by Singularitaet9** [refinedmods/refinedstorage#2646]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
If the disk item still mentions the correct item count, restart your client.

**Comment by Singularitaet9** [comment]
@raoulvdberge I did and I know that there were similar issues. Did this et fixed? If not: I did break the controller, place it again, restart, restart the server, put disks out and in again and even some more things. You once said somewhere it’s a forge bug.
Can I fix it or transfer the items to an other (hopefully not broken) disk.

**Comment by Singularitaet9** [comment]
And yeah it’s probably the sane bug as breaking the drive with disks inside (because I don’t know if someone on my server did that, it’s not impossible)

**Comment by Singularitaet9** [comment]
Why did that get deleted but no one answered or told me why?
Confusion 1000

**Comment by raoulvdberge** [comment]
I deleted because you were making wrong assumptions about a bug. This will confuse other people that might stumble upon this issue. I'll get back to you later.

**Comment by Singularitaet9** [comment]
Okey thank you! Is the other bug different in that case? Will the other bug completely destroy the items or did it get fixed?


However I’m going to note that we are playing on a server and I’ll check as soon as possible if I (myself) can access the grid or if it’s just my friend who can’t do that.

**Comment by Singularitaet9** [comment]
I don’t know why but now, 3 days after the bug, it suddenly disappeared and he can see the items again. Thank you for helping me anyway.
