### ISSUE TITLE
[1.15.2] 'Exception in server tick loop'

### ISSUE THREAD

**Issue by atoldiago** [refinedmods/refinedstorage#2648]
#### Issue description:

I have, literally no idea what to describe, as I am a laymen when it comes to this sort of thing. I can navigate a server, but mods to Minecraft elude me.

#### What happens:

Upon completion of server startup, it immediately crashes with the titled issue. 
Here both crash logs that get generated from this:
[crash-2020-08-07_21.37.03-server.txt](https://github.com/refinedmods/refinedstorage/files/5043814/crash-2020-08-07_21.37.03-server.txt)
[crash-2020-08-07_21.38.03-server.txt](https://github.com/refinedmods/refinedstorage/files/5043816/crash-2020-08-07_21.38.03-server.txt)

The second one explains: "ServerHangWatchdog detected that a single server tick took 60.00 seconds," and for transparency, the allocation of blame on refinedstorage was given by Creeperhost's notifications upon server crash. Claims the exception error originated from 'refinedstorage-1.8.8.jar.'

#### What you expected to happen:

I havent even been able to create anything from refined storage myself, however one of the other players has and, as far as I know, is the only one on the server that has crafted anything related to it.

#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.33
- Refined Storage: 1.8.8

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by atoldiago** [comment]
Reading through that first log, I did notice reference to Immersive Engineering. Maybe its an issue with the power connectors there, being used to power refined storage? Again, I am lost with this stuff. Thank you for any help to figure this out. We've been having a lot of issues on the server lately and its getting to be a bit much.

**Comment by Darkere** [comment]
First crashlog refers to a recently fixed Immersive Engineering bug. 

Second crashlog is a watchdog crash which makes it utterly useless in figuring out what may be at cause. Watchdog crashes happen when a lag spike is too large. It is impossible to tell what causes it from the crashlog.  I have no idea how Creeperhost tried to determine the cause.

**Comment by atoldiago** [comment]
I updated IE yesterday, and the crashes have been happening since then. How should I proceed? Ive already double checked the update for IE on the server (matches the latest posted two days ago 3.1-111). So should I post this to their tracker instead?

**Comment by Darkere** [comment]
Yes you should go to their issue tracker. 

Sorry I the fix I remembered was for 1.16.

**Comment by atoldiago** [comment]
Currently drafting the post now, thank you!
