### ISSUE TITLE
[1.15.2] Crafter sending more recipes at once in a machine

### ISSUE THREAD

**Issue by kill05** [refinedmods/refinedstorage#2652]
#### Issue description:

Crafter sending more recipes at once in a machine

#### What happens:

The autocrafter puts in many recipes per time. As an example, in the modpack i'm playing(Q-tech), to make quartz enriched iron, you need to put in an alloy smelter vanilla quartz and refined iron. Refined iron is made with iron and sand inside an alloy smelter. So I've setup a crafter with both recipes in it, i've set the crafter on "redstone signal locks autocrafting", with a comparator on the back of the alloy smelter, as shown here: https://user-images.githubusercontent.com/50295718/89906438-af1e0880-dbeb-11ea-93f3-3f1f615a7daf.png
The problem is that the crafter sends both the items for both recipes at the same time, so the comparator can't stop the crafter. The same problem happens with other mods' machines that work like the silents mechanism's alloy smelter.

#### What you expected to happen:

The system to send one craft per time and not both of them together.

#### Steps to reproduce:

1. Set up an autocrafting for silents mechanism's alloy smelter
2. Ask for a recipe that needs two different alloys in the alloy smelter

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.31
- Refined Storage: 1.8.8

Does this issue occur on a server? [yes/no]

No

**Comment by Darkere** [comment]
With your setup. The machine receives the first set of items. Then the comparator turns on and unlocks the crafter. Then RS inserts the next set. 

You need to rethink how you are doing the redstone signal. You want to output a signal when the comparator turns off.

**Comment by kill05** [comment]
no, because it is in redstone LOCKS autocrafting, and it works when I only ask the system to make refined iron. Anyways I've found a workaround, using redstone pulse inserts next set and it works for me. Still I consider this as a bug.

**Comment by Darkere** [comment]
Ah. I see. Yeah, that is indeed problematic.

The redstone signal can only be activated a tick after the crafter has inserted its items. So if 2 things get inserted in the same tick it doesn't work. 

I don't see a solution for this. People who want to use the feature like that will have to limit the crafter to only one recipe (simultaneously) and not use speed upgrades.

**Comment by kill05** [comment]
anyways is not that big of a deal, as I found out that using redstone pulse inserts next set works fine with the same setup.
