### ISSUE TITLE
Problem with furnace and import bus

### ISSUE THREAD

**Issue by Hellyclaster** [refinedmods/refinedstorage#2653]
Import bus does not pick up item from furnace output and pick up coal
video - https://youtu.be/1c2uzH4Za1k
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Refined Storage: 1.6.16

Does this issue occur on a server? [yes/no]
no

**Comment by kill05** [comment]
vanilla furnaces can only output from the BOTTOM. Make sure the import bus is on the bottom. Items can only be put from top and fuel only from the sides. Make sure in your system buses are setup like so.

Also what is that video

**Comment by tth05** [comment]
Yeah. You're just extracting the coal from the back in your video. The back side is only meant for that.

**Comment by Hellyclaster** [comment]
Thx!
