### ISSUE TITLE
[1.16.1] ugly thing with AutoCrafting

### ISSUE THREAD

**Issue by Ischtaratu** [refinedmods/refinedstorage#2655]
#### Issue description:
Subject: Auto-crafting with Crafter-Unit

Recipes that require an additional item for the production (for example a saucepan for food => Pams Harvest Craft) need this item for each individual production. If I want to make 64 meals, the autocrafter also requires 64 pots.

The only stupid thing is that the pot is not used up in the recipe and is theoretically available again after production. With sequential production, 1 pot would be enough for 64 meals.

Not a real problem, but an ugly thing.

- Minecraft: 1.16.1
- Forge: 32.0.108
- Refined Storage: 1.9.2

Does this issue occur on a server? [yes/no] 
yes !

**Comment by raoulvdberge** [comment]
Yes, RS doesn't handle reusable items.
