### ISSUE TITLE
1.16 Cannot Modify Processing Recipes, Only shift-click them in from JEI

### ISSUE THREAD

**Issue by AJM10565** [refinedmods/refinedstorage#2658]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Explain better please
