### ISSUE TITLE
[1.15.2] Pushing cables with piston causes immediate server crash

### ISSUE THREAD

**Issue by Johnyknowhow** [refinedmods/refinedstorage#2663]
#### Steps to reproduce:
1. Build a refined storage network (mine had an exporter connected to the cable I tried to move)
2. Put a sticky piston next to the cable
3. Activate the sticky piston

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 1.15.2-31.2.36
- Refined Storage: 1.8.8

Playing with Refined Storage in the Valhelsia 2 - 2.2.8 modpack.

Does this issue occur on a server?
Yes.

#### If a (crash)log is relevant for this issue, link it here:

https://gist.github.com/Johnyknowhow/c4d124603131c9ff38730f9cecc35d6b

**Comment by Darkere** [comment]
Caused by quark. 

They need to fix this https://github.com/Vazkii/Quark/issues/2300 before we can look if we can possibly support it.

**Comment by Johnyknowhow** [comment]
Gotcha. Thanks! At least it isn't that game-breaking of a bug or anything, haha.
