### ISSUE TITLE
[1.12.2 ]Server crash if a very large autocraft

### ISSUE THREAD

**Issue by GammelBro** [refinedmods/refinedstorage#2667]
#### Issue description:
My server is crashing if I request a large Reborn Storage cell.

#### What happens:
My server is crashing and I have to edit the world in mcEdit

#### What you expected to happen:
The craft wont even start or informs you that the craft is very large

#### Steps to reproduce:
1. Add autocraft for a 524M Fluid Cell
2. Try to craft the 524M Fluid Cell
3. Wait for the server crash
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.25.5.2847
- Refined Storage: 1.6.16
- Reborn Storage: 3.3.4.1

Does this issue occur on a server? [yes/no]
Yes it happens on a server

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/GammelBro/260da62c7c40a688599f7f9130a0ec6d
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
1.12 is unsupported.
