### ISSUE TITLE
broken system after crafting 10k items at once

### ISSUE THREAD

**Issue by TheNimbleNinja** [refinedmods/refinedstorage#2668]
#### Issue description:
did a craft of 10k items at once via shiftclicking output of a crafting recipe and broke the entire system all the items wont show up
#### What happens:
system entirely broken no items shown
#### What you expected to happen:
lag but not broken items
#### Steps to reproduce:
1.add stackup mod and refined storage
2.change the stack size to a high number 
3.craft an item out of refined storage and shift click the item out
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12
- Forge:forge-14.23.5.2854
- Refined Storage:refinedstorage-1.6.16.jar

Does this issue occur on a server? [yes/no]
maby not tested
no crash log

**Comment by raoulvdberge** [comment]
1.12 is unsupported
