### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Drakitty1259** [refinedmods/refinedstorage#2669]
Keeping subcrafting components in stock, in a practical way

You need a level emitter for each singular recipe, that does flashy stuff, and takes up space

My thoughts is a new type of Bus, that is usually affixed to a crafter; let's take redstone torches, pistons, trap doors, and hoppers.
normally you'd...have to have a level emitter for each of those, to identify each block, and then designate an amount, and....that would...what have to be applied to seperate crafters?!

How bout you make that a Bus, that can be expanded to the same number of slots as a crafter, and it has it's own card, that can be programed to have the item, and quantity, and it communicates directly to either a crafter, or machine. so 9 recipes, to keep  a stack of pistons, and redstone torches, hoppers, and more complicated FREQUENTLY USED components for more advanced materials.  otherwise, crafting a complicated block means you wait longer for all the sub crafting stages to complete ON DEMAND.   with this, you can have more free use frequently used supplies, to facilitate. 

I hope this is a valuable suggestion, that can be implemented.

**Comment by Darkere** [comment]
You are thinking of AE. In RS Detector + exporter does not even work (yet).

Check the wiki entry for Keeping items in stock. You can already do what you are suggesting with an interface.
