### ISSUE TITLE
[Suggestion] Fix Constructor duplication bug on 1.16.1

### ISSUE THREAD

**Issue by chastain1337** [refinedmods/refinedstorage#2671]
This bug was fixed in 1.9.3, the same version to port to 1.16.2. Modpacks stuck at 1.16.1 have no resolution.

**Comment by raoulvdberge** [comment]
Normally I wouldn't do this, but it seems like modders have trouble with 1.16.2. So let's do a patch release for 1.16.1.

**Comment by raoulvdberge** [comment]
Refined Storage 1.9.2 - Service Pack 1

**Comment by raoulvdberge** [comment]
Unfortunately I can't charge for expensive support contracts like Microsoft does.

**Comment by raoulvdberge** [comment]
Available on Curse now! Enjoy.
