### ISSUE TITLE
Tooltip shows wrong units for fluids

### ISSUE THREAD

**Issue by trejkaz** [refinedmods/refinedstorage#2674]
#### Issue description:

After putting one bucket of water into storage, the fluid grid shows 1, but the tooltip says "1.0 mB".

#### What happens:

![image](https://user-images.githubusercontent.com/43236/92977270-e7a55080-f4cf-11ea-9f6d-b3a3a63035c0.png)

#### What you expected to happen:

"1.0 B", or maybe "1000 mB".

#### Steps to reproduce:

1. Place controller, some power source, fluid storage, fluid interface, fluid grid
2. Dump a bucket of water into fluid interface
3. Hover over water in fluid grid

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.2
- Forge: 33.0.23
- Refined Storage: 1.9.5

Does this issue occur on a server? not tested but issue is with rendering so probably n/a

**Comment by raoulvdberge** [comment]
Can't reproduce this.
![image](https://user-images.githubusercontent.com/10358424/92977741-17cbff80-f48e-11ea-933a-4b9f3cda0d0c.png)
![image](https://user-images.githubusercontent.com/10358424/92977742-1a2e5980-f48e-11ea-9e45-2e3bd758e583.png)

**Comment by trejkaz** [comment]
Hmm. Different version of forge? Maybe I just have to bump up or down?

**Comment by raoulvdberge** [comment]
This is on Forge 33.0.37
