### ISSUE TITLE
RS Issue

### ISSUE THREAD

**Issue by iiMostafaX** [refinedmods/refinedstorage#2676]
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.15

Does this issue occur on a server? [no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Try an exporter with a spawner, with nbt and damage matching disabled.

**Comment by iiMostafaX** [comment]
> Try an exporter with a spawner, with nbt and damage matching disabled.

what is the exporter that u r talking about?? idk how to extarct it from the storage disk and moved it to another disk but still can't
pls i want help it contains too many spawners

**Comment by Darkere** [comment]
https://refinedmods.com/refined-storage/wiki/exporter.html

**Comment by iiMostafaX** [comment]
ok I tried the exporter but it doesn't work
the reason was because it just moves items that u allow by the id and when i tried to put the backpack as a whitelisted it just moved the backpack that i put and didn't move any other backpacks of the same sort
if u have any better way that i can extract the backpack by then tell me.
my discord acc (! H2 - Mostafa#1111)
and thx!
