### ISSUE TITLE
Invetory content deleted when using Mekanism cardboard boxes

### ISSUE THREAD

**Issue by csonyi** [refinedmods/refinedstorage#2677]
#### Issue description:
When using Mekanism cardboard boxes on RS Crafters and Crafting grid, contained items (Patterns and Filters my case) disappear after placing them back down and taking off the box.
Found several issues about it on Mekanism's github page, all suggesting that the bug is in RS, not Mek, and that the reason is that the blocks mentioned above don't write their contents to NBT tags.

#### What happens:
RS blocks are placed, cardboard box placed over them, picked up, placed down elsewhere.
Inventory is wiped, and even though they are placed next to RS blocks that are connected to a system, they aren't powered most of the time (haven't tested it extensively, and I might be wrong about the " most of the time" part... When it happened, I moved ~12 crafters, so I made several trips, and I think a few of them did connect to the system, but their inventories remained empty).

#### What you expected to happen:
Items not disappearing.

#### Steps to reproduce:
Trivial.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.16.1
- Forge: 32.0.108
- Refined Storage: 1.9.2 (not the latest, but I didnt see a mention of anything relating to the bug in any of the releases since)

Does this issue occur on a server? [yes/no]
Happened in SP, didn't try in MP.

**Comment by raoulvdberge** [comment]
Don't use block moving mods with RS, they aren't supported.
