### ISSUE TITLE
[1.16.1 / RS 1.9.2] Silent Gear/Gem's Intergration

### ISSUE THREAD

**Issue by ryanmckane** [refinedmods/refinedstorage#2679]
My first ever question/report so dont bash me if im wrong ;-)

#### Issue description:
Crafting Grid dont show Silent Geear's *ctrl* Tooltip 

#### What happens:
Slent Gear has an in-build tooltip if you press *left ctrl*. 

#### What you expected to happen:
If its possible, integration of tooltips from silent gear 

#### Steps to reproduce:
1. use Crafting Grid
2. hover ofer Silent Gear material
3. press *ctrl* and see if the tooltip appears
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.1
- Forge: 32.0.108
- Refined Storage: 1.9.2

#### Does this issue occur on a server? [yes/no]
no - local gameplay

**Comment by Darkere** [comment]
Duplicate of #2169

**Comment by ryanmckane** [comment]
oh! sorry! just searched for "silent" ...
