### ISSUE TITLE
Client crash with render error when right clicking on controller

### ISSUE THREAD

**Issue by Letoric** [refinedmods/refinedstorage#2685]
#### Issue description:
Client crashes with render error when right clicking on controller
#### What happens:
Crash
#### What you expected to happen:
Open UI
#### Steps to reproduce:
1.  Install jei-1.16.3-7.3.2.36, jeiintegration_1.16.3-6.0.0.8, JEITweaker-1.16.3-1.0.1.4, JustEnoughResources-1.16.3-0.12.0.100, refinedstorage-1.9.6, refinedstorageaddons-0.7.2
2. Create and join singleplayer world with cheats enabled
3. Spawn in/grab from JEI the controller
4. Place controller
5. Right click on controller.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.0
- Refined Storage: 1.9.6

Does this issue occur on a server? [yes/no]
It occurs in both singleplayer and multiplayer, however, the crash is client side only.

#### If a (crash)log is relevant for this issue, link it here:
https://paste.ee/p/n14Ck

**Comment by Darkere** [comment]
Already fixed for next version. Thanks for the report :)
