### ISSUE TITLE
Controller block crashes client when Interacted

### ISSUE THREAD

**Issue by InverseRain** [refinedmods/refinedstorage#2690]
#### Issue description:
Right clicking Controller block crashes client.

#### What happens:
^

#### What you expected to happen:
No crash.

#### Steps to reproduce:
1. Right click Controller.
2. Crash.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: forge-34.1.1
- Refined Storage: 1-9-6

Does this issue occur on a server? [yes/no]

yes

#### If a (crash)log is relevant for this issue, link it here:

https://paste.ee/p/cOm6B

**Comment by Darkere** [comment]
Duplicate of #2685

**Comment by InverseRain** [comment]
Ah, sorry, I tried looking but I didn't see it. Good to know it's been fixed.
