### ISSUE TITLE
Clicking on a controller crashes the game

### ISSUE THREAD

**Issue by helmkamp** [refinedmods/refinedstorage#2691]
#### Issue description:
Clicking on a controller crashes the game
#### What you expected to happen:
Something other than the game crashing ;-)
I just started using the mod, so I'm not sure what should happen. From videos I've seen, this action opens a window.
#### Steps to reproduce:
1. Place down a Controller or Creative controller
2. Right click on the controller
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.6.3
- Forge: 34.1.0
- Refined Storage: 1.9.6

Does this issue occur on a server? [yes/no]
I'm playing a single player game.
#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/PFFDBC2B

**Comment by error44044** [comment]
The exact same thing keeps happening to me and I don't know what to do except not use the mod, can anyone help me? Im on 1.18.2 with the current latest version of forge.
