### ISSUE TITLE
Transporters and interface

### ISSUE THREAD

**Issue by lulukas67** [refinedmods/refinedstorage#2701]
#### Issue description: The logistical Transporters aren't connecting to the interface
![2020-10-08_18 43 07](https://user-images.githubusercontent.com/72570129/95489941-cc771500-0997-11eb-9aa3-596277406961.png)

#### Steps to reproduce:
1. Place interface
2. Place logistical transporter next to it
3.It doesn't connect
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: using FTB infinity Lite
- Refined Storage: refinedstorage-1.2.25

Does this issue occur on a server?  Singleplayer AND Server

**Comment by tth05** [comment]
You're trying to connect Mekanism `Fluid` Pipes to an RS `Item` interface...

**Comment by lulukas67** [comment]
nope, these are item pipes (left = fluid / right = item)
![2020-10-08_19 52 59](https://user-images.githubusercontent.com/72570129/95495666-04825600-09a0-11eb-995f-e1cda0622c61.png)

**Comment by Darkere** [comment]
Try pipes from other mods. Wouldn't be surprised if it's a mekanism bug. 

Regardless 1.10 is not supported. Not by us or by Mekanism.
