### ISSUE TITLE
Exception in server tick loop crash

### ISSUE THREAD

**Issue by Moobien** [refinedmods/refinedstorage#2702]
Was initially having some issues with a remote ender io grain farm, ran both conduits and cabls down to bedrock level. Even though everything was connected there was no RS network at the grain farm. Installed a network reciever and then the transmitter behind a relay with no success, game crashed when I flicked the lever controlling the relay to turn it off and got the below crash.

Could be mod interaction but am unsure.

- Minecraft: 1.12.2
- Forge: 14.23.5.284
- Refined Storage: 1.6.16

Does this issue occur on a server? [yes/no] Negatice

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/F0UgNM4C

**Comment by raoulvdberge** [comment]
1.12 is not supported
