### ISSUE TITLE
Crafter Regulator

### ISSUE THREAD

**Issue by CKY-** [refinedmods/refinedstorage#2704]
Crafter Regulator upgrade that will only allow for one craft recipe to run at a time for blocks like  the "Powah Energizing Cube". 
Use the existing regulator, and make it only do one thing at a time.

**Comment by Darkere** [comment]
Use the crafter redstone modes.

**Comment by CKY-** [comment]
when doing complex crating  it will still put 3 different crafts in a single machine rather than one type of craft at a time.

**Comment by CKY-** [comment]
and yes i understand the fix for this is 5 different orbs one for each with redstone active however that's not elegant.

**Comment by raoulvdberge** [comment]
I think it's elegant

**Comment by Darkere** [comment]
Use pulse mode instead. It will block the crafter after insert instead of on redstone signal. This means it will only ever insert one type of item.

**Comment by CKY-** [comment]
Now that sir, is elegant thank you.. saves from having 15 9x9 cubes of lasers with 15 different orbs.

**Comment by Garueri** [comment]
''I think it's elegant'' was the best thing I heard today lol
