### ISSUE TITLE
Crafter Manager bug

### ISSUE THREAD

**Issue by Rithenar** [refinedmods/refinedstorage#2712]
#### Steps to reproduce:
1. place pattern in a crafter via the crafter manager
2. crafter manager wigs out
3. headache#
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.8
- Refined Storage: 1.9.7

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![image](https://user-images.githubusercontent.com/9939332/96353999-08486380-1097-11eb-922f-8bc8a63ce579.png)

![image](https://user-images.githubusercontent.com/9939332/96354002-139b8f00-1097-11eb-9e58-5b81381a249e.png)

**Comment by Darkere** [comment]
Did you maybe accidently sort the Craftermanager inventory?

**Comment by Rithenar** [comment]
I will not vehemently deny that I did, however, I do not recall clicking the middle mouse button when I was in the crafting manager.  If that is what caused it, however, my bad. I would recommend putting a safeguard for that though - I can't see any use to be able to auto-sort the crafter manager. Maybe allow the patterns to sort within the same crafter but not be able to exit and enter different crafters.  Just a thought.

**Comment by Darkere** [comment]
Yeah, unfortunately that is not something we can easily control.

**Comment by Rithenar** [comment]
bummer. Alright, thanks Darkere
