### ISSUE TITLE
Server Crash when shift scrolling in crafting terminal. 

### ISSUE THREAD

**Issue by DinnerBeef** [refinedmods/refinedstorage#2713]
#### Issue description:
Server crashed when shift scrolling in crafting terminal 
#### What happens:
Server crashed
#### Steps to reproduce:
1. Shift scroll in crafting terminal
2. 
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3 
- Forge: 34.1.22
- Refined Storage: 1.9.7

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/Jymh2Zs8
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Already fixed for the next version!
