### ISSUE TITLE
[1.16.3] Crafter rotated with wrench does not connect to machine

### ISSUE THREAD

**Issue by mtbrenner** [refinedmods/refinedstorage#2717]
Placing a crafter above a Mekanism machine with the crafter not pointing to the machine in the beginning will not recognize the machine when rotated towards the machine with the wrench.

The crafter is visibly aligned to the machine, but the label in the crafter interface still says "Crafter" and when trying to craft items with the machine you get the error "No machine found". If you stand next to the machine and place the crafter looking upwards so that the crafter immediately faces the machine without having to rotate it then the machine is recognized.

Expected result: The label of the crafter shows the machine name and autocrafting with it works. 

#### Steps to reproduce:
1. place machine, e.g. Basic Infusing Factory
2. place Crafter on top of the machine with the crafter not pointing to the machine
3. rotate Crafter with the wrench
4. Check label and try to autocraft with it.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.24
- Refined Storage: 1.9.7
- Refined Storage  Addons 0.7.2
- Modpack ATM6 1.1.6b

Does this issue occur on a server? [yes/no] yes

**Comment by Darkere** [comment]
Can confirm this. Although it doesn't seem to be caused by rotating the crafter. Seemed more like a specific orientation that broke.
