### ISSUE TITLE
Lag to the point of crash.

### ISSUE THREAD

**Issue by RaidingPanda24** [refinedmods/refinedstorage#2720]
#### Steps to reproduce:
1. If I'mma be completely honest, IDK how to replicate. We are playing Dungeons, Dragons, and Space Shuttles and have 90million items in our storage. 1 4096k disk, 3 16384k disks, 24,576,000mb disk, 53,248,000mb disk.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.16

Does this issue occur on a server? yes and on singleplayer if it matters

#### If a (crash)log is relevant for this issue, link it here:

It locks up java and after 45min of waiting no crash, therefore, no crash report made us force close it.

**Comment by tth05** [comment]
1.12.2 is unsupported. You can try my fork if you want support for this version
