### ISSUE TITLE
1.12.2 Refined Storage network receiver breaking

### ISSUE THREAD

**Issue by tacocat300000** [refinedmods/refinedstorage#2722]
Issue description: Network receiver breaks and drops on the ground as an item whenever connected to anything aside form a Network transmitter

What happens: whenever I have my network transmitter and receiver liked with the network card, if I connect anything else to the receiver, the receiver falls to the ground as an item.

What you expected to happen: The network receiver doesn't break, and I can put a controller, then a wireless transmitter to send and receive items to my main system. (Im trying to connect my main base in the overworld to the other dimensions in the modpack, twilight forest, cavern II, etc which is why I don't just use wireless transmitters instead.)

Steps to reproduce:
1. Connect network transmitter to a controller and power it
2. Place a network receiver anywhere in the world
3. Using a network card, connect the receiver and transmitter
4. Connect the network receiver to something (cable, controller, etc)
5. See that the network receiver has broken.

Version: 1.12.2

- Minecraft: 1.12.2
- Forge:14.23.5.2854
- Refined Storage: 1.6.16

Does this issue occur on a server? [no]

no crash log, error message, or anything else.

other info that might be useful: I am playing the Sky of Diamonds modpack, And the receiver was working fine before, but now it breaks. I have not changed any settings since it worked the first time.

**Comment by Darkere** [comment]
The network receiver breaks when you are trying to connect 2 networks together. They are used to extend a single network over distance (instead of cables). 

A network can only ever have 1 controller.

**Comment by p0t4t0sandwich** [comment]
This tends to happen if you have a controller on each end. You need to treat the Network Receiver like a controller: it acts as an extension to your home controller.
