### ISSUE TITLE
Crash when attempting to search in crafter manager

### ISSUE THREAD

**Issue by Letoric** [refinedmods/refinedstorage#2723]
#### Issue description:
In Crafter Manager, attempt to search (I tried to search for Steel) as soon as you try to type in the search box, the client crashes.

Does this issue occur on a server? [yes/no]
It occurs in a client/server game, but the crash is only on the client.

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/HVxjKxe0

**Comment by raoulvdberge** [comment]
Ah this is a small regression after my refactoring. You can avoid this crash for now by removing the invalid pattern from your crafters.
