### ISSUE TITLE
Refined storage system does not recognize redstone in system

### ISSUE THREAD

**Issue by grandogarndo** [refinedmods/refinedstorage#2726]
#### Issue description:
trying to use redstone in auto-crafting recipes and jei auto input doesn't work, but redstone does show up in the system
#### What happens:
redstone only appears in system, cannot be used by auto-crafting
#### What you expected to happen:
redstone being used in auto-crafting
#### Steps to reproduce:
1. download my large modpack
2. get a refined storage system and make a pattern with redstone included
3. Try and use the recipe
...

#### Version (make sure you are on the latest version before reporting):
Not the newest version but i don't believe it should matter
- Minecraft: 
- Forge: 31.2.43
- Refined Storage: 1.8.8

Does this issue occur on a server? [yes/no]

No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
This is very unlikely to be an issue with Refined Storage. You might want to try without any other mods.
