### ISSUE TITLE
Alternatives button not saving

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#2732]
#### Issue description:
When using the alternatives button on an ingredient in processing mode, the selected tags do not save. Using ctrl click works. 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.25
- Refined Storage: 1.9.8

Does this issue occur on a server? yes

**Comment by Szasdragon** [comment]
For me it worked, but not with a convenient mode.
Click on Alternatives, check the options, and after not SET instead click on CANCEL. The patern has the correct oredictionary recipe after this.
