### ISSUE TITLE
Fluid/item mixed processing patterns buggy

### ISSUE THREAD

**Issue by mijofa** [refinedmods/refinedstorage#2735]
#### Issue description:
There's some weird issues with the processing patterns that has just one fluid on one side, and just one item on the other side.
Works fine if I have 1 fluid and 1 item on the input, with just an item an the output. But if I have just a fluid on the input, and just an item on the output, the crafting monitor reports "no machine found"

I also found if I do certain things just right it can crash the whole server and it won't start until I edit refinedstorage_networks.dat and remove all the currently active crafting tasks. That one's much less predictable, but I recommend avoiding attempting to reproduce this issue on a world you care about.

#### Steps to reproduce:
1. Create a pattern with 1 bucket of Liquid Lithium in the input, and 1 Lithium Dust in the output
   NOTE: I have tested with other combinations of liquids and items, and I get the same results
2. Place a crafter pointing at a Mekanism Rotary Condenstrator
3. Place pattern in crafter
4. Request a Lithium Dust be crafted
5. [OPTIONAL, GAME BREAKING] Use Mekanism's configurator in wrench mode to rotate the Rotary Condenstrator around

#### What happens:
After step 4: Crafting fails, the Rotary Condenstrator recieves no input, and the Crafting Monitor reports "No machine found"

Imediatelly upon performing step 5: Game server crashes, stack trace attached. Won't start without removing the current crafting tasks from the data files manually.
The game crash doesn't always happen, and is a bit more finicky to reproduce, I found it reproduces more reliably if I have some other, working, autocrafting tasks happening at the same time. Such as 1024 wooden planks

#### What you expected to happen:
Liquid Lithium be inserted into the Rotary Condenstrator.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.25
- Refined Storage: 1.9.8
- Mekanism: 10.0.15

Does this issue occur on a server? Yes, both multiplayer and singleplayer

#### If a (crash)log is relevant for this issue, link it here:

Stack trace from crash on a singleplayer game http://ix.io/2D5L

**Comment by Darkere** [comment]
Should be fixed in #2734

**Comment by mijofa** [comment]
Ah, so it should.
Do you reckon the game crash is an unrelated issue?

**Comment by Darkere** [comment]
The crash should be a result of the mixup fixed in #2734. So related.

**Comment by mijofa** [comment]
Alrighty then, I'll see if I can figure out a build system for this mod so I can compile and give it a test later tonight. Thanks! :)

**Comment by raoulvdberge** [comment]
Alright then. Should be fixed.
