### ISSUE TITLE
Crashing bug

### ISSUE THREAD

**Issue by Garueri** [refinedmods/refinedstorage#2736]
#### Steps to reproduce:
1. Launch Minecraft and wait till it opens
2. Open Minecraft and the singleplayer tab
3. Launch my world and let it crash
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12
- Forge:1.12-2.6.2.83-universal
- Refined Storage:1.6.15

Does this issue occur on a server? [yes/no]
No. I'm playing singleplayer

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/HDUHQRXX

Things I have in my map that I can list to be strange:
I have a brine being produce and sent to the system at a 1500mb/tick rate, strange thing that once the value of brine reset in my network when it reaches a certain number, I have infinite solid and liquid storage disks on a disk drive

I was trying to extract water from a sink but for some reason, it wasn't staking inside the disk, so every time I would open the fluid grid, water would start to rise up in numbers, like if there was no inside, but my water-consuming machines were receiving water normally

Things I did to try and solve:
I removed cooking for blockheads trying too see if the sink would be the problem
When my world first stopped I was using the wireless crafting grid from Refinedstorage Addons, also removed it but nothing

PC Specs: I7-7700HQ/16gb RAM/Gtx 1050
And I have 8gb ram assigned to the modpack (btw its FTB Revelations)

If you have any knowledge or question, please feel free to do so

**Comment by raoulvdberge** [comment]
1.12 is unsupported
