### ISSUE TITLE
Disk manipulator texture error when connected to storage network

### ISSUE THREAD

**Issue by alyxferrari** [refinedmods/refinedstorage#2738]
#### Issue description:
The disk manipulator's texture changes to something similar to Mekanism's steel block when connected to a storage network. When not connected to a storage network, the texture is correct.

#### Steps to reproduce:
1. Place a disk manipulator. Make note of the texture.
2. Connect the disk manipulator to a powered controller. Make note of the new, incorrect texture.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.42
- Refined Storage: 1.9.8

Does this issue occur on a server? No

**Comment by alyxferrari** [comment]
Forgot to include a screenshot.
[Imgur Album](https://imgur.com/a/xkwCuOO)
Mekanism's steel block on the left, storage network connected disk manipulator on the right.

**Comment by kill05** [comment]
can confirm, also still happening in 1.9.9 with mc 1.16.4

**Comment by Hazmatik** [comment]
I noticed the block seems to rotate when it's placed on a network

**Comment by robertm1771** [comment]
Hazmatik is correct box texture is rotated 180
