### ISSUE TITLE
[Feature request] Exporting liquids and solids at the same time - Filters - Black/White list on exporters

### ISSUE THREAD

**Issue by Garueri** [refinedmods/refinedstorage#2740]
OBS - I'm not actually asking you to add these things,  I just had these ideas and wanted to share, if they are useful ok, otherwise, feel free to scrap it

Permit exporters to export liquids and solids at the same time
EDIT: Also, maybe bigger filters for the exporters?
EDIT2: Would also be cool if we could have black and white lists on exporters, so we could export anything
(like, I want to move my items from one disk to another, but the disk manipulation is too slow, so I make an exporter and blacklist nothing, so it'd export everything)

Let us have multiple crafters with the same recipes (already is implemented, forgive my dumbness)

**Comment by Darkere** [comment]
If two crafters have the exact same recipe tbey will already sbare the load.

**Comment by Garueri** [comment]
> If two crafters have the exact same recipe they will already share the load.
Indeed, I was dumb, just tested it

**Comment by raoulvdberge** [comment]
No, 1 block will not do both items and fluids at the same time.

**Comment by Garueri** [comment]
Thanks for the answerer mate, hope you find something cool out there!
