### ISSUE TITLE
[1.12.2] Cannot pull liquids from fluid grid with modded tanks

### ISSUE THREAD

**Issue by Theoooooo** [refinedmods/refinedstorage#2741]
#### Issue description:
I can't pull liquids from fluid grid with modded tanks

#### What happens:
I've put liquids inside my fluid grid with modded tanks (Thermal Expension tanks, Mekanisms, Ender IO) but i can't retreive liquids with these tanks :/

#### What you expected to happen:
I've expected to pull liquids from the fluid grid with modded tanks, but nothing is happening. I have to use vanilla buckets to do so

#### Steps to reproduce:
1. Put liquids inside the fluid grid with any fluid container
2. Try to pull fluids with modded tanks present in your inventory, it's not working

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no]
Yes

**Comment by raoulvdberge** [comment]
1.12 not supported
