### ISSUE TITLE
Problem with Large Fluid Tank

### ISSUE THREAD

**Issue by cyberpunkbln** [refinedmods/refinedstorage#2745]
Hello Refined Storage has a problem with Large Fluid Tank.

[FluidTank Issue](https://github.com/Kotori316/FluidTank/issues/65)

My debug.log is huge and the debug-snippet ist the only difference between my modpack with and without Refined Storage.

I hope it is a little bug.

At the moment is start without refined storage. For my luck i'm in the early phase of my world;).

thx

**Comment by raoulvdberge** [comment]
Minimal effort bug reports don't get handled, please respect my time. Respect the template and do some more debugging yourself.

**Comment by raoulvdberge** [comment]
I see `com.kotori316.scala_lib.util.LazySupplierWrapper` is interecepting RS code. We don't support that.
