### ISSUE TITLE
[1.16.4] Expanded Storage Support

### ISSUE THREAD

**Issue by TwilightPSN** [refinedmods/refinedstorage#2748]
#### Issue description:
Currently when using an external storage bus on an expanded storage chest it will only read the 1/2 of the chest it is connected to. So would be great if there could be support for the mod to read both chests with one storage buss

#### What you expected to happen:
One external storage bus should read both chests

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.4
- Forge: 35.1.0
- Refined Storage: 1.9.9

**Comment by Darkere** [comment]
This is not something that should be solved on RS's side. Not sure how Expanded storage works but that sounds like it doesn't implement double chests correctly.
