### ISSUE TITLE
found in Enigmatica 6 0.2.14: Constructor doesnt subtract a placeable block from the rf system

### ISSUE THREAD

**Issue by lewggs** [refinedmods/refinedstorage#2750]
#### Steps to reproduce:
1.set up rf system
2.set up a constructor and destructor facing the same block, configuration isn't important, but they have to face the same block. 
3.set a block you have X of to be placed by constructor and watch the numbers go up X+1.every time the destructor breaks it again. 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.1
- Forge: Forge-1.16.1-32.0.108 
- Refined Storage: 1.9.2
-Refined Storage Addons: 0.7

Does this issue occur on a server? Yes

**Comment by tth05** [comment]
Already fixed in newer versions

**Comment by raoulvdberge** [comment]
> make sure you are on the latest version before reporting

**Comment by lewggs** [comment]
i searched through the issue tracker and didn't find it fixed, so i just thought just in case
