### ISSUE TITLE
Incompatible with extreme reactors 2

### ISSUE THREAD

**Issue by Mewtwoy** [refinedmods/refinedstorage#2751]
#### What happens: Ghost blocks are created, which are fluid blocks, they cannot be removed except on survival, and when done so, the game crashes

No blocks from refined storage are close to it, or being used at all

#### Steps to reproduce:
1. CREATE REACTOR WITH FLUID PORTS
2. BREAK FLUID PORTS IN SURVIVAL AND PLACE OTHER BLOCKS WHERE THEY WERE
3. GAME WILL CRASH DUE TO GHOST BLOCKS
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge:
- Refined Storage: 1.99

Does this issue occur on a server? [NO]

#### If a (crash)log is relevant for this issue, link it here:

[https://pastebin.com/jMtPNsPv]

**Comment by ZeroNoRyouki** [comment]
It's from my side of the fence, fixing it

**Comment by ZeroNoRyouki** [comment]
It's fixed in ER 2.0.8
