### ISSUE TITLE
Wrong Fluids Outputted from RS System

### ISSUE THREAD

**Issue by PessimisticBastard** [refinedmods/refinedstorage#2753]
#### What happens:

In this specific instance, I'm trying to get the system to output lava, but it is outputting water instead.

#### What you expected to happen: Lava to be outputted

<a href="https://imgur.com/ZuvPAg8"><img src="https://i.imgur.com/ZuvPAg8.png" title="source: imgur.com" /></a>

#### Steps to reproduce:
1. Have both water and lava stored in system
2. Filter exporter/fluid interface to output lava

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.4
- Refined Storage: 1.9.9

Does this issue occur on a server? Don't know, I only play single player.

**Comment by Mig979** [comment]
I have this issue as well, can we get an update on this? 

Minecraft: 1.16.4
Forge: 35.1.36
Refined Storage: 1.9.11
Modpack: Direwolf20 version 1.4.1

**Comment by Darkere** [comment]
Hey any of you guys have a sink connected via external storage as well?

**Comment by Mig979** [comment]
Hi @Darkere, yes I did have a sink from "Cooking for Blockheads" connected to the external storage directly, is that the cause of the issue? Everything was working with the sink connected to the external storage, it was when I added lava to the system as well that the problem started and I did have other liquids on the system.

**Comment by Darkere** [comment]
The issue appears when fluid is inserted into the sink. The next time the RS system requests this fluid from the sink it will receive water even though it specifically requested the other fluid.

**Comment by UnusualNoises** [comment]
I am experiencing the same issue. I don't have a sink connected to my network, but I do have an external storage connected to a water tank that is perpetually filled with a Mekanism pump.

**Comment by UnusualNoises** [comment]
I attempted to fix the issue by disconnecting other tanks before attaching the fluid interface to request lava, and after attaching the other tanks back on, I have infinite lava. My magma crucible is not running, but I can see the water level fluctuate in the fluid grid, and I have an igneous extruder running consuming the 'free' lava.
