### ISSUE TITLE
Filter system broken for advanced sorting/filter.

### ISSUE THREAD

**Issue by Grandof1** [refinedmods/refinedstorage#2754]
#### Issue description: 
Filtering system broken/not logical or can not sort using "Filter".
#### What happens:
Item(s) ignore filter configuration from "Filter" in a device.
#### What you expected to happen:
When a "Disk Drive" (or other device that accepts "Filter") is set to blacklist/whitelist, a "Filter" is set to blacklist/whitelist an item, it denies/allows that item(s) to be placed into the device before trying to move to the next lower priority device/storage in the network.
#### Steps to reproduce:
1. Make sure "Disk Drive" set to items, blacklist, exact on, priority 0, insert and extract.
3. Set "Filter" to blacklist and add item(s) to filter slots, set NBT and Mod Filter accordingly.
4. Place configured "Filter" into top row of "Disk Drive".
5. Use "Grid"/"Crafting Grid"/"Wireless Crafting Grid) to place the item chosen in _step 3_ into the network.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.0.18
- Refined Storage: 1.9.9
- Refined Storage Addons: 0.7.2

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Grandof1** [comment]
# Documentation
- Lacking for guiding players to basics of advanced sorting/filter.
- Clarification on gui's layout and what items can be used with other items/blocks does not seem to exist.
- Docs (2020-11-26) suggest that a player can create filters with in other filters for advanced sorting/filtering of device which only have 4 and 9 slots. This seems not be the case and not widely clarified or the logistics are broken.

# Notes
I didn't want to put all of this in the issue due to it would not follow the format that is in place. 
The examples below is in the simplest concept. There could be far more advance configurations other then the example below but the outcome is the same. Mod seems to suggest the concept in the example should be possible but does not seem to work.

## Example 1:
Player creates a _Filter_ to [blacklist](https://www.merriam-webster.com/dictionary/blacklist) **cobblestone**, **stone**, and **andesite** from being placed into a _Disk Drive_ (default settings), and inserts the _Filter_ into _Disk Drive_'s top row (not clear in docs what this row is for). Player then goes mining and comes back to their storage network and dumps items into grid. _Grid_ allows the items that were configured in the filter to be inserted into "Disk Drive". Player is now confused/annoyed due to thinking the filter would not allow placement of those items into the network unless player makes a second disk drive.

Player changes _Disk Drive_ mode to [whitelist](https://www.merriam-webster.com/dictionary/white%20list) thinking that would make their blacklist _Filter_ to function. Player then goes to test their theory by attempting to insert the blacklisted items that were configured _Filter_ into the _Grid_ and Player finds out its rejecting the items, but tries to insert other items that are not in the _Filter_ configuration but finds out the _Grid_ rejects all items. Player now more frustrated and confused tries to put blacklist _Filter_ into _Grid_ to find out it accepts the item, resulting in more confusion due to it does not seem to be a way to do what Player is originally wanting to setup and stuck with being limited to only using the 4 and 9 slots that devices offer.

### Conclusion 1
- Player is not able to making advanced sorting/filtering like docs suggest.

## Example 2

Player creates a _External Storage_, _cables_ and a chest to have a storage further away from the storage network. Player wishes to have the chest store all of their food but be able to access it through their _Wireless Crafting Grid_. Player creates a _Filter_ to [whitelist](https://www.merriam-webster.com/dictionary/white%20listl) only the items set in the _Filter_ configuration after laying the _External Storage_, _cable_. and chest down to connect it to the storage network. Player then inserts the _Filter_ into _External Storage_ that is attracted to the chest and sets the mode to **whitelist**. Player inserts their food into their _Wireless Crafting Grid_ and goes to check the chest to make sure the food is in there. Player finds out the food is inserted to the _Disk Drive_ instead of the chest.

Player changes _External Storage_ priority to **1** and tests again but finds out nothing has changed in result. Player then changes mode to **blacklist** while the **whitelist** _Filter_ is still in the top slot and goes to test it again. Player finds out their food now goes into the chest but finds out items that are not in the _Filter_ is also being inserted into the chest. Player is sad and confused and decides to not use _External Storage_ and just stores food in the chest by itself.

### Conclusion 2
- Player is not able to create destinations for certain items to be stored resulting in not allowing for advanced sorting/filtering the storage network like the docs loosely suggest.

**Comment by raoulvdberge** [comment]
Thanks for the notes. I'm closing this issue, and linking it with #2372 so I can keep your comments in mind.
