### ISSUE TITLE
Crafter not putting items in order

### ISSUE THREAD

**Issue by kill05** [refinedmods/refinedstorage#2755]
#### Issue description:

When encoding a processing pattern, i've put some items in a certain order, but the crafter seems to put them in a fixed order.

#### Steps to reproduce:
1. create a pattern in processing mode and 3+ items
2. hook a chest to the crafter with the pattern inside
3. you will notice the items are in the wrong order
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.4
- Refined Storage: 1.9.9

Does this issue occur on a server? [yes/no]

Yes.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by thomaspj10** [comment]
This issue also happens to me. It doesn't happen to all 3+ items patterns. 

Using the `oredict` option when creating the pattern doesn't help, changing the order of the pattern also doesn't help.
