### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Morzh7771** [refinedmods/refinedstorage#2756]
#### Issue description:

I played for the assembly for a month and then one day I go to the assembly and Refiend Storage does not work, I check the disks and they do not show the number of resources in them and also when you put them in the driver it shows 0/0 (Sorry for my English, I'm from Rossi and translate with the help of google translator)
#### What happens:
The disks are empty and I don't know how to fix it
#### Steps to reproduce:(I don't know how i do this)
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2(Mod pack Dungeons, Dragons and Space Shuttles )
- Forge:14.23.5.2847
- Refined Storage:1.16.6

Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![image](https://user-images.githubusercontent.com/48734665/100391901-fec2fb80-3045-11eb-9677-467fd8900268.png)
![image](https://user-images.githubusercontent.com/48734665/100391927-113d3500-3046-11eb-91b2-eb6b00aae29d.png)

**Comment by Morzh7771** [comment]
How to fix it?

**Comment by Morzh7771** [comment]
![image](https://user-images.githubusercontent.com/48734665/100392135-9f192000-3046-11eb-9cb2-1214af61426b.png)
![image](https://user-images.githubusercontent.com/48734665/100392139-a3ddd400-3046-11eb-8917-19bb136fddac.png)

I noticed that the driver does not show that the disc is inserted

**Comment by raoulvdberge** [comment]
Restore from backup.
