### ISSUE TITLE
Auto crafters crash server with 1.16.4 Environmental tech

### ISSUE THREAD

**Issue by BedrockLegends** [refinedmods/refinedstorage#2757]
#### Issue description:
Put a refined storage crafter on an environmental tech crafter

#### What happens:
Server crashes
#### What you expected to happen:
a fix 
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.4 +
- Refined Storage: 1.9.9

Does this issue occur on a server? [yes/no]
Yes
[crash-2020-11-28_11.46.41-server.txt](https://github.com/refinedmods/refinedstorage/files/5611052/crash-2020-11-28_11.46.41-server.txt)

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Report to environmental tech. They are using clientside code on the server.
