### ISSUE TITLE
ATM6 crafting grid will stop allowing me to pull items out

### ISSUE THREAD

**Issue by lookwow** [refinedmods/refinedstorage#2759]
#### Issue description:
ATM6 crafting grid will stop allowing me to pull items out
#### What happens:
When clicking on stored items it will do nothing. Closing out of grid and going back in will allow it to work sometimes
#### Steps to reproduce:
1. taken items out and after 2-5 times it will stop working.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.0.18
- Refined Storage: 1.9.9

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by kill05** [comment]
never happened to me in atm6, the only similar thing that might happen is when you have external storages on drawers that are not chunk loaded

**Comment by Darkere** [comment]
This happens when you have an external storage on a block that sends frequent blockupdates. Like an ender chest for example. 
We still need to look into a fix for that.

**Comment by lookwow** [comment]
You are awesome Darkere. I had an ender tank hooked up. Put a buffer tank between them and the problem is gone. Thanks a ton it was driving me nuts.
