### ISSUE TITLE
cant remove storage parts from storage disks while flying

### ISSUE THREAD

**Issue by Basedgod199** [refinedmods/refinedstorage#2761]
#### Steps to reproduce:
1. fly. 
2. shift right click with disk in hand (any kind)
3. you don't get part back
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.7
- Refined Storage: 1.9.9

Does this issue occur on a server? [yes/no] haven't tested that

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Don't fly
