### ISSUE TITLE
Storage Bus keeps getting disconnected from the system when the server boots up?

### ISSUE THREAD

**Issue by Algester** [refinedmods/refinedstorage#2762]
#### Issue description:
Storage bus seems to "disappear" from the network every time the server boots
#### What happens:
a storage bus connected to the storage drawer system seems to disappear from the refined storage network every time the server starts maybe when I issue the stop command on the server it probably doesnt disconnect cleanly? from the world.
#### What you expected to happen:
when a player connects into the server at least the storage bus should be ready
#### Steps to reproduce:
1. create a medium? ish network
2. have the storage bus connect to a storage drawer controller
3. player leaves and the server gets issued a stop command
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.0
- Refined Storage: 1.9,9

Does this issue occur on a server? [yes/no]
yes

**Comment by Swantsy** [comment]
can confirm on server I play on, happens the same. 

Minecraft: 1.16.4
Forge: 35.1.4
Refined Storage: 1.9,9

**Comment by allout58** [comment]
I believe this is related to https://github.com/refinedmods/refinedstorage/issues/2636
