### ISSUE TITLE
Duplication bug when quick stacking into the system

### ISSUE THREAD

**Issue by PrinceEvince** [refinedmods/refinedstorage#2763]
#### **Issue description:** 

Shift clicking/quick stacking into the system effectively doubles/duplicates the items because it never removes it from your inventory

#### **What happens:** 

https://www.youtube.com/watch?v=Tqwh3jTWI1s&ab_channel=PrinceEvince

#### **What you expected to happen:** 

I expected for the items to just enter the system normally.

#### **Steps to reproduce:**

Haven't figured it out yet. This is the third time it happened to me today, without it ever happening before. I didn't discover it was duplicating items until the second time it happened because I initially thought it was just an annoying bug that wouldn't let me shift click items into my system.

#### **Version (make sure you are on the latest version before reporting):**

- Minecraft: 1.12.2 (Modpack: Dungeons Dragons and Space Shuttles)
- Forge Mod Loader: 8.0.99.99
- Minecraft Forge: 14.23.5.2847
- Refined Storage: 1.6.16
- Refined Storage Addons: 0.4.5

#### **Does this issue occur on a server?:** 
Not sure as I am on single player

**Comment by embeddedt** [comment]
Have you checked whether the duplicated items actually work? Lag can cause the item stack to stay in the clientside inventory, but it will disappear as soon as you try to use it and/or move it.

**Comment by PrinceEvince** [comment]
Yeah. I attached a video. In the video you can see me dropping the
duplicated items onto the ground and picking them up, showing that they are
effectively duplicated. I've been playing a lot of multiplayer recently
with the same modpack and haven't gotten the bug, so I think it might be
single player only.
