### ISSUE TITLE
Disk Drives render with no front face

### ISSUE THREAD

**Issue by sunnyughs** [refinedmods/refinedstorage#2764]
Disk Drives have no front face to the block when rendered in.
![Screenshot_22](https://user-images.githubusercontent.com/26176279/101462504-4a10c000-390a-11eb-9e95-2f31379b757e.png)

Not sure there are many steps needed to reproduce this. 

- Minecraft: 1.16.3
- Forge: 34.1.42
- Refined Storage: 1.9.9

Does this issue occur on a server? Yes

**Comment by Darkere** [comment]
Wait... Disk drives? Are you sure those aren't disk manipulators?

**Comment by sunnyughs** [comment]
> Wait... Disk drives? Are you sure those aren't disk manipulators?

![image](https://user-images.githubusercontent.com/26176279/101558524-26428e00-398d-11eb-9ccb-ec62c4b626de.png)

Though I just noticed this only happens when returning from the nether, and I also have Immersive Portals installed so perhaps the issue belongs there.

**Comment by TheOne20001** [comment]
I found this in Direwolf20 1.16 pack. I found that for 4K discs if you place 3000 or more items in it then both the disc drive and disc manipulator will render invisible. I did not find anything like that for the 1K drive, and the 16K drive is too big to test realistically.

**Comment by raoulvdberge** [comment]
I think this is fixed now. You probably reloaded resource packs.
