### ISSUE TITLE
ice and fire banner

### ISSUE THREAD

**Issue by Spooks69** [refinedmods/refinedstorage#2766]
#### Steps to reproduce:
1. get any banner
2. get any pattern from ice and fire and dye
3. try combine them in a loom
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 1.16.4 - 35.1.11
- Refined Storage: 1.9.9

Does this issue occur on a server? [yes/no] yes
![2020-12-09_18 56 45](https://user-images.githubusercontent.com/75752828/101674392-56069a00-3a50-11eb-82b8-a9893bb63390.png)

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Why did you report this here?

**Comment by Pankeko** [comment]
it breaks any custom banners from other mods, like mubble for 1.15.2
this ice and fire issue also happens in 1.15.2

**Comment by raoulvdberge** [comment]
What does this have to do with refined storage?

**Comment by Pankeko** [comment]
it causes the issue, with a pack of 70+mods, only when i add refine storage it happens, even when im just using ice and fire and refined storage it breaks banners

**Comment by HonestAngel** [comment]
Minecraft: 1.16.4
    Forge: 1.16.4 - 35.1.36
    Refined Storage: 1.9.11
    Ice and Fire and Additional Banners are messed up only when Refined Storage is in the mods folder...
    So yes it is somehow making it impossible to have anything other then default patterns in the loom...
    I don't know why it is happening either...

**Comment by Crioca** [comment]
Having this issue as well. Latest versions of refined storage (1.9.12) and Ice and Fire

**Comment by CivilNikolas** [comment]
I'm having the same issue. The banner patterns from immersive engineering also break. version 1.9.12

**Comment by raoulvdberge** [comment]
Any logs? Did any of you report to ice and fire as well?

**Comment by CivilNikolas** [comment]
I haven't posted anywhere else but i think the issue is with refined storage because as soon as i remove it the patterns from mods (ice and fire, immersive engineering, dark utilities, rats) apply correctly. None of them worked with refined storage present. I really cannot help you any more. I know nothing about modding. Also no logs since there is no crash.

**Comment by raoulvdberge** [comment]
Logs are generated even without a crash.

**Comment by CivilNikolas** [comment]
Here is a log from the game. Tha last thing i did was apply a modded pattern to a banner if that helps. 
https://pastebin.pl/view/4a528082

**Comment by kihgy** [comment]
Okay so banner patterns from rats and alex's mobs mod are also affected in the 1.6.4 version.

**Comment by kihgy** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/issues/3620

**Comment by TheBv** [comment]
Just do add some more information as to why this is happening:
Basically [this ](https://github.com/refinedmods/refinedstorage/blob/db00b7d598380fe2f8773ba4ee1e3a9231cc6ca3/src/main/java/com/refinedmods/refinedstorage/setup/ClientSetup.java#L59) piece of code gets called way before any item registration can take place (e.g banners). What it does is call `Atlases#collectAllMaterials` and this adds the banner textures to the "Banner atlas" but it does so before Ice and Fire registers it's items.
After that the Atlas never gets generated again and therefore the new banner textures are missing.
If this is an issue Ice and Fire needs to deal with please let me know!

**Comment by zymex22** [comment]
lol had same issue when playing right now and searched around the internet to look how to craft that stupid banner, just got a pink and black one everytime i tried... didnt know it could be refined storage causing it, thats so odd...
