### ISSUE TITLE
External storage behaving funny

### ISSUE THREAD

**Issue by SpaceMidget** [refinedmods/refinedstorage#2767]
#### Issue description:
external storage doesnt load block content after singleplayer world reload

#### What happens:
when reloading the SP world external storage doenst read storage drawer content so I have to brake and replace it to get it to work

#### What you expected to happen:
set up the external storage with its priority and forget about it not fiddle with all of them every time I open my world 

#### Steps to reproduce:
1. place a drawer with or without a drawer controller
 2. put an item inside 
3. setup a external storage 
4. the item shows in the network 
5. reload the game
 6. items not showing in the network.
7. brake and replace it 
8. Storage contrler reading the content of the drawer

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2854
- Refined Storage: refinedstorage-1.6.16.jar
Does this issue occur on a server? [yes/no]  NOT SURE 

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by allout58** [comment]
I believe this is related to https://github.com/refinedmods/refinedstorage/issues/2636
