### ISSUE TITLE
Upon loading world, have to replace external storage on drawer controller

### ISSUE THREAD

**Issue by Yur1ck** [refinedmods/refinedstorage#2774]
#### Steps to reproduce:
1. Launch Minecraft (Currently playing on Direwolf20 1.16 modpack, no modifications to the settings from the launcher)
2. Load my world
3. Et voila, no access
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: Not sure how to find this?
- Refined Storage: 1.9.9

Does this issue occur on a server? [yes/no] No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by kreezxil** [comment]
duplicate of which bug tho?

**Comment by Darkere** [comment]
#2636
