### ISSUE TITLE
Items disappeared from refined storage system

### ISSUE THREAD

**Issue by ryno4ever16** [refinedmods/refinedstorage#2778]
#### Issue description:
Items disappeared from refined storage system

#### What happens:
Items that were previously in the refined storage system are no longer present. Hard drives appear empty.

#### What you expected to happen:
Items were expected to remain stored in the refined storage system.

#### Steps to reproduce:
1.Put items in the refined storage system
2.Attempt to access the refined storage system
3.Observe the lack of items in the refined storage system.

I don't really know how to reproduce this one, and I lost the log(I was too focused on resolving the issue and forgot when it happened). Sorry if this bug report is unhelpful, but this essentially deleted hours of progress for a player on my server. Restarting the server and the associated client did not resolve the issue.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.3
- Forge:34.1.42
- Refined Storage:1.98

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Do the disks show that there are items on the disk? Is he the only one on the server that was affected?

**Comment by ryno4ever16** [comment]
The disks did not show that there were items on the disks as far as I'm aware, and he had the only refined storage setup on the server therefore was the only one affected. I've actually since removed the refined storage mod from the server so I can't really look into anything further, unfortunately.

**Comment by kreezxil** [comment]
Interestingly enough this happened on my server which 1.12.2 and most specifically this related issue describes it to a t. https://github.com/TechReborn/RebornStorage/issues/153

And yeah no logs. Nothing in the console either as you swap the drives in and out. New drives load/reload just fine.

**Comment by Darkere** [comment]
That is a different error. The drives show there are no items in them meaning disk corruption. 

In that case restore the world/data/refinedstoragedisks.dat from backup.

**Comment by kreezxil** [comment]
it happened to several players on my server all at the same time.

**Comment by Darkere** [comment]
The disk file contains all disk data for every disk. So yes, it will always affect all players.

**Comment by kreezxil** [comment]
if restore the file as you've suggested, well after the point where players
said it happened. will that not also reset the new disks they made and
began to populate? is there a /command to do the restoration?

**Comment by Darkere** [comment]
Did they make new disks? Then it should be possible to merge the two files with some copy-pasting.
NBT explorer is able to open the file.

**Comment by raoulvdberge** [comment]
We've introduced some corruption protection fixes for 1.9.10.

Important to note: this happens due to Minecraft code, not our code.

**Comment by kreezxil** [comment]
is that implemented in 1.12.2+ or just 1.16.4?

**Comment by tth05** [comment]
1.12.2 updates stopped with version 1.6.4

**Comment by kreezxil** [comment]
Thanks.
