### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Shucai99** [refinedmods/refinedstorage#2782]
Issue description:

IF i Open My system I will kick from server maybe to many on disk?
https://i.imgur.com/tQKx0RW.png
What happens:

Kick From Server
What you expected to happen:

TO many ITems?
Steps to reproduce:

...
Version (make sure you are on the latest version before reporting):

    Minecraft:1.16.4
    Forge:35.1.4
    Refined Storage:rftoolsstorage-1.16-2.0.7

Does this issue occur on a server? [yes/no]
yes
If a (crash)log is relevant for this issue, link it here:

yes
[pastebin/gist/etc link here]
https://hastebin.com/nufitugave.sql

**Comment by Darkere** [comment]
For the crash you linked try disabling your disk manipulator. Or setting max-tick-time in server.properties to -1 if it needs to happen.

For the disconnect you may have to reduce the number of items in the system. 

Both have been reported before.
