### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by nddragoon** [refinedmods/refinedstorage#2790]
#### Issue description: 
I built myself a relatively small modpack and it keeps crashing on launch due to RS. Happens with both 1.9.8 and 1.9.9, with and without Optifine, and with and without ExtraStorage

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.15
- Refined Storage: 1.9.8 and 1.9.9, possibly more

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/nddragoon/335260c3cf045c88c351c5ad4a5c400d

**Comment by Darkere** [comment]
This looks like some other mod is registering a broken model. Unfortunately the only way to track down what mod it is would be to start without it.
