### ISSUE TITLE
GUI pop-up in the way of seeing recipe

### ISSUE THREAD

**Issue by Bellwar** [refinedmods/refinedstorage#2791]
#### Issue description:
Sorry for the description, anyway. When hovering over + sign in JEI and showing the items that can be crafted and are missing the blue pop up that informs you that by ctrl left click you autocraft is in the way of bottom row recipes. See picture for illustration. Sorry in advance, if this isn't original RS feature if not anyone has an idea who adds it?

#### What happens:
![image](https://user-images.githubusercontent.com/9407653/103287506-f6623580-49e2-11eb-901d-698edf4dd89e.png)

#### What you expected to happen:
Move to the right side of the cursor so you can see the recipe.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.13
- Refined Storage: 1.9.9

Does this issue occur on a server? 

no

**Comment by raoulvdberge** [comment]
But, if you don't hover over the button, you can still see the recipe right?

**Comment by Darkere** [comment]
I was actually hoping this would get fixed once they made the changes to the forge tooltip. But it doesn't seem like that did it.

Not sure what is causing the tooltip to appear to the left instead of the right. There is enough space.

**Comment by Darkere** [comment]
Yeah it's a forge issue. Wrapped tooltips get moved to the left side if the cursor is on the right side of the screen, while non wrapped tooltips stay on the right. 

Gonna make a report.

**Comment by raoulvdberge** [comment]
Reported to Forge in https://github.com/MinecraftForge/MinecraftForge/issues/7572

Closing here

**Comment by TheAdamizer** [comment]
Hello hate to necro this but maybe we could have a config to simply disable this tooltip?  I believe anyone using the autocrafting features in RS would very quickly understand what the blue highlighting means in a recipe and therefore the tooltip is useless to them at that point.  Then at least we wouldn't have to punt this down the road and wait for Forge to fix it.  Either way, thank you for your time!
