### ISSUE TITLE
Crafter Duplication Bug

### ISSUE THREAD

**Issue by kevincy75** [refinedmods/refinedstorage#2794]
#### Issue description:
Middle clicking a crafter (normal crafters or crafter upgrades from Extra Storage) with speed upgrades (works properly without speed upgrades in it) in it duplicates the speed upgrades and places them in the first slot of the crafter, and replacing the first pattern.
#### What happens:
Duplicates speed upgrades and the first pattern is replaced (also happens when first slot is empty) with the speed upgrades when trying to sort the inventory of the crafter.
#### What you expected to happen:
The inventory of the crafter to sort.
#### Steps to reproduce:
1. Putting patterns and speed upgrades inside a crafter
2. Middle clicking to sort inventory
3. Speed upgrades being duplicated and replaces the first pattern with the speed upgrades

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.15
- Refined Storage: 1.9.9

Does this issue occur on a server? [no]

**Comment by Jauska** [comment]
Can reproduce on a server. Same things happens. Identical Forge, Minecraft and Refined Storage versions. Running Direwolf20 1.16 pack. If the first slot is empty this will still occur and if the first slot has already 64 upgrades it will not overflow to other slots.

**Comment by raoulvdberge** [comment]
Refined Storage does not add middle click sorting functionality, you'd have to report it to that mod author.
