### ISSUE TITLE
1.12 API files unavailable

### ISSUE THREAD

**Issue by 4rz0** [refinedmods/refinedstorage#2798]
#### Issue description:
The API jar files for building projects that depend on RS are unavaliable, which leads to the issue that such projects can't be built anymore.

#### What happens:
Currently trying to build Building Gadgets for 1.12, which depends on `refinedstorage:refinedstorage:1.6.15-380`.
Gradle tries to contact following sources but can't find anything:
https://gist.github.com/4rz0/55757c9b6863188ee95d2d30b613d86b

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 1.12.2 - 14.23.5.2854
- Refined Storage: refinedstorage:refinedstorage:1.6.15-380

~~Does this issue occur on a server? [yes/no]~~

~~#### If a (crash)log is relevant for this issue, link it here:~~

~~[pastebin/gist/etc link here]~~

**Comment by raoulvdberge** [comment]
Use the search function on the issue tracker

**Comment by 4rz0** [comment]
#2724, for  those who found this one before the original post.
