### ISSUE TITLE
Searching for mod incorrectly filters out that mod's items

### ISSUE THREAD

**Issue by lpacphantom** [refinedmods/refinedstorage#2799]
#### Issue description:
Searching specifically for Industrial Foregoing using "@industrial" does not show that mod's items. The items are visible when not searching for anything and even when searching for the specific item name, but using the @mod filter, it finds nothing. I've only noticed this with Industrial Foregoing, so it may be on their end. JEI does search correctly.

#### What happens:
Searching using "@industrial" finds no items for Industrial Foregoing.

#### What you expected to happen:
Searching using "@industrial" finds that mod's items.

#### Steps to reproduce:
1. Have Industrial Foregoing items in storage.
2. Search "@industrial"
3. See no items

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16
- Forge: 3.0.0-beta.10 (maybe? still trying to figure out FTB Overwolf app)
- Refined Storage: 1.9.9
- Modpack: FTB Direwolf20 1.16 1.1.2

Does this issue occur on a server? [yes/no] Unknown, only using singleplayer

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Malexion** [comment]
Worth noteing that Industrial forgoing recently fragmented their mod into several modules.

Also this works to look up Industrial Forgoing for some reason:

![image](https://user-images.githubusercontent.com/5237473/103434736-0d637c00-4bcb-11eb-96e1-ca6fb5472f09.png)

**Comment by choekstr** [comment]
came here to report this as well.  I found another way that works well (note the JEI interaction is working properly and showing any item with "indust" in the description and RS is showing the mod items like the @ should:

![image](https://user-images.githubusercontent.com/161085/105793118-2fdc8100-5f4e-11eb-9240-c27e6e60e9de.png)

**Comment by raoulvdberge** [comment]
This should be fixed now by https://github.com/refinedmods/refinedstorage/commit/57f6c2b55064f191bd109573d951ce652e59aa64
