### ISSUE TITLE
Texture bug with Optifine on an active network.

### ISSUE THREAD

**Issue by rhpeZ** [refinedmods/refinedstorage#2805]
#### Issue description:
I recently installed Optifine to help improve my game's performance and I have run into this issue where any items that are connected to an active Refined Storage network get this weird texture bug. I have tinkered with every setting and I cannot find any way to fix it.

#### What happens:
Block textures are improperly displayed.

#### What you expected to happen:
Block textures to render correctly.

#### Steps to reproduce:
1.Install Optifine and Refined Storage
2. Load into any world
3.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14,23,5,2846
- Refined Storage: 1.6.16

Does this issue occur on a server? [yes/no]
yes and on a local save.

**Comment by raoulvdberge** [comment]
A screenshot would be helpful.

**Comment by rhpeZ** [comment]
![2021-01-02_18 25 36](https://user-images.githubusercontent.com/42558294/103464578-c7bec480-4d2c-11eb-9d5a-a1d172fbbd96.png)
![2021-01-02_18 28 53](https://user-images.githubusercontent.com/42558294/103464580-c8575b00-4d2c-11eb-99be-25584ae5cc7d.png)

Apologies, I thought I attached the screenshots.

**Comment by raoulvdberge** [comment]
This bug was fixed for 1.16.x. Unfortunately 1.12 is unsupported.

**Comment by Darkere** [comment]
Try a restart :). This error can happen when reloading textures.
