### ISSUE TITLE
Issue Interacting with Grids when network busy

### ISSUE THREAD

**Issue by MadJinx1** [refinedmods/refinedstorage#2806]
#### Context: 
I have a Mekanism 5x ore generation system that needs cobblestone exported from the network. I have a separate system for generating cobblestone when needed that pumps into a drawer that is connected to the network via external storage.  When processing ore, cobblestone is requested about once every 2 seconds and the resulting ingots are imported into the system about twice as fast.  

#### Issue: 
While the above is occurring, if I open a grid I see 0 count stacks of cobblestone added being added and I cannot pull anything out by hand. Through my experimentation with cutting off parts of the network to diagnose, this seems to stop when I cut off the cobblestone exporter.

#### Steps to reproduce:
1. have network that has multiple connections (external storages, importers and exporters)
2. have network export items (larger amounts last longer and effect is more visible)
3. attempt to interact with a grid (have seen in crafting grid, pattern grid and wireless crafting grid from refined storage addons)

#### Versions:
- Minecraft: 1.16.4
- Forge: 35.1.28
- Refined Storage: 1.9.10

Other Mods connected to the network:
- Refined Storage Addons: 0.7.2
- Mekanism: 10.0.18.445
- Mekanism Generators: 10.0.18.445
- mekanism Tools: 10.0.18.445
- Storage Drawers: 8.2.1
- Create: 0.3
- Industrial Foregoing: 3.2.7-7d95990
- Ender Storage: 2.7.0.161-universal

Other Mods that may be related:
- Mouse Tweaks: 2.13-mc1.16.2
- Crafting Tweaks: 12.2.0
- FTB Chunks: 1604.2.2.54
- Inventory Tweaks: 1.0.1
- JEI: 1.6.0.58
- JEI Integration: 6.1.1.11
*Note: numerous other mods present (88 total), but the above are only ones that I believe effect the network. All mods are current as of this posting*

Does this issue occur on a server?  haven't tested

**Comment by raoulvdberge** [comment]
@ScoreUnder  any idea if this has anything to do with your PR?

**Comment by ScoreUnder** [comment]
Unfortunately I think it might be. I'm taking a look at it now, but I don't really know much about mekanism, so I can't find any way to reproduce it. Using just importers, exporters and constructors I can't seem to get the same thing to happen.

There are a few things I want to understand about the nature of the bug:

* Does the 0-item stack start there, or does it appear after a short delay?
* Does it prevent you from removing anything, or just the 0-item stacks?
* Does holding/pressing/releasing shift while it's happening in the grid do anything interesting?
* Do you have a crafting pattern that makes the item which is appearing in 0-size stacks?

**Comment by raoulvdberge** [comment]
@MadJinx1  Any info on this?

**Comment by DustRaven** [comment]
I have the same issue, but in my case it appears when I have an exporter with a crafting card which exports bone dust into an attached Storage Drawer. If I have the grid opened, the 0-item stack appears and shortly after, 3 bone meal appear. This repeats (new 0-item stack, new bone meal stack) until I close the grid.

As soon as the first 0-item stack appears, I cannot interact with the grid anymore.

**Comment by Poke5555** [comment]
im not sure if im having the exact same issue but whenever i export any item for more than a couple minutes the exporter slows down to only 1 export every 2 seconds, changing the upgrades in it doesnt do anything and the only way ive found to fix it is to break the exporter and replace it and having to do that every few minutes to export millions of items is kinda annoying.

**Comment by ScoreUnder** [comment]
I still haven't managed to reproduce this yet (I'll give it another go today, with Storage Drawers in particular) but in the meantime, here's a build with my GUI performance changes (#2705) removed: https://gurren.score.moe/jenkins/job/refinedstorage/job/mc1.16-gui-perf-reverted/1/artifact/build/libs/refinedstorage-1.9.12+1.jar

Note that this is an **unofficial build**, I'm not a maintainer or member of this project in any capacity.

That build might be able to give us a clear "yes" or "no" as to whether it's the changes I've made that have introduced this bug, which will narrow down the search for it in the code. Or it could change the nature of the bug, which would equally provide a clue into what is happening here.

Separate from that, if anyone has a means to provide a world save where it happens, or a screenshot of a setup that causes it, that would also help a lot. World saves can be large and often personal, so I understand if that's a "no". (They may need to be uploaded with a provider that supports large files like google drive or mega)

**Comment by Knito58** [comment]
External storage from "router reborn mod" seems to block the grid sometimes. If the system crafted something I can pull it out. But items from the "external storage" are (mostly, not always) blocked from being used directly.
