### ISSUE TITLE
Empty key binding causes GL Errors

### ISSUE THREAD

**Issue by Virenbar** [refinedmods/refinedstorage#2808]
#### Issue description:
Started playing Direwolf20 1.16 pack and noticed console spam when opening grid.
Empty key binding for "Clear Grid Crafting Matrix" causes GL Errors. Setting key binding to anything stops spam.
Also empty key binding for "Focus Grid Search Bar" causes one GL Error when closing Grid.

Tested with RS only, happens with any grid (wireless included).

#### What happens:
 Console gets spammed with GL Errors

#### What you expected to happen: 
No console spam

#### Steps to reproduce:
First:
1. Unset key binding for "Clear Grid Crafting Matrix"
2. Place any Grid (No controller needed)
3. Open Grid
4. Console gets spammed with GL Errors.

Second:
1. Unset key binding for "Focus Grid Search Bar"
2. Place any Grid (No controller needed)
3. Open Grid
4. Close Grid
5. Console gets one GL Errors

#### Version:
- Minecraft: 1.16.4
- Forge: 35.1.29
- Refined Storage: 1.9.11

Does this issue occur on a server? Yes.

#### If a (crash)log is relevant for this issue, link it here:
No crash, spam only
https://paste.ee/p/4Mbv7

**Comment by aburone** [comment]
I was ripping my hair trying to know which mod caused all the log spam. Realized it was RS and was about to report a bug.
Thank you @Virenbar for giving me a temporary way to stop it
