### ISSUE TITLE
15.2 [1.8.8] when network link breaks receive block

### ISSUE THREAD

**Issue by jsdraven** [refinedmods/refinedstorage#2810]
#### Issue description:
Network Receiver block breaks when linked.
#### What happens:
after putting a network card into the Network Transmitter the corresponding receiver breaks for pickup. I tried placing the receiver back in place. with the receiver back in place the network card replaced into the transmitter will break it again. the grid never shows items from the host location
#### What you expected to happen:
things to work like document says?
#### Steps to reproduce:
1.Minecraft 1.15.2, Forge 31.2.38, refine storage 1.8.8, refine addon 0.6.3
2.Place all blocks as needed. 
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.38
- Refined Storage: 1.8.8

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
remove the controller from one of the two sides.
