### ISSUE TITLE
Disk in Drives Disappearing

### ISSUE THREAD

**Issue by 100xdonaldx001** [refinedmods/refinedstorage#2813]
#### Issue description:
Disks in Drives Disappearing after a Server Crash

#### What happens:
We played normaly till the Server had a big Lag after 120 Seconds the server closed itself with the Crash message, that the server Tick took too long.
After starting up the server again the Disks were gone.

#### What you expected to happen:
Nothing. Disks should be still there.

#### Steps to reproduce:
1. unknown
We didnt interacted with Refined storage at the time the Crash happened.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.16.4
- Forge: 35.1.20
- Refined Storage: refinedstorage-1.9.10
- Modpack: TNP Limitless 3 1.8.3a

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/S4Qjfxg8

**Comment by Darkere** [comment]
Please make sure you update. And read the changelog. If you create new disks afterwards you may be overwriting the temporary file.

**Comment by Talidorn** [comment]
I also am seeing this in the TNP Limitless 3 v 1.8.3a Modpack.  I run my own server.  After a crash drives got wiped.  I removed the old RS, added the 1.9.11 jar, removed the .temp files.  Nothing returned.  All drives and contents still lost.

I'll leave the updated version to see if there is another occurrence of the loss of drives.  I will update in the next day or so.

**Comment by Darkere** [comment]
> removed the .temp files

... Did you read the changelog?

**Comment by Talidorn** [comment]
Yes Darkere, I read and followed the changelog -> "If you are affected by this please go to the world/data/ folder and remove the ".temp" ending from the files before launching." found on https://www.curseforge.com/minecraft/mc-mods/refined-storage/files.  My previous steps left out step 0.5 stop server and step 4 started server.

I'm not sure if it was meant to be snarky/rude... but yes, I followed what you had posted exactly.

Thanks for all you do!  Love the mod.

**Comment by Darkere** [comment]
"If you are affected by this please go to the world/data/ folder and remove the ".temp" ENDING from the files before launching."


Ending being the important bit. I guess I could have phrased that a bit more clearly. 
Those Files contain the data... Why would you delete them.

**Comment by Talidorn** [comment]
LOL.  All good.  The files are gone, As we have just started the pack it wasn't a big loss.

Perhaps change the verbiage to:
"rename the files world/data/refined_storage_whatever.temp to world/data/refined_storage_whatever"  
or
"If you are affected by this please go to the world/data/ folder and shorten the files with the ".temp" ENDING  by taking the .temp from the files and then re-launch your server."
or
Step 1 - Don't be dumb like talidorn
Step 2 - Stop the server
Step 3 - Update mod if you need to
Step 4 - files that have the .temp ending should be renamed to have .temp no longer in the file name. DO NOT BE LIKE TALIDORN and delete these files... they only need to be renamed.
Step 5 ...
Step 6 - profit

I'm sick (Perhaps with the virus that will kill this obese old man) and probably shouldn't be working with server stuff currently.  My ADHD makes it difficult to read instructions clearly and fully... LOL  Thanks again.  You're the best!

**Comment by raoulvdberge** [comment]
Don't turn yourself down like that, it's perfectly reasonable to misread that sentence.

**Comment by 100xdonaldx001** [comment]
Since its already got fixed in 1.9.11 i closed the issue now
