### ISSUE TITLE
[MINOR ISSUE-FOUND THE CAUSE] Refined Storage Pattern Grid not syncinc correctly after shift clicking recipe from JEI 

### ISSUE THREAD

**Issue by FedeKhan** [refinedmods/refinedstorage#2814]
#### Steps to reproduce:
1. pick a recipe from JEI
2. shift left-click it into to the pattern grid terminal
3. the "output" item disappears and cannot be clicked into inventory

#### Versions : 

- Minecraft: 1.16.4
- Forge: 35.1.29
- Refined Storage: 1.9.11
- JEI : 1.16.4-7.6.1.65
- JEI integration : 6.1.1.11
Does this issue occur on a server? Don't Know

**Comment by FedeKhan** [comment]
Apparently it fixed itself by just re-downloading JEI.

**Comment by choekstr** [comment]
Happening to me in TNP Limitless 3 modpack.  Haven't tried redownloading JEI yet, but just mentioning it is not an isolated case.

**Comment by Azruine** [comment]
Same issue here with ATM6 1.3.9b

**Comment by FedeKhan** [comment]
The issue reappeared for me too, after trying to teach the RS system a processing recipe where fluid mixed with items crafting is involved, and probably i found another bug since I cannot remove the fluid amount on the pattern terminal in any way.

I might open a new issue since it is happening consistently

PS: I play also on ATM6 1.3.9

**Comment by choekstr** [comment]
I did notice you can just replace any of the recipe items and the result shows up again and you can then create a pattern.  However, leaving and coming back in is far easier and quicker since it doesn't require a search and replace for one of the recipe items of course.

**Comment by Darkere** [comment]
This appears to be caused by another mod. With just RS and JEI it is working fine, but it is easily reproducible with ATM6. 

Also tested the most likely culprit in Fast Workbench. It is also not the cause. 

Not sure what other mods influence the crafting behaviour.

**Comment by bcrotty** [comment]
This happens to me on Valhelsia 3, except you don't need to be holding shift. Simply clicking the plus icon on the recipe does it if there was something in the output previously. So I can get it to work if the grid and output are clear and I add a recipe, but if the grid and output are not clear, when I add a recipe, the output disappears.

**Comment by 016Nojr** [comment]
Might help you with bugtesting, this list will show you what mods are present in all 3 packs

https://www.modpackindex.com/modpacks/compare?modpacks=21554,21541,21671

**Comment by thelolagemann** [comment]
also had this issue on tnp limitless, polymorph seemed to be the culprit for me, although not seeing it on E6 so not 100% sure it's the root cause

**Comment by Darkere** [comment]
Was able to reproduce with polymorph. Reporting.

**Comment by FedeKhan** [comment]
> Was able to reproduce with polymorph. Reporting.

Don't create a new issue, we already have it here

Hopefully the devs see

**Comment by FedeKhan** [comment]
The issue has now been solved by the polymorph devs, as mentioned in the thread above

Closing this now, thanks everybody
