### ISSUE TITLE
Crafter manager sorting

### ISSUE THREAD

**Issue by Noxally** [refinedmods/refinedstorage#2816]
#### Issue description:
If using an inventory sorting mod, sorting the inventory while in the Crafter Manager will cause all patterns to be sorted top down, meaning if you have a bunch of crafters followed by ones connected to furnaces etc, the furnace recipes will be sorted into first crafter slots.

#### What you expected to happen:
Per-crafter sorting

**Comment by Darkere** [comment]
Duplicate of #2680
