### ISSUE TITLE
Does a Maven exist for this project, and if so what is the repository and string to use for fg.deobf

### ISSUE THREAD

**Issue by Lothrazar** [refinedmods/refinedstorage#2818]
Theres no info about if a maven exists in the readme or on curseforge

**Comment by Darkere** [comment]
Maven: https://repo.refinedmods.com/

Build.gradle from the addons mod: 
https://github.com/refinedmods/refinedstorageaddons/blob/cac773a29d61c0785af22aba5ff05d37a1d86eb3/build.gradle#L88

**Comment by raoulvdberge** [comment]
The maven is linked in the navigation bar of our website

**Comment by Lothrazar** [comment]
Thanks for the quick reply! :)
