### ISSUE TITLE
Crafter Manager Deleting Patterns

### ISSUE THREAD

**Issue by djacicd** [refinedmods/refinedstorage#2821]
#### Steps to reproduce:
1. Explained already.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: forge-1.16.4-35.1.36
- Refined Storage: refinedstorage-1.9.11

Does this issue occur on a server? [yes/no] Yes (Linux)

#### If a (crash)log is relevant for this issue, link it here: ///

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Can you check if this happens with normal crafters or just the crafters from Extra Storage?

**Comment by uecasm** [comment]
FYI, another possibly related issue I observed is that packing a crafter into a Cardboard Box from Mekanism and moving it by one block over will delete all patterns stored in that crafter.  This was originally observed with an Extra Storage Gold Crafter, but it also happens with a standard Crafter too.
