### ISSUE TITLE
Unable to edit fluids in pattern

### ISSUE THREAD

**Issue by djacicd** [refinedmods/refinedstorage#2822]
#### Steps to reproduce:
1. Explained already.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: forge-1.16.4-35.1.36
- Refined Storage: refinedstorage-1.9.11

Does this issue occur on a server? [yes/no] Yes (Linux)

#### If a (crash)log is relevant for this issue, link it here: ///

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Only output or also the input fluids?

**Comment by djacicd** [comment]
Only output fluids.

**Comment by Darkere** [comment]
Alright nice, fixed here: #2819
