### ISSUE TITLE
Game crashes when entering pattern into Crafter

### ISSUE THREAD

**Issue by QuackerOat** [refinedmods/refinedstorage#2828]
#### Issue description:
Game crashes when putting any crafting pattern into Crafter
#### What happens:
Game immediately crashes when placing created pattern into the Crafter
#### What you expected to happen:
The pattern to go into the Crafter and be usable through the refined storage network.
#### Steps to reproduce:
1. Create pattern
2. Put pattern into Crafter
3. Game crashes and can no longer be opened without deleting refinedstorage_nodes.dat
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.36
- Refined Storage: 1.9.11

Does this issue occur on a server? [yes/no]
Yes and also in single player
#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/5aD9zxKM

**Comment by Darkere** [comment]
Make sure to cancel all ongoing crafting tasks before inserting this one. 

Deleting random files is not a good way to go about things... You probably broke a bunch of things doing so.

**Comment by QuackerOat** [comment]
I have some backups and noticed that "nodes" was in the crash log, so I was just testing out things. This happened after trying to update the server/single player from 1.16.1 to 1.16.4. I think breaking the Crafter before the update and replacing it afterwards fixed the issue for now, but I will have to see if that works when I update the actual server I play on.

**Comment by raoulvdberge** [comment]
Closing this as there are no real reproduction steps.
