### ISSUE TITLE
Deleting items from my hotbar

### ISSUE THREAD

**Issue by Cosmology2727** [refinedmods/refinedstorage#2832]
#### Steps to reproduce:
1. Pressing the "r" key will auto-sort my personal inventory, because I have JEI installed.
2. If refined storage is open (I'm in the GUI for, say, crafting), it will auto-sort inventory when I press "r", BUT it does it improperly. Normally, pressing "r" will have JEI sort only your inventory, not your hotbar. When in a refined storage GUI, it sorts inventory and hotbar, and sorts it badly.
3. Sometimes items go missing from my hotbar. I have lost a tinkers pickaxe that was incredibly modified with strong materials and took a lot to make. Another time it deleted a golden bag of holding, which was full of everything I use often. Both cases were extremely frustrating. I should also add it actually deletes items WITHIN the golden bag of holding. It's done this twice now. Extremely frustrating.

QUESTION: Is this fixed in the newest version, 1.16.16 for 1.12.2? If so, I'll update the whole server to fix it, but if not, I'm not going through the trouble or releasing a modpack update for everyone to have to download. Thanks for any help you can provide!
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Refined Storage: 1.16.14

Does this issue occur on a server? [yes/no]
Yes. No crash log, because it's not crashing.
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
The sorting is not done by JEI. That is some inventory sorting mod.

Check the changelog. This version almost a year old, there have been 20+ new versions since. How would we remember what exactly was in it?
