### ISSUE TITLE
Remove Warning When Forge has proper Settings

### ISSUE THREAD

**Issue by TechniumUnlimited** [refinedmods/refinedstorage#2834]
#### Issue description:
Every time I load game it warns me to enable experimental light settings, but I already have

#### What happens:
warns me every time, needlessly

#### What you expected to happen:
to stop warning me when I have done as told

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: idk
- Refined Storage: 1.9.11

![image](https://user-images.githubusercontent.com/29348969/104804270-3288ea80-5786-11eb-9c67-7989cca7a2f9.png)

**Comment by raoulvdberge** [comment]
Optifine resets it

**Comment by TechniumUnlimited** [comment]
Okay can I set it in optifine options

**Comment by MJRamon** [comment]
> Optifine resets it

It didn't reset in U5 though. Is it fixable?

**Comment by TechniumUnlimited** [comment]
> > Optifine resets it
> 
> It didn't reset in U5 though. Is it fixable?

It seems it may be fixed in latest optifine g7

**Comment by callmejay758** [comment]
> Okay can I set it in optifine options

What do you mean by that exactly? I'm trying to remove the warning but haven't seen any option related, can you explain further?

**Comment by MJRamon** [comment]
> > Okay can I set it in optifine options
> 
> What do you mean by that exactly? I'm trying to remove the warning but haven't seen any option related, can you explain further?

That's why question marks are important.
