### ISSUE TITLE
[Cross-mod comp issue] Autocrafting recipes that use a "Build tool" from minecolonies/structurize make you have to have 1 per craft, even though they are not consumed in recipes

### ISSUE THREAD

**Issue by koalalord9999** [refinedmods/refinedstorage#2837]
#### Issue description:
Autocrafting requires a bunch of build tools instead of just one when crafting structurize blocks

#### What happens:
crafts the blocks, and doesnt consume the tool

#### What you expected to happen:
crafts the blocks with only one tool, even if making recipe 100 times

#### Steps to reproduce:
1. queue up craft for some structurize craft
2. craft it
3. get tool back in RS, but still needs multiples for bulk crafting
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.36
- Refined Storage: refinedstorage-1.9.11.jar

Does this issue occur on a server? [yes/no] YES

#### If a (crash)log is relevant for this issue, link it here:

nope

**Comment by waffleattack** [comment]
This actually happens for any recipie where the input isn’t consumed I’ve found, like crafting pam’s flour makes it need to craft a new grinder for each item
