### ISSUE TITLE
Wireless crafting grid not showing

### ISSUE THREAD

**Issue by Amaiaxx** [refinedmods/refinedstorage#2841]
#### Issue description: 
Wireless crafting grid.

#### What happens:
Crafting grid is not displayed in the wireless crafting grid at the bottom like it should be, neither is one displayed in the portable grid. The crafting grid had a crafting section at the bottom but that was all. 
 
#### What you expected to happen:
I expected their to be a crafting grid like I have always seen. Though this is my first time on 1.12.2.

#### Steps to reproduce:
1. Make simple system
2.Bind wireless crafting grid to controller
3.open wireless device
...

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: Yes, added the mod in manually though. Cant play a mod pack without this and yes the versions are correct. 
- Refined Storage: 1.6.16

Does this issue occur on a server? [yes/no]
Yes I have a server for me and my friends. I have tried in creative as well though. 

#### If a (crash)log is relevant for this issue, link it here:
No crashing, just doesn't work / show.

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Make sure you are on the latest version for RSaddons

**Comment by Kammerjunk** [comment]
yeah, this is probably a bug in 1.6.16. though they don't support the version anymore, you can work around it by reverting to 1.6.15.
with Refined Storage 1.6.15 and Refined Storage Addons 0.4.4:
![image](https://user-images.githubusercontent.com/5942183/111076091-32d60580-84eb-11eb-8c47-82c439e4b37d.png)
with Refined Storage 1.6.16 and Refined Storage Addons 0.4.4:
![image](https://user-images.githubusercontent.com/5942183/111076139-6022b380-84eb-11eb-8ee9-6ffb4fb72fdf.png)
(note that versions of Refined Storage Addons below 0.4.4 won't work with Refined Storage 1.6.16, and will cause a crash on startup)

**Comment by Darkere** [comment]
Well yes. Because you need Refinedstorage addons version 0.4.5 for 1.6.16...
