### ISSUE TITLE
java.lang.IllegalStateException: No network node present at BlockPos

### ISSUE THREAD

**Issue by Invy55** [refinedmods/refinedstorage#2842]
#### Issue description:
Refined storage crash my server
#### What happens:
When a player near the refined storage joins, the server crash
#### What you expected to happen:
Server shouldn't crash, and refined storage should work properly
#### Steps to reproduce:
1. Build refined
2. Mess up with mekanism lasers to build the fusion reactor
3. Random crash and can't join anymore
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: forge-1.16.4-35.1.4
- Refined Storage: 1.9.9 or 1.9.11

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/VdbwdBJs #RefinedStorage 1.9.9
https://pastebin.com/taCYDTMa #RefinedStorage 1.9.11

**Comment by Invy55** [comment]
> #### Issue description:
> Refined storage crash my server
> 
> #### What happens:
> When a player near the refined storage joins, the server crash
> 
> #### What you expected to happen:
> Server shouldn't crash, and refined storage should work properly
> 
> #### Steps to reproduce:
> 1. Build refined
> 2. Mess up with mekanism lasers to build the fusion reactor
> 3. Random crash and can't join anymore
>    ...
> 
> #### Version (make sure you are on the latest version before reporting):
> * Minecraft: 1.16.4
> * Forge: forge-1.16.4-35.1.4
> * Refined Storage: 1.9.9 or 1.9.11
> 
> Does this issue occur on a server? [yes/no]
> yes
> 
> #### If a (crash)log is relevant for this issue, link it here:
> https://pastebin.com/VdbwdBJs #RefinedStorage 1.9.9
> https://pastebin.com/taCYDTMa #RefinedStorage 1.9.11

I think a mekanism laser broke a refined storage exporter

**Comment by Invy55** [comment]
I was right, I managed to set block that exporter with air and now I can play again

![image](https://user-images.githubusercontent.com/38048104/105160004-04056980-5b10-11eb-8f33-bb69fd6d6712.png)

**Comment by CraftSpider** [comment]
Got this same crash recently while a schematic was being pasted by Structurize, world reloads fine though

**Comment by mindofme** [comment]
I have the same issue with a misplaced laser, and the game crashed while the laser was attempting to break a refined storage block (I think its my crafting grid). I am curious how OP deleted the block (I think I will probably try to delete the laser instead).

Crash log here
https://pastebin.com/rxUwGE8a

**Comment by Invy55** [comment]
> I have the same issue with a misplaced laser, and the game crashed while the laser was attempting to break a refined storage block (I think its my crafting grid). I am curious how OP deleted the block (I think I will probably try to delete the laser instead).
> 
> Crash log here
> https://pastebin.com/rxUwGE8a
> 
> 

the esiest way i found was to use setblockt he faster you can when joining the world. in your case it would be `/setblock 258 63 247`

**Comment by raoulvdberge** [comment]
We won't be solving this bug for now, please remove RS  blocks the normal way.

**Comment by ciqven** [comment]
I accidentally right-clicked the Crafting Grid with a Moving Wand from the Better Wands mod in hand, this caused the same error. However, even `setblock` is not fixing it:

```
> setblock -256 80 -1154 minecraft:air
[20:01:10] [Server thread/INFO] [minecraft/DedicatedServer]: Could not set the block
```

I tried quite some things to remove this block (all kinds of breaking, replacing, exchangers, pistons, etc) but none seem to work. 

Please consider re-opening this issue, if only for making a quick-fix that clears this illegal state.

**Comment by Invy55** [comment]
have you tried to clean your inventory too?

Il mar 10 ago 2021, 22:05 çiqvĕɳ tyoⱶĭnƺĕ ***@***.***> ha
scritto:

**Comment by ciqven** [comment]
I fixed it.

Tried removing my inventory, did not work. If I try using `setblock` with anything else than air, such as `minecraft:oak_log`, it does actually seem to work, except that this new block can't be deleted and still outputs the error in console when clicked.

However, once I 

1. Deleted the network's controller;
2. Restarted the server;

it was fixed. Still a lot of hoops to jump through for one easy miss-click...

Thanks for helping me troubleshoot 👍

**Comment by Gatoluche** [comment]
Hello.
I had to delete the whole chunk off the world to make it work again.
I understand you´re busy, but consider no one would intentionally point a laser at their controller.
At least make the exception not crash the server and just remove the block. There´s even a message on it that says "consider removing the block" but the world crashes before any attempt to that can be made.
