### ISSUE TITLE
Can't create pattern for Cyclic magma processing

### ISSUE THREAD

**Issue by stefanak-michal** [refinedmods/refinedstorage#2843]
#### Issue description:
Can't create pattern in Pattern Grid for melting Magma Blocks to magma (liquid) for Melting Chamber (mod Cyclic). 

#### What happens:
When I click + in JEI on recipe to add it to Pattern Grid, the magma liquid is added to the left side as input.
If I try to drag magma liquid from JEI to output in Pattern Grid, nothing happen. The liquid isn't added as output.

#### What you expected to happen:
Magma liquid is added as ouput for processing.

#### Steps to reproduce:
1. Open Pattern Grid.
2. Select processing type.
3. Try add magma liquid as output.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 1.16.4-forge-35.1.36/forge
- Refined Storage: 1.9.11
- Cyclic: 1.16.4-1.1.3
- Direwolf20 1.16 1.4.1

**Comment by Darkere** [comment]
Try using a bucket to set the output item. There is a known bug with fluid outputs not working quite right.

**Comment by stefanak-michal** [comment]
@Darkere thanks for the tip. I didn't know I can use bucket with liquid while Pattern Grid is set to Type fluids. It works this way.
