### ISSUE TITLE
Redstone Mode in Impoter, Exporter, and External Storage is broken

### ISSUE THREAD

**Issue by Krutontar** [refinedmods/refinedstorage#2847]
#### Issue description:
Clicking the redstone mode button to change modes instead changes it from item to fluid mode.  It does not toggle, just changes to fluid and more clicks do nothing.
#### Steps to reproduce:
1. Click Redstone Mode button.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge:  35.1.36
- Refined Storage: 1.9.11
- Pack: ATM6 1.4.1

Does this issue occur on a server? [yes/no]  Yes

#### If a (crash)log is relevant for this issue, link it here:
No crash.

**Comment by Darkere** [comment]
Try a restart. 

Otherwise some mod is messing with our GUI's.

**Comment by Krutontar** [comment]
A server and client restart didn't fix it.  All other buttons work.

**Comment by Krutontar** [comment]
Fixed with latest pack update.
