### ISSUE TITLE
Interface duping/flooding network under specific conditions

### ISSUE THREAD

**Issue by Kataiser9** [refinedmods/refinedstorage#2849]
#### Issue description:

When an interface (without a stack upgrade) inserts items to a network with at least one full storage disk, the interface starts duping items in the next disk.

#### What happens:

Specifically, the interface only loses one item per operation as normal, but the network gains the entire contents of the first stack in the interface every operation.

#### What you expected to happen:

Network receiving only one item per operation, i.e., the items that disappear from the interface.

#### Steps to reproduce:
1. Place a creative controller, disk drive, grid, and interface down as part of the same network.
2. Put two 1k storage disks in the drive and manually fill the first disk to (for example) 980/1000.
3. Put several stacks of items in the interface.
4. Watch the disk drive usage. It goes up to 1k normally (in increments of 1) then starts filling up much more quickly.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.37
- Refined Storage: 1.9.11

Does this issue occur on a server? [Tested only in SSP, don't have a server environment to test right now.]

**Comment by Sebaz00** [comment]
Same version of refined storage and assuming the same bug here or very related. It seems to have also duped items and when any new item tries to enter the system (I have my interface act as an external storage so I can autocraft torches and then dump them in a machine) it will keep doubling it until it reaches 2 billion and then reset back to normal, only to then repeat.

![image](https://user-images.githubusercontent.com/25609226/105668720-d6387000-5ed5-11eb-96e4-18e105563c5b.png)

Here's a screenshot of the interface. The Grid also just shows it going up super high. My max storage is only half a million without any creative disks so the interface isn't behaving normally.

**Comment by raoulvdberge** [comment]
Did you duplicate the storage disks in creative mode?

**Comment by Kataiser9** [comment]
Sorry, missed that.

Not entirely sure what you're asking; I pulled two storage disks from the JEI menu for this test. Happened in my survival world too though.

**Comment by raoulvdberge** [comment]
Fixed for the next version
