### ISSUE TITLE
Fluid Autocrafting with Fluid-in-Fluid-out not Working Correctly

### ISSUE THREAD

**Issue by Inkdot-Test** [refinedmods/refinedstorage#2851]
#### Issue description:
When I am trying to craft the liquid oxygen with the Crafter(RS) on a Electrolytic Separator(MEK), it fails to place liquid in, the Crafting Monitor(RS) repies that the machine doesn't accept liquid.
#### What happens:
Due to the fact that RS doesn't support the Mek gas, I was forced to place a Rotary Condensitrator(Mek) on the left and right sides of the Electrolytic Separator so that the oxygen gas & hydrogen gas produced will be liquified into liquid oxygen and liquid hydrogen which qualifies as a fluid and can be stored in RS.
Intended to use the liquid autocraft function to craft liquid with a fixed amount, I put a Crafter(RS) on top of the Electrolytic Separator(MEK), and try to create a pattern transforming 1B water into 1B liquid oxygen and 2B liquid hydrogen.
The pattern gets created and placed in the Crafter(RS), and order of Liquid Oxygen is made in the Fluid Grid(RS).
The order however never gets any progress. The Crafting Monitor(RS) reports 2B Liquid Hydrogen ordered, 1B Liquid Oxygen ordered, 1B water stored.  The red quotation marks appear beside the Liquid Hydrogen and Liquid Oxygen block, stating that the machine doesn't accept fluid, which is not true, since I have successfully used an Exporter(RS) instead of the Crafter(RS) to create the Liquid Hydrogen and Liquid Oxygen and store them in the grid without autocrafting.

#### What you expected to happen:
The Autocrafting for the Liquid Oxygen and Liquid Hydrogen to happen properly, by successfully injecting water into Electrolytic Separator(MEK) according to the quantity of Liquid  Oxygen ordered.

#### Steps to reproduce:
1. Place a Electrolytic Separator(MEK), connect the both sides with a Rotary Condensitrator(Mek), add a bucket water in and the liquid oygen and gas should be produced within the two Rotary Condensitrator(Mek). Use 2 Importer to collect the Liquid Oxygen and Liquid Hydrogen from the Rotary Condensitrator(Mek).
2.  Place a Crafter on the top of the Electrolytic Separator(MEK), connect it to the grid.
3. Construct a liquid to liquid pattern with Pattern Grid and place it in the crafter.
4. Stroe 1B of water in the liquid Grid, try ordering 1B of Liquid Oxygen.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4 forge
- Forge: 1.16.4-35.1.37
- Refined Storage: 1.9.11

Does this issue occur on a server? [yes/no]
no

**Comment by Darkere** [comment]
Only thing I can imagine here is setting up in/outputs on the electrolyzer wrong.

**Comment by Inkdot-Test** [comment]
> Only thing I can imagine here is setting up in/outputs on the electrolyzer wrong.

Emm, don't think so, since the fluid is set to be injected from all the six sides by default. And I also tried replacing the exporter directly with a crafter. The exporter can inject the liquid, but the crafter cannot.

**Comment by bloodscon** [comment]
might be due to the way meka treats it's inventory try using a buffer tank between the crafter and Separator also I'm sure the Separator only accepts water from certain sides (some piping modes seem to override it)

**Comment by Darkere** [comment]
Got this working just fine. Mekanism side configs are a nightmare.
