### ISSUE TITLE
[1.16.4] Crafter cannot pull from mekanism machines when craft is complete

### ISSUE THREAD

**Issue by Crabby-Gamer** [refinedmods/refinedstorage#2852]
#### Issue description:
See title.
#### What happens:
Crafter does not pull from any Mekanism machine when a craft is finished despite said side being set to input/output.
#### What you expected to happen:
Crafter pulls the result from the machine, completing the craft.
#### Steps to reproduce:
1. Setup a basic RS system.
2. Attach a crafter to any Mekanism machine and set the attached side to input/output and enable auto eject in the Mekanism machine settings.
3. Start a craft, I used an  unupgraded energized smelter in the test world but in my live server it happened with any machine at any tier.
4. Input will work fine, it will insert cobblestone.
5. Output will not work, requiring an importer attached to the machine.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.37
- Refined Storage: 1.9.11
- Mekanism: 10.0.18.445 

Does this issue occur on a server? [yes/no]
Yes, I first noticed this issue when playing on a server I set up for some friends.

**Comment by BlueAgent** [comment]
IIRC Crafters don't automatically pull outputs from machines. You need to use an Importer.
