### ISSUE TITLE
"Allowed tags" feature only usable in processing recipes

### ISSUE THREAD

**Issue by aaronhowser1** [refinedmods/refinedstorage#2853]
#### Issue description:
From the [RS wiki](https://refinedmods.com/refined-storage/wiki/pattern-grid.html):

> Allowed tags (Refined Storage 1.7.x or higher)
> The allowed tags system in Refined Storage allows the player to decide which items or fluids can be used as alternatives when the specified item or fluid isn’t found in the storage network.
> These tags are retrieved from Minecraft’s tag system. You can specify the allowed tags in the Pattern Grid.
> To define valid alternatives for an item or fluid, **use CTRL + click** on the input slot and specify the allowed tags that can be used during autocrafting. Items or fluids from that tag are then marked as valid alternatives if the original item or fluid can’t be found in the storage network.
> You can also define valid alternatives by clicking on the item or fluid and then clicking on “Alternatives”.

![image](https://user-images.githubusercontent.com/15698722/105821449-7a76f100-5f80-11eb-918a-36a6cc43b9e0.png)
Holding control and clicking on one of the Planks simply removes it.
![image](https://user-images.githubusercontent.com/15698722/105821477-8662b300-5f80-11eb-92cc-4cc90e8dec12.png)

Since it's set to Exact: False, this recipe still works with Birch Planks (though the Pattern's tooltip doesn't say that it's Exact: False). But is the Allowed Tags feature just not implemented yet?

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.1
- Refined Storage: refinedstorage-1.9.11

**Comment by Darkere** [comment]
The allowed tags feature only makes sense for Processing recipes. 

Crafting recipes only have a list of valid items internally and as such it doesn't really have any direct relation to tags.
(Although thinking about it, theoretically it is possible to make this work)

Disabling exact mode will make the system evaluate all valid items for the recipe in a "random" order. 

Wood recipes are problematic. The Oak button recipe only accepts oak wood planks.
Any other wooden plank would have a different output and as such be a different recipe.

**Comment by aaronhowser1** [comment]
A lot of crafting recipes use tags instead of direct items. Sticks use `minecraft:planks` rather than a list of planks, for instance. TNT uses the tag `minecraft:sand` etc.

**Comment by raoulvdberge** [comment]
Like @Darkere  said, this is by design. You can't modify the tags of a real crafting recipe, as that would break the recipe.

**Comment by Darkere** [comment]
> A lot of crafting recipes use tags instead of direct items. Sticks use minecraft:planks rather than a list of planks, for instance. TNT uses the tag minecraft:sand etc.

Yes. Internally though the resulting crafting recipe will only use a list of items. Minecraft grabs all items in the tag at some point and adds them as an ingredient to the recipe. Non-exact patterns should work with these.

In theory we _could_ allow for only a selection of the ingredients. However this quickly becomes complicated when accounting for the fact that recipes and the allowed ingredients can change over time/versions.
