### ISSUE TITLE
Industrial Foregoing latex exported as Minecraft water

### ISSUE THREAD

**Issue by Apprehentice** [refinedmods/refinedstorage#2857]
#### Issue description:

Industrial Foregoing latex is being exported by Refined Storage exporters and external storage as Minecraft water. Crafters use Industrial Foregoing latex correctly.

#### What happens:

When a Refined Storage exporter or external storage is placed on a fluid inventory and whitelisted for Industrial Foregoing latex, Minecraft water is placed into the fluid inventory instead. If the adjacent inventory already contains Industrial Foregoing latex, inserted by other means such as a bucket of latex, no fluid is inserted. Crafters insert Industrial Foregoing latex into adjacent inventories correctly.

#### What you expected to happen:

A Refined Storage exporter or external storage placed on a fluid inventory and whitelisted for Industrial Foregoing latex should correctly export Industrial Foregoing latex into the fluid inventory.

#### Steps to reproduce:
1. Assemble a Refined Storage network containing Industrial Foregoing latex
2. Place a fluid inventory
3. Connect the fluid inventory to the network with an exporter or external storage
4. Configure the network to fill the fluid inventory with Industrial Foregoing latex
5. Note that the inventory now contains Minecraft water

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.36
- Refined Storage: 1.9.11

Does this issue occur on a server? [yes/no]

Yes

#### If a (crash)log is relevant for this issue, link it here:

N/A

**Comment by Darkere** [comment]
Do you have a sink connected to your system?

**Comment by Apprehentice** [comment]
I do, yes, thank you for suggesting that. I apologize for not being thorough enough in my testing. Putting a buffer between the tank and the system appears to have solved the issue. That makes this another problem, yes? There doesn't appear to be another issue for this.

**Comment by Darkere** [comment]
No. It's fine. Just means I know what happened. This is an issue with Cooking for blockheads. I've reported it and it will hopefully get fixed soon. 

Making a new sink and making sure you do not insert any fluids into it should fix the issue.
