### ISSUE TITLE
Buckets not returned when crafting with filled buckets

### ISSUE THREAD

**Issue by shortnr** [refinedmods/refinedstorage#2859]
#### Issue description:

Empty buckets are not being returned when autocrafting with (at least one) recipe requiring filled buckets. Buckets are being filled with TE Fluid Encapsulator connected to a Crafter (RS).

#### What happens:

When crafting dielectric paste from the Powah mod (Direwolf20 1.16 pack), the paste is autocrafted, but the bucket is not returned.

#### What you expected to happen:

Dielectric paste to be crafted, and bucket to be returned.

#### Steps to reproduce:
1. Have dielectric paste pattern.
2. Request dielectric paste.
3. Get dielectric paste.
4. ...
5. Do not profit.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.36
- Refined Storage: 1.9.11

Does this issue occur on a server? [yes/no]

Unknown

#### If a (crash)log is relevant for this issue, link it here:

No crash.

Be gentle.. this is my first Git bug report :)

**Comment by shortnr** [comment]
Please disregard. I'm a derp.

**Comment by ChrisLane** [comment]
@shortnr where were your buckets going?
Trying to figure out the same mystery here.
