### ISSUE TITLE
UnsupportedOperationException when crafting using crafting grid

### ISSUE THREAD

**Issue by evhub** [refinedmods/refinedstorage#2860]
#### Issue description:

Attempting to craft an item using the crafting grid crashed my client with [this crash report](https://gist.github.com/evhub/7c3b6229f9aaca6c4cca47cfb6161561).

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.9
- Refined Storage: 1.9.11

Does this issue occur on a server? This was a client-side crash when connected to a dedicated server.

#### If a (crash)log is relevant for this issue, link it here:

<https://gist.github.com/evhub/7c3b6229f9aaca6c4cca47cfb6161561>

**Comment by Darkere** [comment]
Duplicate of #2811

fixed for 1.9.12
