### ISSUE TITLE
Holding out portable grid causes severe lag

### ISSUE THREAD

**Issue by recursiveSlacker** [refinedmods/refinedstorage#2861]
#### What happens: Holding a portable grid in hand causes the game's framerate to tank, down to half or even a quarter of what it was before. The issue does not stop at holding out the grid proper, either -- putting Tetra's tool belt in hand when the tool belt contains the portable grid lags the game out exactly like if you held out the portable grid itself. The same occurs if you put it inside of a shulker box or Mekanism's personal chest, and then hold those items -- even more distressingly, this happens if you nest these items, e.g. if you place the portable grid in a Mekanism personal chest, and then place the chest into a Tetra toolbelt and then hold the toolbelt out, it will lag. This notably does not occur with the Ender Pouch from EnderStorage, which is safe to hold out with a portable grid inside of it.

As another minor note, putting the grid in Tetra's toolbelt while you have it in hand will only trigger the lag after you close out of the menu, and similarly will not stop lagging when you remove it from the toolbelt inventory until after you close out the menu as well, while the lag situation instantly updates for things like Mekanism's personal chest. I believe this is due to some different way the belt and the chest handle inventory, and this difference might let you narrow down the possible culprits.

This has nothing to do with the items held within the portable grid, by the way. It lags just as much without a disk in it as it does with a 64k item storage disk, and holding a disk itself causes no lag.

#### Steps to reproduce:
1. Obtain either a Portable Grid or a container such as a shulker box containing a Portable Grid.
2. Either place the grid/container in your hotbar and select that slot as your main hand item, or put it into your offhand slot.
3. Watch your FPS crater.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.1
- Refined Storage: 1.9.11

Does this issue occur on a server? 

I only know of it occurring in singleplayer, have not tested servers.

**Comment by Darkere** [comment]
Tried to reproduce this.. and got 0 difference. Additionally your description does not quite make sense. Having the portable grid inside a bag means it does nothing. And as such it can't really affect your FPS in any way. 

If you can still reproduce it try running a client side profiling with spark to see exactly what the problem is.
