### ISSUE TITLE
[Enhancement] 'Sticky' search on Grids and Crafter Managers

### ISSUE THREAD

**Issue by dylithian** [refinedmods/refinedstorage#2862]
Enhancement idea:
"Sticky" search on various refined storage blocks, like the grids (crafting, pattern, etc) and the crafting manager.

This functionality would give search terms an optional 'sticky' button that would keep the search query in the search field even after the interface for the block has closed.

This allows for separate crafter managers to be automatically preset to display, for example, all matches for 'Furnace', without the need for complicated mechanics like view cards or such.

This also allows for integration with JEI search to have mod filters in various grids, to only show items from that mod.

**Comment by raoulvdberge** [comment]
Already exists
