### ISSUE TITLE
Wrong amount of items displayed

### ISSUE THREAD

**Issue by leglerm** [refinedmods/refinedstorage#2867]
#### Issue description:
I build a very simple system with just a controller, crafting grid and a disk drive with 8 drives (1k and 4k)

I got around 350 nether quartz. When they system is empty it displays 0. When putting it all in it shows the correct amount. 
But when i close the grid and re-open it it shows i got 1.200 from which i can only take out the 350 that i actually have. Even when reopening it still shows me the 800. 

This happens for like 90% of my stored items 

#### What happens:
Displayed wrong amount

#### What you expected to happen:
Show correct amount

#### Steps to reproduce:
1. Put items in
2. Reopen grid and see wrong amount

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.37
- Refined Storage: 1.9.11

Does this issue occur on a server? 
yes. Private server for 2 people

**Comment by Darkere** [comment]
How did you make the disks? Duplicating disks in creative mode creates "linked" disks that access the same storage.

**Comment by leglerm** [comment]
This was actually the problem. I had 4 disks with the same "id".
