### ISSUE TITLE
Simmilar issue to #788

### ISSUE THREAD

**Issue by Hermsmegerms** [refinedmods/refinedstorage#2869]
#### Issue description:
When trying to create a pattern using Mystical agriculture Master infusion crystal, You can only craft one at a time since it thinks the crystal will be consumed.

#### What happens:
An item that does not get consumed is reporting that i do not have enough of the item to craft more than one at a time
#### What you expected to happen:
I should be able to craft as many as i need since the master infusion crystal is not consumed through crafting

#### Steps to reproduce:
1.create a pattern for prudentium essence using the pattern grid (4 inferium in a cross around a master infusion crystal)
2. place pattern in crafter
3. attempt to craft any number higher than 1 
4. crafting will state you do not have enough master infusion crystals even though it is an infinite use item that does not get consumed during use.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.13
- Refined Storage: 1.9.11

Does this issue occur on a server? Yes

**Comment by CYNAX1** [comment]
Thank you for this repport, im also in to the same problem, hope that coder will eventually TELL or do something about this..

And not come out with another excuse telling us already been reported... that when you look in other report there is no answer... just a short answer would be appreciate.

And STOP!!! with have you try with JEI or "clicking OREDICT as oredict is not there in the present version..." and Exact MODE DO NOT solve the issue...

**Comment by AliyahPhelps** [comment]
Having the same issue here. I also cannot "force" an operation by using crt+shift+click. 
Major frustrating.

**Comment by raoulvdberge** [comment]
This is intended
