### ISSUE TITLE
Refined storage disks delete them selfs

### ISSUE THREAD

**Issue by Cody9504** [refinedmods/refinedstorage#2870]
My refined storage disks delete them selfs when i log out and back into my direwolf 20 world. For 1.16.4 and 1.16.5 and when i load a my latest backup for it (which i always back up my worlds before i log off of that said world) the refined storage disks are gone btw ive tested this many times and it does not fail but it doesnt always happen so i dont know if its my pc or a bug

...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Please follow the template.

For weird saving bus double check that you don't have your game saved in a location used by a program like One drive.
