### ISSUE TITLE
Dragging fluid to output part of processing recipe does not work

### ISSUE THREAD

**Issue by pnieuwkamp** [refinedmods/refinedstorage#2871]
#### Issue description:
Using the pattern grid, I can't drag fluids from JEI to the processing recipe outputs. Using a filled bucket does work, as does dragging a fluid to the input side.

#### What happens:
When dragging a fluid from JEI the pattern grid shows the green background, but the fluid is not actually added to the recipe. Programming a pattern confirms that the fluid I tried to drag to the output side is not in the recipe.

#### What you expected to happen:
I expect the pattern grid to add the fluid to the expected outputs

#### Steps to reproduce:
1. Open pattern grid
2. Set the recipe mode to "Processing"
3. Set the the recipe type to fluid 
3. Drag a fluid from JEI to an output slot

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.15
- Refined Storage: 1.9.11
(also happens with 1.16.4/35.1.37/1.9.11)

Does this issue occur on a server?
I'm in a singleplayer world, haven't tested on a server

**Comment by pnieuwkamp** [comment]
Ah, I only now realize #2863 is about the same issue; the title led me astray as I thought it was about magma blocks. That one is closed though. Should this one remain open to keep track or is this known bug tracked elsewhere?

**Comment by Darkere** [comment]
Samne issue has #2822

**Comment by pnieuwkamp** [comment]
Those issues are closed, but the bugs still exist... I guess I just don't understand how Github works. At work we only close issues after it has been resolved, both to keep track and to avoid duplicates.

Sorry for opening duplicates.
