### ISSUE TITLE
Detector crashes when placed in the world 

### ISSUE THREAD

**Issue by WildKarrade** [refinedmods/refinedstorage#2876]
#### Issue description:
Crash on placing the detector in the world.

#### What happens:
Server and client both crash when the chunk is loaded.

#### What you expected to happen:
Detector to work fine.

#### Steps to reproduce:
1. Create Detector
2. Place Detector
3. Detector crashes server/client
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.37
- Refined Storage: 1.9.11

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/ZkT9R96j

**Comment by Darkere** [comment]
Something super funky going on with your install. Nothing we can do to fix that.
