### ISSUE TITLE
Updating from 1.15.2 to 1.16.5 deletes all hard drives!

### ISSUE THREAD

**Issue by mcjojo3** [refinedmods/refinedstorage#2879]
#### Steps to reproduce:
1. start a 1.15.2 world.
2. put drives in a disk drive block.
3. update to 1.16.5
4. profit

- Minecraft: 1.16.5
- Forge: 36.0.22
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes]

**Comment by raoulvdberge** [comment]
Please look up all the other issues about this.

**Comment by mcjojo3** [comment]
I can't find any could you link one?
