### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bloodscon** [refinedmods/refinedstorage#2883]
option in importers GUI to change the way items are imported from items like a chest so instead of pulling from first slot it pulls from the last slot with an item in it or round robins on its pulls

reasons: in a few packs I have played the amount of items that need to be crafted can swamp an importer due to it starting on slot 1 i have had it where i needed 4 importer around a chest with full stack & speed upgrades could not keep up the items in slot 2 could not be cleared as slot 1 was getting repopulated as soon as it was clear this change would help with that

easy way to reproduce is set up 4 redstone furnace ( 2 producing stone 2 producing glass all outputting to 1 chest
with an importer on,  Say slot 1 gets glass slot 2 gets stone in the chest slot 2 will never clear as such no stone goes into the system till the glass is done or you upgrade the importer with stack  + speed but as add more furnace (or faster) it gets worse

option in exporter or interface GUI when crafting upgrade installed to only craft items not pull from storage even if in stock trying to keep more than 64 of item pre-crafted is a redstone nightmare with RS

new item goggles that you wear will highlight all RS blocks/cable in colour from green to red with how busy they are (green having tea and biscuits, red omg she just cannot take anymore captain)

**Comment by bloodscon** [comment]
Btw love the mod got into it on skyfactory 3

**Comment by raoulvdberge** [comment]
Please create an issue per suggestion, a bit more structured.
