### ISSUE TITLE
Mod comparability issue with RS protection from Security Manager

### ISSUE THREAD

**Issue by koalalord9999** [refinedmods/refinedstorage#2885]
#### Steps to reproduce:
1. Put a blank card with no perms into security manager
2. Get your ensorcialltion aoe mining pickaxe
3. Break some blocks at the same x or a coordinates and watch the refined storage just poof outta existence 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 36.0.10
- Refined Storage: 1.9.11

Does this issue occur on a server? [yes/no]
Yes

**Comment by Darkere** [comment]
The other mod needs to make sure to call and respect block break events. 

Not an RS issue.
