### ISSUE TITLE
Server crash when using external storage

### ISSUE THREAD

**Issue by Mannhood** [refinedmods/refinedstorage#2887]
#### Issue description:
Server stops responding when almost done loading or player entering
#### What happens:
Server hangs then crashes when nearly done loading or player entering
#### What you expected to happen:
Well that it would work. But i had 7+ quantum storage chests with External storage on them then the game kept crashing every time i had to download the world run it in single player and if i was lucky that worked and i could then reupload and the server could run for 20 hours or so then went down again. I could see that the crash log was mainly RS mod so i tried to switch to Black hole for industrial foregoing. But got same result. Then i reduced the number of ext storage to 5 but again the problem came back. then i removed all ES from the world and now it is running perfectly.
#### Steps to reproduce:
1.Use DW 20 mod pack version 1.6.1
2.Setup medium complex autocrafting
3.Have 5+ EXT storage on Quantum chest or black hole filled with 30k to 550k items
4.have a melon farm store mellons in quantum storage and then have a squeeser from immersive request mellons
5. have the server run for some time.
6. I have a few world server saves where the "world broke" that i can send/share via google drive 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: forge-1.16.5-36.0.14.jar
- Refined Storage: refinedstorage-1.9.11.jar and refinedstorage-1.9.12.jar

Does this issue occur on a server? [yes/no]
Yes and single
#### If a (crash)log is relevant for this issue, link it here:
Save can be found here cords to location of the external storage are -3902,70,1818 ish and -3822,78,1818
[pastebin/gist/etc link here]
https://pastebin.com/UnuXyAf0

**Comment by Darkere** [comment]
Try adding a 0 to max-tick-time in server.properties.

**Comment by Mannhood** [comment]
Tried it it got the server to load but tik rate suffered so i had to remote all external storage devices that made the server run perfectly

**Comment by raoulvdberge** [comment]
Watchdog crashes are not that useful, unfortunately.

**Comment by Mannhood** [comment]
Ok so your comment made me go back to that world save and test if i could find a reason. So i have had a mob farm running for days to get item but allso i saved all the gear that dropped plan was to strip enchants from it, but I think it's the  thousands of different diamond/iron gear with diffrent combinations of enchants htat is causing the crash. I tried voiding every armor piece from the system and that fixed it. i can even keep the millions of items in som my original idea was wrong. But sending all that data for all those unique items must be the problem. I hope it helps and thank you for making this awsome mod
