### ISSUE TITLE
Pressing tab in the Grid shows hovering text that can garble item descriptions

### ISSUE THREAD

**Issue by MarioSMB** [refinedmods/refinedstorage#2888]
#### Issue description:
Pressing the TAB key while in the Grid (Crafting Grid in my case) shows a hovering text next to the cursor saying "Redstone mode - Ignore redstone signal". If you move the cursor over an item in your inventory, this hovering text remains and overlaps with the item's name.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 35.1.36
- Refined Storage: 1.9.12

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
For what reason are you pressing Tab in the grid? (if you use Tab to focus the grid the issue does not happen)

These are caused by Minecrafts accessibility feature switching between available buttons when you press tag. I don't think it would be a good idea to disable that.

**Comment by MarioSMB** [comment]
I've just verified that this *does* occur with vanilla interfaces (the beacon to be specific), so indeed, this is not really related to Refined Storage.  
That said, I will point out that TAB switching does *not* work properly with the Grid; the second press has the selection box grab input, and further TAB presses no longer do anything.
