### ISSUE TITLE
Yet another reason to add an option to ignore nbt for patterns. 

### ISSUE THREAD

**Issue by Lyl4c** [refinedmods/refinedstorage#2890]
#### Issue description:

Autocrafting code cannot tell the difference between the same blocks used in patterns and in storage due to additional nbt data.

#### What happens:

[Context 1](https://pipe.miroware.io/5bc1294f1c0a1c3ffd485c5b/Minecraft/Mods/Github/Issues/RS1.png)
[Context 2](https://pipe.miroware.io/5bc1294f1c0a1c3ffd485c5b/Minecraft/Mods/Github/Issues/RS2.png)

The Magmators, when crafted by hand or machine, don't have additional nbt stored initially. Especially so when the recipe is shift clicked into the pattern from JEI. Even when I put that Magmator(starter) that has nbt back into the pattern it still wants to craft a fresh Magmator(starter) rather than use existing materials in the storage.

[RS wants to craft new starter machines](https://pipe.miroware.io/5bc1294f1c0a1c3ffd485c5b/Minecraft/Mods/Github/Issues/RS3.png)
[And yet there are 5 already in here!](https://pipe.miroware.io/5bc1294f1c0a1c3ffd485c5b/Minecraft/Mods/Github/Issues/RS4.png)
[nbt context](https://pipe.miroware.io/5bc1294f1c0a1c3ffd485c5b/Minecraft/Mods/Github/Issues/RS5.png)

#### What you expected to happen:

RS autocrafting to use existing materials in the storage system, reguardless of nbt, if the exact option is unchecked in the pattern.

~~#### Steps to reproduce:~~ no!

Looking through closed issues related to nbt data I found that this problem relating to nbt has been reported and closed multiple times! The earliest one I've found on short notice is [from 2016](https://github.com/refinedmods/refinedstorage/issues/565). 4 1/2 years ago. Its basic stuff like this that makes me perfer Ae2 over RS. I like Refined Storage, and I'd like to see it maintained into future versions of minecraft. But seriously, 4 years to delay programming a simple option to ignore nbt? Thats not right.

([Not a valid excuse, blocks with different nbt are still the same block.](https://github.com/refinedmods/refinedstorage/issues/2526#issuecomment-630489492))

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.13
- Refined Storage: refinedstorage-1.9.1.1

Does this issue occur on a server? [yes]

**Comment by Darkere** [comment]
> Not a valid excuse, blocks with different nbt are still the same block.

Indeed they are still the same block. Unfortunately they may not be eligible ingredients for the same recipe. 

The evaluation for whether or not they are a valid ingredient happens when the items are actually used and crafted. A non correct item here would (if not for an existing bug) crash the game. 

Even if they did not crash you would still end up with crafting tasks that will never finish. 

A much better solution is to change the recipe so that the issue disappears. Mekanism has successfully done so for example.

**Comment by raoulvdberge** [comment]
>  But seriously, 4 years to delay programming a simple option to ignore nbt? Thats not right.

We didn't "delay" it, we are just not adding it.

It's not possible to let the player decide WHEN to ignore NBT. That could break recipes/balance in some cases.
