### ISSUE TITLE
[1.16+] Crafting recipe for Network Transmitter and Receiver is too expensive.

### ISSUE THREAD

**Issue by MoleMad** [refinedmods/refinedstorage#2892]
This is more of a suggestion/complaint than an issue, but requiring users to find and mine 8 gold and 8 pieces of extremely rare Ancient Debris just for networking is way too much. At the very least, I think each block should require only 1 netherite _scrap_ instead of a full netherite ingot, as shown below.

![Capture](https://user-images.githubusercontent.com/79708658/109324276-701b7180-7822-11eb-8442-8b91965ed4f1.PNG)

Or if you'd like you can have a slightly more expensive version with 2 netherite scrap like this:

![Capture2](https://user-images.githubusercontent.com/79708658/109324388-99d49880-7822-11eb-9d33-e25f059f831a.PNG)

**Comment by raoulvdberge** [comment]
Wireless technology is expensive!
