### ISSUE TITLE
All my items are gone

### ISSUE THREAD

**Issue by Blober8000** [refinedmods/refinedstorage#2894]
#### Steps to reproduce:
1. I don't know
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.11
- Refined Storage: 1.9.10

Does this issue occur on a server? No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Please read the changelog of version 1.9.11. Just need to rename the file and update.

Also the newest version is 1.9.12.

**Comment by Blober8000** [comment]
> Please read the changelog of version 1.9.11. Just need to rename the file and update.
> 
> Also the newest version is 1.9.12.

So I did that and it didnt work my stuff is still gone

**Comment by Darkere** [comment]
Then you've unfortunately already overwritten your file. Presumably by creating new disks. 

Backup is the only other possible solution then I'm afraid. 

Version 1.9.10 should not be used. We should probably just archive it, or at least set it to alpha.

**Comment by Blober8000** [comment]
> Then you've unfortunately already overwritten your file. Presumably by creating new disks.
> 
> Backup is the only other possible solution then I'm afraid.
> 
> Version 1.9.10 should not be used. We should probably just archive it, or at least set it to alpha.

well I didn't create any new disks cause I lost all my stuff but thx anyway
