### ISSUE TITLE
creative controller cant power my system

### ISSUE THREAD

**Issue by djnugets** [refinedmods/refinedstorage#2896]
#### Issue description:
my system is using more than 32krf/t and keeps shutting down w the creative controller 
#### What happens:
the creative controller isn't powering my system enough
#### What you expected to happen:
the creative controller to power everything w/o problem 
#### Steps to reproduce:
1.get a creative controller 
2.get the system to use more than 32krf/t
3.watch it turn on and off over and over 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge:36.0.43
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
yes 
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Increase the max power setting in the config

**Comment by djnugets** [comment]
im not seeing a config for it

**Comment by Darkere** [comment]
This setting is in the serverconfig /<yourworld/serverconfig/refinedstorage-server.toml.

**Comment by djnugets** [comment]
thank you
