### ISSUE TITLE
[Feature Request] Allow placing Storage Housing inside Disk Drives for decoration.

### ISSUE THREAD

**Issue by ScorcherOfAwesomeness** [refinedmods/refinedstorage#2897]
So I have a few spare Disk Drives sitting in my base's RS room. I was thinking "Why not have it so you can add storage housing to Disk Drives to have them look filled up?" This would be a great improvement to allow survival players to use Disk Drives with Storage Disks as decoration without having to make the components themselves. I think you should have these housings glow green when active with RS  and/or find a way to allow customization of these housings.

**Comment by raoulvdberge** [comment]
I like the idea, but rendering "green"/active for a "dummy" item seems  weird, since there is no storage behind it.

So I would opt in to rendering a "disconnected" disk, but that would kind of defeat the point of the feature in the first place.

So I'm just closing this.
