### ISSUE TITLE
Can't craft Controller

### ISSUE THREAD

**Issue by Shanimzy** [refinedmods/refinedstorage#2900]
#### Steps to reproduce:
1. Install AT Launcer
2. Create Vanilla Minecraft with Forge 1.16.5 Instance
3. Install the following mods ; Immersive engineering/Petrol/Railroading , Refined Storage, Track API, Universal Mod Core
4.  Create new world  (Creative or survival, creative gives you quick access to the items needed to craft the controller)
5. Attempt to craft controller
6. Doesn't work

...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge:  36.0.42
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no] Unsure don't play on server this is a solo play

#### If a (crash)log is relevant for this issue, link it here: N/A

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Install just enough items and check the recipes.
