### ISSUE TITLE
Crash while loading client in phase 1

### ISSUE THREAD

**Issue by VictorGamerLOL** [refinedmods/refinedstorage#2903]
#### Issue description: 
Minecraft just crashed in phase 1 loading

#### What happens: 
Crashed in phase 1 of forge loading

#### What you expected to happen: 
The game to load?

#### Steps to reproduce:
1. Install this modpack (don't question the name): [War crimes-1.zip](https://github.com/refinedmods/refinedstorage/files/6091425/War.crimes-1.zip)

2. Try to start it
3. Crash
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 14.23.5.2854
- Refined Storage: 1.6.16

Does this issue occur on a server? no

#### If a (crash)log is relevant for this issue, link it here:

included in modpack and here:
[crash-2021-03-05_15.16.07-client.txt](https://github.com/refinedmods/refinedstorage/files/6091442/crash-2021-03-05_15.16.07-client.txt)

**Comment by Darkere** [comment]
you are about 10 versions behind on refinedstorage addons....
