### ISSUE TITLE
[Duplicate of Issue #723 Updated] Destructors Do Not Work With Botania

### ISSUE THREAD

**Issue by DizzyDJW** [refinedmods/refinedstorage#2905]
#### Issue description:
Destructors do not pick up transformed blocks, not even with a silk touch upgrade.
#### Notes:
There is no FTBUtilities mod for 1.16.5 if the issue is "allow fake players".
#### What happens:
Destructors break blocks and nothing is picked up.
#### What you expected to happen:
Destructors should break blocks and place them into the system.
#### Steps to reproduce:
1. Place Destructors and Constructors around a Pure Daisy.
2. Set them to pick up packed ice. Insert Silk Touch Upgrade.
3. Set constructors to place ice.
4. Observe ice break and not be picked up.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge:  36.0.45
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
no

**Comment by Darkere** [comment]
> There is no FTBUtilities mod for 1.16.5 if the issue is "allow fake players".

The 1.16 FTB claim mod is called FTBChunks. 


Do blocks other than Ice work?

**Comment by DizzyDJW** [comment]
Yes, but no ice of any kind even another mod's

**Comment by Darkere** [comment]
Hmm I'm unsure what could cause this. An option would be if you did not have anywhere for the ice to be stored?

I set up a test world and both breaking Ice normally and with silk touch worked just fine. Even ice transformed by a pure daisy is working just fine.

**Comment by DizzyDJW** [comment]
That's strange I just tested it myself in a new world and again, even with silk touch upgrades and plenty of empty storage, the destructors just destroy the packed ice once it forms. Had half without silk touch and half with just and didn't get a single packed ice anywhere in the system
