### ISSUE TITLE
[1.16] Compatibility issues between Farmer's Delight cooking pot and Refined Storage auto-crafting

### ISSUE THREAD

**Issue by AbacusOperator** [refinedmods/refinedstorage#2906]
### Issue description:
**Important note**: I don't know which mod in this interaction is responsible for failure, so I am reporting issue identically at issue trackers of both mods involved, thus a bit of introduction is provided to both mods, thus some parts might seem as overexplanation.

#### _Farmer's Delight's cooking pot_
Farmer Delight is a cooking and farming mod. Most cooking recipes in this mod centered cooking pot. Cooking pot is placed atop of heating block, such as magma block or Farmer's delight own stove. Cooking pot's GUI consists of four major parts:

1.  3x2 crafting grid for dish ingredients in the top-left corner.
2.  Serving container input in the bottom-right corner.
3.  'Pre-packed' output slot in the top-right corner.
4. Actual output extraction slot in the bottom-right corner.

Output is produced in the upper output slot (GUI3) if correct pattern if filled in the crafting grid (GUI 1), however to actually output the result as item, appropriate serving container (usually either bottle or bowl) is has to be placed into serving container input slot (GUI 2), it is consumed upon actually creating output item in the output slot (GUI 4)

#### _Refined Storage Auto-crafting_
Refined Storage provides methods for using Vanilla and other mods' machines automatically through storage system and crafter with required crafting pattern, that can be created manually or through JEI integration. The most basic setup of Refined Storage system needed for debugging issue at hand:

0. Cable. Connects parts of system
1. Controller. Block that unites all system together, its GUI lists all parts of storage system. For debug purposes use Creative, that doesn't require energy.
2. Item Storage. Block that actually stores items in the system. Smallest 1k storage is enough for testing any recipes.
3. Grid. Block used to insert and extract items from system, as well as ordering crafting of missing items if patterns for them are in the system.
4. Pattern Grid. Block that used to create patterns for automatic crafting. In this case processing mode should be checked on. Input items placed into the 3x3 input grid on the left and output items placed into 3x3 output on the left. Empty pattern (refinedstorage:pattern) is inputted the upper right slot and written pattern is produced in the slot below it. Pattern grid can be filled out manually or with JEI support by opening JEI recipe while in Pattern Grid GUI and pressing + on the bottom right of recipe in JEI.
5. Processing machine. In this case Farmer's delight cooking pot.
6. Crafter. Blok that should be placed facing the processing machine. Written pattern should placed in it. Should be connected to the rest of storage system.
7. Exporter. Export items from the system. In this case should connects crafter and processing machine in order to place input ingredients into machine. Note that it should not be connected to storage system directly or it will just turn machine into storage by try place items from system into it.
8. Importer. Inputs items into the system. In this case should connects crafter and processing machine in order to take outputs.

#### _The issue itself_

Automated crafting of food in Farmer's Delight's Cooking Pot with Refined Storage system is impossible due to at least three distinct issues:

- Refined Storage pattern grid (and most likely crafter and importer/exporters) doesn't recognize cooking pot's serving container slot (GUI2). Instead serving container is incorrectly recognized as part of output by JEI pattern created through JEI integration and won't go into it slot if manually made part of input side of pattern. This is resulting invalid recipes and cooking pot ultimate inability to be fully automated with Refined Storage.
- Refined Storage pattern grid doesn't differentiate stack of N items from the same item used in N different slots of cooking pot's crafting grid. It just dumps all input items into grid, resulting in stacking of identical items. It is relevant not for all recipes, but those ones that have the same ingredient used more then once, for example, hot cocoa (farmersdelight:hot_cocoa).
- If crafting of multiple of the same item is requested at once, refined storage will try to input totality of crafting ingredients into the cooking pot, even if it ruins recipe. For example, hot cocoa requires one bucket of milk. Milk bucket is not stackable, thus if more than one hot cocoa is requested, Refined Storage puts more than one milk bucket into cooking pot crafting grid, rendering recipe invalid.

### What happens:
Cooking pot's recipe processing pattern created through Refined Storage's JEI integration or manually doesn't produce any outcomes due to Refined Storage not interpreting Farmer's Delight correctly, see details above. Items that are recongized as input are simply damped into

### What you expected to happen:
Refined Storage correctly interprets and executes Farmer's Delight cooking pot recipes, enabling automated crafting when serving containers and cooking ingredients are available.

### Steps to reproduce:
1. Setup Farmer's Delight cooking station consisting of Farmer Delight's cooking pot a top of Farmer Delight's stove.
2. Setup basic Refined Storage system consisting of (Creative) Controller, Grid, Pattern Grid and Item Storage that are adjusted to each other.
3. Place Refined Storage's crafter facing the Farmer Delight's cooking pot.
4. Place Refined Storage's importer and exporter facing Farmer Delight's cooking pot and connect them to the crafter with cable.
5. With cable connect crafter to Refined Storage system that was set up in step 2. **Important note**: Cooking pot's importer and exporter are to be connected to the crafter, but not to the 
6. Variant A: Create Refined Storage's processing recipe pattern for Farmer Delight's cooking pot using Refined Storage support for JEI in Pattern grid. Variant B: Create Refined Storage's processing recipe pattern for Farmer Delight's cooking pot manually adding all ingredients and serving container into the input side of pattern and expected output into output side of pattern.
7. Install one of resulting patterns into the crafter.
8. Add all needed ingredients into the storage system through the grid.
9. Request crafting of cooking pot's product through the grid.

### List of mods & vanilla versions:

- Minecraft: 1.16.5
- Forge: 36.0.46
- Refined Storage: 1.1.12
- Farmer's Delight: 0.3.2
- JEI: 7.6.1.71

Does this issue occur on a server? [yes/no]
No, singleplayer

**Comment by Darkere** [comment]
> Instead serving container is incorrectly recognized as part of output by JEI pattern created through JEI integration

This is on simple farming. They need to add the item as input to the recipe. Not anything we can do about it.

> Refined Storage pattern grid (and most likely crafter and importer/exporters) doesn't recognize cooking pot's serving container slot (GUI2).  and won't go into it slot if manually made part of input side of pattern.

This depends on simple farming. They may have it set up in a way where depending on the side you are inserting into a different slot is accessed. 

> Refined Storage pattern grid doesn't differentiate stack of N items from the same item used in N different slots of cooking pot's crafting grid. It just dumps all input items into grid, resulting in stacking of identical items.

I am fairly certain that as long as the pattern specifies that the item goes into multiple slots, the crafter will respect this. In fact, I received a bug report recently where this was causing problems.

>If crafting of multiple of the same item is requested at once, refined storage will try to input totality of crafting ingredients into the cooking pot, even if it ruins recipe.

RS Crafter have options to work around this issue. Check the redstone options in the crafter.



PS: Please respect our time when reporting bugs. Keep it short and precise.

**Comment by AbacusOperator** [comment]
> I am fairly certain that as long as the pattern specifies that the item goes into multiple slots, the crafter will respect this. In fact, I received a bug report recently where this was causing problems.

All shaped patterns I tried to input into cooking pot failed. I think that the source of the problem is that cooking pot uses 3x2 grid.

>This is on simple farming. They need to add the item as input to the recipe. Not anything we can do about it.

>This depends on simple farming. They may have it set up in a way where depending on the side you are inserting into a different slot is accessed.

>RS Crafter have options to work around this issue. Check the redstone options in the crafter.

Thank you for response.
