### ISSUE TITLE
Diamond Crafter or Crafter Manager - Lag Spike

### ISSUE THREAD

**Issue by DanteAyagawe** [refinedmods/refinedstorage#2910]
#### Issue description: 
Lagging upon holding down shift and pressing left click on a (non-blank)pattern into a crafter or out of a crafter manager lag spikes the game.

#### What happens: 
It goes in and out of the said crafters luckily but lags severely upon doing so

#### What you expected to happen: See desc. above
See desc. above

#### Steps to reproduce: 
1. Craft a diamond crafter or have a system with a lot of pattern.
2. Hold shift left click a pattern in a crafter or out of a crafter manager
3. Lag spike is reproduced
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: forge-36.0.45
- Refined Storage: rsrequestify-1.16.3-2.0.1.jar

Does this issue occur on a server? [yes/no]
[no] Client Side Only

#### If a (crash)log is relevant for this issue, link it here:
No crash log available linking to this issue

[pastebin/gist/etc link here]

**Comment by fell-lucas** [comment]
Hey, I believe you're talking about the diamond crafters from Extra Storage, which is an addon to Refined Storage, it's a different mod. It would probably be better if you opened an issue over there [link](https://github.com/Edivad99/ExtraStorage) as I'm not sure if this is relevant here.

**Comment by raoulvdberge** [comment]
Should be fixed for next version.
