### ISSUE TITLE
(1.16.5) Controller not accepting power. Creative controller not transmitting power.

### ISSUE THREAD

**Issue by auddie2015** [refinedmods/refinedstorage#2916]
#### Steps to reproduce: 
1. Place a controller
2. Place a power source or cable (they won't attach)
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 1.16.5-forge-36.1.0
- Refined Storage: refinedstorage-1.9.12

Does this issue occur on a server? [yes/no] single player, can't say.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Not an RS issue
