### ISSUE TITLE
[1.16.5] Rendering issues with powered blocks

### ISSUE THREAD

**Issue by Ricky12Awesome** [refinedmods/refinedstorage#2919]
[![Watch Video](https://i.imgur.com/YJx3lcb.jpeg)](https://youtu.be/7d5bYCC4tog)
(Click image to go to video)

Rendering issues with powered blocks using optifine shaders (wokrs fine when shaders are turned off).
I started experiencing this when playing [ATM6 Sky (1.0.4)](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6-to-the-sky-atm6s).
from playing the modpack this seems to be the only mod that has major rendering issues, everything else seems to render just fine.

#### What you expected to happen:
Powered blocks render correctly

#### Steps to reproduce:
1. Have refine storage and latest version of optifine
3. Make sure shaders is enabled (internal would work fine)
2. go into a world and place down anything than has an on/off state (or just an on state like a creative controller)

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge: 36.0.46
- Refined Storage: 1.9.12
- Optifine: OptiFine HD U G8 pre8

**Comment by BentoGambin** [comment]
https://github.com/sp614x/optifine/issues/5448#issuecomment-805872165

**Comment by telemenar** [comment]
Specifically this comes from https://github.com/refinedmods/refinedstorage/blob/mc1.16/src/main/java/com/refinedmods/refinedstorage/render/model/FullbrightBakedModel.java#L71

A sample fix from another mod can be seen here:
https://github.com/Melonslise/Subterranean-Wilderness/commit/f1281ea3759c2830c2ef851760132f2efd488597?branch=f1281ea3759c2830c2ef851760132f2efd488597&diff=unified
