### ISSUE TITLE
Interaction with Dimensional storage causes voided drives!!! 

### ISSUE THREAD

**Issue by BrettMoan** [refinedmods/refinedstorage#2920]
#### Issue description:
this is an "unexpected interaction" bug between this mod and https://github.com/Edivad99/DimStorage.

I'm also using https://github.com/Edivad99/ExtraStorage and https://github.com/MelanX/ExtraDisks but i believe this can be reproduced without those mods. that said, there's a possibility the interactions comes from either the Importer from @ExtraStorage, or the drive from @extradisks, so i'm noting it for completeness.

I've described the bug in full over in the issue over on this issue https://github.com/Edivad99/DimStorage/issues/41

but basically, the ME "disk drive" can have the drives removed from it without a block update, which could cause an importer to import the drive "into itself" which could lead to a voided drive.

#### What happens:
drive gets stored within itself if the drive is removed from a disk drive without a block update

#### What you expected to happen:
either 

- disk drives aren't removed by https://github.com/Edivad99/DimStorage 
- or a block update is preformed by https://github.com/Edivad99/DimStorage.
- or if before any items get "imported" into the ME system the importer checks the connected and a drive block isthe highest priority or only priority storage , the importer checks to see if drives are still there before removing the items from the connected storage
- or if and only "disks" get "imported" into the ME system and they have items in them, and there is empty space in a connected disk drive, that the disk drive gets placed there instead of into the system (IE put the disk BACK in to the disk drive, dont put it into the ME).

#### Steps to reproduce:
https://github.com/Edivad99/DimStorage/issues/41

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16
- Forge: 36.1.2
- Refined Storage: 1.9.12

Does this issue occur on a server? yes TNP limitless public server
 
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Dimstorage issue. No clue what they are doing but removing items from an inventory without calling that the inventory changed is not cool.
