### ISSUE TITLE
Storage Disk Dissapear after log off from single player world

### ISSUE THREAD

**Issue by MrCaptainCrunch1** [refinedmods/refinedstorage#2922]
Every time I log out of my single player world on (Enigmatica 6) and log back in my storage disks disappear from my drive causing me to lose all of my items. Luckily the modpack has a backup mod so I was able to get everything back while only losing about 2 hours of progress. However this issue was not a one time thing and everytime I log out I am forced to take the drives out of my system.  I do not know if this is important but I have added some mods to help chunkload more things and I am wondering if that is causing the issue. Anyway I am hoping to get some help so I can solve this issue and not worry about all of my items disappearing and losing hours of progress any more.

- Minecraft: 1.16.5
- Forge:
- Refined Storage:1.9.12

Does this issue occur on a server? [yes/no]no

**Comment by Lice2** [comment]
We have the same problem, if I shut down the server and restart it, all people's storage disks disappeared from the disk drives.

**Comment by raoulvdberge** [comment]
I can't reproduce this. Probably some other mod is conflicting with RS' saving mechanism.
