### ISSUE TITLE
[Suggestion] Fabric Port

### ISSUE THREAD

**Issue by Gerdathlete** [refinedmods/refinedstorage#2925]
Do you have any plans to port this mod to Fabric? All we currently have is AE2 and its horribly buggy and lacks many features Refined Storage has. Fabric modloader is faster and more efficient at loading mods and makes large modpacks more approachable for those with weaker systems, so many developers have begun to port their mods to fabric.

**Comment by raoulvdberge** [comment]
Yes

**Comment by AnasJS99** [comment]
> Yes

Yes indeed. Waiting though....
I don't like Applied storage for its 63 thingy and the bugs ofc's.

**Comment by adroslice** [comment]
> Yes indeed. Waiting though....

He's working on it, if you havent found out yet: https://github.com/refinedmods/refinedstorage2

**Comment by chiconanni** [comment]
Hello, Is there any milestone 2.4 for fabric MC 1.18.2? Ty in advance
