### ISSUE TITLE
Too many items in storage system results in disconnect on opening item grid 

### ISSUE THREAD

**Issue by tmaaan54** [refinedmods/refinedstorage#2928]
#### Issue description:
With over 3 million (estimated) items in storage, server disconnects when item grid is accessed.
#### What happens:
Screen becomes grey, then disconnects with the message "Payload may not be larger than 1048576 bytes"
#### What you expected to happen:
Opening item grid works as normal
#### Steps to reproduce:
1. Have over 3 millions items in storage system (estimated)
2. Attempt to access item/crafting grid

Modpack: All The Mods 6

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5

- Forge: 36.1.2
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[latest.log](https://github.com/refinedmods/refinedstorage/files/6217992/latest.log)

Using multiple disks from refined storage or a single disk from extra storage does not appear to make a difference.

**Comment by Darkere** [comment]
This happens due to the number of items with NBT data. Usually due to mob farms or similar. Removing those should fix the issue. 

Item count itself does not matter if you only have a lot of the same item.

**Comment by tmaaan54** [comment]
That seems to have fixed the problem for now, but is there any way around this? Or do I just have to throw away all my enchanted books and armor/swords from now on?
