### ISSUE TITLE
[1.16.5] Server crash with mekanism laser

### ISSUE THREAD

**Issue by bigenergy** [refinedmods/refinedstorage#2931]
#### Issue description:
Server crash with mekanism laser

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 1.16.5-36.1.3
- Refined Storage: 1.9.12

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/VVWxGmZg

**Comment by bigenergy** [comment]
it seems this happens when the mekanism laser breaks the drive from refined storage

**Comment by bigenergy** [comment]
same thing happens in a singleplayer

**Comment by raoulvdberge** [comment]
We won't be solving this crash for now, please don't remove RS blocks this way.
