### ISSUE TITLE
Disk Won't show up in disk drive or show items is gird.

### ISSUE THREAD

**Issue by Bluemaster75** [refinedmods/refinedstorage#2935]
#### Issue description:
I was playing on a modpack with a friend. I went to go kill the ender dragon, but just before the killing blow registered, my friend  who ran the LAN server had a blue screen. It caused many things, one being the disk basically becoming a ghost item. When placed into the disk drive, it doesn't appear, and doesn't show the items in the grid. Our server wasn't reset at all, but the items are still listed as being in the disk, basically removing all of the items in that disk.
#### What happens:
I place the 64k disk we made into the disk drive. The disk doesn't appear on the block, and it doesn't show the items. It also doesn't extend the amount the disk drive can hold in the bar on the left whenever you right click it. We can still interact with the item and move it though.
#### What you expected to happen:
The disk to act like normal and allow us to access our items.
#### Steps to reproduce(I think):
1. Play the Sky Bees modpack
2. Play on a LAN Server
3. Have a 64k disk in the disk drive
4. Hit the killing blow on the Ender Dragon

- Minecraft: 1.16.5
- Forge: 36.1.2
- Refined Storage: 1.9.12

This issue occured on a LAN Server with a friend

**Comment by raoulvdberge** [comment]
Looks like there was a data corruption issue. I'd restore from backup.
