### ISSUE TITLE
Netherite Crafter loses patterns when moved with Sticky Piston

### ISSUE THREAD

**Issue by bfc19** [refinedmods/refinedstorage#2939]
#### Issue description:
Netherite Crafter lost patterns when moved by a sticky piston.

#### What happens:
When moving a crafter with the sticky piston, every pattern inside is lost and there is no way to get them back.

#### What you expected to happen:
Netherite Crafter would hold the patterns internally.

#### Steps to reproduce:
1. Netherite Crafter with Pattern
2. Move netherite crafter with the sticky piston.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.2
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
Yes

**Comment by raoulvdberge** [comment]
RS does not support moving blocks with pistons.

**Comment by bfc19** [comment]
Would it make more sense to make the block unpushable like obsidian / furnace etc.?

**Comment by raoulvdberge** [comment]
They are unpushable, you installed a mod that makes them pushable.
