### ISSUE TITLE
Advancements not being given in SP 1.16.5

### ISSUE THREAD

**Issue by reckonedstormlight** [refinedmods/refinedstorage#2942]
#### Issue description:
A couple of the advancements aren't being given when the actions should fulfil them, specifically the Security and No Cables Required ones.

#### What happens:
Literally nothing

#### What you expected to happen:
given the advancements

#### Steps to reproduce:

1. Play a single player world 
2. craft the security manager and card as well as the network transmitter, receiver, and card
3. For the security one specifically, bind a security card, configure it, and place it in the manager
4. For the network one specifically, connect as normal with several components including a crafter, external storage, exporter, and importer (connected to their normal things)
5. don't receive the advancements

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.4
- Refined Storage: 1.9.12

**Comment by raoulvdberge** [comment]
I can't reproduce this
![image](https://user-images.githubusercontent.com/10358424/121782799-9edc0e80-cbab-11eb-966f-a6ddf2cbff0f.png)
