### ISSUE TITLE
Master Infusion Crystal (Mystical Agriculture)

### ISSUE THREAD

**Issue by LLIaMMaH** [refinedmods/refinedstorage#2955]
Issue description:
Данный кристалл имеет бесконечное использование. В шаблон рецепта он заносится.
This crystal has endless uses. It is entered into the recipe template.
[https://mc.lliammah.space/other/images/rs/rs_ma_c.jpg](url)

What happens:
При попытке заказать крафт система считает, что его нужно согласно заказанному количеству крафта.
When trying to order a craft, the system considers that it is needed according to the ordered amount of craft.
[https://mc.lliammah.space/other/images/rs/rs_recipe.jpg](url)

What you expected to happen:
АвтоКрафт эссенции с использованием кристалла.
Autocrafting essences using a crystal.
[https://mc.lliammah.space/other/images/rs/rs_cp.jpg](url)

#### Steps to reproduce:
1. Создать шаблон. Create a template.
2. Запросить автокрафт. Request an autocraft.
3. Получить запрошенное количество эссенции. Get the requested amount of essence.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.16.5
- Forge: 36.1.9
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no] - Yes

**Comment by LLIaMMaH** [comment]
Добрый день.
К сожалению не нашел дублирующую ветку, поэтому пишу тут. Если заказать крафт 1 штуки, то кристалл будет изменён. Вместо "Master Infusion Crystal" мы после крафта получим "Infusion Crystal" с 998 / 999 использований.

Good day.
Unfortunately, I did not find a duplicate branch, so I am writing here. If you order 1 craft, the crystal will be changed. Instead of "Master Infusion Crystal" after crafting, we will get "Infusion Crystal" with 998/999 uses.

**Comment by Darkere** [comment]
We are aware of the issue. Fixed in #2660
