### ISSUE TITLE
Breaking other Custom Banners

### ISSUE THREAD

**Issue by tikiMC** [refinedmods/refinedstorage#2956]
I've found that refined storage as well as mowzies mobs breaks some battern patterns from other mods, namely iceandfire, autuminity, and alexsmobs.

- Minecraft:
- Forge:36.1.0
- Refined Storage:1.9.12
![Screenshot 2021-05-05 012537](https://user-images.githubusercontent.com/70704691/117114777-1f078c80-ad41-11eb-85c7-7150dda9a2f0.png)

**Comment by Darkere** [comment]
Will most likely be fixed next update... whenever that is.
