### ISSUE TITLE
RS Autocrafting doesn't work with conflicting recipes

### ISSUE THREAD

**Issue by thelapisfox** [refinedmods/refinedstorage#2958]
#### Issue description:
Here is an example of the issue. In my pack, I have steel fences that are created by both Immersive Engineering and Mapper Base. They are both made with the same exact recipe. When I put the items into the pattern grid, I get the usual double arrows which allows me to select which version of the item I wish to produce (in this case, I want the Immersive Engineering one). I then create the pattern based on that choice and add it to the crafter. When I go to autocraft it, instead of it crafting the version of the item I wanted, it crafts the other version. It doesn't matter if I pick exact or not, it will always pick the other one.

#### What you expected to happen:

I expect it to produce the specific item version I requested.

#### Steps to reproduce:
See above

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.4
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]

Yes

#### If a (crash)log is relevant for this issue, link it here:

no crash

**Comment by Darkere** [comment]
> I get the usual double arrows

This is not a vanilla feature.

**Comment by thelapisfox** [comment]
> > I get the usual double arrows
> 
> This is not a vanilla feature.

Then it must be part of my mod pack. Since I've never played 1.16 vanilla, I assumed it was a new feature. Here is a screenshot to show what I mean.

<img width="1379" alt="for rs issue" src="https://user-images.githubusercontent.com/899111/117229980-e9aa7f80-add0-11eb-8b0b-6cc3cfdfe18f.png">

but, if that is the case, I still don't know how to ensure RS creates the correct item.

**Comment by bloodscon** [comment]
this happens in 1.12 as well if two mods use the same recipe check to see if you have 2 types of steel to craft and see if using the other steel helps

**Comment by adkinss** [comment]
I am having the same problem as well.  I am playing Valhelsia 3 and find that both "Block of Steel" (Immersive Engineering) and "Steel Block" (Mekanism) use the same 3x3 recipe (9 Steel Ingots).  I want a pattern to make "Steel Block", but no matter what I do, the pattern only makes "Block of Steel".  

I took a look at the NBT data for the pattern and see why.  For 3x3 grid recipes (meaning, not the processing recipes), the NBT data only stores the items of each of the 9 slots.  It does not store the item that will be made from that recipe.  I am guessing this is looked up on the fly every time the pattern is referred to, which is why the first recipe found is the one that is selected.

Would it be possible to add support for specifying the item being made to resolve recipe conflicts?

**Comment by thelapisfox** [comment]
> this happens in 1.12 as well if two mods use the same recipe check to see if you have 2 types of steel to craft and see if using the other steel helps

Mod pack uses KubeJS scripts to unify all metals into one (i.e. all ores, ingots, dusts, etc are autocoverted to its Thermal counterpart upon creation).

**Comment by thelapisfox** [comment]
> You use the exact feature??? tick that when setting the pattern
> But this happens when polymorph is in the pack as multiply versions of the receipt for it

Exact doesn't fix it.

**Comment by MarobsKoco** [comment]
Hi there,

it would be handy if the cafters look for a second recipe like with the iron ignots. if i want to make iron bars i have t ways 2 make ingots. From the ore but also from full blocks of iron. i have both recipes in the crafters but it only would look for the first one (in this case the ore) if i have no ore if says ore missing but dosent look for the blocks that would be the second recipe. so i have to get out the recipe from the ore to let the system know that the recipe for the blocks is there.

but if u have more mods, ull get also more recipes. maybe its handy to put in some thing that fix this all. like check recipes in craftes for secong recipe but also let check the recipes from the list if it compairs to what i give in.

friendly greets from me.



Ps. Love the mod, handy to fill shulkers with.

**Comment by MarobsKoco** [comment]
> #### Issue description:
> Here is an example of the issue. In my pack, I have steel fences that are created by both Immersive Engineering and Mapper Base. They are both made with the same exact recipe. When I put the items into the pattern grid, I get the usual double arrows which allows me to select which version of the item I wish to produce (in this case, I want the Immersive Engineering one). I then create the pattern based on that choice and add it to the crafter. When I go to autocraft it, instead of it crafting the version of the item I wanted, it crafts the other version. It doesn't matter if I pick exact or not, it will always pick the other one.
> 
> #### What you expected to happen:
> I expect it to produce the specific item version I requested.
> 
> #### Steps to reproduce:
> See above
> 
> #### Version (make sure you are on the latest version before reporting):
> * Minecraft: 1.16.5
> * Forge: 36.1.4
> * Refined Storage: 1.9.12
> 
> Does this issue occur on a server? [yes/no]
> 
> Yes
> 
> #### If a (crash)log is relevant for this issue, link it here:
> no crash

for this u can choose to let the recipe crafted bij an other crafter. like the crafter of the mod that had the items u want. i also have that problem but i make the prossesing pattern and let the crafter spit the products on the other crafter or barrel or what ever and then let the other crafter do the work.

that is one solution. but it would realy be handy if the craftes look for a second recipe or look at what is givin in. also at the end product. so it makes the item u want.

**Comment by raoulvdberge** [comment]
RS doesn't support a mod that lets you toggle between outputs for a duplicate recipe.
