### ISSUE TITLE
Can't se Wireless grid without a powergen mod

### ISSUE THREAD

**Issue by augugusto** [refinedmods/refinedstorage#2976]
#### Issue description:
it seems refied storage was smart enough to detect that no power generation mods where added, so the controller has infinite energy. this is not true for the wireless grid, so i can't use it
#### What happens:
cant use the wireless grid because i have no way to charge it
#### What you expected to happen:
the wireless grid having infinite power
#### Steps to reproduce:
1.create a new forge instance
2.add only refined storage
3.craft a wireless grid
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.16
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
not tested. only used single player

**Comment by Darkere** [comment]
> smart enough to detect that no power generation mods where added

Nope that's a config option. The wireless grid also has the config option to not use energy.
