### ISSUE TITLE
Can't add recipe to pattern grid from JEI

### ISSUE THREAD

**Issue by jasonnyland** [refinedmods/refinedstorage#2982]
#### Issue description:
Recipes can't be added to the pattern grid from JEI.
#### What happens:
When clicking items in JEI, the squares in the pattern interface grid turn green, but the recipe of the selected item does not show up.  I can only drag the item from the JEI interface to the green squares in the grid.
#### What you expected to happen:
I expect to have similar functionality to the crafting grid, where I left-click the recipe in JEI, see the recipe, then click the + button to transfer the recipe to the grid.
#### Steps to reproduce:
1. Right-click pattern grid to open interface
2. Search item in JEI (ex. "Disk Drive")
3. Click the item

With some recipes you can bypass the broken behavior by right-clicking an item to see ingredient recipes and click the item as an ingredient to get back to the intended recipe.  But the Disk Drive, for example, is not an ingredient for any other recipes... so you'd either have to memorize the pattern and either search each ingredient in JEI and drag it to the grid, or have ingredients in your inventory.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.16
- Refined Storage: 1.9.12
- JEI 7.6.4.90 (also tested with 7.7.0.98)

Does this issue occur on a server? [yes/no]:  Yes

**Comment by Darkere** [comment]
Use the "recipe" (Default: R) keyboard shortcut for now. 

It's a bug in JEI. You can downgrade to 87 to fix.
