### ISSUE TITLE
[1.16.5]Filter enhancement request

### ISSUE THREAD

**Issue by GaN601** [refinedmods/refinedstorage#2983]
#### What happens:
I want to export all the minerals, but I need to add them to the list one by one in the filter card, which is very troublesome.
#### What you expected to happen:
Hope to add a new list item, players set matching rules in the list to match the name and label.
Regular expressions are supported. Then put the list into the marking area of the pipeline for use
#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
#2372
