### ISSUE TITLE
texture bugs

### ISSUE THREAD

**Issue by Skeetle** [refinedmods/refinedstorage#2986]
#### Steps to reproduce:
1 .place blocks next to refinedstorage components
2. power refinedstorage components
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: forge-36.1.23
- Refined Storage: refinedstorageaddons-0.7.2.jar

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

![2021-05-22_09 41 07](https://user-images.githubusercontent.com/80830900/119218848-c8d96e00-bae2-11eb-9951-022742cf2473.png)
![2021-05-22_09 42 53](https://user-images.githubusercontent.com/80830900/119218859-cc6cf500-bae2-11eb-8486-631f80cf3a78.png)

**Comment by djfariel** [comment]
There's a merged PR to fix this here: #https://github.com/refinedmods/refinedstorage/pull/2943

Which should result in RS 1.19.13 but the builds started failing literally the first merge before that. Compare here:
https://ci.refinedmods.com/job/refinedstorage-mc1.16/158/
https://ci.refinedmods.com/job/refinedstorage-mc1.16/159/
I don't know enough about sonar qube to look in to the build failure (and I'm not the author or anyone with the project). If someone could look in to that then we'd have a build that fixes this. 

I guess that technically makes this a duplicate and/or solved.

**Comment by djfariel** [comment]
There's a possible workaround but I want to caution that it might have unintended consequences if you play on multiplayer. Unintended as in I have no idea what might happen or how reliable it will be.

Go to the 159 build here: https://ci.refinedmods.com/job/refinedstorage-mc1.16/159/
Download the refinedstorage-1.9.13+159.jar build artifact. 
Replace your refined storage mod with that version. 

I didn't realize the build artifacts were successfully created when I left my previous comment. Still, this is technically an unofficial build (read: snapshot) so, again, there can be unintended consequences of using this version.

**Comment by Skeetle** [comment]
Thank you for your reply. I replaced the RS mod with the refinedstorage-1.9.13+159.jar build but then my game crashed on startup. Do I need any other of these .jar files or just the refinedstorage-1.9.13+159.jar one?

The game crashed whilst initializing game
Error: java.lang.ExceptionInInitializerError: null
Exit-Code: -1
