### ISSUE TITLE
Server crash related to WorldEdit use

### ISSUE THREAD

**Issue by Bidgam** [refinedmods/refinedstorage#2987]
#### Steps to reproduce:
1. Use WorldEdit and //copy a coordinate around a RS block (in particular the Controller but also disk drive, external storage connector, and possibly a few other blocks (but not all RS blocks are a problem).
2. //paste anywhere in the existing or another world. Creating a schematic shows the same results.
3. Even if the server doesn't crash at this point, successive //paste will show that the block either can't or has a hard time pasting in, resulting in the entire copy of anything around it to possibly not complete.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: forge-1.16.5-36.1.4 and later, but quite possibly earlier as well.
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no] YES

#### If a (crash)log is relevant for this issue, link it here:

https://paste.enginehub.org/TjFlhVX7o

Similar issue reported a while back: https://github.com/refinedmods/refinedstorage/issues/2842#issuecomment-826012745

I've already consulted the WorldEdit folks and they know it's an RS related issue but will help any way they can. Thanks for taking a look!

**Comment by raoulvdberge** [comment]
Don't use WorldEdit on RS blocks for now.
