### ISSUE TITLE
Crafter inserts when in Pulse mode with out pulse for first craft.

### ISSUE THREAD

**Issue by WhatheWorld** [refinedmods/refinedstorage#2991]
#### Steps to reproduce:
1. place crafter next to a machine that excepts items (I used a energizing orb)
2. set crafter to Redstone pulse mode
3. put in a crafting patter into crafter placed in set 1
4. with out ever setting up a redstone pulse, request the item from set 3
5. notice crafter inserts items into machine. (expected result is that it will wait till redstone pulse before inserting items)
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.16
- Refined Storage: 1.19.12

Does this issue occur on a server? Yes

**Comment by Darkere** [comment]
Yes, the intention is that you can react to your craft finishing to trigger the next craft. You can't react with redstone if nothing is happening.
