### ISSUE TITLE
Large auto-crafting jobs significantly lower TPS or crash server

### ISSUE THREAD

**Issue by clbx** [refinedmods/refinedstorage#2992]
#### Issue description:

Whenever a large (8,000+ items) or complex (many sub recipes) auto-crafting job is started, the server lags out for a decent amount of time (30 seconds - 10 minute) and the server either crashes or TPS is halved for the duration of the crafting job.

Most of the crafters point out to Thermal Dynamics itemducts or a Thermal Dynamics Machine or Ender IO Machine

#### What happens:

TPS is significantly impacted, or server crashes

#### What you expected to happen:

The auto crafting jobs do not have a major impact on server TPS

#### Steps to reproduce:
1.  Set up large/complex auto crafting jobs
2. Start large job
3. Wait
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- Refined Storage: 1.6.16
- Refined Storage Addons: 0.4.5 (Using larger disks and the auto crafter from refined storage (the auto crafter does not appear to contribute to the issue) 

Does this issue occur on a server? [yes/no]

Yes

#### If a (crash)log is relevant for this issue, link it here:

No crash log from refined storage, just the expected "No tick in 60 seconds, assuming server is crashed error message"

**Comment by Darkere** [comment]
3 ways to reduce the impact:
- change patterns to make more items at once e.g. 64 sand -> 64 glass
- Use a buffer between crafter and machines that can contain the entire request
- split crafting request into multiple smaller requests.
