### ISSUE TITLE
Can't insert item from main hand when wireless or portable grid is opened in offhand

### ISSUE THREAD

**Issue by Random832** [refinedmods/refinedstorage#2997]
#### Issue description:
The portable and wireless grids understandably prevent you from inserting the grid itself into the storage system, but this is done by locking the main hand slot regardless of whether the grid is in it or not.

#### What happens:
Cannot shift-click or drag item from whichever hotbar slot happens to be selected, or drop an item in that slot if it was empty [shift-clicked items out of the storage system can land there though, oddly enough]

#### What you expected to happen:
Slot behaves normally

#### Steps to reproduce:
1. Put the portable or wireless grid in your offhand
2. Open the grid
3. Try to use the slot that was selected for your main hand

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.16.5
- Forge: 36.1.13
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
- Have not tried on a server

**Comment by Klouver0X** [comment]
im having same issue. I cant take or put stuff in the grid no more even when I have enough storage and such, I am worried
