### ISSUE TITLE
Weird Issue in Sevtech Ages

### ISSUE THREAD

**Issue by RaymanFtw** [refinedmods/refinedstorage#2999]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Refined Storage: 1.6.16

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here] https://paste.ee/p/PVCbs

**Comment by Darkere** [comment]
You are trying to autocraft a recipe without result. So likely some modifications you made to the pack.

Not sure exactly where crafting was stored in 1.12 might be under world/data/ or on the Tileentity of the controller. You might be able to delete autocrafting task with nbt explorer in either case.
