### ISSUE TITLE
Cannot autocraft garland from Fairy Lights

### ISSUE THREAD

**Issue by justwlocke** [refinedmods/refinedstorage#3005]
#### Issue description:
When trying to autocraft the garland, clicking start greys out the start button, and does nothing.

#### What happens:
Start greys out, no autocrafting happens.

#### What you expected to happen:
To open the next window describing required materials

#### Steps to reproduce:
1. Make any color garland pattern, and put it in a crafter
2. Search for garland, and click on it to craft.
3. Enter any number, hit start, and watch it not move on to the next step.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 1.16.5-36.1.24
- Refined Storage: 1.9.12
- [fairylights](https://www.curseforge.com/minecraft/mc-mods/fairy-lights): 4.0.5-1.16.5

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
no

Crafting Grid
![image](https://user-images.githubusercontent.com/84145548/121418236-5d8bfa80-c930-11eb-8c9b-11ba61cd1563.png)

Before Clicking
![image](https://user-images.githubusercontent.com/84145548/121418359-7c8a8c80-c930-11eb-86a8-a0ace17c7c4d.png)

After Clicking
![image](https://user-images.githubusercontent.com/84145548/121418320-71376100-c930-11eb-91d8-7aaaca458104.png)

**Comment by justwlocke** [comment]
It doesn't change from 1 to 4, That was me typing.

**Comment by raoulvdberge** [comment]
Should be fixed for the next version.
