### ISSUE TITLE
Delete button doesn't work

### ISSUE THREAD

**Issue by teknikalarkitekt** [refinedmods/refinedstorage#3015]
Normally when you press delete button it deletes a stack of whatever the mouse is on, but it's not working for refined storage. Somebody told me in order to delete stuff you have to do a whole lot of roundabout dumb stuff. it seems kind of counter productive to make a mod called "refined storage" and then unrefine and deoptimize it to the point where you can't even delete a stack of flint to make room without first building several contraptions and waiting for it to slowly funnel the flint out of the storage disk

**Comment by Darkere** [comment]
>Normally when you press delete button it deletes a stack of whatever the mouse is on

This is not a thing. Some mod is likely adding that. 

This would also break balance for many packs so is probably not going to happen either way.
