### ISSUE TITLE
Free items from Pattern Grid (dupe)

### ISSUE THREAD

**Issue by DAmNRelentless** [refinedmods/refinedstorage#3016]
#### Issue description:
When there are multiple items in the game which share the same recipe, you can just get them for free from the pattern grid.

#### What happens:
You can get the output from the encoded recipe.

#### What you expected to happen:
The output should be locked in place or be a ghost item.

#### Steps to reproduce:
1. have an items in your game which share a recipe
2. open the Pattern Grid
3. place a pattern inside
4. encode the recipe the two items share
5. shift-click the output slot
6. item will be in your inventory and pattern is empty again (also works with an empty system, no items are consumed)

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.16.5
- Forge: 36.1.31
- Refined Storage: 1.9.12

Does this issue occur on a server?
yes, client and server

**Comment by Darkere** [comment]
Likely caused by Polymorph.

**Comment by DAmNRelentless** [comment]
Indeed. It works without Polymorph. Odd that you are able to shift-click the item out because of that mod.
I will submit an issue there and reference this issue. Thanks for the quick response.
