### ISSUE TITLE
Recipes that don't use up ingredients can't be used multiple times

### ISSUE THREAD

**Issue by linuxdaemon** [refinedmods/refinedstorage#3017]
#### Issue description:
When autocrafting, a recipe that doesn't use up one or more of the ingredients can not be queued multiple times in one crafting operation without having multiple of the unused ingredient.

#### What happens:
Pattern set for 4 Infernium Essence and 1 Infusion Crystal (Mystical Agriculture). This recipe should return 1 Prudentium Essence and not use up the infusion crystal. Requesting 1 Prudentium works and the crystal is returned to storage, but requesting multiple Prudentium requires multiple infusion crystals even though they aren't used up. 

#### What you expected to happen:
Ingredients that aren't used up should be able to be used multiple times in one crafting job.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.24
- Refined Storage: 1.9.12

Does this issue occur on a server? Yes

**Comment by linuxdaemon** [comment]
This occurs with vanilla cakes as well, having a recipe that is empty bucket -> milk bucket and then requesting 10 cakes (which returns empty buckets on each craft), requires 30 buckets.

**Comment by linuxdaemon** [comment]
@raoulvdberge whoch issue does this duplicate? I wasn't able to find one

**Comment by raoulvdberge** [comment]
By a lot of issues... There are so many at this point that I don't even bother tagging anymore.
