### ISSUE TITLE
Crash on use of wireless crafting terminal

### ISSUE THREAD

**Issue by Brendan-Cook** [refinedmods/refinedstorage#3018]
#### Issue description:
Game crashes on use of wireless crafting terminal

#### What happens:
Whenever I open the wireless crafting terminal, I crash. I haven't updated any refined storage mods recently, so it might be an interaction with another mod, but refined storage, java, forge, and Minecraft are the only names that appear in the crash report. There is a weird message in the report about sun reflection, which makes no sense to me

#### What you expected to happen:
To see my refined storage terminal inventory

#### Steps to reproduce:
1. Right-click to open wireless crafting terminal
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.4
- Refined Storage: 1.9.12
- Refined Storage Addons 0.7.2

Does this issue occur on a server? no

#### If a (crash)log is relevant for this issue, link it here:
[6152021RefinedStorageCrash.txt](https://github.com/refinedmods/refinedstorage/files/6657325/6152021RefinedStorageCrash.txt)

[pastebin/gist/etc link here]

**Comment by Brendan-Cook** [comment]
Opening the wireless crafting terminal with a keybind also causes the crash

**Comment by Brendan-Cook** [comment]
Opening the regular crafting terminal also causes crash

**Comment by Darkere** [comment]
Do you not have... JEI installed?

**Comment by Brendan-Cook** [comment]
I should... but it hasn't been working. That could be why hold on

**Comment by Brendan-Cook** [comment]
curseforge says its installed and updated to the most recent version

**Comment by Darkere** [comment]
Hmm if JEI wasn't working that might be the reason for that. The crashlog did say that it crashed while we were looking up JEI focus. 

Might be a mod crashing JEI?

**Comment by Brendan-Cook** [comment]
Yeah makes sense I'll play around with it. Gonna close tho since yeah this is probably another mod's fault
