### ISSUE TITLE
[1.12.2] Shift-left clicking items out of any Grid deletes items

### ISSUE THREAD

**Issue by bigyihsuan** [refinedmods/refinedstorage#3021]
#### Issue description:

Shift-left clicking items in any Grid deletes a stack of items.

#### What happens:

Shift-left clicking items in any Grid from the network inventory deletes items. The items are deleted. Its count in the system decreases normally. The items do not appear in your inventory afterwards.

#### What you expected to happen:

A stack of items appearing in my inventory, like a chest or any other inventory. The items should be removed from the network, and in my inventory.

#### Steps to reproduce:
1. Put items into an RS network.
2. Shift-left click the item stack in any Grid to take it out of the network.
3. The stack of items get deleted.

#### Version:

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Refined Storage: 1.6.16

Does this issue occur on a server? [yes/no] yes

Modpacl: [CMFR-MC Modpack v7.0](https://www.technicpack.net/modpack/cmfr-mc-modpack.1857528)

**Comment by bigyihsuan** [comment]
After some more testing, anything involving the combination `shift` will completely delete the items. This includes left click, right click, `ctrl`, and any combination of `shift`, `ctrl`, `left click`, and `right click`.

**Comment by bigyihsuan** [comment]
But is there a workaround? The only workarounds I can think of is using an export bus into a chest (hard to control), or click-move-click each stack manually (very slow when handling several dozen stacks).

**Comment by Darkere** [comment]
This bug is caused by another mod. You'll have to figure out which one yourself.
