### ISSUE TITLE
Crafters Not Autocrafting

### ISSUE THREAD

**Issue by TheGreatNaj** [refinedmods/refinedstorage#3022]
#### Issue description:
Trying to get something to auto craft continuously. I put a pattern for the crafting recipe in the crafter and set it to ignore redstone. That didnt work so I set it to craft with a redstone signal and used a lever. That didnt work so I used a detector to craft when under 100 items and that still didnt work. Manually requesting something to be crafted does work, just cant seem to auto craft.

#### What happens:
Items dont auto craft when set to craft continuously 

#### What you expected to happen:
Items to auto craft continuously

#### Steps to reproduce:
1. Set up a RS storage system 
2. Put a recipe in a crafter with materials in storage for it to use.
3. Set it to ignore redstone, or set it to craft with a signal and give it a redstone signal

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- Refined Storage: 1.6.16

Does this issue occur on a server? [yes/no]
Yes but I also made a separate game launch with only refined storage on it. I used that to test in single player and the same still happened. 
![2021-06-21_03 18 27]

Screenshots from the single player world
![2021-06-21_03 18 27](https://user-images.githubusercontent.com/25763105/122727503-16154080-d245-11eb-83e9-1f250313be2f.png)
![2021-06-21_03 18 31](https://user-images.githubusercontent.com/25763105/122726558-1f51dd80-d244-11eb-88fb-5a42eeefd6c7.png) (Side note, I noticed when in this crafters GUI it said Detector at the top when there was a detector connected. Im unsure if thats intentional)
![2021-06-21_03 18 34](https://user-images.githubusercontent.com/25763105/122726569-21b43780-d244-11eb-84d3-5a0a8f14974e.png)

I feel like Im just missing something obvious but I've had this set up in the past and its worked fine. Was there a change to crafters Im missing or something?

**Comment by Darkere** [comment]
That has indeed changed... A very long time ago. 

https://refinedmods.com/refined-storage/wiki/keeping-items-in-stock.html
