### ISSUE TITLE
Destructor with Silk Touch upgrade causes infinite item duplication when breaking blocks placed by a constructor where the destructor and constructor are on separate RS systems.

### ISSUE THREAD

**Issue by anagran** [refinedmods/refinedstorage#3027]
#### Issue description:
With a constructor and destructor set up on separate RS systems, when there is a silk touch upgrade in the destructor, item duplication occurs.
#### What happens:
The constructor continues to place blocks even after there are no longer any of those blocks in the storage and the quantity in the destructor system continues to rise.
#### What you expected to happen:
I would expect the constructor to stop placing blocks when there are no longer any available.
#### Steps to reproduce:
1.Place down 2 separate controllers, grids, disk drive with disks.
2.Connect a constructor to system A and a destructor to system b both connected to the same block space so that the destructor will destroy the block placed by the constructor
3. Put a silk touch upgrade in the destructor.
4. Put a quantity of a block i.e. stone in system A and add stone to the filter for the constructor to start laying blocks.
5. Observe that the constructor will continue laying stone after the quantity you put in the system is exhausted and you can watch the quantity in system b continuing to grow beyond the original amount.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.31
- Refined Storage: 1.9.13

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![2021-06-27_08 25 29](https://user-images.githubusercontent.com/3802011/123546479-4d429080-d722-11eb-9f1d-3b9249187671.png)

**Comment by Darkere** [comment]
Cannot reproduce. Some mod messing with silk touch breaking?

**Comment by anagran** [comment]
Entirely possible.  This is in Enigmatica 6 0.5 Alpha

**Comment by anagran** [comment]
Well, I built this setup multiple times testing before I submitted the ticket.  Just went back and built it again to check a couple things after your comment and I can no longer recreate the issue.  I will investigate further and close the issue if I can not figure out what was going on.

**Comment by anagran** [comment]
Well, I've tried several time to recreate again, with no luck. I will close this issue and reopen if I ever figure out what caused it to duplicate.
