### ISSUE TITLE
Clicking JEI Item in Pattern Grid No Longer Pulls Up Recipe

### ISSUE THREAD

**Issue by bcrotty** [refinedmods/refinedstorage#3030]
#### Issue description:

Clicking an item in JEI while in the Pattern Grid doesn't open up the recipe for the item.

#### What happens:

When I click an item in JEI while I'm in the Pattern Grid used to pull up the recipe for the item so I could create the pattern. Now the only thing I can do when I left click the item is to drag it to the grid.

The Crafting Grid still allows you to click an item in JEI to pull up its recipe, and that was the behavior in the Pattern Grid in RS 1.9.12.

I can still get to the recipe by hitting 'R'. Left clicking to get the recipe is the only thing that broke.

#### What you expected to happen:
I expect to be able to click an item in JEI while in the Pattern Grid and have the recipe pull up so I can easily create a pattern.

#### Steps to reproduce:
1. Run RS with JEI
2. Open Pattern Grid GUI
3. Click JEI item you want to create a recipe for
4. Notice that the recipe doesn't pull up
5. Emotionally prepare yourself to move your finger all the way to the R key to bring up the recipe
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: forge-1.16.5-36.1.32.jar
- Refined Storage: 1.9.13

Does this issue occur on a server? [yes/no]
Personal LAN server

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
JEI bug. You can downgrade to 87 to fix it. I don't recommend you do so, but it is possible.
