### ISSUE TITLE
Crash to main menu when opening crafting grid

### ISSUE THREAD

**Issue by MGFirestar363** [refinedmods/refinedstorage#3033]
#### Issue description:
Game crashed when opening crafting grid ( have alot of items in my system somewhere around 4 mil)
#### What happens:
Game hangs up for a second the refined storage looks empty save for maybe one or two items, game crashes to main menu
#### What you expected to happen:
The crafting grid opens and shows my items
#### Steps to reproduce:
1. ATM6 to the sky version 1.1.6
2. Don't know precisely
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.31
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://imgur.com/a/trJuzzW

**Comment by Darkere** [comment]
Remove some mob farm items or items with lots of nbt in general from your system.
