### ISSUE TITLE
Autocrafting Pam's Harvestcraft with non-consumables

### ISSUE THREAD

**Issue by bluemug97** [refinedmods/refinedstorage#3038]
#### Steps to reproduce:
1. Make patterns for cheese and ingredients and provide raw resources (including buckets and one pot)
2. Open crafting interface for cheese
3. Interface requests large amounts of pots
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.0
- Refined Storage: 1.9.13

Does this issue occur on a server? [yes/no] not tested

#### If a (crash)log is relevant for this issue, link it here:

Screenshot of the crafting interface in case it's helpful
![Screenshot 2021-07-13 131920](https://user-images.githubusercontent.com/77618183/125444138-9e102f69-11d1-4ad0-b89a-cda11cbeb644.png)

**Comment by bluemug97** [comment]
Hi, I did look for similar issues but didn't find a solution, maybe you can help me out

**Comment by Darkere** [comment]
The solution is to use an external crafter from another mod.
