### ISSUE TITLE
Auto Crafting Pattern "Ingredients ended up needing themselves"

### ISSUE THREAD

**Issue by AmpedNormal** [refinedmods/refinedstorage#3040]
#### Issue description:
Playing on the Enigmatica 6 Modpack so this may be an issue with their ore/ingot dictionary. Using a pattern to create steel using Mekanism machines but when I go to craft, it says the request has failed as one of the crafting ingredients ended up needing itself.

I am able to autocraft the same version of steel ingots by using Coke Coal Dust and Iron Ingots in a Thermal Expansion Induction Smelter, however Mekanism Factories are much faster so would be preferable if I can get them to work, I have loads of other Mekanism machines set up for autocrafting, even other Infusing factories, it seems to just be the steel dust and steel that are the issue.

#### What happens:
Auto crafting of steel fails

#### What you expected to happen:
The steel to be crafted

#### Steps to reproduce:
1. Set up an Iron Crafter to output to a chest
2. Pipe the chest to the bottom and side  of a Mekanism Infusing Factory, put an RS Importer on the other side
3. Set up a second Iron Crafter to ourput to a Smelting Factory and put an RS Importer on another face.
4. Set up a Processing Pattern to input coal and iron to produce enriched iron
5. Set up a second Processing Pattern to input coal and enriched iron to procude steel dust
6. Set up a third Processing Pattern to input Steel Dust and Output Steel
7. Put the First two Patterns in the Chest Iron Crafter and put the third pattern in the Smelting Factory Iron Crafter
8. Try to auto craft any amount of either steel dust or steel ingots (enriched iron is fine)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.65.5
- Forge: 36.1.16
- Refined Storage: 1.9.12
- Enigmatica 6 Version: 0.4.14

Does this issue occur on a server? [yes/no]
Yes

#### If a (crash)log is relevant for this issue, link it here:

No Crash

**Comment by Darkere** [comment]
Did you modify the patterns to accept tags? You'll need to be careful when doing so as you may end up with loops.

**Comment by AmpedNormal** [comment]
Don't know which caused it, but I had a bunch of crafts that were completed but still showing in the crafting monitor, I cleared those and restarted my game and it works now, didn't restart the server though so really not sure what caused it.

**Comment by AmpedNormal** [comment]
Ok never mind, it worked for a test craft of one of each and after leaving and re-entering the grid it now brings up the same error again

**Comment by Darkere** [comment]
You did not answer the question. The behavior you are experiencing indicates that you have set up multiple options for the processing recipes

**Comment by AmpedNormal** [comment]
Sorry I'm not sure to be honest, when I check the box to make it a processing recipe I loose the "exact" checkbox which I assume is that one that dictates whether or not tags are used. From experience with other processing patterns I've set up I don't believe they are using tags as I had to directly select regular sand for making glass otherwise it asked specifically for whichever one was chosen when I brought the recipe from JEI

**Comment by AmpedNormal** [comment]
I'll also add that it seems to be with the Steel Dust specifically, I tried manually crafting enriched iron and putting that into the system but I couldn't craft steel dust or steel ingots, but when I manually crafted steel dust and put that in the system, the Steel Ingot pattern worked

**Comment by AmpedNormal** [comment]
Ok figured it out, I had a second pattern for creating steel dust that I had used for previous recipe's and forgotten about, it put a steel ingot into a crusher and output the steel dust, so it seemed to be stuck in a loop because of that recipe. I've taken it out and everything works fine now.
