### ISSUE TITLE
encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by rVanix** [refinedmods/refinedstorage#3045]
#### Steps to reproduce: 
1. install the mod in a modpack
2. load the game
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.0
- Refined Storage: 1.9.14

Does this issue occur on a server? [yes/no] idk

#### If a (crash)log is relevant for this issue, link it here:

latest log:
https://hastebin.com/riroxoneso.yaml

crash-2021-07-25_12.34.44-fml.txt
https://hastebin.com/gefihixuxi.rb

**Comment by Darkere** [comment]
You updated RS...

You can and will have to remove Refined Curious. It's features are now native to RS.
