### ISSUE TITLE
Sided Setup Error

### ISSUE THREAD

**Issue by Moobien** [refinedmods/refinedstorage#3047]
#### Issue description:
Hey Raoul, just updated to 1.9.14 and its throwing a sided setup error "Refined Storage (refinedstorage) encountered an error during the sided_setup event phase"
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.32
- Refined Storage: 1.9.14

Does this issue occur on a server? [yes/no]
no idea.
#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/Moobien/fa3c774970707d5101acba52927220b8 - latest.log
https://gist.github.com/Moobien/c736e52b389bd03a228a76fd27a09470 - crashlog
[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Caused by refined curios.

**Comment by Moobien** [comment]
I didn't even realise I had that one installed. thanks for that.

**Comment by starforcraft** [comment]
![5248E0C1-A94F-46EA-8311-5D27D4F7D369](https://user-images.githubusercontent.com/60074805/126903013-8c215e0c-d092-4376-ac4e-8920f181cbef.jpeg)
lol

**Comment by Moobien** [comment]
Yeah, i just dont ever remember installing it
