### ISSUE TITLE
RS autocraft does not work with Mekanism recipe ( infusing factory )

### ISSUE THREAD

**Issue by Breakcrafter** [refinedmods/refinedstorage#3049]
#### Issue description:
i wanted to autocraft infused alloy with an infusing factory (from Mekanism).
The Jei mod recommended on the left side of the pattern grid (processing) to insert one iron ingot next to redstone dust. 
The same is happenig with enriched iron and steel dust. 

#### What happens:
When i start the recipe the crafting monitor say's "the Machine doesn't accept item".

#### What you expected to happen:
That the autocrafting system can insert the materials to the infusing factory correctly

#### Steps to reproduce:
1.Built the necessary equipment for RS ( Controller, Diskdrive, Grid, Pattern grid, Crafting Monitor )
2.Create a pattern for infused alloy. Insert one iron ingot next to one redstorne dust ( processing ) on the left side
and infused alloy on the right ( or use Jei ).
3. Request for an infused alloy

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge:1.16.5 - 36.1.0
- Refined Storage:1.9.14
- Mekanism:10.0.21
- Jei:7.7.1.115

Does this issue occur on a server? [yes/no]
-It does occur on Singleplayer and multiplayer.

**Comment by Darkere** [comment]
The infusion factory requires the items to be inserted from 2 different sides. As such you'll need a buffer of some kind or keep the infusion material inside the machine some other way.
