### ISSUE TITLE
[Bug; 1.16.5] Server watchdog immediate crash on startup

### ISSUE THREAD

**Issue by PapiOphidian** [refinedmods/refinedstorage#3051]
We've had no issues with RS before unless processing took 60 seconds, which would result in a similar crash, but now our setup was resistant to this issue until the server started crashing on startup. This is not due to processing as the server was gracefully shutdown while idle. When the server started back up, it would not stay up long enough for any of us to do anything. When I backed up the world and started with a fresh world with the exact same mods, everything works fine again. We now have another RS setup and no issues even after restarting.

I have no consistent steps to reproduce this. I am also unsure as to if others are experiencing this as I did check recent open and closed issues.

I am running latest ver of RS. 

Minecraft 1.16.5
Forge 36.1.32

This issue is occurring on a server.

Stack trace:
https://pastebin.com/RcXncWXB

I feel as though I've covered all I know related, but I can provide more info or a world zip if necessary.

**Comment by Darkere** [comment]
add a 0 to max-tick-time in server.properties

**Comment by PapiOphidian** [comment]
> 
> 
> add a 0 to max-tick-time in server.properties

Is this an actual fix to this or a blanket fix

**Comment by Darkere** [comment]
60 seconds for the first tick is pretty common in modded minecraft as loads of things initialize there. Adding a 0 there sets it to 600 seconds in which case there is certainly a real problem and it's fine if it crashes.

**Comment by PorPit** [comment]
1.12 version has same problem on startup
took more than 120 seconds
[https://pastebin.com/TXgRryEJ](url)
