### ISSUE TITLE
1.16.5 Boot Crashe

### ISSUE THREAD

**Issue by Mini-kun** [refinedmods/refinedstorage#3052]
#### Issue description:
So i'm About to update my modpack and Even my server but it just crash my Client every time i try to boot it up

#### What you expected to happen:
It Boot up normal as i normal upate the mod with out any Probelm

#### Steps to reproduce:
1. Just update mod
2. boot game
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.0
- Refined Storage: 1.9.15

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/dtK9DbdV

**Comment by Darkere** [comment]
remove refined curios
