### ISSUE TITLE
Max item Limit 300mill ? Server Issue

### ISSUE THREAD

**Issue by IchigoGames** [refinedmods/refinedstorage#3054]
#### Steps to reproduce:
1.start A server 
2. build a basic Rs storage system
3. add 300Mill items +1 as it happens with anything over that ammount
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge:36.2.0
- Refined Storage: refinedstorage-1.9.15
-extradisks-1.16.4-1.5.1 for extra storage space
Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here: not a crash

https://www.dropbox.com/s/fv85phs5b10wpp5/latest.log?dl=0 Log file

this is the msg the player got after reaching and going over that limit 
![unknown](https://user-images.githubusercontent.com/11888162/127785071-f931c6ad-4f14-4199-a5bc-43718e092cf8.png)
they could still get on server but when they whent to look at there items in RS it would disconnect every time

**Comment by IchigoGames** [comment]
the Modpack this happens on is my pack The Final Frontier 2 version 8.1

**Comment by Darkere** [comment]
There is no specific number of items that would cause this. The packet size is determined by the number of different items and by the amount of nbt data on these items. 

You can remove some items with lots of nbt (usually mob loot or bees) to get it working again.
