### ISSUE TITLE
[1.16.5] Error during side_setup event phase

### ISSUE THREAD

**Issue by skellitor301** [refinedmods/refinedstorage#3056]
#### Issue description:
Forge issued an error with Refined Storage during the side_setup event phase.
#### What happens:
This is during startup
#### What you expected to happen:
N/A
#### Steps to reproduce:
N/A
#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.16
- Refined Storage: 1.9.15

Does this issue occur on a server? No

#### If a (crash)log is relevant for this issue, link it here:

[Gist](https://gist.github.com/skellitor301/1276ac96d0d9fe42e4d58557e96855c5)

**Comment by raoulvdberge** [comment]
Remove refined curios

**Comment by skellitor301** [comment]
Does RS have compatibility with Curios? Cause I was hoping to utilize the wireless crafting grid in a curios slot to save on inventory space.

**Comment by raoulvdberge** [comment]
You could've also read the changelog of the latest version
