### ISSUE TITLE
Cant take anything out of the RS system

### ISSUE THREAD

**Issue by mguillopo** [refinedmods/refinedstorage#3057]
#### Issue description:
Can't take anything out of the RS system
#### What happens:
when me or anyone on our server try to take anything out of our networks we're all unable to 
#### What you expected to happen:
I expected to be able to pull out multiple stacks of items 
#### Steps to reproduce:
1.open up crafting grid/ wireless crafting grid
2. try to pull items out
3. nothing comes out
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge: 36.1.32
- Refined Storage: 1.9.13

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Try disconnecting external storages you have. There is a known bug where certain ones may prevent you from extracting items.  

Double check the storage you are using to make sure they are configured to allow extraction and aren't whitelisted to only show certain items.

**Comment by mguillopo** [comment]
thanks
that worked 
had to disconnect my silo from immersive engineering and started working properly again
