### ISSUE TITLE
[Request] Show name of named blocks in crafter manager

### ISSUE THREAD

**Issue by kjj194** [refinedmods/refinedstorage#3058]
When you rename a chest/barrel in an anvil the name of it is shown at the top of the inventories gui when it is opened. Currently when a crafter is facing into a chest (useful for automating machines with facing requirements) it will show Chest as the machine, my suggested enhancement is to instead show the name of the inventory the crafter is facing into so that its easier to keep track of which is which.

![image](https://user-images.githubusercontent.com/5005560/128491835-ab3f4f59-a8a9-4f17-955a-2cc470f6222e.png)
![image](https://user-images.githubusercontent.com/5005560/128491872-3598c466-a751-4b1e-aab6-17d37efef1da.png)

**Comment by Darkere** [comment]
rename the crafter instead.

**Comment by kjj194** [comment]
Didn't even think of that, thanks!
