### ISSUE TITLE
Refined Storage Crash

### ISSUE THREAD

**Issue by ApolloReaper** [refinedmods/refinedstorage#3059]
#### Steps to reproduce:
1. Launch minecraft from curseforge
2. Click play
3. Mods start loading, Crashes during final loading before main menu

...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge:36.2.2
- Refined Storage:1.19.15

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://pastebin.com/0Nji3VVJ

**Comment by Darkere** [comment]
Remove refined curios
