### ISSUE TITLE
Massive TPS drop with big autocrafting recipes

### ISSUE THREAD

**Issue by Leclowndu93150** [refinedmods/refinedstorage#3063]
[####] Issue description:
       Tps drop when autocrafting
#### What happens:
     Tps drop from 20 to 3-2-1
#### What you expected to happen:
      Tps stay at 20
#### Steps to reproduce:
1.Install gregtech in your modpack
2.Play a lot and unlock autocrafting
3.Autocraft a long recipes chain
...
I know its an old minecraft version but i beg you fix it :(
#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:last
- Refined Storage: 1.6.16

Does this issue occur on a server? [YES]

**Comment by Leclowndu93150** [comment]
Now i cant log in my server

**Comment by Leclowndu93150** [comment]
![2021-08-08_13 48 54](https://user-images.githubusercontent.com/73310949/128631601-e9db01f4-84fb-4bb2-a719-410d338b9da8.png)
Its the recipe

**Comment by Leclowndu93150** [comment]
bruh

**Comment by embeddedt** [comment]
I recommend using https://github.com/tth05/morerefinedstorage if you are still using 1.12. The autocrafting engine is much more efficient.

**Comment by raoulvdberge** [comment]
> I know its an old minecraft version but i beg you fix it :(

Why do you open issues if you know that I'm no longer supporting that version?
