### ISSUE TITLE
update to newest version 1.9.15

### ISSUE THREAD

**Issue by Timlyminer** [refinedmods/refinedstorage#3065]
#### Issue description:
Refined Storage (refinedstorage) encountered an error during the sided_setup event phase
#### What happens:
game crashes
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:36.2.2
- Refined Storage: 1.9.15

Does this issue occur on a server? [yes/no] 

#### If a (crash)log is relevant for this issue, link it here: 

[pastebin/gist/etc link here]
https://pastebin.com/2yGLF90t

**Comment by Darkere** [comment]
remove refined curios
