### ISSUE TITLE
Connect Refined Storage to Mekanism QIO

### ISSUE THREAD

**Issue by jaz0894** [refinedmods/refinedstorage#3067]
#### Issue description:
Connect Refined Storage to Mekanism QIO

#### What happens:
Is it possible to add compatibility with Mekanism QIO using external storage?
#### Steps to reproduce:
N/a

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.0
- Refined Storage: latest

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Mekanism deliberately made it so that this is not possible. It would be on their side to fix. 

An addon could add compatibility.
