### ISSUE TITLE
Game crashes for no reason in the latest version of 1.16.5

### ISSUE THREAD

**Issue by Bananaguns2** [refinedmods/refinedstorage#3068]
#### Steps to reproduce: 
1.Just open the launcher and click play with the latest version of forge
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge:36.2.2
- Refined Storage:1.9.15

Does this issue occur on a server? [yes/no] No I only play on 
single player
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
[latest.log](https://github.com/refinedmods/refinedstorage/files/6958083/latest.log)

**Comment by Bananaguns2** [comment]
I wish I could send the  mod list Github is not happy with my 120 mod zip file

**Comment by Bananaguns2** [comment]
My system specs are: 

1. Windows 10 home 19043
2. Omen laptop model 15dc1xxx
3. x64 based system
4. CPU i7 9750H
5. 16GB of ram
6. Nvidia GTX 1660TI

**Comment by Bananaguns2** [comment]
I kept downgrading and for some reason this bug only happens for every version after 1.9.13

**Comment by Darkere** [comment]
Remove refined curios.
