### ISSUE TITLE
[1.16.5] [ATM6] Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 1048576 bytes

### ISSUE THREAD

**Issue by KnownAsPower** [refinedmods/refinedstorage#3070]
Issue description: Opening the Refined Storage System will cause a boot from a multiplayer server. The kick message is as follows: "Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 1048576 bytes".

What happens: When you open the refined storage system, the game will kick you.

What you expected to happen: For the game not to kick me.

Steps to reproduce: This one is a bit hard, but I'm going to go off the assumption of what I and my friend tested.

We have a mob grinder that automatically dumps items into our refined storage system. We assume that there is an enchanted item with too much metadata and/or too many enchantments that is causing this issue.

Might I also make a request to allow importers and exporters (and anything else really) to ignore NBT data and enchantments? It would allow me to automatically export these items into trashcans, smelters, and allow me to destroy or repurpose the materials.

Version (make sure you are on the latest version before reporting):

refinedstorage-1.9.15.jar
refinedstorageaddons-0.7.3.jar

- Minecraft: 1.16.5
- Forge: 36.2.0
- Refined Storage: 1.9.15
- Refined Storage Addons: 0.7.3

This issue occurs on a server. Porting the world over to singleplayer does **not** recreate the issue.

I've scoured the internet and found no solution, as well as finding a lot of other people having this exact same issue.

![unknown](https://user-images.githubusercontent.com/77704199/129004469-71be9f3c-6aea-423a-ad1f-0b62673eea2f.png)

**Comment by Darkere** [comment]
> Might I also make a request to allow importers and exporters (and anything else really) to ignore NBT data and enchantments?

This is already possible with "exact mode".

The thing you are suspecting is correct. You'll need to clean up a bit to get it working again.

**Comment by KnownAsPower** [comment]
> This is already possible with "exact mode".

Oh, nice!

> The thing you are suspecting is correct. You'll need to clean up a bit to get it working again.

This implies you are not willing/not able to fix this error. Can I get any insight as to _why_?

**Comment by Darkere** [comment]
It is a rather difficult fix. I've made a solution in #2977 but that hasn't been accepted.

**Comment by KnownAsPower** [comment]
> It is a rather difficult fix. I've made a solution in #2977 but that hasn't been accepted.

Alright, thank you!
