### ISSUE TITLE
milk caused Description: Exception in server tick loop

### ISSUE THREAD

**Issue by OcrSu** [refinedmods/refinedstorage#3081]
#### Issue description:
Description: Exception in server tick loop

#### What happens:
Server Crash

#### What you expected to happen:
Server is running normally

#### Steps to reproduce:
1.Start My Minecraft Server

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge:36.2.4
- Refined Storage:1.9.15
- Java:11

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:

https://paste.loliidc.cn/?a0b2e243b7a8829b#4KNm5rTYkp8VL5Q2AFSM9nwfySase1QPUYbJd14jyJLG

**Comment by Darkere** [comment]
Bug is caused by cooking for blockheads
