### ISSUE TITLE
Storage Drawers + "external storage" = works, but not

### ISSUE THREAD

**Issue by MAXIS05** [refinedmods/refinedstorage#3084]
I am using this mod together with Storage Drawers, I use the "external storage" to connect the drawers to the RS system, I have drawers in 3 different chunks with only one external storage in each one, I had no problems with that, but wanting to add more drawer in other places with their respective external storage, the items go directly to the disks instead of the drawers
Any recommendation?

- Minecraft: 1.16.5
- Forge: 1.16.5-forge-36.2.0/forge
- Refined Storage: 
no server

**Comment by raoulvdberge** [comment]
Please use discord for questions
