### ISSUE TITLE
search item tooltip


### ISSUE THREAD

**Issue by PandaBoy444** [refinedmods/refinedstorage#3087]
Currently the search only searches the item name, not any other data elements. Even when synced with jei (unlike AE2 for example which when synced with jei shows the same results as jei would). I would like to be able to I search :
- tooltip (important!) 
- resource Id
- color
- creative catagory
Etc... 

Expected behavior : search for mending and find mending book
Rality : because mending is a Tooltip to enchanted book it is not found

A fix would be to sync with jei search results ie cross reference jei results with storage content and display matches. This is what AE2 seems to do and I always found it awesome

**Comment by Darkere** [comment]
https://refinedmods.com/refined-storage/wiki/grid.html#search-box-filters

**Comment by PandaBoy444** [comment]
When i search with the prefixes I don't notice any hiccups
