### ISSUE TITLE
Wireless Crafting Grid Crash Problem

### ISSUE THREAD

**Issue by Areavate** [refinedmods/refinedstorage#3090]
#### Issue description:
When I open the Wireless Crafting Grid to take something from it
#### What happens:
The Game Crash
#### What you expected to happen:
Take the item to put in your inventory
#### Steps to reproduce:
1.Open Wireless Crafting Grid
2.Take something from it
3.
...

#### Version (make sure you are on the latest version before reporting):
- Minecraft:1.16.5
- Forge: yes
- Refined Storage:refinedstorage-1.9.15.jar

Does this issue occur on a server? [yes/no]
I play on the singleplayer mode so i think not
#### If a (crash)log is relevant for this issue, link it here:
The game crashed whilst mousereleased event handler
Error: java.lang.NullPointerException: mouseReleased event handler
Codice di uscita: -1
[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
We need the entire crashlog. The text you posted there is useless.

**Comment by Areavate** [comment]
Where i can find that? Sry I'm not practical
@Darkere

**Comment by Darkere** [comment]
This seems to be caused by the Creative Crafter Mod.

**Comment by Areavate** [comment]
> This seems to be caused by the Creative Crafter Mod.
i want to mention that last session I played there was no error at all,but before to start the session with the "error" i updated the creative crafter mod. So if I downdate the craetive crafter mod,the problem should be fixed?

**Comment by Darkere** [comment]
No idea. Please report to them
