### ISSUE TITLE
All drives lost after server restart

### ISSUE THREAD

**Issue by Firefly0402** [refinedmods/refinedstorage#3094]
#### Issue description:
After a server restart all drives were gone
#### What happens:
All drives in 4 different refined storage systems were gone in different locations after a server restart. Also a infinity range upgrade for the network transmitter is gone. 
#### What you expected to happen:
I expected the drives to still be there
#### Steps to reproduce:
I have no idea

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.4
- Refined Storage: 1.9.15

Does this issue occur on a server? [yes/no]
yes
#### If a (crash)log is relevant for this is
[latest.log](https://github.com/refinedmods/refinedstorage/files/7261571/latest.log)
sue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
That sounds like your world/data/refinedstorage_nodes.dat got corrupted. In that case many more things will be missing. 
You can restore that from backup.

Or you can use the refinedstorage commands to restore only the disks.

**Comment by Firefly0402** [comment]
That's really good to know. Thanks :)

Just a question about the commands. I only found commands to create new (empty) disks. Is there also a command to restore lost disks with everything what was on it?

**Comment by Darkere** [comment]
yes

**Comment by Firefly0402** [comment]
> yes

Would you be so kind to tell me that command and how I use it to restore lost disks? Thanks :)

**Comment by Darkere** [comment]
https://refinedmods.com/refined-storage/wiki/commands.html

**Comment by Firefly0402** [comment]
I'll try it out. thanks :)
