### ISSUE TITLE
Creating a pattern for ProjectRed's Buffer Gate crashes the client

### ISSUE THREAD

**Issue by gurmiguel** [refinedmods/refinedstorage#3095]
When trying to create a pattern for autocrafting buffer gate from ProjectRed, whenever the pattern would change its texture to the one of the craft result (pressing Shift or inside a crafter) it crashes the client.

It should instead just show the crafting item.

- Minecraft: 1.16.5 (No optifine)
- Forge: 36.2.4
- Refined Storage: 1.9.15
- Modpack: All the Mods 1.8.4

[Error Log](https://pastebin.com/wmAJMH6g)

**Comment by Darkere** [comment]
Report to project red. Not an RS issue.
