### ISSUE TITLE
Consider options to adjust to random NBT in processing recipes.

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#3107]
Some mods crafting methods cannot predefine the NBT on the item. For example: https://github.com/klikli-dev/occultism/issues/478
where the mod dev picks a random name each time the item is crafted. 

 This would be difficult to solve for regular crafting recipes, but for Processing recipes it might be possible?

**Comment by Darkere** [comment]
I don't remember how it was back then. But this case would work by just not comparing NBT when checking whether this item is a correct result for this processing task. 

https://github.com/refinedmods/refinedstorage/blob/4cf7062d81dc6a69f647218ab1f7cac9c9ce10aa/src/main/java/com/refinedmods/refinedstorage/apiimpl/autocrafting/task/v6/node/ProcessingNode.java#L192

Passing 0 as flag there would be all it takes on the autocrafting side. 

Inputs are more problematic, as you can end up with recipes that sometimes work and other times not. Possible, but not without making it extremely clear what the problem is in the Crafting Monitor.

**Comment by hugoprudente** [comment]
For the inputs it should have a way to choose what you want to ignore like the alternatives. The good example is to use the "quantum entangled singularity" in recipies (what I think is already wrong, but designs right) so they come in pairs and the processing to the 1.9.x today will not ignore it so I need to keep changing the recipe as there's no way to ignore that NBT that make them a pair.

This can be target for the version 2.0 not now but it's something that I would like the team to keep in mind :)

Best mod ever!

**Comment by demethan** [comment]
Hi, 

One more for the books..   https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4714, I came here to check if there was a way to ignore the nbt. 

Would be nice to have a feature to ignore nbt on some items recipes, but I see it might be challenging.  Thanks for the mod.

**Comment by raoulvdberge** [comment]
> I'll make a proposal on how this could work then :)

Closing this for now, we can revisit this then.
