### ISSUE TITLE
Items not showing in Storage Grid

### ISSUE THREAD

**Issue by NordaXGlass** [refinedmods/refinedstorage#3119]
#### Steps to reproduce:
1.I'm using a 256k storage disk from "Extra Storage" so compatibility might be an issue, but I'm playing the Direwolf20 pack on FTB. I accidentally put my "Portable Grid" into my storage system, when I reopened it I cant see any items.
2. I was able to use 1k storage disk and the "Disk Manipulator" to get the item that caused this glitch alone onto a 1k storage disk and the only item I don't have anymore is my "Portable Storage Grid" and the disk it's stored on only shows 1 item, and you cant see the item when you open it.
3.I have access to every item that was on my 256k card due to moving the grid to a different card, but have lost access to every item currently stored in the "Portable Grid."

4:TRUE REPRODUCE::: Put "Portable Grid" into current "Storage Grid" (this did work with 1k disks) then close the grid, when reopened nothing will appear to be in the grid, despite the card having items.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16
- FTB: Direwolf20 1.11.0'
- Forge: I think it's 1.16.5 from the mod list, but idk
- Refined Storage: mod list says multiple so 1.9.12 and 1.9.15
- Refined Storage Addons: 0.7.2 and 0.7.3 again idk why there's 2
- Extra Storage:1.16.4-1.3.1 and 1.16.5-1.4.1

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
So I think you meant to say: "Grid appears empty when inserting a portable grid into it." 

I can't reproduce that. Having multiple versions of mods should not be a problem, but I've heard rumors that the feature that picks the latest version may be a bit buggy, so I would not recommend doing so.

There are other addons in the pack that might also be interfering here and plenty of user error possibilities.  As such... please come back if you can reproduce this with just RS.
