### ISSUE TITLE
Communication error between Mekanism power supply and Refined Storage controller

### ISSUE THREAD

**Issue by KitayHunter** [refinedmods/refinedstorage#3120]
#### Steps to reproduce:
1. Place a power source, wind generator.
2. Attach a basic power cord.
3. Put a controller.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 1.16.5 - 36.2.8
- Refined Storage: 1.9.15

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here: [crash-2021-11-02_14.32.36-server.txt](https://github.com/refinedmods/refinedstorage/files/7463503/crash-2021-11-02_14.32.36-server.txt)
]

[pastebin/gist/etc link here

**Comment by Darkere** [comment]
downgrade RSinfinity booster

**Comment by KitayHunter** [comment]
Is it to remove the mod or use another version?

**Comment by KitayHunter** [comment]
> rebaixar o reforço RSinfinity



> rebaixar o reforço RSinfinity

Is it to remove the mod or use another version?

**Comment by Darkere** [comment]
either will work.
