### ISSUE TITLE
When exporting to chest, merge into existing stacks

### ISSUE THREAD

**Issue by quasarea** [refinedmods/refinedstorage#3122]
#### Issue description:

When exporting to chest, new stack is created in first available slot

There should be option to merge to existing stacks instead, so we can be in control on position/order that items are stored.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.8
- Refined Storage: 1.9.13

**Comment by raoulvdberge** [comment]
Merging is supported. It depends on how the chest handles their stack insertion.

**Comment by quasarea** [comment]
@raoulvdberge I have tried minecraft chests, barrels and iron chest, none work in that way, could you please give me an example of chest that handles this? In all cases I'm able to shit-click items into existing stacks

**Comment by raoulvdberge** [comment]
Just for clarity, this is with an Exporter?

**Comment by raoulvdberge** [comment]
Can you share some screenshots of your setup?

**Comment by quasarea** [comment]
Yes, vanilla chest, rf exporter no upgrades, put some cobble in last slot, set exporter to export cobble, it begins new stack in first slot instead of filling up existing one first

**Comment by raoulvdberge** [comment]
There is a difference between shift clicking and machine insertion. In this case, the machine insertion for the chest doesn't fill existing stacks. I have no examples of chests that do it correctly.
