### ISSUE TITLE
Server crash on boot: Cannot get property DirectionProperty from refinedstorage:cable

### ISSUE THREAD

**Issue by legitswitch** [refinedmods/refinedstorage#3127]
#### Issue description:
Some chunks where there were refined storage cables were deleted due to a different mod causing a crash. It looks like refined storage data is saved in files in the data folder on the server. If a player places cables in the same spot from before they were deleted it seems to cause this crash.

The logs don't show any coordinates and the RefinedStorage node file in the data folder has over 8000 nodes, with position and owner tags in formats that I don't know how to decipher. Some help with this would be greatly appreciated.

![image](https://user-images.githubusercontent.com/88232383/140698948-55738442-95a1-4649-bb29-11705d608d36.png)

#### What happens:
Server crashes on boot.

#### What you expected to happen:
not crash

#### Steps to reproduce:
1. Delete chunks or region files where there are refined storage networks.
2. Replace cables or nodes in the same positions before chunk/region deletion.
3. Possibly crash.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.8
- Refined Storage: refinedstorage-1.9.15

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
Server crash report
https://www.toptal.com/developers/hastebin/zacibejivo.rust

Debug log before and after crash occured
https://www.toptal.com/developers/hastebin/odategekap.pl

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Try searching for -6265292264046469

**Comment by legitswitch** [comment]
How did you come up with that number to search for? Do you know how to translate it into coordinates? I know the problematic area is within 3 chunks of these coordinates: 41756,124,-32008 

No results found on the number you mentioned...

**Comment by Darkere** [comment]
I made this tool quite some time ago: https://github.com/Darkere/BlockPosLongtoInts and input the last coords in your second log. 

Make sure to select the top level when searching in NBT explorer. It should take quite some time to go through all entries.
