### ISSUE TITLE
minecraft doesn't starts

### ISSUE THREAD

**Issue by Nessuno6** [refinedmods/refinedstorage#3136]
#### Steps to reproduce:
1.download the last version
2.press play
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge:36.2.9
- Refined Storage:1.9.16

Does this issue occur on a server? [no]

#### If a (crash)log is relevant for this issue, link it here:

[
[latest.log](https://github.com/refinedmods/refinedstorage/files/7563777/latest.log)
]

**Comment by Darkere** [comment]
creative wireless transmitter is crashing.

**Comment by Nessuno6** [comment]
you weren't right
