### ISSUE TITLE
error during mod loading

### ISSUE THREAD

**Issue by Nessuno6** [refinedmods/refinedstorage#3137]
Issue description: minecraft says: error loading mod
What happens: minecraft starts but says that there are errors during mod loading
What you expected to happen: minecraft starts
Steps to reproduce:
1.download the last version
2.press play
3.
...

Version (make sure you are on the latest version before reporting):
Minecraft:1.16.5
Forge:36.2.9
Refined Storage:1.9.16
Does this issue occur on a server? [no]

If a (crash)log is relevant for this issue, link it here:
[latest.log](https://github.com/refinedmods/refinedstorage/files/7563807/latest.log)

**Comment by Nessuno6** [comment]
This  bug appends only with forge 36.2.9

**Comment by Darkere** [comment]
There is another RS addon mod crashing. This one unfortunately named the crashing hack "rs" so I can't tell you which one it is :/.

**Comment by Nessuno6** [comment]
it isn't like how are you saying, I think it's a forge bug because I changed forge version to 36.2.0 and another mod did the same thing

**Comment by Darkere** [comment]
The crashlog clearly indicates the problem. Did you also update RS by chance?

**Comment by Nessuno6** [comment]
yep

**Comment by Darkere** [comment]
The addon mod is not compatible with the new version of RS.

**Comment by Nessuno6** [comment]
you are right, thank you

**Comment by Nessuno6** [comment]
you and your team are doing a beatiful mod
