### ISSUE TITLE
Relay borked

### ISSUE THREAD

**Issue by NJM1564** [refinedmods/refinedstorage#3138]
Version 1.9.16
#### Issue description:
Relay won't toggle on no mater what I go. Not via external redstone or internal GUI.
Looks lit up initially when loaded world. But after break and replace is not off.
Will not function ether way.

**Comment by mjevans** [comment]
Has this fix been released?  The version on https://www.curseforge.com/minecraft/mc-mods/refined-storage seems to have not been updated since just before the fix.

**Comment by Darkere** [comment]
no

**Comment by anupdebnath** [comment]
any eta?

**Comment by Darkere** [comment]
been out for 2 weeks by now.....
