### ISSUE TITLE
Crash on placing controller

### ISSUE THREAD

**Issue by coolman9902** [refinedmods/refinedstorage#3141]
#### Issue description:
Placing a storage controller crashes the internal server and crash locks the world

#### What happens:
The internal server crashes when a controller is place
#### What you expected to happen:
it shouldn't crash
#### Steps to reproduce:
1.Place storage controller
2. Crash
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.0
- Refined Storage: 1.19.6

Does this issue occur on a server? [yes/no]
possibly

#### If a (crash)log is relevant for this issue, link it here:

https://paste.ee/p/fsw2w

**Comment by Darkere** [comment]
Update Creative Wireless transmitter
