### ISSUE TITLE
Auto-Machining Grid Slots

### ISSUE THREAD

**Issue by ilovehans10** [refinedmods/refinedstorage#3143]
#### Issue description:
This is an enhancement idea for adding a slot/block that will allow for sending items to a machine.

#### What you expected to happen:
Having a block that worked similar to the crafter where it puts items into a machine. This block can be used to automatically smelt/process items remotely. This functionality should be easy to add as the crafter already does roughly the same thing. The item slot that would send the items could be enabled by use of an upgrade that has to be linked to the processing block.

#### Version (make sure you are on the latest version before reporting):
As this is a suggestion I will still fill this out but it is unnecessary 
- Minecraft: 1.16.5
- Forge: 36.2.8
- Refined Storage: 1.9.15

**Comment by Darkere** [comment]
I'm pretty sure what you are suggesting here is already possible. But just to be sure. 

You want to make the crafter insert items into a furnace for example?

**Comment by ilovehans10** [comment]
> You want to make the crafter insert items into a furnace for example?
Similar to that but unlike the crafter the items would not be put into the processing block (like a furnace) based on a pattern but would instead be put into the processing block after you put them into a processing slot in the inventory screen of a grid.

This would make it so that if I was away from my processing room and wanted some cobble in my inventory smelted but didn't have a pattern I could put the cobble in the processing slot linked to a processing block that would put the cobble in a furnace and then when it was done smelting an importer would pull it back into the system where I could grab it.

**Comment by Darkere** [comment]
Ah I see. I've actually thought about something like this before. But it unfortunately pretty much competes with autocrafting.

And Addon could add blocks that do that but it doesn't fit in the base mod I'm afraid.
