### ISSUE TITLE
error loading mod

### ISSUE THREAD

**Issue by Nhune** [refinedmods/refinedstorage#3144]
#### Steps to reproduce:
1.press play
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge: 36.2.16
- Refined Storage: 1.9.16

Does this issue occur on a server? [no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
[crash-2021-11-22_11.51.20-fml.txt](https://github.com/refinedmods/refinedstorage/files/7580745/crash-2021-11-22_11.51.20-fml.txt)
![image](https://user-images.githubusercontent.com/94803711/142857550-729ebeab-0124-4c0a-a5d4-b744d7229a8b.png)

**Comment by Darkere** [comment]
An addon mod is crashing as it is not compatible with our new version. Can't unfortunately tell you which one but please mention if you find out which it is.

**Comment by Nhune** [comment]
Removed all Addons and even Reinstalled rs and it continues to crash.
[crash-2021-11-22_12.24.55-fml.txt](https://github.com/refinedmods/refinedstorage/files/7580961/crash-2021-11-22_12.24.55-fml.txt)

**Comment by Darkere** [comment]
This is still some other mod hacking into our code. I looked through the mod list... My bet is on creative tweaker or its library?

**Comment by Nhune** [comment]
after some time testing the mods that can give conflict i found one that was crashing 
Mod: Mekanism: Addons
Version: mekanismaddons-1.16.5-2.2.1.jar

**Comment by Darkere** [comment]
Thank you
