### ISSUE TITLE
Wireless Transmitter - needs to be attached directly on controller rather than any block in the network

### ISSUE THREAD

**Issue by Marxone** [refinedmods/refinedstorage#3145]
#### Issue description:
Wireless controller was possible to be attached to a cable or any other block. In Refined Storage 1.9.16 it is now only possible to use Wireless Transmitter attached to Controller directly. 

Happened on AllTheMods 6 - 1.8.10 , but reproduced on clean install of Forge 36.2.8 with just clean Refined Storage 1.9.16. 

#### What happens:
Wireless Transmitter stopped functioning after update. When loading world, it appeared as active, but after replacing the Wireless Transmitter on the same spot, it was inactive (dark)

#### What you expected to happen:
I expect that Wireless Controller connected to a cable that is connected to the controller will function. Seems like it was working since 1.8.3 version according to change log. 

#### Steps to reproduce:
1. Place a Controller
2. Place Cable attached to controller
3. Place Wireless Transmitter to the cable
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.8
- Refined Storage: 1.9.16

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:

--

**Comment by Darkere** [comment]
There is a bug in 1.9.16 that cause the wireless transmitter to only work if it was placed on top. Not when it is placed on the side or upside down.

I've fixed the issue a couple hours ago. It will work again in the next update :)

**Comment by Marxone** [comment]
Oh great. I just noticed it can be on vertical. Thank you :)
