### ISSUE TITLE
Server crash on player login.

### ISSUE THREAD

**Issue by Wissi** [refinedmods/refinedstorage#3146]
#### Issue description:
Server crashes on player login.

#### What happens:
Server crashes on player login.

#### What you expected to happen:
Server not crash on player login.

#### Steps to reproduce:
1. Player was working fine progressing in refined Storage.
2. Player logged out.
3. Player crashes server when tries logging in again.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge:  36.2.8
- Refined Storage: 1.9.16

Does this issue occur on a server? [**yes**/no]

#### If a (crash)log is relevant for this issue, link it here:

[[pastebin/gist/etc link here](https://paste.centos.org/view/f6570590)]

**Comment by Darkere** [comment]
Please try increasing max-tick-time in server.properties (just add a 0). Something is taking a very long time to load.
