### ISSUE TITLE
Can't use Wireless items

### ISSUE THREAD

**Issue by Dragonianz** [refinedmods/refinedstorage#3148]
#### Steps to reproduce:
1. updated Oceanblock
2.loaded Oceanblock
3.loaded saved game
4.pressed c or right clicked wireless crafter
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.9
- Refined Storage: 1.9.16

Does this issue occur on a server? [yes/no]no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
There is unfortunately a bug that causes wireless transmitter to stop working if they are not placed upright. Is already fixed in the next update.

**Comment by MoonStalk** [comment]
as a work around, connect your wireless transmitter directly to your controller

**Comment by Darkere** [comment]
> as a work around, connect your wireless transmitter directly to your controller

That is not necessary. Just needs to be upright.
