### ISSUE TITLE
Server crash on joining

### ISSUE THREAD

**Issue by ToxykAuBleu** [refinedmods/refinedstorage#3149]
#### Issue description:

I attempted joining my server and after 60 seconds, the server told me it has crashed.
Very similar with #3146, I also attempted joining the world on singleplayer and it worked perfectly fine.
I tried to increase max-tick-time in server.properties, when I joined, the server didn't respond at all, so I timed out.

#### What happens:

The server crash on player join

#### What you expected to happen:

The server not crash on player join

#### Steps to reproduce:
1. Progress with the mod (place some block of the mod in the world)
2. Shutdown the server
3. Start the server
4. Attempt to join the server and wait 60 seconds until it crash

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.8
- Refined Storage: 1.19.6

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

[Redirection link](https://pastebin.com/9Pt2Hmp1)

**Comment by raoulvdberge** [comment]
What makes you think that RS causes this?

**Comment by ToxykAuBleu** [comment]
The only thing that was new in the world between 2 sessions was just placing basic stuff (like craft monitor, disk storage).
Are you thinking that RS did not cause this ? or are you sure ? 😅

**Comment by Darkere** [comment]
The cause is likely a chunk that isn't loading. It crashes offthread and makes the main thread wait forever. Resulting in this timeout crash. 

There is no indication that RS is at fault for that (also, I don't think we do anything that could even cause chunkgeneration to error out that way).
