### ISSUE TITLE
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError. Crash

### ISSUE THREAD

**Issue by leagueoftim** [refinedmods/refinedstorage#3150]
#### Issue description:

I just created a  modpack for me and my friends and if i'm trying to load Minecraft it says that Refined Storage and RF Addons couldn't load correctly cuz of org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError. I just wanna know what causes this problem.

#### What happens:

Nothing can't open/load Minecraft

#### What you expected to happen:

Minecraft to load xD

#### Steps to reproduce:

/ 

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.9
- Refined Storage: 1.9.16

Does this issue occur on a server? [yes/no]

no 

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/bJ2U8FpM

**Comment by Darkere** [comment]
Crash caused by Mekanism: Addons. 
Not sure if they've released an update to fix this.

**Comment by MorningSage** [comment]
Fix is in the pipeline, but I'm not near a computer to be able to update.

My apologies, all.
