### ISSUE TITLE
Sided_Setup error

### ISSUE THREAD

**Issue by DaRubb3rDucky1** [refinedmods/refinedstorage#3151]
#### Issue description:
Minecraft is crashing when I try to run it
#### What happens:
When I tried to load Minecraft it wouldn't let me and says Refined Storage (refinedstorage) encountered an error during the sided_setup event phase
#### What you expected to happen:
Minecraft to load
#### Steps to reproduce:
1. Load Minecraft with these mods
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.66
- Refined Storage: 1.9.16

Does this issue occur on a server? [yes/no]
No
#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/zaCAm9Wh
[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
remove refined curios. RS has native support for curios now.
