### ISSUE TITLE
CANT take items outside the refined storage system. Cant click on anything in the grid.

### ISSUE THREAD

**Issue by Juanchio88** [refinedmods/refinedstorage#3152]
#### Steps to reproduce:
1.100% Of the time happens when i attach an external storage into a Tank (Multiblock) from Immersive Engineering. Currently is also happening with Dank Storage Dock (Block).

#### Version (make sure you are on the latest version before reporting): refinedstorage-1.9.16

- Minecraft: 1.16
- Forge: 
- Refined Storage: refinedstorage-1.9.16

Does this issue occur on a server? [yes/no] Yes

**Comment by Darkere** [comment]
We are aware :)
