### ISSUE TITLE
Can't interact with covers nor remove them without breaking the covered cable

### ISSUE THREAD

**Issue by bdunogier** [refinedmods/refinedstorage#3155]
#### Issue description:
Can interact with covered elements, and can't remove covers without breaking the covered cable.

#### What happens:
Covered elements can't be interacted with, and breaking a covered cable breaks the cover.

#### What you expected to happen:
Breaking a cover breaks the cover and not the cable, or a way to interact with covered elements without breaking them.

#### Steps to reproduce:
1. Cover a exporter/importer...
2. Try to interact with it

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.16.5
- Forge: 36.2.9
- Refined Storage: 1.9.16

Does this issue occur on a server? Probably

P.S. Covers are great, thank you for bringing them back.

**Comment by Darkere** [comment]
Shift rigthclick with the wrench.

**Comment by bdunogier** [comment]
What, really ? My, it's in the wrench's doc. I'll submit a PR that adds it to the covers doc.
Thank you.
