### ISSUE TITLE
Wireless Transmitters dont work when placed not on UP-Face of a cable

### ISSUE THREAD

**Issue by fampat** [refinedmods/refinedstorage#3158]
#### Issue description:
Since 1.9.16 Wireless Transmitters dont work (also wont light up) when placed not on UP-Face of a cable.

#### What happens:
Cant access wireless-grid due to missing network

#### What you expected to happen:
Prior to 1.9.16 Wireless Transmitters also worked when placed on any face of a cable, for example DOWN-Face when the cable was on the ceiling.

#### Steps to reproduce:
1. Setup a minima storage network
2. Connect and put a cable from the controller to a ceiling
3. Attach a Wireless Transmitter to the DOWN-Face of a cable above you on the ceiling
4. It will not recognize the network and wont light up

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.18
- Refined Storage: 1.9.16
- Refined Storage Addons: 0.7.4

Does this issue occur on a server? yes

**Comment by Darkere** [comment]
Fixed next version.
