### ISSUE TITLE
No items in grid

### ISSUE THREAD

**Issue by VoidDave** [refinedmods/refinedstorage#3159]
#### Issue description:
Item can be puted into system / grid item then item count rise up. But there aren`t visible inside of any grid
#### What happens:
I crafted stack of iron (from geted from roost mod) and then items disapered from grid (all) i can put items inside but cant get it out. 
If you can pls reply heare with possible fix. (I tried server restart, moving grid controller and disk drive, puting backup of the word before the issue )
#### What you expected to happen:
To be able to see item and be able to take it
#### Steps to reproduce:
1.Make block (iron block gold block etc)
2.Press shift and spam for multipe stack craft
3.Put crafted blocks inside

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.5.2847
- Refined Storage:1.16.16

Does this issue occur on a server? [yes/no]
yes

**Comment by Darkere** [comment]
Restart client

**Comment by VoidDave** [comment]
It worked sorry for taking your time. I should thinked about it first
