### ISSUE TITLE
Wireless Transmitter not connecting.

### ISSUE THREAD

**Issue by Xida00** [refinedmods/refinedstorage#3161]
#### What happens: 

I had a total of 4 wireless transmitters on a network all working with range modes. I tried to do some rewiring around the base and the moment i broke a cable leading to a transmitter or broke a transmitter and replaced they all refuse to work. 

I did manage to get one to work by placing it upon a machine block, however it seems when attached to cables they refuse to work. 

As you can see below on top is working as normal, one to the right on cable refuses to work.
#
![Screenshot 2021-12-03 110625](https://user-images.githubusercontent.com/95475917/144592455-96148f52-5f72-4255-834a-e90e63605cbc.png)
#### What you expected to happen: Item to connect to network. 

FTB Ocean Block Lastest version.
- Refined Storage: 1.9.16
- Refinedstorageaddons 0.7.4

Does this issue occur on a server? Not sure

**Comment by Darkere** [comment]
There is a currently a but that prevents transmitters from working unless they are placed upright. Fixed in dev.
