### ISSUE TITLE
Cannot make processing recipes anymore since updating to newest Modpack version where the version of RS stayed the same.

### ISSUE THREAD

**Issue by e30Birdy** [refinedmods/refinedstorage#3164]
Modpack
FTB OceanBlock

Modpack version
1.10.1

Mod Version:
refinedstorage-1.9.16

Log Files
No response

Describe the bug
I made a bunch of autocrafting patterns and now trying to make one for Grout to Seared Bricks and I cannot shift click in the recipes. Nor can you drag and drop from the right. Made a video to show.

If mode is not processing it does let one drag from the right. Just seems processing mode is broken.

I just did some tests and in my current world it does what the video below does and when I make a new world it works fine. FTB team told me to report here to see if you all can figure out what happened since I moved from version 1.9 to 1.10.1 of their modpack where the RS mod version didn't change.

Steps to reproduce
I show all the steps in video link I attached.

Expected behaviour
Click the plus and create processing recipe or ability to drag and drop parts into recipe from JEI

Screenshots
https://youtu.be/hfr6rIG2Crc

Additional information
No response

**Comment by Darkere** [comment]
You are in fluid mode...
![image](https://user-images.githubusercontent.com/4283717/145415191-c341c645-0c8f-4f99-9977-f17d8c6c46fb.png)

**Comment by e30Birdy** [comment]
> You are in fluid mode... ![image](https://user-images.githubusercontent.com/4283717/145415191-c341c645-0c8f-4f99-9977-f17d8c6c46fb.png)

LOL I feel like an idiot.. I didn't change it to fluid and no one else caught it, thanks for seeing that. I still feel stupid as if I would have changed it then I would have thought of looking at that. Hardly use fluid mode in this pack so I didn't even thing to look.
