### ISSUE TITLE
Missing potion fluids/buckets in JEI.

### ISSUE THREAD

**Issue by Mystikite** [refinedmods/refinedstorage#3168]
### Describe the bug

Excuse me if this doesn't belong here.

When attempting to Fluid craft, JEI has no registered fluids for the various potions other than a generic 'Potion', and no Buckets of the various Potions (except Bucket of Awkward Potion, which has its own issues that i will report separately).

This means that while i can pipe specific potions from say, Thermal's Alchemical Imbuer' INTO the RS fluid grid, I find myself unable to create crafting patterns in the Pattern Grid, as i can not pull from JEI, nor from a bucket in my inventory, nor using a potion/splash potion to represent the fluid.

### How can we reproduce this bug or crash?

Use a mod (Thermal, Immersive Engineering, etc) to craft potions as Fluid. ( Potion of Strength (3:00) )
Export to RS Fluid Grid.
Create a Processing crafting pattern for that potion:
Click on Item Type.
Add 1 Blaze Powder to Input.
Click on Fluid Type
Attempt to Add Awkward Potion from JEI either as a Fluid or as a Bucket by dragging from JEI or Inventory.
Attempt to Add Potion of Strength (3:00) as a Fluid to Output as a Fluid or Bucket by dragging from JEI or Inventory.

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

1.16.5-forge-36.2.19

### What Refined Storage version is this happening on?

1.19.6

**Comment by Darkere** [comment]
This is due to how Thermal registers its potions. There is nothing we can do about this. 

The only way to interact with them is via autocrafting by pressing the + on the recipe, or by filtering for the "potion fluid" with exact mode off.
