### ISSUE TITLE
1.18 Support

### ISSUE THREAD

**Issue by cadpri** [refinedmods/refinedstorage#3181]
### Describe your enhancement

hello,

is it possible to get a Version that runs on a 1.18 Server ?
i tried to install the latest version but seems to only work on a 1.18.1 server.

but my server is runnning on 1.18

**Comment by raoulvdberge** [comment]
Nope, upgrade to 1.18.1. Why would I support an obsolete version?

**Comment by cadpri** [comment]
the thing is that my server runs one of the top5 mod packs: better minecraft. and it runs on 1.18.

since you refused to support it: are you okay if i pay someone else to recode your mod to run on 1.18 ?

**Comment by raoulvdberge** [comment]
The latest version of Better Minecraft runs on 1.18.1:

https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack-new/files/3569493

Why can't you upgrade the server?
