### ISSUE TITLE
Crafter kills TPS

### ISSUE THREAD

**Issue by ManciDRaffy** [refinedmods/refinedstorage#3184]
### Describe the bug

If you place a crafter and do a normal craft every second or third time, the TPS drops very low.

FTB Direwolf20 Modpack

If not crafting, TPS is at 20

I don't know if that is normal but would be nice if its fixable or I get an answer :)

### How can we reproduce this bug or crash?

1. Place crafter
2. Put any pattern in
3. craft
4. look at /tps

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.9

### What Refined Storage version is this happening on?

1.9.16

**Comment by Darkere** [comment]
Please install and run spark while the lag is happening. So it becomes possible to figure out the cause.
