### ISSUE TITLE
can`t join modded server, server crash

### ISSUE THREAD

**Issue by bulkasmakom1** [refinedmods/refinedstorage#3188]
### Describe the bug

I` don`t know if this is even appropriate place to try asking for solution but i`ve lost all hope to find it myself
There is really no details one day i play and the other day i try to join server, walk a couple of blocks and then server just crashes
After that i couldn`t join even once, server crashes every time

### How can we reproduce this bug or crash?

i have no idea how to reproduce 
there is crash if needed
[crash-2021-12-24_11.24.53-server.txt](https://github.com/refinedmods/refinedstorage/files/7775129/crash-2021-12-24_11.24.53-server.txt)
t

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.22

### What Refined Storage version is this happening on?

1.9.16

**Comment by Darkere** [comment]
wtf...  According to Curle this can happen if you do dumb things with threads. Which means this is certainly not caused by us. 


You should be able to avoid this specific crash by removing the wireless item you have on you or by disabling wireless charging through flux networks.
