### ISSUE TITLE
Refined storage deletes auto crafted items after crafting them

### ISSUE THREAD

**Issue by cover1234** [refinedmods/refinedstorage#3193]
### Describe the bug

What happened:
I auto crafted 10 importer looked in my storage it got to 5 and then went down to four then it got to 7 and went down to 6 by the end I only had 8 importers

What is expected to happen:
auto craft 10 importers and end up with 10 

### How can we reproduce this bug or crash?

1.Make a autocrafting set up

2. put a pattern for importers

3. auto craft 10 importers

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

Forge - 36.2.20

### What Refined Storage version is this happening on?

Refined Storage - 1.9.16

**Comment by Darkere** [comment]
They were either extracted by something else from somewhere on the network or are stuck in autocrafting (make a crafting monitor to check).

**Comment by cover1234** [comment]
it only works if the entire time its auto crafting im looking at the crafting monitor and if im not it still happens

**Comment by Darkere** [comment]
We would have a million bug reports if something that simple would be voiding items. 

The code for that hasn't been touched in a year. 

If you are super certain it is just RS, make a minimal pack (just RS and maybe JEI) and try to reproduce there.

**Comment by cover1234** [comment]
it works on a world with just Refined Storage and JEI but not in atm6
