### ISSUE TITLE
Getting spongepowered error with no mekanism addons

### ISSUE THREAD

**Issue by 1matto** [refinedmods/refinedstorage#3195]
### Describe the bug

getting the spongepower error and I don't have Mekanism addons installed

### How can we reproduce this bug or crash?

just starting up minecraft

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.21

### What Refined Storage version is this happening on?

1.9.16

### Relevant log output

```shell
[crash-2021-12-29_04.06.58-fml.txt](https://github.com/refinedmods/refinedstorage/files/7788192/crash-2021-12-29_04.06.58-fml.txt)


```

**Comment by raoulvdberge** [comment]
Remove Refined Curios, it is now native in RS.
