### ISSUE TITLE
Recipes only use vanilla ingots

### ISSUE THREAD

**Issue by Scarfiremmi** [refinedmods/refinedstorage#3204]
### Describe the bug

When testing a custom modpack (1.16.5), I discovered that this mod only uses vanilla iron and gold ingots in its recipes, rather than allowing other materials with the same tags, such as Immersive Geology's iron and gold ingots

### How can we reproduce this bug or crash?

I discovered this by having Immersive Geology (an Immersive Engineering addon) and Refined storage installed and going through recipes in JEI.

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

1.16.5-forge-36..2.22

### What Refined Storage version is this happening on?

1.9.16

**Comment by Darkere** [comment]
For crafting recipes disable exact. For processing recipes you can click the ingredient and enable valid tags under alternatives.
