### ISSUE TITLE
Wireless transmitter only works when attached to top of RS objects, not sides or bottom of those objects

### ISSUE THREAD

**Issue by hornsfan01** [refinedmods/refinedstorage#3208]
### Describe the bug

Previously, a Wireless Transmitter would light up and allow the use of a Wireless Grid when the transmitter was placed attached to any side of an RS object like a grid, Network Receiver, or cable. After the most recent patch, they only "light up" and allow the use of a Wireless Grid when they are attached to the top of these objects. They do not "light up" nor allow Wireless Grid access when attached to the sides or bottom of these objects.

### How can we reproduce this bug or crash?

Build a powered controller in Creative. Attach RS cables to it. Attach RS wireless transmitters to the top and the sides and the bottom of either the controller or any of the cables. The ones on top will light up and provide access to the controller, but the ones attached to the sides and bottom will not.

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.20

### What Refined Storage version is this happening on?

1.9.16

**Comment by Darkere** [comment]
Fixed in dev
