### ISSUE TITLE
autocrafting gets stuck

### ISSUE THREAD

**Issue by Spongman** [refinedmods/refinedstorage#3217]
### Describe the bug

I have a reasonably complicated storage setup, and things generally work ok, but sometimes, seemingly randomly, some recipes auto-crafted by crafting upgrades just halt for some reason and then never continue.

often when this happens i get weird states like this:

![image](https://user-images.githubusercontent.com/1088194/149855491-813528fd-30a5-487d-bdfe-14059a50ffc6.png)

and this

![image](https://user-images.githubusercontent.com/1088194/149855517-1088afde-c32d-408b-8d76-69aff11a2ae5.png)

I'm not sure what's going on there. The ingredients for crafting the items are available, the previous batch of items seems to have crafted successfully, but it just sits there telling me uselessly it has a bunch of empty buckets that it's having a really hard think about.

At this point, in order to continue, I have to go through all the currently crafting jobs and cancel all those that are in this state. Kinda takes the whole 'auto' out of auto-crafting...

### How can we reproduce this bug or crash?

no idea what's causing this.

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.20

### What Refined Storage version is this happening on?

1.9.17

**Comment by Darkere** [comment]
Any chance for a wold download? We know this bug exists but haven't had the chance to investigate it.

**Comment by Spongman** [comment]
https://file.pizza/download/ihtegf6x

**Comment by Spongman** [comment]
https://toffeesha.re/c/87MRAW2XpA

**Comment by Darkere** [comment]
Forgot to ask which pack you are playing :) ?

Also 1.9.17 hasn't been released yet... so I doubt you are playing on that?

**Comment by Darkere** [comment]
thank you. This allowed me to find the bug in a couple minutes.

**Comment by Spongman** [comment]
btw: i just built the 1.16 branch and at first glance it looks much better: no jobs getting stuck!
