### ISSUE TITLE
Speed downgrade, crafting 1 at a time

### ISSUE THREAD

**Issue by Yusunoha** [refinedmods/refinedstorage#3218]
Currently there's speed upgrades in RS that export or craft items/fluids as fast as possible.
But this is not what you always want, sometimes when you try autocraft an item with a machine from another mod, this machine can't handle it if all the items get dumped in 1 go.

Would it be possible to create a speed downgrade item that you can insert into crafters. This speed downgrade will only allow RS to craft an item 1 at a time. So for example, if you request an item 8x, it'll export 1 amount worth of materials, wait for the machine to craft and insert the item into the network, before continueing with the second craft etcetcetc

**Comment by Darkere** [comment]
https://refinedmods.com/refined-storage/wiki/crafter.html#crafter-modes

This can easily be achieved with crafter modes.
