### ISSUE TITLE
Silk Touch Upgrade for Destructor does not collect grass

### ISSUE THREAD

**Issue by Calvin315** [refinedmods/refinedstorage#3219]
### Describe the bug

I am trying to use a Destructor to collect grass, I have a silk touch upgrade for the destructor but it just collects the seeds?

### How can we reproduce this bug or crash?

1. Place a Destructor above a grass block
2. Insert a Silk Touch Upgrade into the Destructor
3. Apply bone meal to grow grass under the Destructor 

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.22

### What Refined Storage version is this happening on?

refinedstorage-1.9.16

**Comment by SuperKael** [comment]
This is not a bug, you cannot collect grass with silk touch...
