### ISSUE TITLE
small change to the piping system

### ISSUE THREAD

**Issue by ORCXodus** [refinedmods/refinedstorage#3220]
### Describe your enhancement

Ok, maybe im the first person who has suggested this.. i didnt see any suggestions relating to this in any other comment section..

In your RS mod you have color coded pieces for most of the different parts.. save one.. and its the one I would love to see implemented.. the pipes (cables)... I have a 15 story skyscraper that has multiple storage units because I do not want my fermenter/generators (Immersive engineering) pulling from my food supply to generate the biodiesel.. so i have several pipes running up the core shaft of the building (my bio farm is on floor 8, my power plant on Basement level 2, and my food farm is on floor 4.. my vault (where my main storage is housed is in basement level 1...).. but I also have a bio-plant for making automotive biodiesel on another floor...as u can see its a complex system that I want to keep different item/fluid storage's separate so as they do not leach off my main food/wood supply... therefor.. having a few different colored pipes (as you have everything else color coded) would be awesome... that way i can color code my piping system and know that i have not inadvertently crossed connections..  This occurred at one point and my power grid began sucking my food supply dry! yikes.. 

even if you didnt want to add say 16 different colored pipes... maybe another way is have a paint brush tool.. so u can click on a pipe and set its color...  or.. and this I have seen implemented (moving elevators mod) being able to hold a color of dye in your hand and click on the pipe.. all pipe connected to that pipe turns that color...

**Comment by raoulvdberge** [comment]
#2637
