### ISSUE TITLE
Clear button offset

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#3222]
### Describe the bug

![image](https://user-images.githubusercontent.com/4283717/150486503-8890d3df-408c-4252-bfaf-9ab21a930ab9.png)

### How can we reproduce this bug or crash?

1

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.22

### What Refined Storage version is this happening on?

f11ec57

**Comment by raoulvdberge** [comment]
807da8529aac31a8f1993f5fe7430e751c6bd55e
