### ISSUE TITLE
Crafting grid can't be used by just one player

### ISSUE THREAD

**Issue by Topher2225** [refinedmods/refinedstorage#3227]
### Describe the bug

we added refined storage to all the magic and just one of us can't use the crafting grid. we tried reinstalling, deleting there player data, and other small things. also he can't use any of the wireless things. 

### How can we reproduce this bug or crash?

i haven't seen anyone else have this problem on the server but its just four of us. 

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.22

### What Refined Storage version is this happening on?

1.9.15

**Comment by raoulvdberge** [comment]
We'd need logs.
