### ISSUE TITLE
Allow Importers to have items pushed to them

### ISSUE THREAD

**Issue by AerosAtar** [refinedmods/refinedstorage#3230]
### Describe your enhancement

This feature would allow mods that include resource generators without buffers/internal inventories to interact with a RS system without the need for a 'buffer chest' between the generator and importer, allowing for much greater felxibility in builds.

If this could cause issues with the way filtering works, perhaps have it as an upgrade that also disables the filter slots or swaps them to buffer/inventory slots?

Examples of mods that this would help with include Botany Pots and Caged Mobs.

**Comment by Darkere** [comment]
So.. The interface?

**Comment by AerosAtar** [comment]
Apologies, I appear to have missed a point in my description. Importers can be hidden using Covers, while Interfaces cannot, therefore this change would allow for greater flexibility in creating tidy/aesthetic builds.
