### ISSUE TITLE
 Autocrafting items return to the system and autocrafting does not end

### ISSUE THREAD

**Issue by Soyalzeetos** [refinedmods/refinedstorage#3231]
### Describe the bug

Autocrafting items return to the system and autocrafting does not end

### How can we reproduce this bug or crash?

just ask for auto crafting

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.23

### What Refined Storage version is this happening on?

0.7.4

**Comment by Darkere** [comment]
Please provide more details. What type of item does not finish. How are you inserting the item into the system?

**Comment by Soyalzeetos** [comment]
before autocrafting in the furnaces worked after I updated it does not detect that the items have already been crafted

**Comment by Darkere** [comment]
Please provide more details. What type of item does not finish. How are you inserting the item into the system?

**Comment by Soyalzeetos** [comment]
> Por favor, forneça mais detalhes. Que tipo de item não termina. Como você está inserindo o item no sistema?

Importer

**Comment by Soyalzeetos** [comment]
I've always used the importer but after the last update it doesn't show that the item comes back, in this case I pass the iron ore through the enrichiment chamber of the mekanism dps mod through a furnace but it still doesn't consider the item returned, and I have to keep canceling and starting over the crafting
