### ISSUE TITLE
Ticking block entity in newest version from controller

### ISSUE THREAD

**Issue by Arceus73** [refinedmods/refinedstorage#3233]
So i saw there were some issues by others but in my case after bein stuck in a restart loop and then changing the removeErroringEntities and tiles to true the server always ended up showing the crash report in the console 10 times and being weirdly glitched and flashing. I tried joining out of curiosity and after freezing everything i saw the console flashing again and then showing my ingame name and me joining. then my game unfroze and i was on the server. The storagesystem was offline except for the controller. I broke it and the server console stopped flashing and as i placed it down again everything seemed to work fine. i checked the storage and all items were there.
Except for one thing: the fluids. i had a kitchensink importing water for quite some time but there was no water in the system and the craftable fluids and some others were missing as well. I checked the creative fluid cell and it showed: Stored: -1,629,094,014.
I think the crash was maybe caused by the quantity in the creative fluid storage Disk.

**Comment by Arceus73** [comment]
i just saw the fluid storage cells are weirdly glitching and duplicating when i put them in. The duplicates are not ghost items but really working and also have negative numbers

**Comment by raoulvdberge** [comment]
Interesting, I wonder why you felt the need to click "Open a blank issue" when there is clearly a "Bug" option that states: "Found a bug or **encountered a crash**? Please report it here."

![image](https://user-images.githubusercontent.com/10358424/151702654-a2e1c6d2-dcae-43f6-b844-ab0efc7c1008.png)
