### ISSUE TITLE
External Storage doesn't recognise Mekanism Dynamic Tank

### ISSUE THREAD

**Issue by ramonGonzEdu** [refinedmods/refinedstorage#3235]
### Describe the bug

After building a 5x5x5 mekanism tank and placing the external storage on the valve or on the frame, and switching its mode to fluid, RS doesn't pick up that it's facing a fluid storage. Same issue occurs with a tinkers construct smeltery.
(Issue also occured with 1.9.16)

Mekanism+Refined Storage are the only things necessary.

### How can we reproduce this bug or crash?

1. Build a (5x5x5) mekanism tank or tinkers tank
2. Place the external storage on the valves or on any block of the multiblocks
3. Switch external storage mode to fluid
4. Tank isn't detected (won't show in external storage or in fluid grid)

![Screenshot_20220130_124142](https://user-images.githubusercontent.com/71736881/151710856-ea81852d-39c0-4b90-b670-4e56ea98388a.png)
![Screenshot_20220130_124136](https://user-images.githubusercontent.com/71736881/151710859-14e93e20-37c8-491a-a189-62673bc341e8.png)
![Screenshot_20220130_124124](https://user-images.githubusercontent.com/71736881/151710860-b22a32eb-12c7-437c-a83b-1ff2c04c81c1.png)

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.1.22

### What Refined Storage version is this happening on?

1.9.17

### Relevant log output

```shell
N/A
```

**Comment by Darkere** [comment]
The tank is responsible for exposing the fluid tank there. We can't do anything to force that. No idea where and if the dynamic tank exposes its inventory, but for the tinker's you should be able to put the external storage on the drain of a formed smeltery.
