### ISSUE TITLE
Items dissapear from grid

### ISSUE THREAD

**Issue by czychuuu** [refinedmods/refinedstorage#3236]
### Describe the bug

I just wanted to craft something and all i se is nothing.
Yes i have power disks etc.
cant select 1.12.2 in mc version

### How can we reproduce this bug or crash?

![2022-01-30_22 33 02](https://user-images.githubusercontent.com/60987404/151719021-a25c8866-c205-4d24-b188-0f2b56e9b029.png)
![2022-01-30_22 33 14](https://user-images.githubusercontent.com/60987404/151719023-ae93f2ec-8450-4286-87b1-4f67d4adda6c.png)
![2022-01-30_22 33 22](https://user-images.githubusercontent.com/60987404/151719024-d245c1f4-d1d9-405c-ae0c-fd38393b9553.png)

### What Forge version is this happening on?

14.23.5.2855

### What Refined Storage version is this happening on?

1.6.16

### Relevant log output

```shell
[22:39:25] [Server thread/DEBUG] [FML]: The world 6d860b38 (world) may have leaked: seen 2240 times.
[22:39:35] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save world
```

**Comment by Darkere** [comment]
try restarting client

**Comment by raoulvdberge** [comment]
What Minecraft version is this happening on?
No response


Guess I need to make this field required :D

**Comment by czychuuu** [comment]
> 

read description "cant select 1.12.2 in mc version"
