### ISSUE TITLE
the crafting grid cannot be accessed

### ISSUE THREAD

**Issue by netnet75** [refinedmods/refinedstorage#3241]
### Describe the bug

I am on a server with my son and he has made a crafting grid but I have no access to it and when I try to access it, it just acts like a regular block

### How can we reproduce this bug or crash?

I don't know what produced this bug it just started to happen

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.0

### What Refined Storage version is this happening on?

1.9.16

**Comment by Darkere** [comment]
2 possibilities I can Imagine. 
A) He has a security manager and that doesn't allow you to access the grid
B) He has claimed the chunk with some claiming mod and you can't access any blocks in the area.

**Comment by netnet75** [comment]
he don't have these on

**Comment by netnet75** [comment]
i made the crafting grid and it doesn't work does anyone know why please

**Comment by netnet75** [comment]
hi what do you mean by logs

**Comment by Darkere** [comment]
Please try:
- checking if anything appears in your latest.log when you try to open the grid (google it)
- check if the same thing happens in a singleplayer creative world

**Comment by netnet75** [comment]
it works on singleplayer   and nothing in the lastest log

**Comment by raoulvdberge** [comment]
send us the contents of the log

**Comment by netnet75** [comment]
![image](https://user-images.githubusercontent.com/99442070/154814528-0933a527-b148-47cd-94a8-7ac0e63f3330.png)

**Comment by netnet75** [comment]
please can someone help
