### ISSUE TITLE
CRASHING: Breaking grid crashes server

### ISSUE THREAD

**Issue by aerialspring** [refinedmods/refinedstorage#3248]
### Describe the bug

Player broke crafting grid with vanilla pickaxe and server crashed. 

Minecraft 1.18.1
Forge 39.0.79
Refined storage v 1.10.0

Player tried to vein mine it (ore excavator): https://pastebin.com/9Uq88KLK
Player just broke the crafting grid with pick: https://pastebin.com/zf1Byzp2

### How can we reproduce this bug or crash?

Break crafting grid with pickaxe

### What Minecraft version is this happening on?

Minecraft 1.18.1

### What Forge version is this happening on?

39.0.79

### What Refined Storage version is this happening on?

1.10.0

**Comment by aerialspring** [comment]
Breaking fluid grid has same result. Player broke it with open hand. https://pastebin.com/1BcMt6nk

**Comment by Darkere** [comment]
Seems to be caused by polymorph?

**Comment by aerialspring** [comment]
I've left a bug report over there as well. Unfortunately, only seems to occur when breaking RS grids by any means. 

Using Polymorph 0.37

**Comment by Darkere** [comment]
polymorph has a config to disable integration. that might help

**Comment by aerialspring** [comment]
Tried a couple of things:

- Updated to latest polymorph (0.38) with no change in behavior
- Updated Forge to 39.0.85 with no change in behavior
- Disabling Polymorph integration for RS and RS addons resolves the crash on breaking the grids. 

Updated the bug report on Polymorph with this new information. Thank you!
