### ISSUE TITLE
Update to 1.18.2 / Forge 40.0.13+

### ISSUE THREAD

**Issue by isaaclepes** [refinedmods/refinedstorage#3257]
### Describe your enhancement

I wanted to make sure you were aware that Refined storage does not work on 1.18.2.  On-load error is:
![image](https://user-images.githubusercontent.com/54421422/158069924-076bafc8-edcd-43e9-8945-4f9233ed3dd9.png)

Requesting enhancement:  1.18.2 | Forge 40.0.13 support.

**Comment by BinLox** [comment]
Seconded

**Comment by Andronomos** [comment]
Thirded

**Comment by raoulvdberge** [comment]
Thanks for making me aware.

**Comment by raoulvdberge** [comment]
https://github.com/refinedmods/refinedstorage/releases/tag/v1.10.2
