### ISSUE TITLE
Cables don't connect to energy producers

### ISSUE THREAD

**Issue by airnote85** [refinedmods/refinedstorage#3259]
### Describe the bug

(Not reproducible with just Refined Storage since it doesn't provide energy producers.)

### How can we reproduce this bug or crash?

1. Set up a test world with Refined Storage, Create, and Create Crafts & Additions.
2. Place a Controller with cable connecting it to an Alternator (from CC&A) powered by a Creative Motor (from Create).
3. Observe that the cable does not visually appear to be connected to the Alternator, and the Controller's energy buffer is not being filled.
4. Optionally, break the Controller and place it directly on the Alternator instead. This works (its energy buffer begins filling).

### What Minecraft version is this happening on?

Minecraft 1.18.1

### What Forge version is this happening on?

39.1.0

### What Refined Storage version is this happening on?

1.10.0

**Comment by raoulvdberge** [comment]
Yeah thats not how it works. Cables don't accept energy.
