### ISSUE TITLE
Structure block cannot save Refined Storage elements

### ISSUE THREAD

**Issue by leviathan13** [refinedmods/refinedstorage#3260]
### Describe the bug

Storage disks and various upgrades are not saved at all when exporting a structure using the structure block, even while saving entities. Furthermore, all "grid" blocks are incorrectly rotated in the same direction irrespective of their original direction (this happens regardless if you rotate the structure or not using the structure block).

I would imagine it will be difficult to make the structure block correctly export every aspect of RS, but I think it should at least not mess the block directions and have all the upgrades in place (if not the whole configuration/storage, the upgrade items themselves be in place).

### How can we reproduce this bug or crash?

1. Create a Refined Storage set up, with multiple "grid" blocks facing different directions.
2. Save everything in a minecraft structure (with entities) using the structure block.
3. Reload the structure in another spot.

### What Minecraft version is this happening on?

Minecraft 1.18.1

### What Forge version is this happening on?

39.1.2

### What Refined Storage version is this happening on?

1.10

**Comment by raoulvdberge** [comment]
Known issue and won't be fixed for RS 1.

**Comment by leviathan13** [comment]
Alright, thanks. If this will be addressed in the future, I think it would be already great if the rotation of the blocks could be preserved correctly.

**Comment by raoulvdberge** [comment]
RS 2 supports that and more: https://youtu.be/VCsr5M7sr4o
