### ISSUE TITLE
Server crash 1.16.5

### ISSUE THREAD

**Issue by Dimotr3** [refinedmods/refinedstorage#3262]
### Describe the bug

Hello ! I come to ask for your help because I currently have a server with the Ragnamod 6 modpack but it crashes as soon as we try to connect to it. I already know that the problem comes from refined because the first line of the crash is "java.lang.NoClassDefFoundError: com/refinedmods/refinedstorage/energy/ItemEnergyStorage". 
I've already tried to ask the modpack developer directly but they don't respond.
The full crash report : https://pastebin.com/41WHUs2b

### How can we reproduce this bug or crash?

I don't know how to reproduce because when I downloaded the world save to test, everything worked fine.

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.22

### What Refined Storage version is this happening on?

1.9.17

**Comment by Darkere** [comment]
potentially a broken RS download? Try redownloading the RS jar. 

Could also be that super obscure classloading error that has been making the rounds :/

I believe flux networks also has a config option to disabled wireless charging which might help you out in this case.

**Comment by Dimotr3** [comment]
Thank you for your answer. I have already tried to reinstall the server with the modpack but it does not work. I removed the flux network block and the server no longer crashes but now I have a new error : https://pastebin.com/xBwu4vrB

**Comment by Dimotr3** [comment]
I removed all the advanced importer/exporter so I really don't understand

**Comment by raoulvdberge** [comment]
Not an RS issue
