### ISSUE TITLE
I'm experiencing severe stuttering in my local player game

### ISSUE THREAD

**Issue by shuaidemeikan** [refinedmods/refinedstorage#3265]
### Describe the bug

I am playing the game locally, and I feel that the tps is very low when I play recently, so I installed a "spark mod" to analyze the performance of the game. The results of the analysis are as follows, https://spark.lucko.me/jYo3OEI7ZJ
According to this analysis, 90% of the time is occupied by this mod, so that my tps is only 5
The hardware I use is ryzen 5600x + gtx1070 + 32G memory, the game version is: 1.16.5, the forage version is: 36.2.0
I would like to know why this is and what to do to avoid this problem
Because I don't know what information to provide, I can only provide performance analysis from spark. If I need to submit what information, I will submit it in time
Since I am from China and my English is limited, it may seem strange to use Google Translate, please forgive me

### How can we reproduce this bug or crash?

I don't know how to reproduce this error, or the tps is very low every time I run the game...

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.0

### What Refined Storage version is this happening on?

1.9.16

**Comment by Darkere** [comment]
Importer on an integrated dynamics block is causing the issue. I assume its on an Integrated Dynamics interface.
