### ISSUE TITLE
Display craftable improvements

### ISSUE THREAD

**Issue by leviathan13** [refinedmods/refinedstorage#3270]
### Describe your enhancement

I'd like to suggest a few improvements to the display mode and crafting process.

### The display

Currently a grid has three display modes:

- Normal: show items you have and crafting icons for those you don't.
- Only craftables: show only crafting icons for saved patterns, even for items that are in stock.
- Hide craftables: hide crafting icons and show only items that are in stock, but not if they can be crafted.

First of all, I'm not sure if the last one is intended, because it makes impossible to truly separate craftables and a plain inventory display. I don't see why "hide craftables" should hide the items you currently have. It should hide the crafting icons and only display all items in stock, so that you can neatly separate items and crafting icons with two grids (otherwise you can't).
Maybe it could also be useful a "show both" option, where both stocked items and crafting icons are shown together in order to fulfill both the purpose of displaying the content of your storage and crafting new items. The "normal" option only show the crafting icons for the items not present.

### The crafting UI

If you click a crafting icon, you are prompted to choose how many items you want to craft and then the system will tell you if the request is possible. I find this rather counter-intuitive because I generally have no idea how many items I can make in the first place. Possible ways to address this:

- Have a "craft all possible" option, that will calculate the maximum amount of currently craftble items or simply display such a number in the first window.
- Merge both windows together (the "pick how many items" and the "monitor" that tells you if the request is possible while displaying the available ingredients). This way I can increase and decrease the amount of items to craft and I have an immediate feedback on the expected result.

Independently of these, another useful thing would be displaying the "craft" text in red in a grid if it's not possible to craft any items at all.

**Comment by Darkere** [comment]
The first one is a bug. It should not be hiding craftable objects if they exist in storage. 


To the second question. It is not possible to predict perfectly how many items you are able to craft. Finding out how many are possible can also be quite expensive performance wise. 
All options you mentioned here are cool ideas but have potential to turn the entire experience into a lag fest, when more complex crafts get involved. That is why they don't exist.

**Comment by leviathan13** [comment]
Sure, I think performance should have the priority, but what about having those two windows "merged" or be displayed together to have a live feedback? Would that be possible? Or alternatively, what about just showing the stocked number of ingredients before without having the system calculate exactly how many items will be crafted. The player can then make an educated guess.

**Comment by Darkere** [comment]
To show the used materials we need to go through the crafting tree and basically calculate the entire thing. Doing that every time you change a number would cause issues on servers. 
Figuring out which ingredients are needed for this recipe requires the same thing.

**Comment by leviathan13** [comment]
There is also a much simpler solution to this... here's an example of the crafting process:

You make your crafting "order"

![crafting1](https://user-images.githubusercontent.com/19937699/161220180-513666d1-a9ef-44ef-abf7-0ce1f2ae25c0.png)

then get a "preview".

![crafting2](https://user-images.githubusercontent.com/19937699/161220286-53613665-ca43-479d-bbf7-3d0bea8317ab.png)

But if you want to change that "order", maybe because you don't have enough items or something like that, the cancel button will close the window and you will have to re-do the whole process again from the grid.

So... why not add a simply "back" or "edit" button that will re-open the first window so that you can adjust the numbers on the request? That should save a lot of time and clicking.

Sidenote: shouldn't the "available" in the preview window be "needed" instead? I have a lot more of bamboo stored. Maybe there should be both like

- needed: 2
- available: xxx

This way one can guess how many items they can craft.

**Comment by Renniuq** [comment]
Perhaps a good work around is, when calculating out a crafting request anyways, if there's not enough ingredients to complete the request, have it tell you how many it *could* make with the information it calculated right then, since the calculation is being done either way at that time? Rather than dynamically calculating a max possible all the time, or checking every time you make any craft request, only have it tell you the max when you make a request and it is too large for your current materials?

So, when it gives the list of what you have, and what it is missing, it could say something similar to "Requested: ****, Possible: ****", basically.

Hopefully that'd be a better middle ground between performance and usability.

**Comment by raoulvdberge** [comment]
While I don't understand the first request regarding "The display", I do agree with your analysis that you need to be able to tweak the amounts from the same screen @leviathan13 

This will be implemented for RS 2.
