### ISSUE TITLE
400.000 Iron suddenly bugged themselves into 400.000 of mekanisms refined alloy

### ISSUE THREAD

**Issue by derteufelqwe** [refinedmods/refinedstorage#3272]
### Describe the bug

My 400.000 Iron suddenly vanished and I instead have 400.000 enriched alloy now.

I was doing the following thing:
- Auto crafting a rather complex item
- Mid crafting I replace the receipe for mekanism enriched alloy
- I then canceled the crafting process
- -> I now have no Iron but 400.000 enriched alloy

### How can we reproduce this bug or crash?

As of now I have not found a way to reproduce this but I will try to

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.33

### What Refined Storage version is this happening on?

1.9.19

**Comment by raoulvdberge** [comment]
Sorry, I need reproduction steps.
