### ISSUE TITLE
Cable items improvements

### ISSUE THREAD

**Issue by leviathan13** [refinedmods/refinedstorage#3276]
### Describe your enhancement

Hello, I'd like to share some suggestions about cable items. Since these are small suggestions, I decided to collect them in a single post.

1. You should be able to access importer/exporters/external storages though covers. You currently can access them only by right clicking their "face", however that can be hard with a cover and a container in the way. If you could access their GUI just by right clicking the whole block, it would be much easier to set up and manage a cable system.
2. Cables and cables items should support objects like redstone components (levers), doors and lanterns, at least if they have a cover.
3. Exporters should have a priority order. For example, they should deliver items with the priority of the order of items in the filer row. This can be useful for example with fuel: you can filter a bunch of fuel items, and the exporter will try to deliver them in the order you specify. This way you won't waste precious items if cheaper items are available. Currently, items are selected at random if more than one item white-listed is available.
4. Filter items should work in the filter row of cable items (exporters, importers, external storage). Filter items are only used to create a filtered view in grid monitors, but what if they could be used as actual filters in other cable items? This would effectively increased the filter slots, allow more advances filter selection and also make it easier to "move/copy filters" between cable items.
5. Importers/exporters should interact with composters. Vanilla hoppers can interact with composters, therefore I think RS importers/exporters should too (they currently don't).
6. Constructors/destructors (or maybe importers/exporters?) should interact with cauldrons. Vanilla hoppers cannot interact with cauldrons, so you might want to keep cauldrons "uninteractable", but this would open new possibilities of automation (lava farms for example).
7. A grid monitor over a container (or connected to it in some other way) should open that container's inventory too. This way you could move items between you central storage and that container without being the "middle man" with your inventory. (I understand that this could be complicated to implement and not really important, but I'm just throwing it out there).
9. The Regulator Upgrade should work with importers and external storage too. For example:
- With exporters (current): keep a _minimum_ amount of specified items in the container.
- With importers: keep a _maximum_ amount of specified items in the container. Every items past that limit, will be collected. Therefore it will collect items only past that amount you specify.
- With external storage: it should do both things. You specify an amount, and the external storage will try to keep that amount in stock, but also collect any excess items. This can be useful to avoid a certain item to overflow the container in order to leave other slots for other items.

**Comment by raoulvdberge** [comment]
This issue is a bit chaotic, but some parts transfer over to RS 2.
