### ISSUE TITLE
Lighting issue

### ISSUE THREAD

**Issue by ZEROX7** [refinedmods/refinedstorage#3278]
### Describe the bug

wehn disk drive is placed to north east or west the disk drive turns dark south sides seem better but not right anyway
the drive has to be suranded by blocks
![image](https://user-images.githubusercontent.com/12628051/163623095-566b4737-ac67-4ce5-a244-356909df2b10.png)

### How can we reproduce this bug or crash?

place disk drive inside a wall

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

39.1.2

### What Refined Storage version is this happening on?

refinedstorage-1.10.1.jar

**Comment by Darkere** [comment]
Enable experimental lighting pipeline in the forge-client.toml config to fix.
