### ISSUE TITLE
no craft

### ISSUE THREAD

**Issue by Deskarato** [refinedmods/refinedstorage#3281]
### Describe the bug

When I want to craft, I put the same materials, but the item does not com
![2022-04-17_13 28 25](https://user-images.githubusercontent.com/59540324/163722595-5628979b-5ab8-4dcb-a519-3978fcafa284.png)
![2022-04-17_13 29 21](https://user-images.githubusercontent.com/59540324/163722597-fcb02057-06c3-4924-9090-dfe26eb4c368.png)
e there is evidence in the photos

### How can we reproduce this bug or crash?

I don't know how to solve the problem

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.052

### What Refined Storage version is this happening on?

refinedstorage-1.10.2.

**Comment by Darkere** [comment]
Report to your pack author. Something else is breaking the recipe.
