### ISSUE TITLE
World corruption after using copy paste gadget

### ISSUE THREAD

**Issue by JanThomas118** [refinedmods/refinedstorage#3291]
### Describe the bug

Using the copy paste gadget in creative mode to copy parts of an RS Network makes the game crash.
The game crashes every time one tries to join this world again

### How can we reproduce this bug or crash?

1. Place controller (use creative mode for everything)
2. Place importer on chest with a couple blocks distance
3. Connect importer with controller
4. Use copy paste gadget from building gadgets to copy the chest and the importer and a couple cables
5. paste it somewhere else (not connecting to old network)
6. Game crashes and world cannot be loaded ever again

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.29

### What Refined Storage version is this happening on?

1.9.17

### Relevant log output

```shell
https://0x0.st/oAqs.txt
```

**Comment by raoulvdberge** [comment]
Will be fixed by #3326

**Comment by raoulvdberge** [comment]
Hello. This bug has been fixed in v1.12.4 of Refined Storage. If this issue persists anyway, please feel free to create a new bug.

**Comment by raoulvdberge** [comment]
This bug has also been fixed in **v1.11.7** of Refined Storage for **Minecraft 1.19.2**. If this issue persists anyway, please feel free to create a new bug.

**Comment by raoulvdberge** [comment]
Hello, this bug is now also fixed for Minecraft 1.18.2 in v1.10.6.
