### ISSUE TITLE
Disk Drive lighting issue (Issue 530 & 970)

### ISSUE THREAD

**Issue by BonaireDreams** [refinedmods/refinedstorage#3292]
### Describe the bug

Blocks placed around disk drive make drive turn dark/black. Same as very old issue 530 and 970, except no Optifine installed. Initially discovered this in my custom modpack. Tried disabling the only 2 video mods I had (FPS reducer, & Better FPS, tried disabling my texture pack. None worked, then decided to rule out all mods.
Created a brand new Minecraft profile with only Refined Storage, no graphics mods, no texture packs.
Started a new word, placed a few disk drives. Single drives look fine, as soon as you start to place opaque blocks around them they go black.
![screenshot 7](https://user-images.githubusercontent.com/5133282/166126492-55898050-e4f7-43c2-8528-2617f24f6310.jpg)
![screenshot 8](https://user-images.githubusercontent.com/5133282/166126527-bd99a1e1-cfd9-4d59-b7df-94e3158fda11.jpg)
![screenshot 9](https://user-images.githubusercontent.com/5133282/166126529-6413f490-85c8-47f2-a48e-575d38038bed.jpg)
![screenshot 10](https://user-images.githubusercontent.com/5133282/166126531-9b7cf7c2-f500-42c7-a97f-be8063e53b47.jpg)
![screenshot 11](https://user-images.githubusercontent.com/5133282/166126739-182b7cf4-56cf-4e96-a44a-23d59494fc90.jpg)

As in previous reports, this also affects the disk manipulator, No other blocks appear to be affected.

### How can we reproduce this bug or crash?

Create minecraft world with only Refined storage
Place diskdrive
place opaque blocks around it

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.0

### What Refined Storage version is this happening on?

1.10.2

**Comment by raoulvdberge** [comment]
Forge issue. Turn on experimental lighting pipeline in the forge client config.

**Comment by BonaireDreams** [comment]
Excellent! That fixed it. Thank you.
For anyone needing to know how to adjust that setting. Find the forge-client.toml file in the config folder. Edit it with notepad and change the experimentalForgeLightPipelineEnabled = false to experimentalForgeLightPipelineEnabled = true.
![screenshot 12](https://user-images.githubusercontent.com/5133282/166127097-48613623-fc9c-4fee-90f1-57c83ed94d52.jpg)
