### ISSUE TITLE
[1.18.2] RS search not using JEI search correctly

### ISSUE THREAD

**Issue by ocram9** [refinedmods/refinedstorage#3293]
### Describe the bug

When you use the Refined Storage search with JEI synchronized search mode enabled it will type the text in the RS search field but not in the JEI field. This also happens when you type in JEI, it only shows up in the RS search field. This gets a little confusing when exiting the inventory, JEI shows the items of the previous search but the search field is empty.

JEI version: 1.18.2-9.7.0.194

### How can we reproduce this bug or crash?

1. Open a RS grid
2. Set search box mode to JEI synchronized or two-way
3. Search something in RS or JEI

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.0

### What Refined Storage version is this happening on?

1.10.2

**Comment by raoulvdberge** [comment]
This should be fixed now if you update JEI.
