### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by CanBoy67** [refinedmods/refinedstorage#3294]
### Describe the bug

When I go to start my 1.16.5 forge server I am unable to finish loading the server due to java.lang.Exception: Mod Loading has failed, I asked the folks over on the forge forums and they said that it was a refined storage error.

### How can we reproduce this bug or crash?

Start Server
Wait for a bit
server crashed

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.3.33

### What Refined Storage version is this happening on?

1.9.17

### Relevant log output

```shell
https://pastebin.com/vxtFRmZp
```

**Comment by Darkere** [comment]
pretty sure this is caused by mekanism addons
