### ISSUE TITLE
Crash when autocrafting [java.lang.IllegalStateException]

### ISSUE THREAD

**Issue by Gbergz** [refinedmods/refinedstorage#3295]
### Describe the bug

A player on our server was autocrafting when suddenly the server crashed.

### How can we reproduce this bug or crash?

Not sure, entirely but:
1. Autocraft
2. Wait.
3. Crash.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.0

### What Refined Storage version is this happening on?

1.10.2 | https://www.curseforge.com/minecraft/mc-mods/refined-storage/files/3712882

### Relevant log output

(Couldn't paste without using gist. too much text)
```shell
https://gist.github.com/Gbergz/6c274838154951ca4b0d14fe0b60c036
```

**Comment by Darkere** [comment]
Caused by whatever you've connected your external storage to. It's reporting that we can extract steel during simulation but not returning the item when not simulating. 

IMO we shouldn't crash though since that makes it difficult  to track down the actual problem.
