### ISSUE TITLE
:[Bug]: World Braking - FluidStack cannot be cast to class ItemStack

### ISSUE THREAD

**Issue by manmaed** [refinedmods/refinedstorage#3300]
### Describe the bug

Game Crashes When fluild is impoted into a Reborn Storage Disk and makes world unplayable

### How can we reproduce this bug or crash?

1. get system with item disks and reborn storage fluid disks
2. put importer on a tank
4. change impotert to mode fluid
5. Boom CRASH!

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.16

### What Refined Storage version is this happening on?

1.10.2

### Relevant log output

```shell
https://pste.me/v1/paste/SV45IfYmTGs/raw
```

**Comment by Technici4n** [comment]
The RebornStorage dev told you it's fixed in version 4.0.1, yet you're still running RebornStorage version 4.0.0.

**Comment by manmaed** [comment]
sorry attacted old crashlog new crash log here: https://pste.me/v1/paste/QlkfwHsd7yk/raw

**Comment by gigabit101** [comment]
Item will still have old nbt on it defining its old type, Should work fine in a new world, Not a lot I can do about old worlds

**Comment by Darkere** [comment]
If its just nbt shouldn't creating a new disk work?
