### ISSUE TITLE
Figured why I am getting double entries and crafting breaks...

### ISSUE THREAD

**Issue by batlham** [refinedmods/refinedstorage#3301]
### Describe the bug

With just JEI and RS installed I could auto-craft iron blocks to nuggets but then couldn't get the auto-crafter to go back to blocks. It would tell me I didn't have the materials. 
In my main game, I found one of my double entries. Auto-crafting only recognized one group and not the other.
They also don't stack in my inventory.
I exported my inventory with "save and load inventories"
28 : '{Count:1b,id:"compressed:cobbled_deepslate_i",tag:{}}',
29 : '{Count:1b,id:"compressed:cobbled_deepslate_i"}',
The problem always ends up being the empty tag entry.
If I put those in a chest the tag is stripped and they stack together.

Pretty sure it is this mod attaching the empty tag when crafting....

### How can we reproduce this bug or crash?

Auto-Craft from iron blocks to nuggets. The go back up. It usually happens. Using JEI to set the recipe usually always breaks auto crafting. Since it is not setting items with empty tag.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.19 also tried it 40.1.0

### What Refined Storage version is this happening on?

1.10.2

**Comment by batlham** [comment]
I went back to my testing instance today. I installed saveandloadinventories to look at what was going on. I couldn't cause the error with items not stacking... so don't know what caused it yesterday. Its the same world and everything except for the one extra info mod.
Going to keep messing with it...

**Comment by leviathan13** [comment]
Just FYI, it seems that RS doesn't really handle multiple patterns for the same output (given the example you made of _"Auto-Craft from iron blocks to nuggets. The go back up."_). See [this suggestion](https://github.com/refinedmods/refinedstorage/issues/3263). Though your issue seems to be different.

**Comment by batlham** [comment]
yes I know... I removed and put in new patterns to go up. currently trying to get it to do it again... it was constant yesterday... but not today :/

**Comment by batlham** [comment]
Don't know what the problem was in the test instance. I tried everything that was failing yesterday but now it works. I was able to auto-craft a crafter no worries. and it didn't say I was missing iron when I had stacks. :/
The blank tag never showed up so it must be another mod. I made a new instance and stated removing mods.. till the problem stopped. Fracking "Quark".. Today they released a update with note... "- Added experimental features to remove enchantments and fix a stacking issue with mods sometimes"  So now the tag thing has been fixed in my main game as well.  It wont fix items that have the blank tag on them you need to pull them out and put them in a chest... Also, crafting patterns have to be remade to remove the empty tag... sorry to have bugged you..
