### ISSUE TITLE
autocrafting not working with vanilla materials

### ISSUE THREAD

**Issue by Lewyfcb9pro** [refinedmods/refinedstorage#3302]
### Describe the bug

when I click on the pattern pattern to craft a blank pattern it doesn't work because it says that there is no redstone and no glass even though there is a stack of each in the storage

### How can we reproduce this bug or crash?

1.make a fully functional rs system with a crafter
2.set the pattern for anything that has vanilla materials
3.click on it to craft
4.it says that the vanilla materials aren't there

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.28

### What Refined Storage version is this happening on?

1.9.17

### Relevant log output

```shell
don't know if it helps but here is the modlist https://pastebin.com/vkP0LcwZ (sorry for it being messy I just used a manually triggered crash to get the modlist from the crash-report)

if you want the entire log I will send it in a comment not a pastbin thing but normal because it is above 512 KB

I would attach a video proof with a AE2 system too but the video is too big
```

**Comment by Lewyfcb9pro** [comment]
The issue you marked as a "duplicate" is something completely different because he cannot shift-click the recipe from jei on my side the autocrafting just doesn't work like completely with vanilla materials I would also attach a video but it's 91,6 mb which is too much for github

**Comment by Darkere** [comment]
upload to gifcat or youtube or something? Or make the video smaller...

The issue is likely the same. Some mod is causing random nbt on items this would also break autocrafting.

**Comment by Lewyfcb9pro** [comment]
https://youtu.be/d2yww9k3AJY here it is. If you know what is causing this issue please tell or which mod

**Comment by Lewyfcb9pro** [comment]
and also modlist is included in the pastebin link it's just a ctrl+c crash because I was to lazy to type every single mod

**Comment by Darkere** [comment]
I see. Since the issue is also present in AE, that means that this is certainly not an issue within RS. 

If I had to guess, I would point at Electrodynamics, since they've caused problems before, but that is just an unsubstantiated guess. 

Binary search disabling mods will likely get you to the culprit the fastest (though keep in mind the problem could be on the items in the storage). 

Regardless, not an RS issue.

**Comment by Lewyfcb9pro** [comment]
nope Electrodynamics didn't cause this but the AE thing I noticed it only while filming the Vid (tested AE for different things before this) and can you also give me a hint on which mod/mods can be causing this issue
