### ISSUE TITLE
Syngas will not import into advanced generators with any part of refined storage

### ISSUE THREAD

**Issue by SpiderKraken** [refinedmods/refinedstorage#3305]
### Describe the bug

i can pull syngas out of the syngas producer but it will not go into the fluid intake valve with importers, fluid interfaces (which work on the output dont register as connected to the intake

### How can we reproduce this bug or crash?

connect to a syngas producer via the fluid output block. use fluid storage block or preferred method to store. now try to connet it to the fluid intake on a gas turbine. it will not register as connected so no syngas moves into the generator

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.19

### What Refined Storage version is this happening on?

1.10.2

**Comment by Darkere** [comment]
None of what you wrote make sense....

Can you post a screenshot of what isn't working?

**Comment by SpiderKraken** [comment]
there would be no point in a screenshot as no configuration of  blocks works. i know how to use refined storage it works everywhere else but its weird here the only way i can explain it is that the fluid intake  on advanced generators only work on the syngas machine and the heat/steam machine. if i try to put those to fuels into the steam turbine or the gas turbine the fluid inputs do not register any of the connections from refined storage. so you cannot push these fluids into the machines that make power. i tried using refined storage, xnet, pipez.  it works with xnets mekanism add on only but i dont want mekanism installed just for one task.

**Comment by SpiderKraken** [comment]
so either refined storage is not giving the correct triggers to the machine  ( which i doubt) or theres some weirdness between all these mods includin refined storage and advanced generators fluid input

**Comment by Darkere** [comment]
From what it looks like, Advanced Generators will only output to blocks that can contain fluid, which would be a bug in advanced generators. 

Placing a fluid interface directly next to a fluid outlet works. 
Exporter on fluid input also works without problems.
