### ISSUE TITLE
Pattern clearing machine or recipe.

### ISSUE THREAD

**Issue by shale1337** [refinedmods/refinedstorage#3313]
### Describe your enhancement

Self explanatory, one of the bugs (that I'm gonna open issue on) made a huge mess out of hundreds of patterns and I would like to do them over again rather than trying to find proper patterns in my inventory, most of them are also obsolete so I'd like to have a way to clear them so they could be overwritten through pattern grid.

I know that I can slot them in but that sadly not an option because written patterns don't stack.

**Comment by Darkere** [comment]
Shift rightclick with pattern in hand

**Comment by shale1337** [comment]
> Shift rightclick with pattern in hand

I have hundreds of them in the grid. It's not really practical, sadly.

**Comment by raoulvdberge** [comment]
Don't really like the idea, since you won't end up with that much obsolete patterns in a normal playthrough.
