### ISSUE TITLE
Sort option in Crafter Manager doesn't work in intended way.

### ISSUE THREAD

**Issue by shale1337** [refinedmods/refinedstorage#3314]
### Describe the bug

Very destructive interaction with [Inventory Profiles Next](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next) where sorting happens through all of the crafters instead of all of them separately. 

In worst case the sorting feature should be disabled just like it's disabled in crafters themselves. 

### How can we reproduce this bug or crash?

1. Open Crafter manager. 
2. Click "Sort" from Inventory Profiles Next 
3. Have all the items move around between different crafters instead of being sorted inside of each of them.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.20

### What Refined Storage version is this happening on?

1.10.2

**Comment by raoulvdberge** [comment]
Thanks for the report, but this is really on inventory profiles next to fix. I can't add support for every sorter mod out there.
