### ISSUE TITLE
Add to Modrinth Repository

### ISSUE THREAD

**Issue by ruwey** [refinedmods/refinedstorage#3316]
### Describe your enhancement

This isn't exactly a feature in a game play sense but, now that CurseForge is making it harder to use their API for third party launchers, I think that it would be worth adding this mod to the [Modrinth](modrinth.com) repositories. They have a gradle plugin called [minotaur](https://github.com/modrinth/minotaur) so adding it shouldn't be too bad. 

Thanks for all your work on this mod!

**Comment by raoulvdberge** [comment]
Not planned for now.

**Comment by raoulvdberge** [comment]
@ruwey  It's now available on Modrinth: https://modrinth.com/mod/refined-storage
