### ISSUE TITLE
The problem of displaying templates for the autocraft request

### ISSUE THREAD

**Issue by AmoReeves** [refinedmods/refinedstorage#3317]
### Describe the bug

When the template is placed in the collector, and there is already a certain amount of the item being created in the system, then it is impossible to request more. Is there any way to fix this. I can 't choose the version of the muldshi . so I will write here the minecraft version 1.12.
![Base-Profile-2022 06 03-01 23 35 01](https://user-images.githubusercontent.com/103487040/171700420-b17a000e-3500-4ca9-a8f0-ef3046f35cd4.gif)
2

### How can we reproduce this bug or crash?

Open RS Storage Systems

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

14,23,5,2860

### What Refined Storage version is this happening on?

1.16.6

**Comment by Darkere** [comment]
https://refinedmods.com/refined-storage/wiki/grid.html

**Comment by AmoReeves** [comment]
Thanks, I just couldn't find these hotkeys.
