### ISSUE TITLE
[Distribution request] Modrinth upload

### ISSUE THREAD

**Issue by LuciusV** [refinedmods/refinedstorage#3318]
### Describe your enhancement

Hi,
AE2 is on modrinth, why you wouldn't add RS to there as well please. 
No doubt community will want more and more  mods there
I've seen https://github.com/refinedmods/refinedstorage/issues/3316, please think again.

**Comment by raoulvdberge** [comment]
I've thinked again, still not planned.

**Comment by LuciusV** [comment]
It's up to you but I don't really get your logic. Because of the recent events regarding CurseForge's controversial changes modded Minecraft community should support independent mod hosting platforms whenever possible.

**Comment by raoulvdberge** [comment]
@LuciusV  It's now available on Modrinth: https://modrinth.com/mod/refined-storage
