### ISSUE TITLE
Remove Storage Disk from Disk Drive without permission

### ISSUE THREAD

**Issue by luo-2233** [refinedmods/refinedstorage#3319]
### Describe the bug

In the case that Security Manager is configured in Refined Storage, an unprivileged person can still use the funnel to remove the Storage Disk from the Disk Drive.

### How can we reproduce this bug or crash?

1.Configure Security Manager（Put an unbound and unauthorised Security Card）
2.Let unauthorised people place Hopper under Disk Drive

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.35

### What Refined Storage version is this happening on?

1.9.17

**Comment by luo-2233** [comment]
I found it on the server, the server takes the forge core

**Comment by raoulvdberge** [comment]
Not really possible to fix.
