### ISSUE TITLE
Enhance integration with other mods by using direction in NetworkNodeListener.discoverNode 

### ISSUE THREAD

**Issue by Crimix** [refinedmods/refinedstorage#3323]
### Describe your enhancement

**What I have been trying and observed**
I have been trying to use an capability with `INetworkNodeProxy` with a sided block, but when `NetworkNodeListener` finds nodes in `discoverNode` it loops though all the directions to find the blocks relative to it to ask for the capability.
But it does not pass the opposite direction to the call asking for the capability so only if the block answers to a direction `null` 
will it work.

**My idea**
To facility better intregration between mods and refined storage it would make sense to pass the direction to the call asking for the capability, mods that does not use the direction will still work, but others mods that has a sided block config will now work with refinded storage.

So far as I can see, the places in the code that should be changed to facility this is `NetworkNodeListener.discoverNode` and `NetworkUtils.getNodeFromBlockEntity`, but I think you know that better than me. The only testing I have done of this is to change the proxy inside `NetworkUtils.getNodeFromBlockEntity` in a breakpoint to see it work at a glance in my development enviroment.

**Comment by raoulvdberge** [comment]
Will go most likely in RS for 1.19.3 as this breaks api.

**Comment by raoulvdberge** [comment]
This has been fixed for RS 2 .
