### ISSUE TITLE
Snea+right click not working for 256k storage disks

### ISSUE THREAD

**Issue by TheDireWolf13** [refinedmods/refinedstorage#3327]
### Describe the bug

Trying to disassemble extra disks and works fine with 64K and lower but not 256K or higher.

### How can we reproduce this bug or crash?

craft 256k sotrage disk.
attempt to shift+right click to break apart

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.52

### What Refined Storage version is this happening on?

1.10.2

**Comment by Darkere** [comment]
256k disks are not part of RS
