### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by Arakken** [refinedmods/refinedstorage#3330]
### Describe the bug

When using a constructor/destructor in a compact machine on radioactive waste barrels from mekanism, they appear to be duping themselves. The barrels are quantum entangled and the system was only given 2 waste barrels to begin with. This is happening inside the ATM 7 modpack.
![setup](https://user-images.githubusercontent.com/108599399/177022182-ec2275b6-9446-4931-bb42-6c9fa5e40cc5.png)
![waste](https://user-images.githubusercontent.com/108599399/177022183-d817140a-96e3-4787-af93-87ec5c0f6573.png)
 

### How can we reproduce this bug or crash?

1. setup refined in a compact machine
2. setup constructors and destructors for nuclear waste from mekanism fission reactors

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

1.18.2-forge-40.1.31/forge

### What Refined Storage version is this happening on?

1.10.2

**Comment by raoulvdberge** [comment]
This was fixed in v1.10.3
https://www.curseforge.com/minecraft/mc-mods/refined-storage/files/3921390
