### ISSUE TITLE
Panel-type interaction blocks

### ISSUE THREAD

**Issue by AerosAtar** [refinedmods/refinedstorage#3331]
### Describe your enhancement

I would like to make the following enhancement suggestions:

1. Change the following cable blocks to instead be 'panels' that connect to a single cable face:
- Exporter
- Importer
- External Storage
- Constructor
- Destructor

All panels in (1) would allow for (hollow) covers to be placed on the same face without removing their ability to interact with the connected block.

2. Add panel versions (as above) of the following and allow 1:1 crafting between the two versions (block and panel) for each: 
- Crafter
- Interface
- Fluid Interface
- Grid
- Crafting Grid
- Pattern Grid
- Fluid Grid
- Crafting Monitor
-  Crafting Manager
- Storage Monitor
- Security Manager
- Detector

All panels in (2) would allow for covers (regular and/or hollow) to be placed on the same cable face, and would sit flush with the cover (so the screen would appear to be embedded in the cover's block type), otherwise screen-type ones would default to a full-block texture for that face (i.e. how the blocks currently appear on the screen face). The detector panel would have a small default texture, and be hidden by a cover.

3. Allow Network Transmitters to connect to multiple Network Receivers, saving users some space when setting up multi-location networks. I suspect this one would be more complicated than the previous two, and personally consider it lower prioity on my wish list.

The above ideas mostly came from how AE2 currently handles things. However, RS is a far superior storage solution in my opinion and I would therefore love to see it have these. This would allow for much more streamlined and compact setups for players, as well as allowing them more choice around aesthetics and the like.

I also feel like these would be a good companion with #3276.

**Comment by raoulvdberge** [comment]
Not gonna do this.

**Comment by AerosAtar** [comment]
While I won't argue the decision (it's your mod, not mine), could I at least know the reason for it being rejected?
