### ISSUE TITLE
Autocrafting Alternatives: Textbox input

### ISSUE THREAD

**Issue by MagisterXero** [refinedmods/refinedstorage#3333]
### Describe your enhancement

Please, please consider this one...
<img src="https://i.imgur.com/AhololZ.png" />

Sometimes a modpack maker adds just a bit too many items to a tag.
When this happens, it takes literal minutes to find an oredict tag that should be simple to find under normal circumstances.

This could all be simplified by just inserting a textbox into the GUI to allow users to directly specify the tag/oredict they are looking for. Not necessarily asking for it to filter the tags for the item in question (though that might also be nice) but at least specifying specific tags would suffice. I can't seriously be the only person who has encountered this issue in a large, well-made modpack.

**Comment by Darkere** [comment]
Might be an option to make showing the items in the tag optional

**Comment by raoulvdberge** [comment]
Hi! Thanks for the suggestion. This has been added to the RS 2 tracker, and will be implemented for RS 2.x. 

Closing this issue for RS 1.x on this repository.

**Comment by raoulvdberge** [comment]
@MagisterXero  Thank you for the suggestion, this is how it looks like in RS 2 now:
![image](https://github.com/user-attachments/assets/782fe860-b68e-4c13-ba3e-6481ab8a5e5e)
