### ISSUE TITLE
Fluid from Thermal's Fluid Encapsulator in output instead input

### ISSUE THREAD

**Issue by Flachdachs** [refinedmods/refinedstorage#3334]
### Describe the bug

I want to create a Processing Pattern for the Fluid Encapsulator of the Thermal Series. When using JEI to insert the ingredients to the recipe the fluid is inserted into the output field instead of the input. This wouldn't be that much of a problem if not half of the fluids are not shown in JEI. So these fluids can't be pulled by hand into the input. Some of these fluids are for example the result of the Alchemical Imbuer (i.e. Potions). Also when activating the Fluids checkmark of the Pattern Grid the upper part above the recipes section stays in the item mode, you can't pull these fluids from there either.

On the other hand the recipes of the Bottling Machine of Immersive Engineering don't have this problem. The input fluid is correctly inserted into the input part. So this might be a problem that is caused by Thermal Series. However, it would be nice to be able to work around this problem. E.g. pulling the fluids from the upper part after switching to Fluids mode or being able to move fluids (and items) between input and output.

Secondary problem: when clicking a fluid in the Fluid Grid for which no filled bucket item exists the fluid gets lost and you'll get an empty bucket instead. The system should deny such an operation.

### How can we reproduce this bug or crash?

- Install a basic system 1.18.2 with newest versions of Forge, RS, Thermal Series and optionally Immersive Engineering.
- Select a recipe from the Fluid Encapsulator that fills a bucket or a glass bottle.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.54

### What Refined Storage version is this happening on?

1.10.2

**Comment by Darkere** [comment]
report to thermal. We just read from JEI

**Comment by Flachdachs** [comment]
What about the proposes general improvements?
