### ISSUE TITLE
Option to only allow processing pattern

### ISSUE THREAD

**Issue by PssbleTrngle** [refinedmods/refinedstorage#3335]
### Describe your enhancement

A config option the only allow pattern of the "processing" type to be created.
Would be great for modpacks that want to out-source regular crafting to a different machine, instead of just allowing to be done via the crafter

**Comment by raoulvdberge** [comment]
You should probably remove crafting recipes instead on the modpack level. This config option only seems useful for 1 percent of the users and we don't do config options in that case.

**Comment by Darkere** [comment]
Well removing the crafting recipes would presumably also break the other crafter that they want to outsource the crafting to. 

But I agree this seems a bit niche.

**Comment by raoulvdberge** [comment]
Would it, though? The other crafting that they're outsourcing to wouldn't use regular crafting recipes, right?

**Comment by Darkere** [comment]
If the other crafter doesn't use regular crafting recipes there would be no point in disabling crafting patterns as they already would need to be processing patterns then. 

Crafters like the multiblock crafter from create use the regular crafting recipes and just allow them to be used in their machine.

**Comment by PssbleTrngle** [comment]
Yes, I was only talking about removing the option the create pattern that ore not of the type "processing", so crafters can only be used to send items to other machines and not to craft items like a crafting table.
But I also understand that this is a very niche thing

**Comment by raoulvdberge** [comment]
Ah, now I understand. I was under the impression that "specialized" crafting machines have their own recipe types.

But still, it's a bit too niche. Could perhaps be solved by an addon that hooks into RS instead?

**Comment by PssbleTrngle** [comment]
I will look into solving it by creating an addon mod, but I am not sure if it would be possible without creating a mixin for the base  mod, which sounds like a bad solution

**Comment by Darkere** [comment]
It is possible without mixins... just 10x harder

**Comment by PssbleTrngle** [comment]
Not really sure how that would be possible looking at the code

**Comment by Darkere** [comment]
Replacing the entire pattern grid.

**Comment by PssbleTrngle** [comment]
I would rather have to replace the entire [GridScreen](https://github.com/refinedmods/refinedstorage/blob/75b24c1cc540e609be369797babe83d81a07b4af/src/main/java/com/refinedmods/refinedstorage/screen/grid/GridScreen.java#L160), which also sounds like a bad solution

**Comment by raoulvdberge** [comment]
Just changing the grid screen will probably suffice.
