### ISSUE TITLE
Crafting upgrade not auto crafting certain items

### ISSUE THREAD

**Issue by EricBuist** [refinedmods/refinedstorage#3336]
### Describe the bug

I am trying to automate Mekanism's metallurgic infusers uwing a Refined Storage interface to provide enriched materials. I tried to have an interface providing all the enriched materials, and use an XNet system to feed them to infusers, so infusers backstuff with a single enriched material instead of a stack. I created patterns for Enriched Redstone, Enriched Diamond, etc., installed the patterns in a crafter attached to an Enrichment Chamber, and if I manually auto-craft enriched materials, that works correctly. However, when I set an Interface to provide enriched materials, although I installed a crafting upgrade, Enriched Redstone doesn't auto-craft. It will export to the interface if there is enriched redstone in the system, but not auto-craft. It auto-crafts all the other enriched materials. I searched for more than 45 minutes, verifying the pattern again, again and again, and I cannot find anything wrong.

### How can we reproduce this bug or crash?

1. Create a pattern for Enriched Redstone, turning one redstone into one Enriched Redstone.
2. Attach a crafter to an enrichment chamber as input, and output to an exporter.
3. Verify that enriched redstone can be manually auto-crafted.
4. Attach an interface to the network, set the interface to provide one Enriched redstone, and add a crafting upgrade.
5. Observe that the interface is not provisionned with additional enriched redstone.

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.20

### What Refined Storage version is this happening on?

1.9.15

**Comment by Darkere** [comment]
Make sure that you are able to autocraft the exact amount the interface is missing. There are no attempts to craft less than that.

**Comment by EricBuist** [comment]
> Make sure that you are able to autocraft the exact amount the interface is missing. There are no attempts to craft less than that.

Interface provides just one Enriched Redstone, not many. I checked that several times.

**Comment by EricBuist** [comment]
Bug fixed itself when I logged back in, so I imagine it will be impossible to reproduce, so closing.
