### ISSUE TITLE
Game keeps crashing when right clicking crafting grid

### ISSUE THREAD

**Issue by Thelegendking** [refinedmods/refinedstorage#3338]
### Describe the bug

[crash-2022-07-14_16.58.14-client.txt](https://github.com/refinedmods/refinedstorage/files/9111405/crash-2022-07-14_16.58.14-client.txt)

### How can we reproduce this bug or crash?

1. Right click/Open Dyed crafting grid
2. Game freezes
3. Crash

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.35

### What Refined Storage version is this happening on?

refinedstorage-1.9.18

**Comment by raoulvdberge** [comment]
This doesn't seem to be caused by RS.
