### ISSUE TITLE
ether gas removed

### ISSUE THREAD

**Issue by iridium22** [refinedmods/refinedstorage#3339]
### Describe the bug

when i try to import ether gas from industrial forgoing it gets deleted and not imported to refind storage fluid drive 

### How can we reproduce this bug or crash?

import ether gas from tank through wireless network 

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.54

### What Refined Storage version is this happening on?

refinedstorage 1.10.2 aka direwolf20 1.18 version 1.7.0

**Comment by Darkere** [comment]
Do you have a sink connected to your system via external storage?

**Comment by iridium22** [comment]
yes ?

**Comment by Darkere** [comment]
Make sure you do not insert anything into that. It voids fluids.

**Comment by iridium22** [comment]
i have only a external storage

**Comment by Darkere** [comment]
Make sure it is set to only extract not insert...

**Comment by iridium22** [comment]
now it works ty
