### ISSUE TITLE
Disk drive assigns unique id to inserted drives without one

### ISSUE THREAD

**Issue by MemeticGitHubUser** [refinedmods/refinedstorage#3340]
### Describe your enhancement

I am using this mod along with create, and i figured out a way to expand my storage even farther, By using detectors, conveyors, and some redstone, I can make it so that the disk drive automatically swaps out all of the currently installed drives  for a fresh set when they completely fill up. and the full drives go to a chest. I thought I could make it even better when I autocrafted a thousand 1k drives and put them into a drive, which then I put it into the input of that autoswapping disk drive I made, but they didn't go in because they had no unique ID, which they obtain upon entering your inventory. Could you make it so disks without a unique ID get one upon entering a disk drive?
![image_2022-07-16_192111279](https://user-images.githubusercontent.com/40185397/179374846-0077e71a-ae4e-4a8a-9ec5-451d32d3f0a9.png)

**Comment by JoshuaRowePhantom** [comment]
Upvote 👍

**Comment by raoulvdberge** [comment]
The data on disks is stored separate from the disk item. This is stored in a registry stored on your world. If I populate the registry on crafting recipes, you can really easily spam the registry by just autocrafting.. which has a performance impact at some point. So, I believe requiring player input is actually a good thing here. 

I think your automation is admirable, but there are better options to have bulk storage.
