### ISSUE TITLE
[1.18.2] using the Grids search bar locks access to closing the menu with 'Esc' or the currently bound inventory key

### ISSUE THREAD

**Issue by popguy12** [refinedmods/refinedstorage#3341]
### Describe the bug

I just went through and updated a few mods alongside forge in this small pack, and all of a sudden the search bar in the grids just kinda breaks closing the window. I have no clue what could have caused this, and ive had to use JEI's search bar to get out of it, but in doing so now JEI will always close if the inventory key is pressed.
I dont know much about how a bunch of this stuff is coded, but my only thought is maybe this is somethin weird on Forges end? cause it all worked fine in 40.1.25
takin a look through the logs doesnt show anything out of the ordinary either.
i tried downgrading a few mods and Forge, messin around with configs, and still havent been able to get it fixed yet.

### How can we reproduce this bug or crash?

Pretty much just
1. Load RS with Forge 40.1.60
2. Open Grid, click the search bar
3. attempt to close the GUI using 'Esc' or the currently bound inventory key

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.60

### What Refined Storage version is this happening on?

1.10.2

**Comment by maxdudek** [comment]
Also having this issue ^

**Comment by maxdudek** [comment]
Workaround that we just found (assuming you have Quark): In Key Binds --> in the "Quark Misc" category, the Back button is bound to Mouse Button 4. This Key Bind lets you exit the menu

**Comment by Letaddl** [comment]
I have the same problem, I tried to install Quark but it broke the modpack

edit: i deinstalled debugify and it worked

**Comment by raoulvdberge** [comment]
I can't reproduce that.
