### ISSUE TITLE
Add a Configuration Card that will allow transferring configuration over to other RS components

### ISSUE THREAD

**Issue by tanyan-tanyan** [refinedmods/refinedstorage#3345]
### Context
In Mekanism, there is a configuration card item, which allows you to copy machine configuration, for example what side is output, input, and then redstone sensitivity, etc. It can then be used on other machines to transfer over the exact same configuration. This helps with building large-scale machine projects more efficiently. 

In other words, [shift + right click] with the card will copy configuration from "Infusing Machine 1", and [right click] will paste that configuration into "Infusing Machine 2".

### Suggestion
Add a Configuration Card to the mod. From my understanding of RefinedStorage, this card could copy configuration of the following components:
- Importer
- Exporter
- External Storage
- Disk Drive
- Storage Monitor
- Storage Block
- Constructor
- Destructor
- Detector
- Grid View Settings
etc...

Some ideas for what the Configuration Card could transfer over:
- Redstone Sensitivity [OFF/ON/PULSE]
- Mode [WHITELIST/BLACKLIST]
- Exact Mode [ON/OFF]
- Type [ITEMS/FLUIDS]
- Access Type [INSERT/EXTRACT/BOTH]
- Priority [NUMBER]
etc...

### Extra Request
If this is implemented, could you please add support for RS addons, such as the Requester and improved tiers of importers, exporters and others? Thank you in advance!

**Comment by raoulvdberge** [comment]
I quite like this idea.

**Comment by raoulvdberge** [comment]
Hi! Thanks for the suggestion. This has been added to the RS 2 tracker, and will be implemented for RS 2.x. 

Closing this issue for RS 1.x on this repository.

**Comment by raoulvdberge** [comment]
@tanyan-tanyan  Implemented for RS 2!
