### ISSUE TITLE
fluids being deleted in fluid disk. 

### ISSUE THREAD

**Issue by darkfang1989** [refinedmods/refinedstorage#3348]
### Describe the bug

video detail of problem:

https://youtu.be/YcFTLyfEDXI

seems to only happen when import/exporting that fluid, just sitting there doesnt seem to do anything. 

tried with different tiered import/exporters and default RS ones, same result. 

playing on ATM6, latest version. 

10G ram allowed, i7 6700k, SSD.

### How can we reproduce this bug or crash?

make storage

import/export fluids

keep constant import/export 

open/close grid/wireless grid. 

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.35

### What Refined Storage version is this happening on?

1.9.17

**Comment by starforcraft** [comment]
I think this will be fixed in the next Version from RS (This is probably happening because of integer overflow) Just put a External Storage on the sink
