### ISSUE TITLE
Items voidind on craft cancel if no more space left

### ISSUE THREAD

**Issue by TiphaineLAURENT** [refinedmods/refinedstorage#3349]
### Describe the bug

My use case is trying to craft an Infinite Storage Part.
I did have the resources before starting.

The craft get locked because there was not enough space to store the crafted part (I am using Mystical Agriculture so a few essences can easily get multiplied after crafted).
I cancel the craft and now that I want to restart it I am missing a lot of the needed resources. Best exemple are the quartz essences which I am now needing ~700 000.

I don't know if it is relevant but I am playing AllTheMods7

### How can we reproduce this bug or crash?

1. Start a big craft with a nearly full storage
2. Once the disk are full but the craft not finished cancel it

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.60

### What Refined Storage version is this happening on?

1.10.2

### Relevant log output

```shell
-
```

**Comment by raoulvdberge** [comment]
Ok, but where should the items go if there is no space? Drop on the ground?

**Comment by TiphaineLAURENT** [comment]
A simple fix would be to display an error on the craft status informing the user that there is no space left and he should add more but if he cancel it, items will be voided.

The complex option would be to precalculate the space needed before the craft and not start it if it is not possible. I am not really sure if it is possible in term of time. Maybe enable the check with a ingame toggle also informing the user about the risk of not checking ?

**Comment by Darkere** [comment]
I think it would be reasonable if we prevented users from cancelling a task if there is not enough space. Just need to figure out a way to make that transparent to users.

**Comment by raoulvdberge** [comment]
This has been added to the RS 2 tracker, and will be implemented for RS 2.x.

Closing this issue for RS 1.x on this repository.
