### ISSUE TITLE
System shuts down if it is using more than 16k FE/T

### ISSUE THREAD

**Issue by lyssar** [refinedmods/refinedstorage#3350]
### Describe the bug

I am not completly sure if this is a bug of the System.
When my system is consuming more than 16000 fe/tick the controller stops working and shuts down the system even if he hast 32000 internal and a production attached which is fast enough to add more than 16k fe/t into the system.
It feels like a bug and if not I would like to see a possibility to enlarge the controller FE storage.

### How can we reproduce this bug or crash?

1. build up a system with crafters, importer etc to reach more than 16k fe/t
2. Controller will shut down

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.60

### What Refined Storage version is this happening on?

1.10.2

**Comment by Darkere** [comment]
You can increase the buffer of the controller in the config

**Comment by lyssar** [comment]
This dont answer my bug question at all @Darkere - if the buffer has 32k and I consume 16001 fe/t why the system shuts down if my input is > 16001 fet/t

**Comment by Darkere** [comment]
Your power source only produces power every second (or more) ticks. This means the system will run out of power as RS does consume the 16k fe/t every tick. 

Increasing the buffer will fix the issue.

**Comment by lyssar** [comment]
That is not correct. Mekanism Cables are transfering at base rate 32k/t not per second. I used the elite cable (406k/t transfer) and they have there own internal storage so you "fill" the cable.
The energy is not an issue an you can see a "flicker" of the controller which is produced more than once a second so the energy is provided per tick noch per second

**Comment by Darkere** [comment]
> Mekanism Cables are transfering at base rate 32k/t not per second

Mekanism cables have optimizations in place. They will say they are transferring 16kfe/t but are actually transferring 32kFe/2t.

This is good. Saves on performance. And generally most blocks have enough buffer to run through that without a problem. The default RS values are just not set up for such high power consumption.

**Comment by lyssar** [comment]
Sure it is but than they should document that better :D 
So yeh the only solution is to raise the limit of the controller. Surely this is just an issue with modpacks using additional items like from RSInfinityBooster mod for the wirless transmission (which leads to a 12k / ti consumption). So these Modpacks should raise there default values

**Comment by Nevrai** [comment]
I was about to report this. I’m having the same issue, and it’s incredibly frustrating. I’ve talked to others who have the same issue as well.

I can confirm that raising the buffer in the config file solves the issue. This is such a glaring issue that, in my opinion, the buffer should be raised in the mod by default. Either that or making some other sort of fix, such as making the controller consume 16k every other tick rather than every tick.

**Comment by raoulvdberge** [comment]
Modpacks should just increase the buffer size. 

Either way, this bug is solved in RS 2. There, multiple controllers on a single network are allowed to increase the buffer.

**Comment by Nevrai** [comment]
That sounds promising. RS2 isn’t available yet, correct? Is there anywhere I can follow its development? The page linked [here](https://www.reddit.com/r/feedthebeast/comments/nff3st/announcing_refined_storage_2/) is no longer available.

**Comment by Darkere** [comment]
https://github.com/refinedmods/refinedstorage2

There are some early versions you can use.
