### ISSUE TITLE
Wireless Upgrades shutting down system

### ISSUE THREAD

**Issue by Dragkin920** [refinedmods/refinedstorage#3351]
### Describe the bug

Playing ATM7 had the infinite range and Dimension cards in my wireless transmitter all the sudden system shut down found that if i removed the Dim card system would work again.  4 days later same thing happened took the range upgrade out to make system work again now I have no wireless.

### How can we reproduce this bug or crash?

Not Sure what is wrong and cant find relevant info to be able to reproduce

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

Not Sure should be most recent

### What Refined Storage version is this happening on?

refinedstorage-1.10.2.jar

**Comment by raoulvdberge** [comment]
Sorry, I can't do much with this report.
