### ISSUE TITLE
Compact numbers in Crafting Monitor

### ISSUE THREAD

**Issue by Leclowndu93150** [refinedmods/refinedstorage#3355]
![image](https://user-images.githubusercontent.com/73310949/183609140-2e3809ea-6584-4a7f-ab3f-860d0ac7c8e0.png)

**Comment by raoulvdberge** [comment]
Hi! Thanks for the suggestion. This has been added to the RS 2 tracker, and will be implemented for RS 2.x. 

Closing this issue for RS 1.x on this repository.
