### ISSUE TITLE
Crafter manager displaying crafters incorrectly

### ISSUE THREAD

**Issue by Nevrai** [refinedmods/refinedstorage#3358]
Patterns are not showing up where they should be in the crafter manager. For example, as you can see in the screenshot below, the plank patterns I have in my precision sawmill show up under the metallurgic infuser, and the ingots I have in my chemical injection chamber and the bucket of creosote oil I have in my fluid encapsulator all show up under the precision sawmill. The osmium compressor and enrichment chamber crafters also appear to have no patterns, yet they do.

This affects almost every crafter. The patterns _are_ in the crafters they should be in, but they show up incorrectly in the crafter manager. I can still take out patterns and put patterns in; it’s just a visual issue. If I put a pattern under the metallurgic infuser next to the planks, they go in my precision sawmill. However, this still makes it incredibly difficult to use the crafter manager.

This wasn’t an issue from the beginning but has been an issue in my world for a while now. Breaking the crafter manager and placing it back down didn’t solve the issue, and neither did making a new crafter manager. Breaking one of the crafters and placing it back down doesn’t fix anything either.

![Crafter manager bug](https://user-images.githubusercontent.com/59761487/185761694-cea9205d-56bf-47ca-b77b-5822f25fd103.png)

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/) (version 0.4.26—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Refined Storage:** 1.10.2

**Comment by raoulvdberge** [comment]
We need better reproduction steps. Ideally, try to reproduce this on a save with just RS and send it to us. Only then it's actionable.
