### ISSUE TITLE
Server crashes when connecting an external storage to an inventory with a lot of items or liquid

### ISSUE THREAD

**Issue by Nevrai** [refinedmods/refinedstorage#3359]
The server crashes when putting an external storage on an inventory with an exorbitant number of items or a large amount of liquid. When this happens, you can’t interact with anything, and the game freezes if you leave the world, so you have to restart the game. Upon relogging, it’s rolled back, so it’s impossible to put down the external storage. I’ve tried this three times, and it happened each time.

This happened when putting an external storage on a [Sophisticated Storage](https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage) barrel with about 40 thousand raw iron in it, and it also happened when putting an external storage on a [Mekanism](https://www.curseforge.com/minecraft/mc-mods/mekanism) dynamic tank with 465,850 buckets of brine in it. This doesn’t happen when using external storage on inventories with fewer items or less liquid. It also doesn’t happen when connecting external storages to [Functional Storage](https://www.curseforge.com/minecraft/mc-mods/functional-storage) drawers with millions of items.

This was in a single-player game.

### Screenshots

<details>
  <summary>Screenshots (click to expand)</summary>

**The barrel I tried putting an external storage on:**
  
![barrel](https://user-images.githubusercontent.com/59761487/185773244-2bac3905-f3e6-47c9-8352-858cc62d2776.png)

**The dynamic tank I tried putting an external storage on:**

![2022-08-21_04 47 28](https://user-images.githubusercontent.com/59761487/185773222-7dcd1894-1dcb-4e8a-9130-933ef3dce8ae.png)
  
</details>

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/) (version 0.4.26—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Refined Storage:** 1.10.2

**Comment by DeleteMetaInf** [comment]
My server crashed again when putting a creative edxporter from [Cable Tiers](https://www.curseforge.com/minecraft/mc-mods/cable-tiers) onto a [Functional Storage](https://www.curseforge.com/minecraft/mc-mods/functional-storage) controller connected to several drawers with a total of over 17 million items in them. There was also an external storage on this controller. I tried it again after restarting, and it happened again.

It seems like Refined Storage cannot handle external storage on an inventory with millions of items in one spot, even if it’s a storage drawer.

**Comment by DeleteMetaInf** [comment]
My server crashed again when putting a creative edxporter from [Cable Tiers](https://www.curseforge.com/minecraft/mc-mods/cable-tiers) onto a [Functional Storage](https://www.curseforge.com/minecraft/mc-mods/functional-storage) controller connected to several drawers with a total of over 17 million items in them. There was also an external storage on this controller. I tried it again after restarting, and it happened again.

It seems like Refined Storage cannot handle external storage on an inventory with millions of items in one spot, even if it’s a storage drawer. This was in the latest version of RS, 1.10.3.

**Comment by Nevrai** [comment]
My server crashed again when putting a creative edxporter from [Cable Tiers](https://www.curseforge.com/minecraft/mc-mods/cable-tiers) onto a [Functional Storage](https://www.curseforge.com/minecraft/mc-mods/functional-storage) controller connected to several drawers with a total of over 17 million items in them. There was also an external storage on this controller. I tried it again after restarting, and it happened again.

My system also won’t export any more raw copper to my drawer when it has 4.6M raw copper in it, even though I have 3.1M more raw copper in my system.

It seems like Refined Storage cannot handle external storage on an inventory with millions of items in one spot, even if it’s a storage drawer. This was in the latest version of RS, 1.10.3.

**Comment by Darkere** [comment]
If only there was a template that gave us the relevant info for debugging things

**Comment by Nevrai** [comment]
Okay. Apologies. Resubmitted this issue with steps to reproduce: #3360.
