### ISSUE TITLE
Disk drives and disk manipulators have improper rendering

### ISSUE THREAD

**Issue by Nevrai** [refinedmods/refinedstorage#3362]
### Describe the bug

Disk drives and disk manipulators appear far too dark. This has been a problem since I started playing 1.18.2 and was also a problem back in 1.12.2. It happens with and without shaders enabled. It may be an incompatability with [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) or [Starlight](https://www.curseforge.com/minecraft/mc-mods/starlight-forge), which are installed, but I don’t know.

![2022-08-23_16 26 14](https://user-images.githubusercontent.com/59761487/186184366-70187298-a540-4182-96fe-f125ad559b9f.png)

### How can we reproduce this bug or crash?

1. Place a disk drive or disk manipulator

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/) (version 0.4.27 [latest])
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Refined Storage:** 1.10.3 and 1.10.2

**Comment by raoulvdberge** [comment]
Turn on forge experimental rendering. Fixed for 1.19 too.

**Comment by Nevrai** [comment]
@raoulvdberge I had already tried that, but unfortunately, it did not work. Not only did it result in my fps reducing to about 3 frames per second with shaders on, but it also did not fix this rendering issue (even without shaders enabled).

Are you going to fix this in the 1.18.2 version? Would be much appreciated!

**Comment by raoulvdberge** [comment]
Are you using optifine or any rendering mods? Probably, as you have shaders. I don't think it's supported in that case.

I won't be backporting fixes.
