### ISSUE TITLE
Refined  GUI scale

### ISSUE THREAD

**Issue by Jin16** [refinedmods/refinedstorage#3364]
### Describe the bug

![2022-08-27_00 17 48](https://user-images.githubusercontent.com/20618588/187032099-f694e691-f25b-4e11-9fac-0bdb35c1511e.png)
is there a way to change/ fix the GUI scale

playing a mob pack called Encrypted_ version 2.1

this maybe another mod that is interfering 

### How can we reproduce this bug or crash?

N/A

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.73

### What Refined Storage version is this happening on?

1.10.3

**Comment by raoulvdberge** [comment]
I don't see the problem

**Comment by Jin16** [comment]
> 

look at where the box where it say "sorting type" is should it not be close to the interface is

**Comment by raoulvdberge** [comment]
![image](https://user-images.githubusercontent.com/10358424/193250411-ab55f8d6-67d1-487f-bcc2-6c528ea0fc27.png)


Sorry, can't reproduce it.
