### ISSUE TITLE
[Bug] Fluid recipes only pass a singular fluid 

### ISSUE THREAD

**Issue by CKY-** [refinedmods/refinedstorage#3366]
### Describe the bug

Auto crafting with fluids 
When trying to craft with fluids, only the first fluid is passed into a tank, yes tanks can only hold one type of fluid  but once the tank is empty  the next fluid should be passed.. 

adding a crafter to  a tank or to tinkers smeltery input port  should result in all fluids to be added to the object in question if there is enough room. Not the first fluid..  

### How can we reproduce this bug or crash?

add a recipe to a crafter that has more than 1 fluid  
have it transfer both fluids into a tank of any kind 
remove the fluid from that tank as quickly as possible.
the next fluid will not be added tank.  

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.68

### What Refined Storage version is this happening on?

1.10.3

### Relevant log output

```shell
there is no Log
```

**Comment by raoulvdberge** [comment]
@Darkere  Do you know anything about this?

**Comment by Darkere** [comment]
Similar to items, if you have multiple fluids you want to insert with crafting you need to have something that accepts multiple fluids at once.

**Comment by raoulvdberge** [comment]
Ah, works as intended then.

**Comment by CKY-** [comment]
> Similar to items, if you have multiple fluids you want to insert with crafting you need to have something that accepts multiple fluids at once.

and tinkers smeltery accepts multiple fluids at once

**Comment by CKY-** [comment]
> Ah, works as intended then.

No its not working as intended, if it were then the smelter and other tanks would accept the fluids when crafting not just the first fluid.  

![image](https://user-images.githubusercontent.com/8982158/193272042-36df0b60-c05d-4721-a542-a02448a59a25.png)

![image](https://user-images.githubusercontent.com/8982158/193272247-3ca597f1-0682-4649-bf6a-11a9d9a917cd.png)

![image](https://user-images.githubusercontent.com/8982158/193272851-5c6db77a-5b23-4db8-8df0-66972c340109.png)

**Comment by Darkere** [comment]
hmm it should not be inserting anything... you are right.

**Comment by CKY-** [comment]
And it magically works in a single player with forge version 40.1.80 -_- sorry to have bothered you both keep up the amazing works that you do 
![image](https://user-images.githubusercontent.com/8982158/193277425-a3e83f05-ef7b-4434-8a70-b5e5347cb0e1.png)


my apologies i have not revisited this in a month but have been keeping up to date on all things related

**Comment by CKY-** [comment]
This however is not working on a server? what's the difference?
