### ISSUE TITLE
Fluorite and charcoal block (Mekanism) cable covers have a broken texture

### ISSUE THREAD

**Issue by Nevrai** [refinedmods/refinedstorage#3367]
### Describe the bug

Cable covers, both regular and hollow, made with [Mekanism’s](https://www.curseforge.com/minecraft/mc-mods/mekanism) fluorite or charcoal blocks have a broken texture. This didn’t used to be the case, but this suddenly started happening recently, as I noticed it with my existing fluorite block hollow covers that I had placed before and were working just fine before. I haven’t updated Refined Storage or Mekanism as I’m already on the latest versions for 1.18.2, so I don’t know why this suddenly started happening. This issue does not occur with cable covers made with other blocks. I’ve only noticed it with Mekanism’s fluorite and charcoal blocks. Even cable covers made with Mekanism’s fluorite ore appear normally.

For the record, this _did_ start happening after I updated from Forge 40.1.68 to 40.1.69, so that might have something to do with it; I’m not sure.

### Screenshots

![2022-08-31_06 47 10](https://user-images.githubusercontent.com/59761487/187595615-d469c6bd-d3b2-4451-afca-9dc9bdb34dc1.png)

![2022-08-31_06 46 58](https://user-images.githubusercontent.com/59761487/187595620-0529311e-d919-43f6-a327-dd7d54cbfa6b.png)

![2022-08-31_06 49 20](https://user-images.githubusercontent.com/59761487/187595674-77a85d72-6d23-4948-8043-249313fca68b.png)

### How can we reproduce this bug or crash?

1. Craft a cable cover or hollow cable cover made from fluorite or charcoal blocks from Mekanism.
2. Place it on a Refined Storage cable.

### Versions

* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.29 [latest])
* **Minecraft:** 1.18.2
* **Forge:** 40.1.69
* **Refined Storage:** 1.10.3 (latest)
* **Mekanism:** 10.2.5.465 (latest for 1.18.2)

**Comment by raoulvdberge** [comment]
> For the record, this did start happening after I updated from Forge 40.1.68 to 40.1.69, so that might have something to do with it; I’m not sure.

 Can  you verify that?

You seem to be using some rendering enhancing mods. What happens if you disable those?

**Comment by raoulvdberge** [comment]
Closing due to lack of reaction.
