### ISSUE TITLE
Unable to select all in JEI search bar when using RS grids

### ISSUE THREAD

**Issue by MarioSMB** [refinedmods/refinedstorage#3368]
### Describe the bug

For reference, this was reported on the JEI tracker and it was suggested that I report the issue here for a collaborative solution: https://github.com/mezz/JustEnoughItems/issues/2975  

When using a grid or crafting grid in regular search mode, backing out of the grid's search bar and using JEI's search bar instead, one is unable to use CTRL+A to select all the text in JEI's search bar, the cursor just goes to the end of the text.

### How can we reproduce this bug or crash?

1. Enter some text in JEI's item search bar
2. Access a RS grid and escape from the grid's search bar
3. Click on JEI's search bar
4. Press CTRL+A to select all

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.68

### What Refined Storage version is this happening on?

1.10.3

**Comment by razgriz5000** [comment]
I don't think this has anything to do with Refined Storage as I have the same problem with JEI in ATM7 To The Sky which does not have refined storage as a mod.

**Comment by raoulvdberge** [comment]
See the above.

**Comment by MarioSMB** [comment]
So both ends are saying this isn't their problem... I suppose I'll be reporting back to the JEI side of things hoping for a solution.
