### ISSUE TITLE
Hide certain tags

### ISSUE THREAD

**Issue by Testing123-svg** [refinedmods/refinedstorage#3370]
### Describe your enhancement

Could you please add a feature to add certain tags when selecting alternatives in processing recipes in the pattern grid?

I am using Minecolonies as well and minecolonies adds tags where almost every block is added. It makes setting alternatives so much more labourious. It would be so nice if I can just hide certain tags or disable them completely for alternatives

**Comment by raoulvdberge** [comment]
So basically: a search function?

**Comment by raoulvdberge** [comment]
See #3333
