### ISSUE TITLE
Compatibility with silicon from other mods please!

### ISSUE THREAD

**Issue by adamkad1** [refinedmods/refinedstorage#3371]
### Describe your enhancement

Let the recipes use any forge:silicon tagged item please!

**Comment by raoulvdberge** [comment]
That's interesting, I thought we already did this.  But we seem to be using our own silicon tag.

**Comment by jlc3tx** [comment]
I'm having this issue now as well in 1.19.2. I'm unable to craft Refined Storage silicon. The recipe is not available. Instead, it crafts silicone from Applied Energistics 2 only. The processors will only take refined storage silicon.

**Comment by BLKMRK3T** [comment]
This issue is on 1.16.5 as well. Due to using Emendatus Enigmatica the quartz in my pack smelts to their tagged forge:silicon by default, this would be a GREAT enhancement.
