### ISSUE TITLE
JEI recipe usage in crafting grid ignores items in storage.

### ISSUE THREAD

**Issue by Devalut** [refinedmods/refinedstorage#3374]
### Describe the bug

Trying to create vanilla and modded recipes results in the recipe failing and the items missing as if none were in the network despite being in abundance.

### How can we reproduce this bug or crash?

1. Use JEI Recipe auto complete while using crafting grid
2. Attempt to craft recipe

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.74

### What Refined Storage version is this happening on?

latest for 1.18.2

**Comment by Devalut** [comment]
How is the issue completed?

**Comment by Darkere** [comment]
This is an issue with another mod adding random data to items. Not something we can fix.

**Comment by Devalut** [comment]
Ah, thanks for the reply.
Any chance you could give me more information or is it too much of a hassle? (Seeing as the mod author themselves couldn't be bothered, how sad.)

**Comment by Darkere** [comment]
That is already all the information we have. It's not the first time this has happened, and there is no easy way to track down which other mod is doing it. 

That means we cannot help you.

**Comment by Devalut** [comment]
Ah such a shame, but I appreciate the straight answer!

**Comment by Devalut** [comment]
Found mod causing the probelm:
https://www.curseforge.com/minecraft/mc-mods/weapon-leveling
