### ISSUE TITLE
Allow Regulator Upgrades to be Placed on Importers

### ISSUE THREAD

**Issue by NicolasNewman** [refinedmods/refinedstorage#3377]
### Describe your enhancement

There's been a fair number of scenarios where I've needed a minimum amount of items in my storage container before they can be imported into my RS network. While you can achieve the opposite effect by using exporters and a regulator upgrades, it does not work the other way around. What I'd like to suggest is the ability to use regulator upgrades on importers.

If this is a feature you'd be willing to have in the mod but are too busy I could potentially look into implementing it myself and submit a PR. I'd specifically need this feature in 1.16 so I could back-port it as well. 

Note:
This feature was mentioned amongst many others in #3276 but no response was given and I felt it's focus was too broad to begin this discussion there.

**Comment by raoulvdberge** [comment]
Let's consolidate into #3276
