### ISSUE TITLE
[1.18.2] Constructor/Destructor pair causing server stutter in v1.10.3 on custom modpack.

### ISSUE THREAD

**Issue by bastetfurry** [refinedmods/refinedstorage#3378]
### Describe the bug

I made an ore processing machine with constructors and destructors equipped with fortune 3 upgrades inside a compact machine with Storage Drawers as ore buffers connected trough an external storage, when i let that machine run every three or four blocks the whole server hangs for several seconds.

We have a much larger external storage with Storage Drawer drawers in our base, so i would try to rule out that to be a huge problem.

The idea behind this setup was that Compacting Machines can't reach our main Refined Storage setup but as the constructor/destructor setup causes client lag i wanted that in its own dimension where it won't bother us, so we transport the ores in trough ender chests and transport the processed raw items out with the same but on a different channel.
Energy comes in trough RFTools Dimensional Cells.

### How can we reproduce this bug or crash?

Recreate the setup in the picture and let it run, i can give access to our server for debug purposes.
As you can see i tried to catch the problem with Observable, but sadly to no avail.

![2022-09-25_15 54 49](https://user-images.githubusercontent.com/3686292/192147821-93fc0fea-de2d-4ea5-817c-81b4b28a2708.png)

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

forge-1.18.2-40.1.69

### What Refined Storage version is this happening on?

1.10.3

**Comment by raoulvdberge** [comment]
We'd need a spark report or profiling report, I'll close the issue for now as it's not actionable.
