### ISSUE TITLE
Crafters Support for Crockpots mod

### ISSUE THREAD

**Issue by isaaclepes** [refinedmods/refinedstorage#3379]
### Describe your enhancement

Crockpot support for Refined Storage crafters. Refined Storage takes the category items as literal requirements. For example, if the recipe requires 'cold', the crafter will report the item 'cold' missing, even if I have snow, ice, etc. in the storage.

I am not sure which mod to request this from, so I am going to open a ticket on both and cross-reference them.

https://github.com/SihenZhang/CrockPot/issues/71

![image](https://user-images.githubusercontent.com/54421422/192945447-478a79b1-30de-4ce1-816f-3f99ed631088.png)
![image](https://user-images.githubusercontent.com/54421422/192945473-f661b092-7c9b-4703-b647-ab7d9dab96c3.png)
![image](https://user-images.githubusercontent.com/54421422/192945508-ed9236fc-9fda-451d-94d4-5782d81d848c.png)

**Comment by raoulvdberge** [comment]
Not for RS
