### ISSUE TITLE
Crashing when looking for blocks on creative/JEI - 1.19.2

### ISSUE THREAD

**Issue by ghost** [refinedmods/refinedstorage#3387]
### Describe the bug

The Game loads normally. I load a save.
I get in creative to look for blocks from this mod, click on this mod's tab on creative inventory, when I scroll a little, first the game freezes for a couple of seconds.  Then. a "saving game" screen appears, then the crash happens.

### How can we reproduce this bug or crash?

Get in creative or JEI to look for blocks from this mod

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1.25

### What Refined Storage version is this happening on?

v1.11.0 

### Relevant log output

```shell
[crash-2022-10-03_20.12.31-client.txt](https://github.com/refinedmods/refinedstorage/files/9701636/crash-2022-10-03_20.12.31-client.txt)
```

**Comment by Darkere** [comment]
optifine issue

**Comment by ghost** [comment]
Confirmed it works well without it.  That's a bummer...  Found the perfect mod and it doesn't work with it..

**Comment by raoulvdberge** [comment]
@elienaimg See https://github.com/refinedmods/refinedstorage/issues/3388
