### ISSUE TITLE
💥Crashing💥 on Minecraft 1.19.2? Disable OPTIFINE

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage#3388]
## Optifine is **currently** incompatible with Forge for Minecraft 1.19.2

This has been reported to Optifine: https://github.com/sp614x/optifine/issues/7127

Refined Storage is not the only incompatible mod!
Applied Energistics and Mekanism are other examples of incompatible mods with Optifine on 1.19.2.

The temporary fix *for now* is to remove or disable Optifine in your instance.

**Comment by marlester-dev** [comment]
yeah, use sodium instead

**Comment by ghost** [comment]
I got it to work while trying to install the create mod. on the issues section, they said the newest and beta versions of forge aren't working 100% with optifine yet...
Installed:
OptiFine-1.19.2_HD_U_H9 (most recent version of optifine)
Forge-1.19.2-43.1.1 (the forge version with most compatibility with optifine at the moment)

No crashes so far...

**Comment by raoulvdberge** [comment]
Optifine has fixed this issue so I guess we can close this.
