### ISSUE TITLE
Server Crashes on bootup

### ISSUE THREAD

**Issue by redgamer229** [refinedmods/refinedstorage#3389]
### Describe the bug

I Start up the server
It stays online fir 1-2 minutes then shuts down

i was told by my server hoster to come ask you guys

### How can we reproduce this bug or crash?

i have no clue what the bug really is

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.80

### What Refined Storage version is this happening on?

1.10.3

### Relevant log output

```shell
at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:167) ~[refinedstorage-1.10.3.jar%23108!/:1.10.3] {re:classloading}
    at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onLevelTick(NetworkListener.java:17) ~[refinedstorage-1.10.3.jar%23108!/:1.10.3] {re:classloading
```

**Comment by raoulvdberge** [comment]
your log is 2 lines, not much we can do with that.

**Comment by redgamer229** [comment]
i can grab the whole log, sorry i new to this type of stuff

**Comment by redgamer229** [comment]
https://pastebin.com/3AhmPx1D

**Comment by Darkere** [comment]
Try increasing max tick time in server.properties. 1 min is fairly low

**Comment by redgamer229** [comment]
that worked. thanks for the help
