### ISSUE TITLE
Missing silicon recipe

### ISSUE THREAD

**Issue by CyberIdiot2077** [refinedmods/refinedstorage#3391]
### Describe the bug

I'm playing the ATM8 and after getting a few storage cells from AE2 I hated the whole process, so I proceded to install RS and some addons to add more disks, problem is the recipe for silicon doesn't exist. I downloaded and installed CraftTweaker, that (at the time of writing) was even updated just a few hours ago, to add the recipe myself but it gives a "java.lang.reflect.invocationtargetexception" error and doesn't let the pack load. Am I missing a mod/library/api that the mods needs? Or is it a conflict with the AE2 silicon recipe? I have 0 ideas any help is appreciated A LOT!

### How can we reproduce this bug or crash?

Install the latest RS 1.19.2 version available into the ATM8 pack (i'm using version 0.0.16 but i've tried 0.0.15 too)

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1.27

### What Refined Storage version is this happening on?

v1.11.0

**Comment by camkona** [comment]
came here to post this, looks like i can get it out of creative but cant get it in survival.

**Comment by camkona** [comment]
side note, i tried removing ae2 and all dependencies from my server/profile but the game would not launch without it

**Comment by CyberIdiot2077** [comment]
I've just fully reinstalled the pack, i'll add the rs mods again and see if anything changes.

**Comment by CyberIdiot2077** [comment]
Nothing changed, I'll dump in the void couple of stacks of AE2 silicon and give myself RS silicon :I

**Comment by camkona** [comment]
this has to be a seperate pack in atm8 causing this, on a fresh forge profile with just ae2 and RS, i can smelt quartz into silicon just fine. odd

**Comment by jlc3tx** [comment]
I reported the same problem under another issue about 10 days ago. No response yet.

**Comment by CyberIdiot2077** [comment]
As of now i'm just smelting nether quartz into AE2 silicon and then I exchange 1:1 with cheats, I tried to install CraftTweaker to add the recipe myself but adding that mod makes the pack crash with this error "java.lang.reflect.invocationtargetexception".

**Comment by CyberIdiot2077** [comment]
> I reported the same problem under another issue about 10 days ago. No response yet.

Sad

**Comment by Darkere** [comment]
ATM8 issue

**Comment by jlc3tx** [comment]
Lame answer. Glad to see commitment to excellence [sarcasm].
