### ISSUE TITLE
[1.10.3] Recursive Recipe Issue - Crushing stone into cobblestone

### ISSUE THREAD

**Issue by Peekofwar** [refinedmods/refinedstorage#3392]
### Describe the bug

I created a process pattern that tells the RS system that it can make cobblestone using stone in the Mekanism crusher machine... However, when I try to use this process, it comes up with an error stating the process results in the item being used by itself. 

Thinking about it now, I believe it might just be a recursive issue where it thinks it should turn the cobblestone back into stone to make cobblestone, which would get nowhere.

![image](https://user-images.githubusercontent.com/10189526/195484711-d1fced30-101b-4369-8515-6f71de4b4f05.png)
![image](https://user-images.githubusercontent.com/10189526/195486015-51fc8056-9204-4aa7-aed0-62600cb6f711.png)
![image](https://user-images.githubusercontent.com/10189526/195485219-c0715a00-c713-4f62-9ff3-e9b9c7d21921.png)

How hard would it be to prevent the system from doing this? It already identifies the recursive error and denies craft action. 

### How can we reproduce this bug or crash?

1. Create a process recipe that states one stone results in one cobblestone.
2. Place that recipe in a crafter with a Mekanism crusher, or other crushing device that can crush stone into cobblestone.
3. Have another recipe that tells the machine it can smelt one cobblestone into one stone
4. Attempt to craft something using this process.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.60

### What Refined Storage version is this happening on?

1.10.3

**Comment by Darkere** [comment]
Implementing recursive recipes is rather difficult and not something we will be looking into for RS1.
