### ISSUE TITLE
Lighting Bug

### ISSUE THREAD

**Issue by manthoszh** [refinedmods/refinedstorage#3393]
### Describe the bug

There is a weird darkness that appears when the lighting smooth is on. Happens with settings at both minimal and maximum smoothing. The problem seems to go away when the smoothing is turned off.

Current version installed: refinedstorage-1.10.2.jar

This is a part of: All the Mods 7-0.4.29.zip

Smoothing on:
![2022-10-14_21 45 27](https://user-images.githubusercontent.com/71455308/195963709-0cf025d9-833b-47e3-b84f-738fe85f1363.png)

Smoothing off:
![2022-10-14_21 49 52](https://user-images.githubusercontent.com/71455308/195963717-7971817b-ed40-4f8d-9149-8fd1c4c91b75.png)

Not sure if this is happening to other blocks in the pack.

### How can we reproduce this bug or crash?

Place in world and switch lighting smoothing on and off

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.68

### What Refined Storage version is this happening on?

1.10.2

**Comment by Peekofwar** [comment]
![2022-10-15_00 19 09](https://user-images.githubusercontent.com/10189526/195968386-351b4762-4150-46fb-9c7c-22d7d97c7299.png)
I have the same issue

**Comment by raoulvdberge** [comment]
Turn on the Forge experimental lighting pipeline. Also fixed in 1.19.

**Comment by Peekofwar** [comment]
> Turn on the Forge experimental lighting pipeline. Also fixed in 1.19.

Is that a launch parameter, or something in the in-game settings?

**Comment by Darkere** [comment]
Its an option in the forge-client config
