### ISSUE TITLE
Ambient Machine Noises

### ISSUE THREAD

**Issue by Peekofwar** [refinedmods/refinedstorage#3394]
### Describe your enhancement

Would be cool if when I walk around my RS core chamber, or near RS terminals, there were some computer noises that play. Maybe the quiet but audible sound of a small fan...?

Would also be cool if a machine working played certain sounds... Like if a drive in a disk drive is being used, it makes some faint ticking noises, or a crafter starts making some kind of noise indicating it's doing stuff... Maybe the RS Control block makes some kind of faint humming noise.

**Comment by raoulvdberge** [comment]
Cool idea, but would fit more in an addon.

Also my sound design skills suck, so if you're able to do it, feel free :D

**Comment by Peekofwar** [comment]
> Also my sound design skills suck, so if you're able to do it, feel free :D

I know nothing about modding/Java, but I probably could do something sound-wise.
