### ISSUE TITLE
RS won't let me put iron ingots in

### ISSUE THREAD

**Issue by zoomzoom97** [refinedmods/refinedstorage#3398]
### Describe the bug

I went to put my iron in my storage system, but it will not let me. It lets me put anything else innn that I've tried, except for iron ingots.

### How can we reproduce this bug or crash?

1. Make a RS system
2. Try to put iron ingots in

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1.43

### What Refined Storage version is this happening on?

1.11.0

**Comment by Darkere** [comment]
Check your storage. You likely blacklisted Iron from entering it.
