### ISSUE TITLE
Input one set of item if invetory is empty

### ISSUE THREAD

**Issue by Caerglad** [refinedmods/refinedstorage#3403]
### Describe your enhancement

Hi,
can you imlement same feature that exist in AE2, putting 1 set of crafting ingridients at a time?
I've tired to set up Powah auto crafting, in some modpacks getting redstone pulse from comparator just does the trick, but in enigmatica 6 expert it doesn't work if crafting more than 1 set. In ATM7 modpack AE2 crafter has a way to input just one set and it works perfectly, same story with Thermal Expansion Induction smelter - it tends to clog up with 2 recipes running at the same time.

**Comment by Darkere** [comment]
https://refinedmods.com/refined-storage/wiki/locking-and-unlocking.html#redstone-pulse-inserts-next-set

**Comment by Caerglad** [comment]
Ok, so FYI: compactor + immersive cable doesn't work with Powah Energizing Orb, but compactor + vanila redstone + repeater does (with crafter set to redstone pulse)
