### ISSUE TITLE
[1.18.2] When using Rubidium, disk drives render as dark when using smooth lighting, even with the experimentalForgeLightPipelineEnabled set to true, but only when placed next to other blocks

### ISSUE THREAD

**Issue by TheD0ct0r101** [refinedmods/refinedstorage#3404]
### Describe the bug

Before anyone asks, I did read up on the Optifine version of this issue, and from what I understand Optifine completely changes the lighting pipeline, and as far as I am aware, the chances of this being fixed is essentially zero due to the fact that Optifine is closed source and invasive to Minecraft's engine.

To clarify, I am running the mod on Stoneblock 3 for 1.18.2, and this lighting bug happens ONLY when Rubidium is installed, so being a modpack shouldn't affect anything.

What I AM curious about however, is whether or not something can be worked out with Rubidium's dev unlike optifine's dev. Rubidium afaik is open source, and the developer seems to work very closely with FTB Team members to fix issues, so I'm sure they would be willing to cooperate in fixing this.

### How can we reproduce this bug or crash?

1. Install Rubidium 0.5.4 (or any version probably) + Refined Storage
2. Ensure smooth lighting is on and the experimental pipeline is on.
3. Observe disk drives when placed next to other blocks or themselves.

![2022-11-08_10 08 22](https://user-images.githubusercontent.com/11579139/200630380-e00c4f4e-4d5b-453d-a352-0b3782efb202.png)
![2022-11-08_10 08 28](https://user-images.githubusercontent.com/11579139/200630405-efe8e473-e1f0-4b9d-92e1-00eb3f24eecc.png)

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.84

### What Refined Storage version is this happening on?

1.10.3

**Comment by Darkere** [comment]
Report to rubidium. RS just uses forge features.
