### ISSUE TITLE
[1.19] Refined Storage lags when viewing certain recipes with JEI

### ISSUE THREAD

**Issue by SnakerBone** [refinedmods/refinedstorage#3406]
### Describe the bug

When viewing recipes that use forge:wood, forge:planks, forge:stone, forge:glass, forge:potions, etc in JEI the whole game will lag and sometimes even crash. I believe its because it is trying to cycle through all the different variants. This seems to be a RS issue as AE does not have this problem

### How can we reproduce this bug or crash?

Try and remove recipe cycling for common tags (if possible) or perform extensive bug testing/fixing for this issue

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1.47

### What Refined Storage version is this happening on?

1.11.1

**Comment by Darkere** [comment]
Please run spark on the client while the lag occurs. So we can see what might be the problem.

**Comment by SnakerBone** [comment]
Hello, here are the profiler results: https://spark.lucko.me/XzhPrcM47D 

When I started the profiler I viewed the recipe for the furnace (vanilla furnace) & the pity machine frame (from industrial foregoing) with the crafting grid open. Viewing the furnace recipe was a little laggy but viewing the pity machine frame recipe nearly crashed my game

**Comment by Darkere** [comment]
You'll need to run sparkc instead of spark to profile the client side instead of server side.

(also just if you are interested your bees are lagging your game :D )

**Comment by G33kman** [comment]
Hoping not to totally hijack this thread but I believe I'm having the same issue as OP.
Here's a link to my results: 

https://spark.lucko.me/EbGfygZBeE

I notice it's only when I go to view a recipe within RS if I open my inventory and use the search bar in JEI to do that same thing it shows everything without issue.

Hope this helps to see what's going on.

Thanks

**Comment by Darkere** [comment]
Alright, that confirms my suspicion. Its the JEI resource tracker. Will need to optimize that at some point.

**Comment by G33kman** [comment]
At least one of us knows where to look next. Lol
Appreciate the response!

**Comment by ShroomAgent27** [comment]
Just want to add my profile too.

https://spark.lucko.me/nK1fjisjWv

Minecraft Version: 1.19.2
Forge Version: 43.1.47

AMT8 Version: 0.1.10

Using jars
refinedstorage-1.11.1.jar
refinedstorageaddons-0.9.0.jar
refinedcooking-3.0.2.jar
jei-1.19.2-forge-11.4.0.285.jar

**Comment by raoulvdberge** [comment]
Thanks for providing us with the spark profiles!

**Comment by SnakerBone** [comment]
Hello! Sorry I'm a little late but here's my results 😅

https://spark.lucko.me/sYUtdqUVAS

**Comment by Rithenar** [comment]
I am not sure if you have enough profilers or if this was already addressed but I am also having major issues with the game nearly crashing when I look at some recipes in JEI in RS/ Here is my profiler. It was taken while requesting all recipes that an induction Smelter (TS) can craft

https://spark.lucko.me/bEa7kwNBh5

**Comment by Tyyni707** [comment]
The lag seems exponentially worse when view a recipe in JEI while in RS and Create Mod shapeless crafting is in the first tab of the recipe

**Comment by CoolFreeze23** [comment]
Has there been any update on this? It's hard to even play tbh. If the recipe includes any type of items that have multiple variants it lags tremendously. Including anything with wood, anything with ingots, anything with wool, etc. I'm about to just transfer all my items to a AE2 system until its fixed for now.

**Comment by raoulvdberge** [comment]
Modpack issues:
- https://github.com/AllTheMods/ATM-8/issues/389
- https://github.com/AllTheMods/ATM-8/issues/289
- https://github.com/AllTheMods/ATM-8/issues/164

**Comment by raoulvdberge** [comment]
@Darkere  is looking for maps to reproduce the issue with. Please send them to us via this issue!

**Comment by Pokemonplatin** [comment]
I already created a fix, will pr it later today

**Comment by raoulvdberge** [comment]
@Pokemonplatin  Please first consult with us before making PRs. @Darkere  already has a fix in staging and just needs to test it.

**Comment by Pokemonplatin** [comment]
Well anyway if you still need a test world, here is the one i used https://drive.google.com/file/d/1X5nE8nge4EnIDk4i4Eqyk9kMasnQjfXM/view?usp=sharing

**Comment by raoulvdberge** [comment]
Fixed in aaf528bce28f0808a170893b7e748ce14162b7ff #3428
