### ISSUE TITLE
Crafting grid shows wrong number of stored items

### ISSUE THREAD

**Issue by AmyMoriyama** [refinedmods/refinedstorage#3408]
### Describe the bug

After some time, no idea what triggers it, the crafting grid shows wrong number of items. Usually many times the number that is actually in storage. Taking everything out of the system then taking all the drives out and putting the drives back and adding items back to the system temporarily fixes it.

1.19.2

### How can we reproduce this bug or crash?

Not sure. It seems pretty random.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1.43

### What Refined Storage version is this happening on?

1.11.1

EDIT: It seemed to be related to some issue with multiple drives essentially being identical. It almost seems that it's a dupe bug. When I set up the system for testing, I grabbed one drive from creative and used middle mouse to turn it into many. This might be related. Maybe the creative duping of the drives set them all up to dupe items added, at least the system thinks the items are there, but they actually aren't there.

Explanation of screenshots. First one shows how much the system thinks it has. The second shows how many actually exists (took them out and put in hotbar).

![2022-11-16_03 44 02](https://user-images.githubusercontent.com/87048190/202299380-ce11e6dd-164c-420a-8525-afb8c3c36d93.png)

![2022-11-16_03 44 17](https://user-images.githubusercontent.com/87048190/202299454-7f9c1f7b-fd8a-4094-a338-68ea9f16643d.png)

**Comment by raoulvdberge** [comment]
Don't use middle click, you'll end up sharing the same disk ID and then this behavior happens. :)
