### ISSUE TITLE
Feature idea: Scheduling recipes

### ISSUE THREAD

**Issue by tizu69** [refinedmods/refinedstorage#3411]
### Describe your enhancement

I'd love to see a feature to be able to request items via autocrafting without actually having the items in the system yet. The RS system should just wait, depending on a setting in the crafter block, until 1) all items are provided or 2) items get put into the machine directly once inside the system.
However, there should be a cap of 2 or 3 scheduled recipes at one time due to it being too OP imo.

**Comment by raoulvdberge** [comment]
Use an interface with a crafting upgrade.
