### ISSUE TITLE
Disk Drives are able to accept more items than they can hold.

### ISSUE THREAD

**Issue by kalutro** [refinedmods/refinedstorage#3412]
### Describe the bug

This happened in StoneBlock 3.

I am not sure how the bug happened, but all 5 of my drives suddenly filled up with the exact same number of a single item (Netherrack Brick). I hadn't done anything new, but I noticed my autocrafting stopped working and when I checked my Disk Drive it had more than 5 billion items in it.

Now, I don't think RS caused this issue, though I may be wrong, but I do have a Compressed Refined EMC Link from ExtendedeXchange hooked to an External Storage. The External Storage is set to Extract Only.

The odd part is I have been using multiple EMC Links with multiple items for days now, including the one for Nether Bricks and it caused no issues. Maybe TPS lag could have caused this? Not sure but my TPS was at 101ms when I noticed this.

I guess the solution could be to disallow actually adding more than a disk can hold. No idea. I will attach a screenshot showing the issue.
![2022-11-17_09 41 44](https://user-images.githubusercontent.com/69569507/202520983-138ff224-f19f-4f39-b87a-a84410e90e89.png)

### How can we reproduce this bug or crash?

I am not sure how this happened.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

Unknown

### What Refined Storage version is this happening on?

1.10.3

**Comment by raoulvdberge** [comment]
Sorry, the reproduction steps are not actionable. Please see if you can reproduce it with ExtendedeXchange and report to them if necessary. In general, please try to formulate better reproduction steps if you want us to look into this.
