### ISSUE TITLE
Dropper-esque block

### ISSUE THREAD

**Issue by CanINotUseTruth** [refinedmods/refinedstorage#3413]
### Describe your enhancement

I am trying to automate an in-world craft that requires dropped items, this is obviously possible with Minecraft's dropper but a block that worked similarly to an exporter that could drop stacks rather than a single item out into the world directly from the system and maybe would wait until the stack in front of it is gone to help with automation of in-world crafting recipes. Example of an in-world craft: Flux dust from Flux Networks.

**Comment by Darkere** [comment]
constructor

**Comment by CanINotUseTruth** [comment]
The constructor acts as a block placer, not a dropper. What I'm suggesting is something that outputs/drops the item onto the ground not place it in it's block form.

**Comment by raoulvdberge** [comment]
The constructor has a dropping option
