### ISSUE TITLE
[1.18.2] Interface Duplication Glitch

### ISSUE THREAD

**Issue by Kitteh6660** [refinedmods/refinedstorage#3414]
### Describe the bug

There is still a duplication glitch and it involves Interface. As such, if you have stackable items, it will keep duping to full stack and you can take as many items as you want.

This is done on version 1.10.3 of Refined Storage for Minecraft 1.18.2.

### How can we reproduce this bug or crash?

1. Set up Controller, Disk Drive, and Interface as normal, add a Grid too. Make sure all of the parts are powered with FE.
2. Make sure Disk Drive is set to extract only.
3. Open the Interface GUI, place at least 2 items into Interface Import. Must be in the same slot, and must be stackable.
4. Observe that the items will multiply and it will briefly vanishing before reappearing seemingly as single stack. (Server). On Single Player, it will keep doubling (but it will disappear if it hits max integers)
5. Try to take the items out of import slots. It will be at full stack and you can take as many as you want.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.84

### What Refined Storage version is this happening on?

1.10.3

**Comment by raoulvdberge** [comment]
Can't reproduce this:
![image](https://user-images.githubusercontent.com/10358424/206849987-cb75c76d-4545-4bc0-9362-42f619f83e29.png)

**Comment by Kitteh6660** [comment]
The bug is present in 1.18.2. I've sent the video showing the duplication bug. The item must be stackable and have a quantity at least 2 inside one slot.

Key points:

1. The Disk Drive must be set to extract only. Which is shown in the video.
2. The duplication happens when you put stackable items, put more than 1 item in the same slot. Has to be the same slot.
3. Once the quantity exceeds 2,147,483,647, the item inside the slot gets deleted.

https://user-images.githubusercontent.com/5838739/206883750-c55792fb-9283-414f-bf25-0d629076a794.mp4

**Comment by raoulvdberge** [comment]
Thanks for this bug report. Turns out I was reproducing it wrongly.

In any case, it's fixed in 1.19.2 and will be backported to 1.18.2 in a bit.

**Comment by raoulvdberge** [comment]
Has been fixed in v1.10.4 for 1.18.2.

**Comment by Kitteh6660** [comment]
Awesome to hear!
