### ISSUE TITLE
Obscure API breaks Refined Storage JEI crafting

### ISSUE THREAD

**Issue by Gorgok** [refinedmods/refinedstorage#3415]
### Describe the bug

Forge - 40.1.85
jei-1.18.2-9.7.1.255.jar
obscure-api-8-1.18.jar
refinedstorage-1.10.3.jar

Crafting by clicking recipes in from JEI in the crafting grid fails to get all the items even when they are all in system. Seems a little random what items end up missing and sometimes it works; often it doesn't. Remove obscura and everything is fine (even in a 250 mod pack).

### How can we reproduce this bug or crash?

1. JEI click 'grid' recipe into crafting grid
2. Some items populate crafting grid, some do not

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

Forge - 40.1.85

### What Refined Storage version is this happening on?

refinedstorage-1.10.3.jar

**Comment by Darkere** [comment]
This sounds like it would be an issue with the obscure-api mod?

**Comment by raoulvdberge** [comment]
Please report to them and if necessary we can still look into it, let us know in that case.
