### ISSUE TITLE
Controller is a ghost block

### ISSUE THREAD

**Issue by RevolvingMadness** [refinedmods/refinedstorage#3416]
### Describe the bug

When I place down the controller it's a ghost block, it gets removed from my inventory but when I click where it was it appears again (as to be expected like a ghost block)

### How can we reproduce this bug or crash?

I dont know

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.85

### What Refined Storage version is this happening on?

1.10.3

**Comment by RevolvingMadness** [comment]
Here is the crash log: https://crashy.net/TPTym0oqhFw5vSlkRqHD

**Comment by Darkere** [comment]
Then you have something that prevents you from placing the block serverside. This is unrelated to RS. And the crashlog has nothing to do with either.

**Comment by RevolvingMadness** [comment]
it was bigger stacks
