### ISSUE TITLE
Chained crafters not naming based on anvil renamed crafters

### ISSUE THREAD

**Issue by duckhunter392** [refinedmods/refinedstorage#3418]
### Describe the bug

When chaining crafters together using an anvil renamed crafter, the first crafter (the renamed one) obviously has it's name set correctly, but the crafter placed on top of the first one will use the name of the machine the first one points to. For example:

![image](https://user-images.githubusercontent.com/17309033/204419183-7c8aa5ba-90a3-4d7d-b708-15beba8db1ef.png)

Labels for above image:
Crafter 2 (Top)
Crafter 1 (Middle)
Chest (Bottom)

Crafter 1 is anvil set to "Test ABC"
Crafter 2 should be an extension of "Test ABC" but instead it shows up as "Chest"

### How can we reproduce this bug or crash?

1. Place a chest
2. Anvil set the name of a crafter to something custom
3. Put custom named crafter ontop of chest
4. Put another crafter ontop of the first crafter
5. Check the names of each crafter in the UI or a crafter manager

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

Forge-40.1.68

### What Refined Storage version is this happening on?

refinedstorage-1.10.3

**Comment by raoulvdberge** [comment]
Thanks for reporting. Fixed for the next version.
