### ISSUE TITLE
[Crash] Crash with Terra Incognita and Cuneiform

### ISSUE THREAD

**Issue by Catomax262** [refinedmods/refinedstorage#3419]
### Describe the bug

For some reason it crashed when i typed the letter "t" in the search bar.

### How can we reproduce this bug or crash?

1. Go to search items tab.
2. Type "t", example: search for a dirt path
3. Crash

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.84

### What Refined Storage version is this happening on?

1.10.3

### Relevant log output

```shell
no logs, info in the crash
```

**Comment by raoulvdberge** [comment]
> no logs, info in the crash

So where is your crash?

**Comment by Catomax262** [comment]
> > no logs, info in the crash
> 
> So where is your crash?

oh i forgot

**Comment by Catomax262** [comment]
https://crashy.net/RNPc3MrBeGWmp7r5JvUL

**Comment by raoulvdberge** [comment]
That doesn't seem like an RS issue.
