### ISSUE TITLE
"Epic" issue about network node and world representation desyncs

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage#3424]
A long time ago... I made an architectural decision for RS that has worked good for us for years. Unfortunately, since mods and Minecraft are evolving, this decision is quite problematic now.

This issue is alleviated in RS 2, but needs (temporary) fixing/workaround in RS 1.

## Blockstate mismatch
- https://github.com/refinedmods/refinedstorage/issues/3410
- https://github.com/refinedmods/refinedstorage/issues/3383

## Network(Node) mismatch
- https://github.com/refinedmods/refinedstorage/issues/3357
- https://github.com/refinedmods/refinedstorage/issues/3376
- https://github.com/refinedmods/refinedstorage/issues/3405
- https://github.com/refinedmods/refinedstorage/issues/3326
- https://github.com/refinedmods/refinedstorage/issues/3337
- https://github.com/refinedmods/refinedstorage/issues/3291
- https://github.com/refinedmods/refinedstorage/issues/3273
- https://github.com/refinedmods/refinedstorage/issues/2610
- https://github.com/refinedmods/refinedstorage/issues/3459
- https://github.com/refinedmods/refinedstorage/issues/3583
- https://github.com/refinedmods/refinedstorage/issues/3563
- https://github.com/refinedmods/refinedstorage/issues/3555
- https://github.com/refinedmods/refinedstorage/issues/3556
- https://github.com/refinedmods/refinedstorage/issues/3477
- https://github.com/refinedmods/refinedstorage/issues/3586

## Confusing behavior
- https://github.com/refinedmods/refinedstorage/issues/2254

**Comment by raoulvdberge** [comment]
Some work for this has been done already on: https://github.com/refinedmods/refinedstorage/commit/885d46c7b9844096ebd8ae6af0874fbb5764d534

**Comment by Gnuelch** [comment]
Here's a workaround for some of these bugs to get your world running again:

(i'm on 1.19.2 and got a crash followed by being unable to log in with the error `class com.refinedmods.refinedstorage.apiimpl.network.node.ExporterNetworkNode cannot be cast to class com.refinedmods.refinedstorage.apiimpl.network.node.ImporterNetworkNode`)

1. stop your server
2. open any world editor (like amulet) and delete the affected node(s) / block(s). you need to know where the node is located for that though. 
3. start the server and log in.
4. **THIS IS IMPORTANT**: take out each and every storage disk and pattern in all crafters and disk drives in existence and store them somewhere else.
    if you don't do this, you WILL lose them. they disappear out of the refined storage machines when deleting the .dat file in the next steps
6. stop the server again.
7. go to [world folder]/data/ and delete refinedstorage_nodes.dat
8. start the server again.
9. reinsert all disks and patterns and you're good to go.

Don't break or place refined storage stuff using unconvential methods. break them by hand or with normal tools until this is fixed i guess.

note that i have no clue if deleting the nodes data file has other effects. i'm writing this just minutes after i got my world to work again.

**Comment by raoulvdberge** [comment]
**Note to addon developers**

**If you are using `NetworkNodeBlockEntity`**

Starting from RS v1.12.4 for MC 1.20.1 (and version v1.11.7 for MC 1.19.2, v1.10.6 for MC 1.18.2) it is strongly advised to pass the network node class type to the constructor.

For example:
```diff
    public DetectorBlockEntity(BlockPos pos, BlockState state) {
-       super(RSBlockEntities.DETECTOR.get(), pos, state, SPEC);
+       super(RSBlockEntities.DETECTOR.get(), pos, state, SPEC, DetectorNetworkNode.class);
    }
```

In order to avoid crashing bugs at runtime when a block entity mismatches with its network node representation, RS needs to know the class type.

Both constructors will keep existing to ensure compatibility, but please move to this new format to avoid crashes (see this bug report for a nice list).

**When can I use this API?**

Now!
- For MC 1.20.1: v1.12.4
- For MC 1.19.2: v1.11.7
- For MC 1.18.2: v1.10.6

**If you are not using `NetworkNodeBlockEntity`**

If you have a custom implementation of `INetworkNodeProxy`, remember to cast safely when you are retrieving the node from the network node manager.
Like so:

```diff
    @Override
    @Nonnull
    @SuppressWarnings("unchecked")
    public N getNode() {
        INetworkNodeManager manager = API.instance().getNetworkNodeManager((ServerLevel) level);

        try {
            INetworkNode node = manager.getNode(worldPosition);

            if (node == null) {
                LOGGER.warn("Expected a node @ {} but couldn't find it, creating a new one...", worldPosition);
                node = createAndSetNode(manager);
            }

-           return (N) node;
+           return networkNodeClass.cast(node);
        } catch (ClassCastException e) {
            LOGGER.warn("Node @ {} got desynced with it's block entity container, recreating", worldPosition, e);
            return (N) createAndSetNode(manager);
        }
    }
```

**Comment by raoulvdberge** [comment]
Fixed in https://github.com/refinedmods/refinedstorage/commit/9b30bece19c0e2cd843921b2cbe7f2ca9d347def

Will be fixed for RS v1.12.4 for MC 1.20.1 and will probably be backported to MC 1.19.2.

**Comment by raoulvdberge** [comment]
This is now backported to MC 1.19.2 in version v1.11.7.

**Comment by raoulvdberge** [comment]
This is now backported to MC 1.18.2 in version v1.10.6.
