### ISSUE TITLE
Jei Crash when scrolling

### ISSUE THREAD

**Issue by AshiDeino** [refinedmods/refinedstorage#3425]
### Describe the bug

I was working on a modpack for a singleplayer world and added refined storage for 1.19.2, and when i scrolled on the jei menu to where refined storage items were shown my game just crashes every time. I confirmed that it was refined storage because i didnt have the issue when i removed it and reloaded into the world. I saw a bug report for other people having a similar issue where it would just lag their game alot, and since my pc isnt meant for gaming and minecraft only runs on 60fps after alot of tweaks with settings, i think that it may be the same issue. 

(also i am new to modding so i dont know how to check my forge version so since i might just be having the same issue, i put the same fore version that the post i mentioned earlier used, it might be wrong so if it is please let me know how to check)

### How can we reproduce this bug or crash?

Use JEI and Refined storage, when scrolling to the page in JEI where refined storage is, my game crashes. Since my pc is of lower quality then alot of other peoples, it might just be a lag spike for other people.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

43.1.47

### What Refined Storage version is this happening on?

1.11.1

**Comment by raoulvdberge** [comment]
So where is the crash?

**Comment by AshiDeino** [comment]
What do you mean?
Im new to github and crash reports altogether so i dont really know what else im supposed to do, like how to get proof of it
Every time i scroll to the page in JEI with refined storage stuff showing, my game freezes then immediately just crashes, so im not to sure what else i need to say or what to show

**Comment by Darkere** [comment]
When you crash the game creates a crash-report in the crash-reports folder. Generally your launcher should have an option to open the folder for the pack in which the crash reports folder resides. 

Ideally upload the contents of the relevant crashreport to https://gist.github.com/ and share the link.
