### ISSUE TITLE
Vanilla crafting table is in <tag:items:refinedstorage:crafting_tables> and not other modded ones (I use BYG)

### ISSUE THREAD

**Issue by INooBTooMuch** [refinedmods/refinedstorage#3426]
### Describe the bug

The Crafting Table has this `<tag:items:refinedstorage:crafting_tables>` tag on it and there is another tag `<tag:items:forge:workbench>` that could be used maybe.

I sent it over to discord at first and I was told to make a bug report : https://discord.com/channels/342942776494653441/342944559682289685/1051079145565724682

Also BYG is [Oh The Biomes You'll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)

### How can we reproduce this bug or crash?

1. Not a crash but I used the `/ct hand` command from [CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker) and saw there is a tag in the crafting table.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.85

### What Refined Storage version is this happening on?

refinedstorage-1.10.3.jar

**Comment by raoulvdberge** [comment]
`forge:workbench` seems to be defined by BYG. Forge doesn't seem to have a workbench tag themselves. Is the BYG tag a good alternative? What are other mods using?

**Comment by Darkere** [comment]
From what I can find its `forge:workbenches`. used by BYG and Tinkers. 

Though tinkers does have a fallback so that `forge:workbench` also works, plural is vanilla convention.

**Comment by INooBTooMuch** [comment]
The only item tag that the vanilla crafting table had was the `<tag:items:refinedstorage:crafting_tables>` tag and the BYG crafting tables had the `<tag:items:forge:workbench>` (aslo a `<tag:items:c:workbenches>`) so it makes sense that it wasn't defined by forge in the end (I thought it was forge because it had the `forge` instead of the modid). 

There also is a [Cyclic](https://www.curseforge.com/minecraft/mc-mods/cyclic) crafting table `<item:cyclic:workbench>` that has only the `<tag:items:forge:workbench>`. Its up to you what you want to do since its not added by forge, its simple either way.

**Comment by raoulvdberge** [comment]
Fixed in RS 2, as there we are using convention tag `c:player_workstations/crafting_tables`.
