### ISSUE TITLE
Jei Crashes my game when scrolling to view Refined storage items

### ISSUE THREAD

**Issue by AshiDeino** [refinedmods/refinedstorage#3427]
### Describe the bug

I was making a modpack with refined storage in it, and when scrolling through the JEI menu in my inventory, itd crash before loading any refined storage items. 
I made a bug report earlier this week but it was closed before i could figure out how to share my crash report. 
After my game crashes, it brings me back to the launcher and when i click "view crash report" it'd open a notepad page with a bunch of text on it. Sadly my monkey brain cant figure out how to get it on something else that might make it easier. But i took some advice in a comment from my previous bug report and copied all the text from the notepad onto a gist on GitHub. 
Here is the link i was able to get with all the text.
https://gist.github.com/AshiDeino/c000d7aa0b098fd6ab183c10dcb4a50b 
If more info is needed you will need to explain to me how to get it because i am new to the whole concept of modding 

### How can we reproduce this bug or crash?

Open the world, open your inventory. In the JEI search menu try to type @refinedstorage.
When I try to do this the game freezes when I'm at @r because the only mod i have installed that starts with r is refined storage, and once it loads items it'll just freeze then crash. 

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1.47

### What Refined Storage version is this happening on?

1.11.1

**Comment by raoulvdberge** [comment]
Remove or update optifine.
