### ISSUE TITLE
Non-existent items in crafting grid

### ISSUE THREAD

**Issue by Arotomic** [refinedmods/refinedstorage#3432]
### Describe the bug

When i open my crafting grid for the first time after loading a world, all the items appear to have been multiplied, and now i have 4 times the items, except that those items do not actually exist, and I can't pull them out. I am playing on ATM8.
![refined storage bug](https://user-images.githubusercontent.com/110884011/208264608-e585cf08-26a3-49e4-8cde-710b62211a16.png)

### How can we reproduce this bug or crash?

This rarely works, but sometimes the bug shows up when you do this:
1. place a disk drive, a controller, a disk manipulator, and a crafting grid down next to each other.
2. fill the disk drive with storage disks and insert items
3. take out the disks and put in new ones
4. Put the items in the old disks back in using the disk manipulator
5. Leave and rejoin
6. Open the crafting grid

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1.55

### What Refined Storage version is this happening on?

1.11.1

**Comment by raoulvdberge** [comment]
Is there any possibility that you have duplicated disks in creative mode?

**Comment by Arotomic** [comment]
No, but i figured out that it seems to be putting the items into every disk in the drive, and removing and replacing some of the disks works.

**Comment by raoulvdberge** [comment]
The reproduction steps aren't really actionable, sorry. Please reopen if you have a consistent reproduction case.
