### ISSUE TITLE
Warning Regarding NBT Items

### ISSUE THREAD

**Issue by Shyrtle** [refinedmods/refinedstorage#3434]
### Describe your enhancement

There is a warning that pops up on the Storage Housing quest. -- In ATM8, regarding this mod. 

I am not sure if this is the proper place to reach out, but I am wondering if putting NBT items in the refined storage system will cause issues. I can't find anything regarding this anywhere besides in the game, so I am wondering if the issue has been resolved, and the warning is just still in the game?

The current warning states the following:
"""
IMPORTANT: Do not store NBT items on a disk. This increases overall lag in the chunk, and can eventually corrupt your save. If you are unsure what NBT items are, the general rule of thumb is "If it doesn't stack, don't put it in your system."

NBT items are regular items that have tags attached to them, like durability of items, enchantments, flag colors, etc. You know those Apotheosis Gems you keep getting from killing mobs? Those enchanted pickaxes? Yea, don't put that in your Refined Storage system.
"""

Does this still apply? If so, my enhancement request would be to allow storing of NBT items. Which is probably more difficult than it sounds, so I don't mind if this request is closed after answering the question.

Thanks!

**Comment by raoulvdberge** [comment]
Welp, this is annoying. We have modpack authors making technical assumptions about the mod and putting statements in their packs about RS without reaching out to me first, and I get to answer the questions. I'm not too happy about this, I will check with the ATM team.

**Comment by alfredggttv** [comment]
Heyyo!

I'm the dev that wrote this in the quest book, and this was definitely my bad! I'm going to reach out to you for a few questions regarding the issues, but I promise that this was not meant in any ill will! This is something that I had researched as to why a lot of people had issues with RS, and it came to the point of people saying that storing millions of NBT items in an RS disk leads to data corruption.

This was an honest mistake on my behalf for not reaching out to you beforehand. I'll get this patched out and shoot you a message in the meantime!

**Comment by raoulvdberge** [comment]
Hey @alfredggttv, thanks for the message. No problem, everyone makes mistakes. I'll close this issue for now then.
