### ISSUE TITLE
Add Redstone Mode to Detectors (allow them to be turned on or off with redstone) to allow checking advanced truth conditions without bulky redstone circuits.

### ISSUE THREAD

**Issue by QuickBASIC** [refinedmods/refinedstorage#3440]
### Describe your enhancement

Currently detectors can't be turned off and on with redstone like many other RS machines. I propose allowing Detectors to be turned off or on with redstone like the other machines. This would allow stacking multiple conditions to turn on multiple machines.

Example from Immersive Engineering: a Detector set to  Mode "Emit signal when less than this amount" for Plant Oil on top of a Detector set to mode "Emit signal when more than this amount" for "Wheat Seeds" with Redstone mode set to "Only work with redstone signal" on top of an Exporter with Redstone mode set to "Only work with redstone signal". This would mean that the detector for wheat seeds would only turn on and check the amount of items if the Plant Oil was below a certain amount and only turn on the Exporter if both conditions are met.

This would allow checking multiple conditions without building complex and bulky redstone circuits or the complexity of changing the Detector to do more than it was initially designed to do.

Alternatively (for RS2?) create an advanced detector that allows checking multiple conditions with the option of AND or OR or XAND or XOR as a tick box or mode.

**Comment by Darkere** [comment]
You can turn off detectors with relays. 
Receiving and sending out redstone from the same block would force that rotation becomes super important. That already sucks a bit with crafters, but is necessary there.

**Comment by raoulvdberge** [comment]
There's no need to overcomplicate detectors. You can (quite easily) still achieve this with vanilla redstone.

Thanks for the suggestion though!
