### ISSUE TITLE
Using + Crafting from JEI on refined storage cable covers while in a refined storage crafting grid kicks you from servers

### ISSUE THREAD

**Issue by iiVeil** [refinedmods/refinedstorage#3443]
### Describe the bug

Relevant log output: `[13:42:32] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: iiVeil lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes`

Using quick (+) crafting from jei on refined storage cable covers sends a packet so large the server kicks you.

### How can we reproduce this bug or crash?

1. Set up refined storage system with a crafting grid attached
2. Use the "+" in the jei menu to quick craft refined storage cable covers

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.0

### What Refined Storage version is this happening on?

1.11.2

### Relevant log output

```shell
[13:42:32] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: iiVeil lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
```

**Comment by raoulvdberge** [comment]
You are not on the latest version.
