### ISSUE TITLE
Functional Storage / External Storage Item

### ISSUE THREAD

**Issue by moneyblind** [refinedmods/refinedstorage#3447]
### Describe the bug

The mod is not currently able to see any items in the "Functional Storage" mod. This mod acts exactly like Storage Drawers.

In times of the past, we would be able to hook an "External Storage" item to the controller and see its contents on the network.

### How can we reproduce this bug or crash?

Place functional storage controller with adjacent storage "drawers"

Connect a face of the controller to the External storage.
Connect the external storage to the RS network.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1

### What Refined Storage version is this happening on?

1.11.1

**Comment by Darkere** [comment]
There hasn't been an update to RS, so we can't have broken anything.  And I'm fairly certain there was a very recent update to Functional storage. So post on their issue tracker.

**Comment by moneyblind** [comment]
Non-issue. I noticed the linking tool just now in the mod. I linked, and it functioned. Thank you! Please close.
