### ISSUE TITLE
DataParameter desync

### ISSUE THREAD

**Issue by Darkere** [refinedmods/refinedstorage#3449]
### Describe the bug

When Addons register Parameters using this method: https://github.com/refinedmods/refinedstorage/blob/99a671223de8791ff81d334e8b142bba5a702789/src/main/java/com/refinedmods/refinedstorage/blockentity/data/BlockEntitySynchronizationManager.java#L52

There is a chance for desychronization. We added `synchronized` to fix it, however that only fixes the desync in Singleplayer. The desync still happens on servers as the order on the server may not be the same as on the client. 

A potential option would be to change the Registry key from Integer to BlockEntityType. But this would be a breaking change for any addons using it. 

### How can we reproduce this bug or crash?

1. Play RS on server and get "lucky".

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43+

### What Refined Storage version is this happening on?

1.11

**Comment by raoulvdberge** [comment]
We could fix this in 1.19.3 sometime by the end of this month.

**Comment by Artcore1992** [comment]
Any known workaround for this or info about update? Ofc on serverside
