### ISSUE TITLE
Adjust how Node (And other) data is stored in `./server/world/data/refinedstorage_nodes.dat` for easier repair

### ISSUE THREAD

**Issue by JustAnotherGhostName** [refinedmods/refinedstorage#3452]
### Describe your enhancement

Suggestion:

Currently Refined Storage has several different bugs that result in various forms of crashes / kicks / corruptions. From a server administrative perspective, it is rather hard to find the specific part of the dat files which gets corrupted as the data is not stored in an easily searchable manner (IE, searching through it with NBT Explore shows items through data -> nodes -> entries which does not specify human readable coordinates).

Background:

This makes it rather hard to manually repair corrupted data, ultimately requiring a roll back of the files, or if possible, breaking the network in the corrupted chunk, restoring the region file data, but keeping the updated RS data. 

If you are not lucky, the corruption could be a form that instantly crashes with the relevant RS data files, instead of creating ghosted invisible chunks, which ultimately forces the roll back. These roll backs of course are much less ideal as it can roll back every RS networks data by however much time, just for an individual networks corruption.

Proposed Solution:

Adjust how the data is stored so that the "entries" data falls under a region cords, then chunk cords, structure. Knowing the location of the corrupted chunk, it becomes much easier for a server admin to either manually fix the individual chunk, or just roll back the chunks data based on a previous backup without affecting everyone else on the server.

**Comment by raoulvdberge** [comment]
RS2 will store block data in the chunk with the block entity. Unfortunately, this can't be easily fixed for RS1.
