### ISSUE TITLE
System shuts down if more than 50% of total energy used

### ISSUE THREAD

**Issue by dmauldin** [refinedmods/refinedstorage#3453]
### Describe the bug

The RS controller stores 32,000 FE by default.
If the total energy usage by devices in the network exceeds 16,000 FE, then the entire system will shut down.

I haven't looked at the code yet, but I'm guessing this is a problem with order of operations, where 16,001 FE is removed, then there's not enough energy on the next check, which may happen before adding more energy into the system?  I'll try to have a look at the code and see if I can follow what's happening that might cause this.

### How can we reproduce this bug or crash?

This is probably not easy to reproduce with just Refined Storage.  I have an ATM8 server that's been up for about a week and it's been an issue for a few days because of the massive amount of autocrafting players are doing.  The CableTiers devices take up substantially more energy from the controller than the base devices do.  ie: you'll probably not hit anywhere 16000 FE usage unless you're using mods that add on to RS.  RebornStorage is another great example.  It limits the multi-block size to 16x16x16, but if you create a 16x16x16 block it needs more than 16000 FE from the controller on its own and shuts the controller down.  :)

The temporary solution has been to just double the capacity from 32000 to 64000.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.3

### What Refined Storage version is this happening on?

1.11.4

**Comment by Darkere** [comment]
The issue is generally on the power provider side. Some cables only insert their power every second tick. 

If you are using addons you Just need increase the powerbuffer....

**Comment by dmauldin** [comment]
Thanks for the response. I’ve tried several power sources. I’ll try as many
more as I can and get back to you with the results.

Mod interactions can make everything much more interesting. 😄
