### ISSUE TITLE
Fails to load on new instance - NoSuchMethodError (MultiMC)

### ISSUE THREAD

**Issue by darkwiz666** [refinedmods/refinedstorage#3456]
### Simplified issue:
Fails to load on new instance - NoSuchMethodError

> Failure message: Refined Storage (refinedstorage) has failed to load correctly
> java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.(java.lang.String)'

Installed version of Forge is 44.1.0
Installed MC version is 1.19.3
RF jar version 1.11.4 for MC version 1.19 (and I don't see any information on which Curse version is best, so I used the current stable version)

### Error Log: 

> A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at com.refinedmods.refinedstorage.item.group.MainCreativeModeTab.<init>(MainCreativeModeTab.java:11) ~[refinedstorage-1.11.4.jar%23129!/:1.11.4] {re:classloading}
> -- MOD refinedstorage --
> Details:
> 	Mod File: /C:/Users/[USER]/Desktop/MultiMC/instances/Refined Storage Testing/.minecraft/mods/refinedstorage-1.11.4.jar
> 	Failure message: Refined Storage (refinedstorage) has failed to load correctly
> 		java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.<init>(java.lang.String)'
> 	Mod Version: 1.11.4
> 	Mod Issue URL: https://github.com/refinedmods/refinedstorage
> 	Exception message: java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.<init>(java.lang.String)'
> Stacktrace:
> 	at com.refinedmods.refinedstorage.item.group.MainCreativeModeTab.<init>(MainCreativeModeTab.java:11) ~[refinedstorage-1.11.4.jar%23129!/:1.11.4] {re:classloading}
> 	at com.refinedmods.refinedstorage.RS.<clinit>(RS.java:29) ~[refinedstorage-1.11.4.jar%23129!/:1.11.4] {re:classloading}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.0.jar%23132!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.0.jar%23131!/:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
> 
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.19.3
> 	Minecraft Version ID: 1.19.3
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 17.0.2, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
> 	Memory: 278435840 bytes (265 MiB) / 536870912 bytes (512 MiB) up to 1073741824 bytes (1024 MiB)
> 	CPUs: 12
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
> 	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
> 	Microarchitecture: Zen 2
> 	Frequency (GHz): 3.59
> 	Number of physical packages: 1
> 	Number of physical CPUs: 6
> 	Number of logical CPUs: 12
> 	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
> 	Graphics card #0 vendor: NVIDIA (0x10de)
> 	Graphics card #0 VRAM (MB): 4095.00
> 	Graphics card #0 deviceId: 0x2489
> 	Graphics card #0 versionInfo: DriverVersion=31.0.15.2647
> 	Memory slot #0 capacity (MB): 8192.00
> 	Memory slot #0 clockSpeed (GHz): 2.67
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MB): 8192.00
> 	Memory slot #1 clockSpeed (GHz): 2.67
> 	Memory slot #1 type: DDR4
> 	Virtual memory max (MB): 29130.69
> 	Virtual memory used (MB): 24225.50
> 	Swap memory total (MB): 12800.00
> 	Swap memory used (MB): 1482.31
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
> 	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
> 	ModLauncher launch target: forgeclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		mixin-0.8.5.jar mixin PLUGINSERVICE 
> 		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
> 		fmlloader-1.19.3-44.1.0.jar slf4jfixer PLUGINSERVICE 
> 		fmlloader-1.19.3-44.1.0.jar object_holder_definalize PLUGINSERVICE 
> 		fmlloader-1.19.3-44.1.0.jar runtime_enum_extender PLUGINSERVICE 
> 		fmlloader-1.19.3-44.1.0.jar capability_token_subclass PLUGINSERVICE 
> 		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
> 		fmlloader-1.19.3-44.1.0.jar runtimedistcleaner PLUGINSERVICE 
> 		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
> 		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
> 	FML Language Providers: 
> 		minecraft@1.0
> 		lowcodefml@null
> 		javafml@null
> 	Mod List: 
> 		client-1.19.3-20221207.122022-srg.jar             |Minecraft                     |minecraft                     |1.19.3              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
> 		forge-1.19.3-44.1.0-universal.jar                 |Forge                         |forge                         |44.1.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
> 		refinedstorage-1.11.4.jar                         |Refined Storage               |refinedstorage                |1.11.4              |ERROR     |Manifest: NOSIGNATURE
> 		jei-1.19.3-forge-12.1.1.8.jar                     |Just Enough Items             |jei                           |12.1.1.8            |COMMON_SET|Manifest: NOSIGNATURE
> 	Crash Report UUID: b598fdb6-2682-4b57-9d90-24e67da3dbad
> 	FML: 44.1
> 	Forge: net.minecraftforge:44.1.0[08:06:19] [Render thread/INFO] [minecraft/Minecraft]: Stopping!

### How can we reproduce this bug or crash?

1. Create new MC instance in MultiMC
2. Install Forge version 44.1.0 via MultiMC
3. MMC places Refined Storage in Loader Mods
4. Start game:
5. Mod MC throws exception when mod fails to load

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

44.1.0

### What Refined Storage version is this happening on?

1.11.4

**Comment by raoulvdberge** [comment]
> Installed MC version is 1.19.3

And a bit later in your report...

> What Minecraft version is this happening on?
> Minecraft 1.19.2

There is no Refined Storage version yet for 1.19.3. You are loading a 1.19.2 mod on 1.19.3.

**Comment by raoulvdberge** [comment]
Also, Curse shortens the versions in the overview. Just click through on the version number:

![image](https://user-images.githubusercontent.com/10358424/214576378-95f74301-3969-4550-8a96-ea5ea12bc093.png)

**Comment by darkwiz666** [comment]
Yup, that was the issue...so used to everything being .3
