### ISSUE TITLE
Can not add or remove items when connected to a functional storage system.

### ISSUE THREAD

**Issue by HeavyDeception** [refinedmods/refinedstorage#3458]
### Describe the bug

When adding a functional storage system to an RS external storage you can no longer remove items.

Mod pack: All The Mods 8

### How can we reproduce this bug or crash?

1. add items to an FS system
2. connect with an RS system
3. try to remove items.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

43.2.3

### What Refined Storage version is this happening on?

1.11.4

### Relevant log output

```shell
no logs
```

**Comment by HeavyDeception** [comment]
This happens if I use JEI to add things to the crafting grid.

![javaw_nXfOqOOuZC](https://user-images.githubusercontent.com/20760785/215200798-cd065dfe-c0c6-4dfd-8199-67413752c025.png)

**Comment by HeavyDeception** [comment]
After restarting this seems to have fixed itself I don't really know what's going on I got a video of it working wrong tho.

**Comment by raoulvdberge** [comment]
Can you reproduce it 100% of the time? Are you sure your external storage is in the correct access mode?

**Comment by HeavyDeception** [comment]
Yes it's in the correct access mode and it seems to happen 50% to 60% of the time.

**Comment by HeavyDeception** [comment]
I have a video of it happening Just can't upload it here.

**Comment by Darkere** [comment]
Just another case of https://github.com/refinedmods/refinedstorage/pull/2789

I forgot I wanted to update that branch
