### ISSUE TITLE
Failure Splitting Packets on Channel "refinedstorage:main_channel"

### ISSUE THREAD

**Issue by YannD-Deltagon** [refinedmods/refinedstorage#3466]
### Describe the bug

I am encountering an error when updating the grid interface in Refined Storage.

The following error message is displayed: "Failure Splitting Packets on Channel "refinedstorage:main_channel". with class com.refinedmods.refinedstorage.network.grid.GridItemUpdateMessage. Number of Packets sent 5, expected number of Packets 7, maximum number of packets for a message of this type 5."

### How can we reproduce this bug or crash?

Open Minecraft 1.18.2 and load the world with Refined Storage 1.10.4 and Forge 40.2.1 installed.
Access the grid interface in Refined Storage with a creative storage with more than **1 000 000** items and fluid
Observe the error message displayed.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.2.1

### What Refined Storage version is this happening on?

1.10.4

### Relevant log output

```shell
Failure Splitting Packets on Channel "refinedstorage:main_channel". with class com.refinedmods.refinedstorage.network.grid.GridItemUpdateMessage.  Number of Packets sent 5, expected number of Packets 7, maximum number of packets for a message of this type 5
```

**Comment by Darkere** [comment]
Yes there are limits to the amount of items that you can add to a system. That limit only cares about data size which means predominantly items with lots of nbt cause you to reach that limit quickly. Large stacks of a single item don't matter. 

We've increased the limit for 1.19 in a recent update

**Comment by YannD-Deltagon** [comment]
Ok, i try to delete items with name or nbt
No update on the road for 1.18.2 ?

**Comment by YannD-Deltagon** [comment]
I transferred all these items in 1 copy to another RStorage, 50,000 different items, ouch...
