### ISSUE TITLE
Exact Mode on/off state is switched

### ISSUE THREAD

**Issue by deguix** [refinedmods/refinedstorage#3469]
### Describe the bug

Using Regulator Upgrade on Exporter while Exact Mode is on will place any amount of items up to the amount specified on the item slots, which is supposed to happen when it's off, rather than only placing the amount specified if there are enough. When it's off, it does what it's supposed to happen when it's on.

Most likely also happens to other things that have "Exact Mode" setting but didn't test it.

(Using ATM8 1.0.10 modpack)

### How can we reproduce this bug or crash?

It's much easier to see this while using machines that require a minimum amount of items for a recipe to work. I used the Enrichment Chamber from Mekanism with the 3 iron ore -> 4 iron dust recipe:
1. Connect Exporter to Enrichment Chamber (by default the "Exact Mode" switch is set to "On").
2. Place Regulator Upgrade on the Exporter.
3. Have less than 3 iron ore but more than 0 in the system.
4. See that the 1 or 2 iron ore are placed in the Enrichement Chamber input (bug).
5. Switch "Exact Mode" on Exporter to "Off", and put the iron ore back in the system.
6. See that no iron ore are in Enrichement Chamber's input (bug).

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.3

### What Refined Storage version is this happening on?

1.11.4

**Comment by Darkere** [comment]
Exact mode defines whether the item that get exported needs to have the exact same nbt or if nbt can be ignored. It has nothing to do with the amount.
