### ISSUE TITLE
Support Fluid containers < 1000 mB

### ISSUE THREAD

**Issue by Crazyafk** [refinedmods/refinedstorage#3472]
### Describe your enhancement

I just entered some molten metals using tinkers' construct's copper cans, but i can't get the fluids back out.
It would be great if refined storage could support this functionality.

Thanks

**Comment by TheDarkFlame** [comment]
I found that my best bet for getting fluids in/out of RS was through a pneumaticcraft tank. They have the ability to take in fluid items, they will either instantly extract the fluid into the tank, or instantly fill the item with fluid.


from there you could set up 2 tanks as follows:

filling items: crafter -> tank -> importer | **blacklist** empty item types (eg empty bucket, canister, etc) so it doesn't pull the still empty item before filling it  
emptying items: crafter -> tank -> importer | **whitelist** an empty item (eg empty bucket, canister, etc) so it doesn't pull the still full item before emptying it

Now just create:
**processing** recipes for: item+fluid = filled item 
**processing** recipes for: filled item = fluid + item

**Comment by raoulvdberge** [comment]
You can get them out through automation blocks. But not through the grid. The grid is optimized for the most common use case. No need to clutter the UI for something this specific.
