### ISSUE TITLE
Portable Grid eats (remove,empty,disapear) Storage Disks

### ISSUE THREAD

**Issue by iTaeyeonKim** [refinedmods/refinedstorage#3474]
### Describe the bug

When opening Portable Disk and putting Storage Disk inside and close it, Portable Grid will eat Storage Disk. I don't know why is this happening, but all I know that this bugs appears on my modded 1.12.2 version and also on my 1.19.2 version.
1.12.2 uses: refinedstorage-1.6.16
1.19.2 uses: refinedstorage-1.11.4

Video proof: https://www.youtube.com/watch?v=K6mugOEd_eQ&ab_channel=iTaeyeon
In video I tried shifting Storage Disk inside Portable Grid and also manually place it inside, not working.
**(This bug does not happening to Creative Portable Disk, which is very strange to me)**

PS: While recording this video, I found out that also is able to duplicate Storage Disks, I didn't know that before filming this.

### How can we reproduce this bug or crash?

1. Open Portable Grid
2. Put Storage Disk inside
3. Close Portable Grid
4. Open Portable Grid

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.0

### What Refined Storage version is this happening on?

refinedstorage-1.11.4

**Comment by raoulvdberge** [comment]
Try reproducing with just RS installed

**Comment by iTaeyeonKim** [comment]
Can't test it, because I always have crash when trying to open Portable Grid:
https://pastebin.com/TmVZJ9gr

**Comment by Darkere** [comment]
Add JEI remove optifine

**Comment by iTaeyeonKim** [comment]
Ok. RS, JEI (solar and hammer just for rf) and problem does occur as I mentioned above

**Comment by iTaeyeonKim** [comment]
Yes, SolarFluxReborn or HammerLib causes the problem.

**Comment by raoulvdberge** [comment]
Please report to them and link this issue.

**Comment by iTaeyeonKim** [comment]
> Please report to them and link this issue.

Done

**Comment by Zeitheron** [comment]
Do you, by any chance, have dispersive upgrade, that charges player inventories?
If so, try removing it, and see if it resolves your issue.

**Comment by iTaeyeonKim** [comment]
> Do you, by any chance, have dispersive upgrade, that charges player inventories? If so, try removing it, and see if it resolves your issue.

Yes, I do

**Comment by Zeitheron** [comment]
As a temporary solution, just don't use it, because it's behavior do have this issue with AE2 as well.
