### ISSUE TITLE
Item display x10

### ISSUE THREAD

**Issue by OMG67** [refinedmods/refinedstorage#3475]
### Describe the bug

While the number of items itself is not affected, the display in the grid is multiplied by 10 (I have 4 andesite yet the grid shows 40), and when I try to take them all out, it takes the 4 and it says there are still 36 left even if there aren't (trying to take out more doesn't work)

### How can we reproduce this bug or crash?

I have no idea how it happened, I just placed the items in the grid, processed some items in a Basic Smelting Facility (Mekanism), inserted the items, went exploring and mining and once I got back and opened the grid, the item display was already multiplied.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.2.1

### What Refined Storage version is this happening on?

refinedstorage-1.10.5.jar

**Comment by OMG67** [comment]
Update:

It seems it also bugs the crafting, meaning if I try to craft something manually it's all  ok, but if I try to make 1 of an item and have the required material to do one more, I can just spam Shift + Left Click and it keeps popping out the created material (I can store and retrieve the created items) and it uses no resources IF they were multiplied.

But if I add a material I didn't have when this glitch happened it will use it up, but not the materials that it multiplied by 10 in the display.

**Comment by raoulvdberge** [comment]
I'm missing reproduction steps.
