### ISSUE TITLE
Random crashes connecting cables and/or exporters within ATM8 (and most recent RS and Forge)

### ISSUE THREAD

**Issue by mherzogjr** [refinedmods/refinedstorage#3477]
### Describe the bug

server crashes immediately when trying to connect RS pieces together.  While I cannot create this event consistently.  It has now occurred several times at different locations.  In all situations they have been cables or exporters adjacent to machines (in one case a mechanism crusher, and in the most recent case a IF stonefactory....  

We are using ATM8.

### How can we reproduce this bug or crash?

It's not consistent or predictable... just becoming regular
It occurred the first time when I tried to remove an exporter, and the most recent time when I tried to create 2 pieces of cable.  The errors seems identical.

I have attached 2 of the crash logs.  
[crash-2023-03-02_21.35.19-server.txt](https://github.com/refinedmods/refinedstorage/files/10878598/crash-2023-03-02_21.35.19-server.txt)
[crash-2023-03-02_00.00.06-server.txt](https://github.com/refinedmods/refinedstorage/files/10878600/crash-2023-03-02_00.00.06-server.txt)

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

1.19.2*46.2.6

### What Refined Storage version is this happening on?

1.11.5

### Relevant log output

```shell
see attached crash logs
```

**Comment by Paradox101** [comment]
We are getting this crash too.

ATM8 same as OP.

[crash-2023-03-22_01.09.01-server.txt](https://github.com/refinedmods/refinedstorage/files/11071220/crash-2023-03-22_01.09.01-server.txt)
[crash-2023-03-26_01.09.59-server.txt](https://github.com/refinedmods/refinedstorage/files/11071251/crash-2023-03-26_01.09.59-server.txt)

Its strange that it appears to be crashing around the same time...

**Comment by Raccamoon** [comment]
Same problem with ATM8 1.0.21b and Refined Storage 1.11.6 (currently the newest version for minecraft 1.19.2). Really hope this will get fixed as it is unplayable at this point. I have had to give up the world after spending weeks playing with my friends. Maybe I'll swich to AE2 if i bother.

**Comment by raoulvdberge** [comment]
See https://github.com/refinedmods/refinedstorage/issues/3424

**Comment by raoulvdberge** [comment]
Hello. This bug has been fixed in v1.12.4 of Refined Storage. If this issue persists anyway, please feel free to create a new bug.

**Comment by raoulvdberge** [comment]
This bug has also been fixed in **v1.11.7** of Refined Storage for **Minecraft 1.19.2**. If this issue persists anyway, please feel free to create a new bug.

**Comment by raoulvdberge** [comment]
Hello, this bug is now also fixed for Minecraft 1.18.2 in v1.10.6.
