### ISSUE TITLE
[1.19] Refined Cable directly or indirectly cause lightning issue when chunk unload

### ISSUE THREAD

**Issue by SigmaFlame** [refinedmods/refinedstorage#3478]
### Describe the bug

Hello,

Refined Storage causes massive problems with lightning in chunk where a network is configured.
It seems to cause the problem only when the network travels more than one chunks
If machines are all placed together without cable there is no problem, but in this case I think it is because they are all in the same chunk.
Only the chunk without the controller is affected.

### How can we reproduce this bug or crash?

1. Configure a network inside multiple chunks
2. Go away in order to unload the chunk
3. Move again inside the chunk
4. See there is massive light issue, torch no longer lights
5. Even Mekanism solar panels says the sky is blocked when there is not
6. Removing a piece of the cable between my two parts of the network and repeat step 2 and 3 fix the issue
7. Destroying instead the Grid at the other side of the cable also fix the issue

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.6

### What Refined Storage version is this happening on?

1.11.5

### Relevant log output

```shell
I have no relevant lag output when chunks unloads.
```

**Comment by SigmaFlame** [comment]
Indirectly cause a bug with Mekanism as well :
https://github.com/mekanism/Mekanism/issues/7754

**Comment by pupnewfster** [comment]
That or actually more likely try removing rubidium it is probably breaking tons of things. (Meant to sent this on the mek issue but got mixed up which tab I was clicked into, but still try removing rubidium)

**Comment by SigmaFlame** [comment]
Rubidium is only installed client-side.

**Comment by raoulvdberge** [comment]
Refined Storage doesn't do anything with lighting. Also, try without Rubidium before creating bugs.
