### ISSUE TITLE
Network Receiver breaks when linking

### ISSUE THREAD

**Issue by DTKing26** [refinedmods/refinedstorage#3479]
### Describe the bug

When inputting a network card into a transmitter, the associated receiver breaks into item form.

### How can we reproduce this bug or crash?

1. Place controller, grid and transmitter down
2. Get network card
3. Place receiver down
4. Right click on receiver with network card
5. Place network card into transmitter

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

43.1.52

### What Refined Storage version is this happening on?

1.11.5

**Comment by raoulvdberge** [comment]
Read the docs properly

**Comment by DTKing26** [comment]
What documentation are you referencing?  This isn't my first time with Refined storage.

**Comment by Darkere** [comment]
A network can only have one single controller.
<https://refinedmods.com/refined-storage/wiki/controller.html#controller-limit>

**Comment by DTKing26** [comment]
Thanks @Darkere!
