### ISSUE TITLE
Rename "Exact Mode" to "Exact NBT Mode"

### ISSUE THREAD

**Issue by deguix** [refinedmods/refinedstorage#3481]
### Describe your enhancement

Simply renaming that option will clarify it's meant to affect NBT and not the amount of items.

**Comment by raoulvdberge** [comment]
A tooltip that states "NBT sensitivity" might be a better option.

**Comment by raoulvdberge** [comment]
This has been planned for RS 2.

**Comment by raoulvdberge** [comment]
In RS 2 we now just call this "Fuzzy Mode" (inverse of Exact mode)
