### ISSUE TITLE
Refined Storage auto-crafting isn't working with wireless transceiver/transmitter from an external storage.

### ISSUE THREAD

**Issue by 25lolstreet** [refinedmods/refinedstorage#3482]
### Describe the bug

When attempting to auto-craft, it doesn't take the items from an external storage connected via wireless receiver/transmitter. In my case, I have an auto-craft recipe which takes cobblestone from an external storage via sophisticated storage drawers across a wireless receiver/transmitter, and is supposed to grind the cobblestone into gravel and gravel into sand, then smelt it into glass. The refined storage grid recognizes the amount of cobblestone in the external storage, and allows me to take stacks of it out, but doesn't pull it while auto crafting. My issue is specifically in ATM8, but I believe that this is an issue persisting between sophisticated storage drawers and Refined Storage itself. In my reproduce field, I will state to boot ATM8 but as I said before, I believe this is a problem between the two mods themselves.

### How can we reproduce this bug or crash?

1. Launch ATM8
2. Create a Refined Storage system
3. Set up an auto-craft that takes cobblestone, grinds it to gravel, then grinds it to sand, then smelts the sand into glass.
4. Set up a wireless Receiver/Transmitter between two points
5. Connect the Transmitter to a Sophisticated Storage System via an external storage.
6. Attempt to auto-craft said recipe

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.6

### What Refined Storage version is this happening on?

1.11.5

**Comment by Darkere** [comment]
You are likely running into chunkloading issues. 
There is no difference between connecting via wireless or directly.
