### ISSUE TITLE
Wrench Config

### ISSUE THREAD

**Issue by JaboyKoral** [refinedmods/refinedstorage#3484]
### Describe your enhancement

I'd like to be able to disable the ability to rotate non-RS blocks with the RS wrench, as it overlaps with other mod wrenches. Maybe a whitelist/blacklist or config option?

For more context- in my modpack I'm trying to keep building more vanilla-ish and disabling any mod wrenches that allow rotating of stairs, doors, etc, and I'd like to keep the RS wrench as a technical block modifier.

**Comment by raoulvdberge** [comment]
https://refinedmods.com/refined-storage/wiki/faq.html#i-have-an-idea-for-a-feature-that-can-be-toggled-on-or-off-with-an-config-option
