### ISSUE TITLE
Add "keep last search" option for Search Box Mode

### ISSUE THREAD

**Issue by DmitryScaletta** [refinedmods/refinedstorage#3486]
### Describe your enhancement

For example:
Normal (keep)
Normal (autoselected keep)

Similar option in AE2:
![image](https://user-images.githubusercontent.com/5096735/228840566-8ed162ba-8ab5-4f2c-b753-db8f668bcd15.png)

**Comment by raoulvdberge** [comment]
This already exists, but as a config option. It's not exposed in the gui as I don't think many people will use it.
