### ISSUE TITLE
Allow stack upgrade in crafter

### ISSUE THREAD

**Issue by jonatjano** [refinedmods/refinedstorage#3491]
### Describe your enhancement

Allow stack upgrades on the crafter.

Usage : Create
When using Create Depots and Belt, item sent one by one won't stack, while items sent by stack are processed by stack

The current way to do stack crafting is to send into a chest and set a funnel at the other side of the chest to drop onto the depot/belt, unfortunatly this solution makes the first item being outputted alone from the chest because it didn't have time to stack yet

Having stack upgrade on the crafter would allow bulk crafting using Create

One way to equilibrate this could be to allow 3 stack upgrades and each stack upgrade multiply the max stack size by 4, which gives 0 upgrade = 1 item, 1 upgrade = 4 items, 2 = 16, 3 = 64

**Comment by Darkere** [comment]
Just change the pattern...
