### ISSUE TITLE
Autocrafting / Modular Routers Cards 

### ISSUE THREAD

**Issue by Tabascopunk** [refinedmods/refinedstorage#3492]
### Describe the bug

Every detail of this [previously](https://github.com/refinedmods/refinedstorage/issues/1290) resolved post describes precisely what is occuring now in the ATM 8 pack with Modular Routers cards being crafted through Refined Storage.

### How can we reproduce this bug or crash?

1. Set a pattern for a Sender Mk1 card.
2. Set a pattern for a Sender Mk2 card.
3. Request a craft of Sender Mk2 and be told no Mk1's available.

At this point, I tried every combination I could think of insofar as exact mode, dragging each ingredient piece from REI, making an actual Mk1 and using that for the recipe using both exact and non, etc.. No dice. Granted, those cards have a ton of NBT data but it has worked in the past in previous versions.

That aside, Refined Storage is still the GOAT.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

1.19.2 43.2.6

### What Refined Storage version is this happening on?

1.11.5

**Comment by DmitryScaletta** [comment]
> making an actual Mk1 and using that for the recipe

I can confirm that this approach works fine for me
ATM8

![image](https://user-images.githubusercontent.com/5096735/230763477-d9683760-d7fc-4e2f-b5a8-f8b45b592bcc.png)

**Comment by raoulvdberge** [comment]
See #3363
