### ISSUE TITLE
64k item storage disk bugged. [1.18.2]

### ISSUE THREAD

**Issue by deadspidervenom** [refinedmods/refinedstorage#3494]
### Describe the bug

Suddenly items already in the storage whether external or internal will no longer appear, but newly added items will apprear until you leave the grid. Removing the 64k storage disk fixes everything.

Each time i access the grid with the bugged disk install i get this error log

[15:03:53] [Render thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Client java.lang.NullPointerException: null

### How can we reproduce this bug or crash?

1. Create/spawn 64k item disk
2. Start storing items.

I do not know if its a certain item or a amount.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.2.1

### What Refined Storage version is this happening on?

1.10.4

### Relevant log output

```shell
[15:03:53] [Render thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Client java.lang.NullPointerException: null

Full log, probably needed.
https://mclo.gs/OjCa57b
```

**Comment by deadspidervenom** [comment]
I have finally found the item that bugged it out. "Locked Advanced Filter" from "Worm Industries" To get it you have to add a item to the filter and lock it for use.

**Comment by Nekiplay** [comment]
![image](https://github.com/refinedmods/refinedstorage/assets/35975332/58ba0dc9-ec6e-4b16-8de4-30043fd8f8d9)
I also have a bug with the display, but different

**Comment by raoulvdberge** [comment]
Unfortunately, your logs no longer exist. Also, the reproduction steps are not really usable.
