### ISSUE TITLE
Grid + Armor Stand

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [refinedmods/refinedstorage#3498]
### Describe your enhancement

Adding a grid to an armor stand to create a 'npc' or just a nice little aesthetic population to builds would be nice.

Effectively it would be cabled from the bottom and you could dress it in armor.

I'd like to hear comments regarding this idea.

**Comment by raoulvdberge** [comment]
What would be the use of this? Would it kind of be like an RS villager?

**Comment by Simon-Bitdiddle** [comment]
The use case is partially cosmetic and partially functional: 

The functional intention is defined by the grid used in the creation of the hybrid. It would operate as normal to access the attached RS network.

The cosmetic intention would be to create ad hoc stands in a variety of places with the ability to add armor/weapons to a given unit.

A full use case example would be as an armored NPC at a desk. Interacting with the stand would allow the user to access the RS network it is attached to with a more visually appealing aspect.

Further refinements would be things like lockable filters for RS access, lockable stands to prevent changing armor/items.

**Comment by raoulvdberge** [comment]
I understand what you're saying but there's no correlation between armor stand functionality and grid functionality, so I don't really think this feature makes sense.
