### ISSUE TITLE
Maximum number of regulators in a network?

### ISSUE THREAD

**Issue by Brucecally** [refinedmods/refinedstorage#3503]
### Describe the bug

Using the Stoneblock 3 (1.6.1) running locally, which has RS (1.10.4) and RSa (0.8.2) and I think I have hit an intentional limit that I can’t find documented anywhere. 

In trying to add yet another Regulator card to an exporter and the network is glitching on/off, exactly as if it’s running out of power. However, the Controller is still up and showing full power. 

I can continue to add more exporters and other power drawing blocks to the grid, as well as other upgrade items, with no ill effects. 

The network is very extensive with regulators used in too many locations to count individually. 

### How can we reproduce this bug or crash?

Very large network with as many regulators as possible. 

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

FTB app version 1.5.1

### What Refined Storage version is this happening on?

1.10.4

### Relevant log output

```shell
No logs generated
```

**Comment by Darkere** [comment]
Increase the power buffer of the controller in the server config

**Comment by Brucecally** [comment]
Thanks for the quick answer, but how would one do that? Especially as the controller is stating that the buffer is still full and usage is well below that? Approx 16k FE/t.

**Comment by Darkere** [comment]
Go to your folder folder and under serverconfig find the refinedstorage-server.toml. Open the file and change the maximum amount of power of the controller.

At 16k you'll run into an issue where if your power source only fills the controller every second tick (for optimization reasons) it will cause issues.
