### ISSUE TITLE
"autoselected" mode breaks JEI bookmarks shortcut

### ISSUE THREAD

**Issue by Spongman** [refinedmods/refinedstorage#3505]
### Describe the bug

usually in JEI you can click outside the search box to remove the focus and use the JEI bookmark key while hovering over an item in the JEI list to add it to the JEI bookmarks list, as described in this tooltip:

![image](https://github.com/refinedmods/refinedstorage/assets/1088194/d9f4fb79-0ba0-482c-a0e3-4b3a73d99ddb)

However, when using a RS Grid in any of the "autoselected" modes, this is impossible. Clicking outside the textbox anywhere does _not_ clear the focus, and hitting the JEI bookmark key (eg. "a") _always_ inserts that text into the searchbox instead of adding the JEI bookmark.

### How can we reproduce this bug or crash?

1. open grid
2. choose a "autoselected" mode
3. click in empty space (outside the text box)
4. try to add a JEI bookmark

This also affects other JEI keys like "Show Recipe" (r) and "Show Uses" (u).

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.6

### What Refined Storage version is this happening on?

1.11.6

**Comment by raoulvdberge** [comment]
yes, that is intended. Autoselected mode ensures the searchbox is always selected.
