### ISSUE TITLE
"tab" key doesn't close Open/Close RS Inventory UIs

### ISSUE THREAD

**Issue by Spongman** [refinedmods/refinedstorage#3506]
### Describe the bug

Tab doesn't close Grid UIs when bound to "Open/Close Inventory"

### How can we reproduce this bug or crash?

1. bind "Tab" key to "Open/Close Inventory"
2. in-game, hit "Tab" a few times. note: it toggles the inventory open/closed.
3. open a vanilla Furnace. hit "Tab" to close it.
4. open an Enchanting Table. hit "Tab" to close it.
5. open a Mekanism Crusher. hit "Tab" to close it.
6. open a Cyclic Combustion Generator. hit "Tab" to close it.
7. open a Function Storage drawer UI. hit "Tab" to close it.
8. open an AE2 Insciber UI. hit "Tab" to close it.
9. open a ForceCraft furnace. hit "Tab" to close it.
10. open a Refined Storage Grid. hit "Tab" to close it. it doesn't work.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.6

### What Refined Storage version is this happening on?

1.11.6

**Comment by Darkere** [comment]
check keybinds. tab is by default assinged to something in the grid

**Comment by Spongman** [comment]
'Tab' is only bound to vanilla 'Open/Close Inventory'. Are you able to reproduce this issue locally?

**Comment by Darkere** [comment]
No. Closing the grid with tab works just fine with inventory bound to tab.

It does not work if you have autoselect enabled. Since you would be typing the tab symol into the search bar.

**Comment by Spongman** [comment]
what purpose does "typing the tab symbol into the search bar" have?

I _do_ have autoselect enabled.

Since 'Tab' doesn't actually do anything in that instance, can you just fall-back to the keybind behavior? This is a pretty common  UI behavior, eg. in Google Chrome, if you put the caret in the URI bar andd hit tab, it doesn't insert a tab character into the URI (not a valid character for URIs anyway), it instead defaults back to the default tab-key behavior (in this case tabbing focus around controls).

**Comment by raoulvdberge** [comment]
We do respect this with the "e" key. If you press E while not focusing the search bar, it'll close the UI. 
If you press E while focusing the search bar, it'll type E in your search bar.
What you're asking for is, effectively, an exception for the tab key because it doesn't make sense to type that in the bar.

**Comment by raoulvdberge** [comment]
Fixed in RS 2. However, the search box can't be focused when you do this.
