### ISSUE TITLE
Crafters from Extra Storage deleting Patterns

### ISSUE THREAD

**Issue by RazeTM** [refinedmods/refinedstorage#3509]
### Describe the bug

Hi

maybe im wrong here but idk where else to put it up. So the netherite crafters sometimes getteing their pattern inventory deleted after a server restart and/or crash. I cant reproduce it bc it doesent happen after every crash or restart. Rarely enough for me to not reproduce but often enough to be very annoying.

### How can we reproduce this bug or crash?

put patterns in a netherite crafter
manual server restart, planned server restart, server crash (doesent happen everytime)
patterns inside certain crafters are deleted

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.11

### What Refined Storage version is this happening on?

ExtraStorage-1.19.2-3.0.1 refinedstorage-1.11.6

**Comment by raoulvdberge** [comment]
1) We need logs
2) Wrong repo.

**Comment by RazeTM** [comment]
1. i cant reproduce it / pinpoint the issue exactly when it happens and therefore cant provide the logs.
2. what does "repo" mean?
@raoulvdberge
