### ISSUE TITLE
Allow items from the JEI bookmarks in filters and patterns

### ISSUE THREAD

**Issue by GeggsLegs** [refinedmods/refinedstorage#3510]
### Describe your enhancement

Right now its impossible to use items and fluids that don't exist in item form in-game inside of patterns and filters. Such as the potion fluids in create, which can only be found while looking at recipes. These items can still be bookmarked in jei however, because the bookmarks preserves nbt data.
Would it be possible for a shortcut to be added to move the items in the bookmarks to filters and patterns, thereby adding the ability to use these items in autocrafting?

**Comment by Darkere** [comment]
This needs to implemented by JEI.
