### ISSUE TITLE
Iron Jetpack (no valid recipe)

### ISSUE THREAD

**Issue by SikiciBebek** [refinedmods/refinedstorage#3511]
### Describe the bug

U are not able to autocraft the copper jetpack
any ideas how to fix it?

### How can we reproduce this bug or crash?

scan the recipe

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

43.2.8

### What Refined Storage version is this happening on?

refinedstorage-1.11.6

### Relevant log output

```shell
Dont have one but could restart the server if u want to have one
```

**Comment by raoulvdberge** [comment]
User error not  a bug.

**Comment by SikiciBebek** [comment]
and how do i fix it?
