### ISSUE TITLE
Pattern TANKS frames while looking at it, or having it in inventory

### ISSUE THREAD

**Issue by lcpichette** [refinedmods/refinedstorage#3512]
### Describe the bug

I made a pattern with a platinum hammer and a an iron ore to make iron dust.

I also have a platinum hammer pattern, and other patterns.

Suddenly, my game TANKED in frames upon making the pattern. I tossed the pattern using Q, and looked away from it instinctively. My frames returned to normal.

I cannot trash the item (I don't know what mod provides it, but it's a trash icon/slot at the bottom right of inventory), so I had to put it in a chest with a sign saying "DO NOT OPEN", I could probably delete it with lava, but for now that seems to work. 

https://github.com/refinedmods/refinedstorage2/assets/54318714/0c110f93-d0e5-4128-886a-5e9c73c33a9d

It's not a big deal once you know what the issue is, but I think that some people might not be able to figure out what the issue is here.

### How can we reproduce this bug or crash?

1. Create necessary RS2 setup to create patterns
2. Create a hammer from All The Ores (I was using platinum, I'm not sure if this is an issue with the other hammers)
3. Use the hammer and an ore with a pattern grid to create a pattern that uses the hammer (non-exact, non-processing) to create dust. 
4. You should now have the pattern of-subject which tanks frames

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

CurseForge, ATM8 v1.0.19b

### What Refined Storage version is this happening on?

1.11.6

**Comment by Darkere** [comment]
please run /sparkc profiler while looking at the pattern, then post the report here.
