### ISSUE TITLE
Smithing Table Support

### ISSUE THREAD

**Issue by bigtruckin78** [refinedmods/refinedstorage#3515]
### Describe your enhancement

It would be nice to have a smithing table tab in the main crafting page and also on the pattern terminal so that crafting any recipes that require it is much easier.

**Comment by raoulvdberge** [comment]
This has been implemented for RS2, where we have support for the smithing table and stonecutter.
https://github.com/refinedmods/refinedstorage2/issues/104

**Comment by raoulvdberge** [comment]
@bigtruckin78  And this is how it looks like:
![image](https://github.com/user-attachments/assets/c92fd4d2-a1bb-4b14-be9d-250145505a89)

![image](https://github.com/user-attachments/assets/1955be3f-234e-4ce9-9505-aa49ff4b709e)
