### ISSUE TITLE
All counter to 0, the steps to follow are literal and the case has been closed without fixing the bug.

### ISSUE THREAD

**Issue by SpartanDraco** [refinedmods/refinedstorage#3516]
### Describe the bug

Without more, when you start the world again there is nothing in the system, it is as if it ran out of energy, I tried to remove mods and is not a conflict, was down to update 1.11.5 and no longer happens, when entering the game in a world already created the system is completely disconnected, has energy but has no "connected" storage., I don't know how to get the log output

### How can we reproduce this bug or crash?

starts a world with the done system

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.14

### What Refined Storage version is this happening on?

1.11.6

**Comment by raoulvdberge** [comment]
We can't do much with your issue...

> starts a world with the echo system

This isn't a reproduction step

**Comment by SpartanDraco** [comment]
is literally when it happens, just load a world, go to your inventory and there's nothing!

**Comment by SpartanDraco** [comment]
![Captura de pantalla (170)](https://github.com/refinedmods/refinedstorage/assets/11298827/b4c36b55-c789-44b6-86a0-81a095e400e3)
![Captura de pantalla (169)](https://github.com/refinedmods/refinedstorage/assets/11298827/54ce4bfc-63ab-4c56-9686-7bed66e9c828)
![Captura de pantalla (171)](https://github.com/refinedmods/refinedstorage/assets/11298827/0e60a301-adef-419b-9694-c256ab8dc9bf)

As I said, the reproduction steps are literal as I have said, is to enter and here I leave pictures

**Comment by SpartanDraco** [comment]
I'm going to say it literally: 
I open panel, remove cable
![Captura de pantalla (172)](https://github.com/refinedmods/refinedstorage/assets/11298827/ec01ae10-99b4-457b-b1c0-813bf965372d)
I lay cable
![Captura de pantalla (173)](https://github.com/refinedmods/refinedstorage/assets/11298827/c2f64ceb-aa2b-473b-a63f-3bb55d9a2756)
works again
![Captura de pantalla (175)](https://github.com/refinedmods/refinedstorage/assets/11298827/00ece46a-cb92-45af-bcf2-d425abb91240)
![Captura de pantalla (174)](https://github.com/refinedmods/refinedstorage/assets/11298827/d1b1e07a-5340-4b6e-ab53-e0c558d505f7)
as I said, as soon as you enter the server/match/map it does not work.

**Comment by SpartanDraco** [comment]
I know that the steps to follow sound very ironic, but that's what happens, there are no steps to follow, is literally load the map and do not work the cables or the hard disk storage, I do not know what it is, but it does not work and I attach photos so that I believe me, I have even direct I'm doing the game and it is clearly not working when entering the map in the latest update of the mod
