### ISSUE TITLE
Texture Pack Colours not being correct

### ISSUE THREAD

**Issue by Bluemethyst** [refinedmods/refinedstorage#3518]
### Describe the bug

i was trying to change the colour of the RS UI's to match those from [this pack](https://modrinth.com/resourcepack/default-dark-mode) and it didnt seem to change the colours of the titles or the UI itself but it made the text go mint green half of the time? the colours i selected were 168168168 for primary and 797979 for secondary. Not sure if that helps. A discord mod told me to make a bug report about it and said they have known about the issue.

### How can we reproduce this bug or crash?

Change any colour of the gui using the way specified on the official wiki

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

Latest version of forge for 1.16.5

### What Refined Storage version is this happening on?

RS 1.9.18

**Comment by raoulvdberge** [comment]
you want rgba colors. For example:
```
{
  "pack": {
    "pack_format": 9,
    "description": "Visual Diversion\n§r§bWelcome to the dark side."
  },
  "refinedstorage": {
    "primary_color": 11184810,
    "secondary_color": 11184810
  }
}
```
See https://legacy.curseforge.com/minecraft/texture-packs/unity-dark-edition for example
