### ISSUE TITLE
Crafter making items disapearing in the grid 

### ISSUE THREAD

**Issue by FumiiKage** [refinedmods/refinedstorage#3519]
### Describe the bug

So, for the exemple i'll use scaffolding
I actually have 7 scaffolding in my grid, and i wanted to make an autocraft of this!
When i put my pattern in the Crafter, my 7 scaffolding are not showing anymore, I can't see them in my grid

I'm playing on a server and the controller wasn't placed by me.

### How can we reproduce this bug or crash?

1. Make a friend do a full setup of refined storage
2. Take a pattern of any items and put it in the crafter 

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.2.8

### What Refined Storage version is this happening on?

1.10.5

**Comment by raoulvdberge** [comment]
Reproduction steps are insufficient
