### ISSUE TITLE
GUI Not closing

### ISSUE THREAD

**Issue by Multi-Coder-24** [refinedmods/refinedstorage#3530]
### Describe the bug

The GUI for any block is not closing after esc is pressed effectively trapping the player in the GUI with no way out but to crash or force quit the game.

### How can we reproduce this bug or crash?

1. Load the latest 1.20.1 version
2. place any GUI based block down
3. Open GUI
4. Attempt to close

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.0.19

### What Refined Storage version is this happening on?

1.12.1

**Comment by raoulvdberge** [comment]
I cannot reproduce this. Can you try reproducing with just RS installed, no other mods?

**Comment by Multi-Coder-24** [comment]
After going back on, the bug has gone, so my only guess is this was a server side glitch.

**Comment by raoulvdberge** [comment]
After changing the Search Box Mode to JEI synchronized (two-way autoselected) it cannot be closed anymore
But as soon as you change it back to normal it can be closed again
