### ISSUE TITLE
Pressing E in a grid with a Search Box closes the GUI

### ISSUE THREAD

**Issue by starforcraft** [refinedmods/refinedstorage#3537]
### Describe the bug

Pressing E in any grid with a search box closes its own GUI because E is bound to Open/Close Inventory. This is now happening because of the fix https://github.com/refinedmods/refinedstorage/commit/03c62700a3d5abcd08a1fb1de2b77d94c6bf87dd which causes all keybindings to not be ignored anymore

### How can we reproduce this bug or crash?

1. Place down any grid with a search box
2. Try typing E in it

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.0.43

### What Refined Storage version is this happening on?

1.12.2

**Comment by XGI223** [comment]
This bug is bound to the inventory bind key. I changed the inventory bind key to a numpad "number" and that seems to be a temporary workaround. this bug might have to do with the inventory trying to open at the same time refined storage is causing it to close refined storage? I could be wrong.
