### ISSUE TITLE
Processing patterns don't work at all on any mashine

### ISSUE THREAD

**Issue by NxckyBear** [refinedmods/refinedstorage#3538]
### Describe the bug

When autocrafting, I did create processing pattern for cooking beef, put it into the crafter facing the furnace. I got the error machine not found, machine doesn't accept item (the output item). Both errors do I get.
while doing the same with a metalurgic infuser (mekanism mod), and an infused alloy pattern, I only get machine doesn't accept item.
both errors should actually not be thrown as it is the output item and as in the guide stated, RS will know what item to expect, not sure why it would insert the item, which should be the output, into the mashine.
(it happens in MC version 1.16.5 I cant choose that in the dropdown)

### How can we reproduce this bug or crash?

1. get a furnace and a crafter
2. place crafter facing the furnace
3. create a pattern which cooks beef into steak (processing pattern: input is raw beef, output is steak)
4. start a crafting task in the grid
5. look into the crafting monitor

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

36.2.34

### What Refined Storage version is this happening on?

1.9.18

**Comment by Darkere** [comment]
You cannot pick 1.16.5 because that version is unsupported.

Make sure your machine can accept the item you are trying to use from the direction the crafter is facing.

**Comment by raoulvdberge** [comment]
![image](https://github.com/refinedmods/refinedstorage/assets/10358424/f45f8276-3c47-4b1e-8e20-a0e934d35e16)
I sometimes wonder why we even have templates.
