### ISSUE TITLE
Grid closes when pressing "e" in the search box

### ISSUE THREAD

**Issue by samjviana** [refinedmods/refinedstorage#3543]
### Describe the bug

The grid GUI closes when pressing "e" on the search box. 

### How can we reproduce this bug or crash?

1. Access storage through the Grid
2. Try to search an item with "e", like "redstone"
3. The grid closes when pressing "e"

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.0.19

### What Refined Storage version is this happening on?

1.20.1

**Comment by Darkere** [comment]
duplicate. update
