### ISSUE TITLE
More grid filter slots - modpacks have way too many mods

### ISSUE THREAD

**Issue by joel4848** [refinedmods/refinedstorage#3545]
### Describe your enhancement

Filters are really useful in mod packs to add the tabs above the storage inventory so you can easily say "I want to only see the Create/RS/Blood Magic stuff I have in my RS network" and click the relevant tab. However, mod packs have dozens of mods, and only being able to have 4 filters means you can only have tabs for 4 mods, which seems an unusual restriction. Would it be possible please to have more than 4 filter slots?

**Comment by raoulvdberge** [comment]
How would you integrate it in the UI?

**Comment by joel4848** [comment]
> How would you integrate it in the UI?

See the attached image (apologies for my poor photoshopping skills)

It could be done in a visually similar way to the creative inventory when there are multiple mods - tabs and then arrows on top to cycle through multiple tabs. Then for the filters, you could extend the filter slots on the right downwards, and also have an arrow to scroll down through the slots. Alternatively for the filters, there could be a new "mod filter" item which lets you create up to, say, four mod filters in the one item (or more - or maybe have different tiers of mod filter items, who knows).

![2023-11-06_16 27 05](https://github.com/refinedmods/refinedstorage/assets/51252788/8cf9dc24-8d4b-4a80-ad25-0dd9ff065ec3)

**Comment by raoulvdberge** [comment]
Hi, we'll tackle this for RS 2 (see linked issue above.)
