### ISSUE TITLE
Crafter UI issue

### ISSUE THREAD

**Issue by davyoliver** [refinedmods/refinedstorage#3546]
### Describe the bug

Modpack: ATM-9
When opening the Netherite crafter in my world it has this weird issue with the UI

### How can we reproduce this bug or crash?

1. Craft a netherite crafter
2. Open it
![Screenshot at 2023-07-23 03-36-32](https://github.com/refinedmods/refinedstorage/assets/64219301/43a743f0-df97-407e-99b4-c63c48f97565)

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.1.1

### What Refined Storage version is this happening on?

1.12.3

**Comment by Darkere** [comment]
netherite crafter is not part of RS
