### ISSUE TITLE
Speed upgrade dupe method.

### ISSUE THREAD

**Issue by rzecz** [refinedmods/refinedstorage#3547]
### Describe the bug

Placing speed upgrades within a crafter, and middle clicking in the place that you put patterns in, will "take out" the speed upgrades from their spot (without taking them out), and put them inside the pattern inventory, basically duping them. 

This happened to me on Technopolis 2, and they are not ghost items, you can drop them, use them, relog with them.

### How can we reproduce this bug or crash?

1. Get a single speed upgrade, and a single crafter
2. Place down the crafter
3. Put said upgrade inside the crafter
4. Middle click the pattern inventory
5. get rich

https://github.com/refinedmods/refinedstorage/assets/95442964/cbf3098f-f227-4600-aeae-be24f189fc49

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.11

### What Refined Storage version is this happening on?

1.11.6

**Comment by Darkere** [comment]
report to mod that allows for middle click item movement.
