### ISSUE TITLE
Wrench being able to rotate/change texture of covers

### ISSUE THREAD

**Issue by markaabo** [refinedmods/refinedstorage#3549]
### Describe your enhancement

So, the problem is when using the covers and trying to have blocks like logs as the covers with textures that are horizontal, i can't seem to find a way to get a cover design that emulates a sideways log (horizontal) with both the sideways end texture as "top side" of a log block and the top of the cover is "side" of a log.

This seems to be a thing missing for all blocks that you can have different texture versions on vectial and horizontal

A fix that would make it so much better is adding a mode to the wrench that just "switches" the texture of the covers current block so for example you can shift right click or something like it, to change the texture of the cover

How it could work is:
 When you shift right click a cover it changes the texture to the different availble textures for the block. so if its a log it can be changes from "Log top" -> "Log side, Horizontal" -> "Log side, Vertical" -> "Striped version, Top" -> "Striped version, Side Horizontal" -> "Striped version, Side Vertical" -> and loop around back to "log top"
 
When the cover is destroyed it could either return to the starting type or it could stay as the current type
 
 
It would eleminamte the need for cover items for alot of blocks when they have different types like log and striped log, it would save the players time not needing to craft each time and store them. it would make covers extremly customizable and way easier to use and hide cables

**Comment by raoulvdberge** [comment]
Sorry, the cover rendering code is complex enough as is. We have people wanting support for connected textures too, and this feature request just complicates too much.
