### ISSUE TITLE
Compatibility Refined Storage and Polymorph

### ISSUE THREAD

**Issue by jouki** [refinedmods/refinedstorage#3550]
### Describe your enhancement

Hello,

as per the title, would be please possible to integrate the polymorph functionality (having the same recipe for multiple items). It is kinda annoying not being able to craft certain items that overlap with their recipes since we have Crafting Grid. :)
We'd really much appreciate the effort <3

Mod CF page:
https://www.curseforge.com/minecraft/mc-mods/polymorph

Cheers,
Jouki

**Comment by raoulvdberge** [comment]
No, recipes are supposed to be unique. It's the modpack developer responsibility to ensure that there is no overlap.

**Comment by jouki** [comment]
I am no modpack developer (nor do I have any experience with it), I just downloaded two mods having the same recipe for knives. I'm not sure why you needed to banish me instantly without clarifying the situation but I see people like me are not welcome here...
Sorry for wasting your time.

**Comment by raoulvdberge** [comment]
I understand that it's annoying if your feature request is denied but I urge you to read my message again, neutrally. I didn't banish you and I didn't say you weren't welcome ;)
