### ISSUE TITLE
Server crash loop on boot after updating one of my all the mods 8 servers. 

### ISSUE THREAD

**Issue by jaynotgay** [refinedmods/refinedstorage#3554]
### Describe the bug

Server crash loop on boot after updating one of my all the mods 8 servers. 
https://mclo.gs/s9YcEqI

### How can we reproduce this bug or crash?

Update a modpack with the mod RS refinedstorage-1.11.6

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

.3.14

### What Refined Storage version is this happening on?

refinedstorage-1.11.6

### Relevant log output

```shell
https://mclo.gs/s9YcEqI
```

**Comment by raoulvdberge** [comment]
Sorry, 1.19.2 is no longer supported.
Also, a watchdog crash isn't helpful for our purposes.
