### ISSUE TITLE
client locked out of server

### ISSUE THREAD

**Issue by DarkShadow012** [refinedmods/refinedstorage#3556]
### Describe the bug

I play on my server with other 2 people on TNP Limitless 6 Modpack.
I created a compact machine enter it and when i started to put cables from refined storage to connect the machines from mekanism and refined storage, the server kicked me out and can't go in.

### How can we reproduce this bug or crash?

dont think i can reproduce

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.21

### What Refined Storage version is this happening on?

1.11.6

**Comment by DarkShadow012** [comment]
[latest.log](https://github.com/refinedmods/refinedstorage/files/12467655/latest.log)
and here is the log

**Comment by raoulvdberge** [comment]
See https://github.com/refinedmods/refinedstorage/issues/3424

**Comment by raoulvdberge** [comment]
Hello. This bug has been fixed in v1.12.4 of Refined Storage. If this issue persists anyway, please feel free to create a new bug.

**Comment by raoulvdberge** [comment]
This bug has also been fixed in **v1.11.7** of Refined Storage for **Minecraft 1.19.2**. If this issue persists anyway, please feel free to create a new bug.
