### ISSUE TITLE
Bug with using Crafting Cards

### ISSUE THREAD

**Issue by jenJennMC** [refinedmods/refinedstorage#3558]
### Describe the bug

something I've been dealing with for a while, so I'm more of just curious to know if anyone else has dealt with it: The RS crafting upgrade can cause items with zero value to appear in the crafting grid (both physical and wireless) and as a result, no items are able to be pulled out unless the gui is closed and reopened and its values are refreshed.

![image](https://github.com/refinedmods/refinedstorage/assets/143634479/9227e84c-28cf-4fe6-8803-a6f4439eae57)

### How can we reproduce this bug or crash?

have sugar in the system have milk in the system, and have a way for the system to be able to autocraft milk and sugar then put a crafting card in a constructor for cake 

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

36.2.39

### What Refined Storage version is this happening on?

1.9.18

**Comment by raoulvdberge** [comment]
Sorry, I can't reproduce this. Please try to reproduce with only RS installed.
