### ISSUE TITLE
1.20 curseforge

### ISSUE THREAD

**Issue by Dirkie04** [refinedmods/refinedstorage#3560]
### Describe the bug

im trying to use it on curseforge minecraft 1.20 buit it gives "This version is incompatible
 with the profile modloader
 Fabric)." and i cant select it on the browse mods search

### How can we reproduce this bug or crash?

start a 1.20.1 modpack 
cant select refined storage 
so downloaded it and put in the mod folder
error message This version is incompatible with the profile modloader (Fabric).

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

0.232.1.1

### What Refined Storage version is this happening on?

1.12.3

**Comment by raoulvdberge** [comment]
Read the error message.
