### ISSUE TITLE
items not showing up

### ISSUE THREAD

**Issue by REDSCULL-00** [refinedmods/refinedstorage#3562]
### Describe the bug

I would open my refine storage crafting grid and it would show me nothing even the settings is on display normal/ all default
i managed to semi fix it by crafting a grid and placing it but sometimes it doesn't work please fix this
doesn't

### How can we reproduce this bug or crash?

Open the crafting grid again and again 
Try going in and out of Chunk and have network transmitters and receivers to multiple locations

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

forge/1.19.2-43.2.20

### What Refined Storage version is this happening on?

1.11.6

**Comment by raoulvdberge** [comment]
Sorry, those reproduction steps are unusable
