### ISSUE TITLE
RS and Tom's Simple Storage instant crash - unable to reconnect afterwards

### ISSUE THREAD

**Issue by zayco15** [refinedmods/refinedstorage#3563]
### Describe the bug

I was making my RS network in order to stop using Tom's simple storage, everything went neat until I started placing the cables, which was what caused the crash. my Tom's simple storage network had over a thousand slots ocuppied and my RS crafting grid was next to Tom's Inventory Connector.

Crash Report: https://mclo.gs/akxFbbU

### How can we reproduce this bug or crash?

1. Have a fully working Tom's storage
2. Place a RF cable next to a connected Tom's simple storage cable
3. Instant crash - Even crashed the whole server
4. When trying to reconnect, the problem "Invalid player data" appears on screen each time

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

Forge Ver: 47.1.3

### What Refined Storage version is this happening on?

Refined Storage 1.12.3

**Comment by raoulvdberge** [comment]
Please see #3424 - this issue will be tackled there

**Comment by raoulvdberge** [comment]
Hello. This bug has been fixed in v1.12.4 of Refined Storage. If this issue persists anyway, please feel free to create a new bug.

**Comment by raoulvdberge** [comment]
This bug has also been fixed in **v1.11.7** of Refined Storage for **Minecraft 1.19.2**. If this issue persists anyway, please feel free to create a new bug.

**Comment by raoulvdberge** [comment]
Hello, this bug is now also fixed for Minecraft 1.18.2 in v1.10.6.
