### ISSUE TITLE
Broken controller transfer limit.

### ISSUE THREAD

**Issue by Techno2k** [refinedmods/refinedstorage#3565]
### Describe the bug

The controller's transfer rate is capped at 50% of max power capacity.

### How can we reproduce this bug or crash?

Place down a controller and a power sorce. 

build a system that uses above 50% of max capacity ~32K. 

and watch the system blink of lack of power. 

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43,2,14

### What Refined Storage version is this happening on?

1.11.6

**Comment by Darkere** [comment]
Some power transfer mods, reduce the tickrate of powertransfer to only run every second tick. In that case the controller runs out of power every second tick, as soon as you cross 16k.

The default values, make reaching 16k fe/t rather difficult. It's usually the result of some addon or config changes. Packmakers should be increasing the power buffer if they do add those mods. 

RS itself is fine using more than 16k if its there every tick. 
![image](https://github.com/refinedmods/refinedstorage/assets/4283717/27a1343a-fa17-4293-8e8b-eb50e03ffd52)
