### ISSUE TITLE
Cant pickup items on system

### ISSUE THREAD

**Issue by mariomteixeira** [refinedmods/refinedstorage#3566]
### Describe the bug

Playing on ATM9

When I enter in a Wireless Grid or a normal Crafting Terminal I can't pickup items, I need to close the terminal and re-open again to work.

### How can we reproduce this bug or crash?

1. A normal system (Controller, Crafting Grid, Crafters, Diskdrive)
2. Pickup some items on the system
3. After some items or even when trying to get the 1st item the item doesnt go to hand...

https://www.youtube.com/watch?v=cz0GVv3LlJA < Video about it

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.1.3

### What Refined Storage version is this happening on?

1.12.3

**Comment by tom89194** [comment]
I am having similar issues on the mechanical mastery modpack 
RS 1.10.5
When I first open a terminal I can remove items, but after a random amount of time I am no longer able to remove items.
The terminals are also getting a visual item duplication issue and usually the inability to pull items happens along with the appearance of visual item duplication. Reopening the terminal restores the ability to remove items for a few seconds.

**Comment by waleez1881** [comment]
i have the same problem now in ATM9 0.1.6 how to solve the issue ?

**Comment by raoulvdberge** [comment]
I think this is related to external storage updating - but I can't remember which issue this was

**Comment by tom89194** [comment]
I had an ext storage on a drawer system and also an emc link item that let the RS pull emc items directly. I had thought that maybe the speed at which item counts are modified on one or both of those two would be causing some sort of update issue...
So I tried without one and then without the other and also without both, I still had trouble with the system not letting me remove items in all three cases after the window was open for more than a few seconds. There may have been other ext storages in my system at the time I tried this, but they would have been on single block storages that were fed items fairly slowly and shouldn't be causing trouble unless there is a mod interaction issue with ext storage on certain blocks/mods that no matter how tame the item modification rate is there is a problem.

**Comment by raoulvdberge** [comment]
I found the issue: https://github.com/refinedmods/refinedstorage/issues/2568

**Comment by tom89194** [comment]
For anyone hunting for reasons that an RS system might be locking item extraction after the grid is opened for a few seconds:
I had external storages attached to output sides of mekanism factories and started having issues, even with only one of these with an external storage attached. 
I guess be very careful about the types of blocks you use external storages on.....
