### ISSUE TITLE
payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by Felkey** [refinedmods/refinedstorage#3568]
### Describe the bug

Players getting disconnected from server with the above error when tryIng to use the + button to fill the recipe for create's water wheel in jei. Happens when using the crafting grid and the wireless crafting grid (from the addon mod). Error does not happen when using a normal crafting table. 

Using version 1.11.6 on 1.19.2. Playing the ATM8 1.0.25 pack if that helps. 

### How can we reproduce this bug or crash?

See above

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.14

### What Refined Storage version is this happening on?

1.11.6

**Comment by Ronzan** [comment]
I get the same error in ATM9 0.1.12  - also when + clicking the create waterwheel recipe.
MC 1.20.1
Forge version 47.1.3

Only the client gets kicked and I can usually just reconnect again.

**Comment by raoulvdberge** [comment]
See #3450
