### ISSUE TITLE
Refined storage not refined enough

### ISSUE THREAD

**Issue by lucacelea** [refinedmods/refinedstorage#3569]
### Describe the bug

There is no tophat or monocle anywhere on the repository. Dissapointing

### How can we reproduce this bug or crash?

Look at the repository homepage

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

1

### What Refined Storage version is this happening on?

1

**Comment by raoulvdberge** [comment]
Not actionable
