### ISSUE TITLE
Machine input fluids get imported by importer

### ISSUE THREAD

**Issue by loving2** [refinedmods/refinedstorage#3570]
### Describe the bug

Machine fluid inputs can be taken from with the importer. When this happens, the fluid input does not update with a new value of fluid remaining. This results in fluid duping.

The importer does not take input items, so I expected it to do nothing for input fluids as well.

I concluded this must lie in RS and not GTCEu-Modern because I could also pull the input fluid out of the machine by using Create's fluid pipes and pump, which did update the fluid remaining value in the machine's input.

### How can we reproduce this bug or crash?

Unfortunately this requires a machine with a fluid input, in this instance it was found by testing with GregTechCEU Modern.
1. Install GregTechCEU Modern version 1.0.12.f from CurseForge
2. Install Refined Storage version 1.12.3
3. Make a new world
4. Set up an RS network with fluid storage
5. Place a Basic Chemical Reactor from GT down
6. Insert a bucket of rubber (or any other fluid) into any fluid input slot in the Basic Chemical Reactor
7. Place an importer on the Basic Chemical Reactor, in Fluid mode
8. Watch as you get infinite rubber (or any other fluid)

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.1.3

### What Refined Storage version is this happening on?

refinedstorage-1.12.3

**Comment by raoulvdberge** [comment]
Thank you! This has been fixed for the next RS release.
Gregtech will also be making a change as to not report these input slots as extractable.

**Comment by raoulvdberge** [comment]
This bug has been fixed in v1.12.4 for Minecraft 1.20.1 and v1.11.7 for Minecraft 1.19.2.
Thank you for reporting.

**Comment by raoulvdberge** [comment]
Hello, this bug is now also fixed for Minecraft 1.18.2 in v1.10.6.
