### ISSUE TITLE
Pattern Grid inventory should give out comparator signal

### ISSUE THREAD

**Issue by Ashenguard** [refinedmods/refinedstorage#3572]
### Describe your enhancement

I was thinking since you can feed a pattern grid with a hopper, Why not get a redstone signal out of it with a comparator...

### Why do I think it's useful? 
With an exporter and crafting upgrade, I can easily fill the pattern grid with patterns so I never run out of patterns... but a whole stack in there? That's too much...

With a comparator, we can get a signal when there is a pattern inside and we can disable the exporter so it doesn't fill the pattern grid and as soon as the pattern is used, another pattern should be crafted and placed inside...

**Comment by Darkere** [comment]
use a regulator upgrade instead
