### ISSUE TITLE
Search bar deselection

### ISSUE THREAD

**Issue by LeSwede** [refinedmods/refinedstorage#3579]
### Describe the bug

The only way to unselect the RS search bar is to either press Escape or Enter. Where as before you could just click anywhere in the grid and the bar would be unselected.

### How can we reproduce this bug or crash?

Just open any Grid and select the search bar. Click anywhere and the bar does not get deselected 

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.1.3

### What Refined Storage version is this happening on?

1.12.3

**Comment by raoulvdberge** [comment]
Hi, thank you for reporting. I will be investigating this for the next RS version.
