### ISSUE TITLE
crashing when opening the grid

### ISSUE THREAD

**Issue by KooKooGH** [refinedmods/refinedstorage#3585]
### Describe the bug

whenever opening the grid with a nbt item inside it it crashes the entire game and doesnt allow you to retrieve the items from inside

### How can we reproduce this bug or crash?

1. put a nbt item in the grid
2. try opening it

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.14

### What Refined Storage version is this happening on?

1.11.6

### Relevant log output

```shell
Internal Exception: java.lang.NullPointerException: Cannot invoke “net.minecraft.nbt.CompoundTag.m128425(String,int)” because nbt is null
```

**Comment by raoulvdberge** [comment]
That is not the complete log. Please provide the complete log

**Comment by KooKooGH** [comment]
its because of a memory overflow of nbt items. it overloads rs and causes a crash everytime you open the crafting grid. since if moved to ae2

**Comment by raoulvdberge** [comment]
Not sure if your explanation is correct since I can't verify the crash.

**Comment by KooKooGH** [comment]
Ill send the log in abt a day not around my pc at the moment
