### ISSUE TITLE
Set of 3 bugs, on 1.19.2 version of Monumental Experience pack, using refined storage (1.11.7)

### ISSUE THREAD

**Issue by mberlin1** [refinedmods/refinedstorage#3594]
### Describe the bug

3 bugs to go over:

bug 1:   have to pull network card in and out to get refined to work on startup

bug 2:   if accidentally click wireless crafting grid on a refined cable in another dimension, loses network until crouch clicking on any grid in the location of the actual controller

bug 3: even with the "accept alternates" nbt data on version 1.11.7 turned on, the recipes still don't seem to be able to handle items from modular router. in fact, if i craft one by hand, put it in the storage, and let the crafter craft one, they won't stack. ever.  When future recipes call on them, the crafter will refuse to put either of them out into a chest, even if they're produced by earlier recipes in the same sequence.    Strangely, if i ask an exporter to export all of that item, it'll export all of them.  It's the crafter itself that seems to have some sort of discrimination problems.  I'd be happy to provide pictures of the recipes, and the patterns if necessary.  I have also tried clearing out refined storage of all of these various creations, allowing it to only use the ones it has crafted itself. no dice.

### How can we reproduce this bug or crash?

reproduce bug 1:
1.  Start minecraft with an existing world containing refined storage setup
2.  have an ore generator working in another dimension, whose output is connected to a network receiver via an importer (in this case, a compact dimension)
3.  Ore and other items will sit in the generator's buffer until i go back to the overworld dimension where the controller is located, pull any network card and place it back into its slot.

reproduce bug 2:
1.  go into compact dimension (or any other)
2. right click wireless crafting grid onto refined  cable. Grid will instantly lose its network and "network unavailable" will show up in chat each time the device is clicked
3. going back to the controller's original dimension and clicking on any of the grids will restore its connection

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.3.5

### What Refined Storage version is this happening on?

1.11.7

### Relevant log output

```shell
If there are debug settings i can turn on to help with this effort i'd be happy to provide them.
```

**Comment by raoulvdberge** [comment]
Bug 1: Probably user error. Ensure all chunks are loaded.
Bug 2: Same as above.
Bug 3: Duplicate: #3363

**Comment by mberlin1** [comment]
That's a pretty glib answer.  All chunks are definitely loaded.   By two seperate loaders.     I can prove it if you'd like to hear the descriptio ninstead of blowing me off.

**Comment by Sandriell** [comment]
Also experience issue # 1 on 1.19.2.

Have to pull out and put back in the network card every time I load in on a dedicated server. Can assure the chunks are all loaded, because the network receiver is only 11 chunks away- I can see the chunk it is in.
