### ISSUE TITLE
Quick tabs between grids

### ISSUE THREAD

**Issue by Niklars** [refinedmods/refinedstorage#3596]
### Describe your enhancement

I think it would be really good to have quick tabs to switch between grids/monitors in similar way as the mod Tinkers Construct have when you switch between workbenches. 
It wuold make it faster and easier to switch between grids and monitors.

Example
![quick_tabs](https://github.com/refinedmods/refinedstorage/assets/500308/a3506721-1a72-493f-ba77-6150f3ce8c09)

Link to image also
https://imgur.com/a/BPAYTn5

**Comment by raoulvdberge** [comment]
Quick tabs? What do you mean by that?

**Comment by Niklars** [comment]
I mean, the small tabs up on top enables you to switch between the connected grids and monitors that you have connected to the system. Just like Thinkers Construct have for their workbenches. So you dont have to exit the screen and use another grid or monitor when you want to do another task.

**Comment by Niklars** [comment]
I made a gif to show.
https://imgur.com/a/QlmKNaH

**Comment by raoulvdberge** [comment]
Ah. No, that doesn't fit my vision of the mod. I don't like all GUI switching like that.
