### ISSUE TITLE
Refined Storage Tooltips are anchored in the wrong place.

### ISSUE THREAD

**Issue by RobinVanTol** [refinedmods/refinedstorage#3597]
### Describe the bug

Tooltips for non-inventory UI elements for Refined Storage are way off to the top left. Tooltips for items seem fine.

screenshots from this issue are the exact same as my issue: 
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2134

Posting on the main RS git since im having the same issue in a different pack and it didn't get fixed in the linked issue

### How can we reproduce this bug or crash?

make controller
hover power
make grid
hover settings on the side
set up autocrafting
make crafting monitor
order something for crafting
hover progress

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.14

### What Refined Storage version is this happening on?

1.11.6

**Comment by Darkere** [comment]
>  it didn't get fixed in the linked issue

It did get fixed in the linked issue. Meaning this is some other mod messing with with tooltips
