### ISSUE TITLE
Toggle Multiple Results from Same Pattern

### ISSUE THREAD

**Issue by JarethMaxter** [refinedmods/refinedstorage#3598]
### Describe your enhancement

I'm running both Refined Storage and The Aether.  If I go to a normal work bench, and I put in 4 gold in a diamond pattern, refined storage by default would make a Gold Gear.  However, this same pattern in The Aether makes a Gold Ring.  In a normal crafting bench I can click a button to change which output I am looking for, but I don't have this option within Refined Storage's crafting grid or pattern grid.  Is there a way we can add that sort of functionality for when multiple addons have the same patterns with very different outputs?

**Comment by raoulvdberge** [comment]
Pack devs need to avoid duplicate recipes.
However, I heard there is an addon "Refined Polymorphism" coming out soon.

**Comment by 62832** [comment]
You'll be happy to know that the aforementioned add-on is [now available](https://curseforge.com/minecraft/mc-mods/refined-polymorphism).
