### ISSUE TITLE
Wish for development.

### ISSUE THREAD

**Issue by NeffBr** [refinedmods/refinedstorage#3600]
### Describe your enhancement

Hi!
Please make it work :)
To have the EMC panel transfer the blocks learned in it via external storage bus to the creation terminal.
We are talking about such mods as: Refined Storage и ProjectE

**Comment by raoulvdberge** [comment]
I'm unable to understand your request

**Comment by jonatjano** [comment]
You can use the transmutation interface from (I think) project Expansion
