### ISSUE TITLE
Upgrade disk with items in

### ISSUE THREAD

**Issue by BooBooFastCat1** [refinedmods/refinedstorage#3607]
### Describe your enhancement

It would be a lot more convenient for upgrading my storage system i could put my 1k storage disk full of items into a crafting table with 2 1k storage parts and get a 4k disk with those items in

**Comment by jsProj** [comment]
I can vouch, having to transfer from thousands of items into bigger disks takes time, but feels right because simulates a downtime/infrastructure update.

**Comment by raoulvdberge** [comment]
This has been added for RS 2.
https://github.com/refinedmods/refinedstorage2/issues/658
