### ISSUE TITLE
Create vaults are compatible with the external storage system. They probably shouldn't be.

### ISSUE THREAD

**Issue by Linksapprentice** [refinedmods/refinedstorage#3608]
### Describe your enhancement

Create vaults, in most modpacks, are relatively early game. They offer a large amount of storage, at the cost of having no gui, meaning that to import and export to them you need hoppers, create contraptions, etc. When used with a refined storage system they offer over 200,000 storage capacity with none of the downsides of not having a gui. this basically sidesteps the need for storage disks in most modpacks with both mods. I say this, as a modpack dev myself, that would rather not take all of the use out of create vaults by changing the vaults recipe to make this combination less OP.  For reference, the recipe for a full size create vault from vanilla materials is about 4 stacks of iron and a stack of barrels.

**Comment by raoulvdberge** [comment]
It's not up to refined storage to make balancing decisions, but rather to the modpack author.

**Comment by Linksapprentice** [comment]
right right, but there's no way, as far as I'm aware to blacklist inventories from being read by the external storage blocks from refined storage.

**Comment by raoulvdberge** [comment]
We don't do blacklisting as it's confusing for the player. You'll have to change the recipe.
