### ISSUE TITLE
Filtering by mod in the exporter

### ISSUE THREAD

**Issue by anagram3k** [refinedmods/refinedstorage#3610]
### Describe the bug

I am trying to export items using a mod filter. The expected result would be the exporting of all items of a mod, but I can't make it work. 

### How can we reproduce this bug or crash?

My guess is the exporter does not work with a whitelisted Mod Filter. I don't have a log of this issue, but it should be very easy to test.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

47.2.16

### What Refined Storage version is this happening on?

1.12.4

**Comment by raoulvdberge** [comment]
This is not possible. A filter in an exporter does nothing.
