### ISSUE TITLE
Server crashes when opening a grid

### ISSUE THREAD

**Issue by oisjferf** [refinedmods/refinedstorage#3612]
### Describe the bug

My server crashes everytime I open the grid, if I rejoin the server and directly open the grid, 99% of the items are missing and after closing and reopening, crashes again. By the way, it only happened when my 1024k Storage card was full. I manipulated that card into a 262M Storage, but it also crashes when it reaches about 1.6-1.8 million items. I am playing the ATM8 [Modpack.] (url) https://youtu.be/nbQ4fnER_fQ Here is a video of my problem

### How can we reproduce this bug or crash?

1. Join server
2. have more than 1.6 million items on a 262M storage disk
3. many of those Items should be armor/tools

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.14

### What Refined Storage version is this happening on?

1.11.6

### Relevant log output

```shell
Connection Lost  Internal Exception: com.refinedstorage.network.PacketSplittintException: Failure Splitting Packets on Channel "refinedstorage:main_channel". Number of Packets sent 10. Number of Packets ecpected 12, maximum number of packets for a message of this type 0
```

**Comment by oisjferf** [comment]
Update: I updated my atm8 version, now the server isn´t crashing anymore, but my refined storage system is still glitched, the items are bugging and I can´t see the items except the items I freshly put in. It´s now the version 1.11.7. Another update: I found out, that the storage disks are bugged

**Comment by raoulvdberge** [comment]
You have too much unique items in your system. Try to remove some.
