### ISSUE TITLE
Controller does not light up if capacity is 0 and useEnergy is false

### ISSUE THREAD

**Issue by MarioSMB** [refinedmods/refinedstorage#3615]
### Describe the bug

I was testing 0 energy usage and capacity on all blocks (as I recall there may be some cases where useEnergy is not respected/available on some) and found that setting useEnergy = false and capacity = 0 in the controller section causes the controller itself to not light up (it still works by activating connected storage blocks).  
Giving it a capacity of 1 works around this allowing it to light up properly, but I thought I'd report the odd behaviour anyway!

### How can we reproduce this bug or crash?

N/A

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.17

### What Refined Storage version is this happening on?

1.12.4

**Comment by raoulvdberge** [comment]
Yes, that is normal. useEnergy stops the consumption of energy. If you change the capacity to 0, the network has no energy to use in the first place since there is no capacity for anything.

For this reason we're removing useEnergy in RS 2, it's confusing.
