### ISSUE TITLE
Items Disappeared from terminal but are still craftable

### ISSUE THREAD

**Issue by Jamesed619** [refinedmods/refinedstorage#3619]
### Describe the bug

I don't know how I did it, but the items are still there, but I can't grab them. The terminal is blank, but I can still craft with jei. Was hoping to find a way to show my items because I can't grab tools or anything. It pretty much started over my world.

### How can we reproduce this bug or crash?

Can't reproduce it.

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

beta

### What Refined Storage version is this happening on?

1.12.4

**Comment by Wulwsten** [comment]
![image](https://github.com/refinedmods/refinedstorage/assets/12305498/940d29e9-efbc-4c0d-a56b-722a0bb32dac)
Switch it up

**Comment by raoulvdberge** [comment]
Try to restart your client
