### ISSUE TITLE
fluids disappearing when crafted

### ISSUE THREAD

**Issue by Thekebabthief** [refinedmods/refinedstorage#3620]
### Describe the bug

craft any liquid if it goes into your storage it just deletes it i was doing it with gregtech liquids and mekanism liquids both destroyed also happans if you try to put a bucket into it as well

### How can we reproduce this bug or crash?

craft a liquid let it get imported into system

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.19

### What Refined Storage version is this happening on?

1.12.4

**Comment by raoulvdberge** [comment]
Bad reproduction steps
