### ISSUE TITLE
mark something as "not consumed" in autocrafting pattern

### ISSUE THREAD

**Issue by codethinki** [refinedmods/refinedstorage#3621]
### Describe your enhancement

I would like to know if there is a way to mark some item as "not consumed" in an autocrafting pattern. Because if i use the "philosophers stone" for turning n diamonds into n * 4 gold, the autocrafting system wants the resources for n philosophers stones, even tho it doesn't need them, it just needs one because its not consumed when crafting

**Comment by raoulvdberge** [comment]
Not planned.
