### ISSUE TITLE
Add Official NeoForge Support (Tag)

### ISSUE THREAD

**Issue by OracleHisty** [refinedmods/refinedstorage#3623]
### Describe your enhancement

On Modrinth and Curseforge as of now, the "Forge" version for 1.20.1 and above does not have a built-in tag for NeoForge, prior to the migration to their own codebase, despite currently being compatible functionally. I suggest since the NeoForge codebase will not diverge until 1.21, add the tag for such on the respective versions

> 1.20.1+ releases
> Prior to 1.21 being released.

**Comment by raoulvdberge** [comment]
Hello, thx for notifying me. I have made the changes to the 1.20.1 versions on curseforge and modrinth.
