### ISSUE TITLE
Issues interacting with Assorted Storage

### ISSUE THREAD

**Issue by DraconisLeonidas** [refinedmods/refinedstorage#3625]
### Describe the bug

While playing with a modpack, I've encountered an issue, and I'm unsure if it's an issue with Refined Storage or Assorted Storage, but I figure I might as well start here since, as far as I can tell, Assorted Storage is working properly. I'm using a bunch of crates because hopper botany pots are really nice, but when setting up my refined storage, I'm finding it's not properly interacting with the storage crate controller. The thing is, it IS interacting with it in some capacity. If I set the priority high on the 'external storage' part and the disk priority low, then try to input the item into the grid, the item is accepted and is properly transported to the crate. However, nothing is showing up on the grid itself, not even the item I just put in. The external storage part is properly set to allow both import and export, and according to what documentation is on their site, you should be able to get items out through it. Just to test, I also made a storage crate bridge and tried connecting that to the external storage, but it did nothing. Connecting the external storage directly to a crate properly shows that crate's contents, but only for that crate.

### How can we reproduce this bug or crash?

1. Install pack with Refined Storage and Assorted Storage ver 10.0.3
2. Set up network with Refined Storage
3. Set up a Storage Crate and a Storage Crate Controller
4. Set up External Storage connected to Controller
5. Check Grid (Items will not show up)
6. Attempt to insert items (so long as there's an empty slot in the crates and the external storage has highest priority, the item should properly go to the crate)

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.20

### What Refined Storage version is this happening on?

1.12.4

**Comment by Darkere** [comment]
This is something Assorted Storage would need to add.
