### ISSUE TITLE
Crafting Grid Inventory Dissapears

### ISSUE THREAD

**Issue by ManikFerret** [refinedmods/refinedstorage#3627]
### Describe the bug

after a set amount of items the refined storage inventory disappears from all interfaces while still existing and being able to be used in crafting recipes using JEI 

![image_2024-02-02_125730189](https://github.com/refinedmods/refinedstorage/assets/129821758/8f85ec8f-115e-4178-9d5c-821b211c903d)

### How can we reproduce this bug or crash?

Filling a storage system with all unique items like different kinds of armor and tools as well as mass amounts of blocks
unloading the chunk constantly 
having hundreds of crafting patterns exporters and importers 
try to overload the system 

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

forge-47.2.19

### What Refined Storage version is this happening on?

1.12.4

**Comment by raoulvdberge** [comment]
This is not a RS grid.
