### ISSUE TITLE
Unable to pull items out of the system.

### ISSUE THREAD

**Issue by phrostt** [refinedmods/refinedstorage#3628]
### Describe the bug

Can craft items, can insert items, but cannot pull any item out of the system by shift clicking, shift scrolling, or any other way. All other automation works.

### How can we reproduce this bug or crash?

Playing ATM9, late game, lots of automation and resources. Storage disk has 4.1m worth of items in it.

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.19

### What Refined Storage version is this happening on?

1.12.4

**Comment by daman540** [comment]
Currently dealing with the same issue. For now I'm moving to applied energistics 2 mod for storage.

**Comment by raoulvdberge** [comment]
Insufficient reproduction steps.
