### ISSUE TITLE
Network Receiver stops working when I'm offline 

### ISSUE THREAD

**Issue by elittsp** [refinedmods/refinedstorage#3629]
### Describe the bug

Using all the mods 9 currently. Server hosted, have both chunks in the overworld and chunks in Everbright dimension chunk loaded. When I log off the network receiver stops working as if it is no longer loaded and I need to remove network card and re-insert network card into the transmitter in order to kick start the system again. 

(in everbright dimension) Continues to work for approx. 5 minutes (maybe up to an hour, unsure) - then my exporters stop sending out raw ores to get processed because the network receiver is no longer connected.

I know other things are chunk loaded and working because I setup Solar Panels (in everbright) as my only power source and those continue to power everything in Overworld while im offline. 

### How can we reproduce this bug or crash?

1. Create system in overworld
2. Network Transmitter in overworld - chunk loaded
3. Network Receiver in Everbright Dimension - chunk loaded
4. Exporter into furnace from Network Receiver in Everbright
5. log off for 1-2hours

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

forge-47.2.19

### What Refined Storage version is this happening on?

1.12.4

**Comment by raoulvdberge** [comment]
#3609
