### ISSUE TITLE
pipeline issues

### ISSUE THREAD

**Issue by WindyJellyfish** [refinedmods/refinedstorage#3636]
### Describe the bug

its weird, the pipes from refined pipes dont work with anything except tanks from a completely different mod, no grid, no fluid storage block, just the tanks

### How can we reproduce this bug or crash?

just try adding water into the fluid grid (with the controller block active), using the disk drive with the right mode and the right disk, and a fluid storage device too, it just doesnt work

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.2.10

### What Refined Storage version is this happening on?

1.10.6

**Comment by raoulvdberge** [comment]
You need to add water via a fluid interface, if you're using pipes from refined pipes.

**Comment by WindyJellyfish** [comment]
none of the blocks work though, the fluid interface does not work
