### ISSUE TITLE
Move translations to Crowdin from the json files

### ISSUE THREAD

**Issue by GaalFlorian** [refinedmods/refinedstorage#3656]
### Describe your enhancement

I have seen many other mods and entities (examples: Mekanism, Forge, NeoForge) use Crowdin instead of having json-s for all language files in the repository. I was wondering if it would be worth the effort to do it for RS or RS2 as well.

To my understanding, it would make it so that translations could be provided without making changes to the repository. It also has the option to add context to the translatable texts, making it easier to provide an accurate translation.

I have no input on what the downsides are (other than the additional effort of making the change), as I've only used it as a translator and never as the owner of a repository.

**Comment by raoulvdberge** [comment]
Hi there, thanks, I've applied your suggestion.

Refined Storage 2 is now available on Crowdin: https://crowdin.com/project/refined-storage-2

Refined Storage 1.x will not be available on Crowdin.
