### ISSUE TITLE
Storage Monitor should work with hoppers and pipes

### ISSUE THREAD

**Issue by djmattyg007** [refinedmods/refinedstorage#3658]
### Describe your enhancement

I should be able to insert and extract items to and from storage monitors with hoppers and pipes. In some cases this could be a much friendlier way of utilising Refined Storage in automation that isn't aware of Refined Storage. This would be a nicer way to implement certain automation compared to using an exporter on a chest.

**Comment by raoulvdberge** [comment]
We have the "interface" for that use case
