### ISSUE TITLE
Crash on Server launch

### ISSUE THREAD

**Issue by IndecisiveZuri** [refinedmods/refinedstorage#3660]
### Describe the bug

Whenever I launch my server I keep getting crashes shortly after it starts giving a crash report pointing towards Refined Storage. Was wondering if I can get some eyes on this to see if it's maybe a conflict of mods or a bug with RS since I only get crash logs pointing at refined storage just before the crash. 

Additional information: I'm running mods from modpack ATM9.

[crash-2024-03-21_20.00.46-server.txt](https://github.com/refinedmods/refinedstorage/files/14716789/crash-2024-03-21_20.00.46-server.txt)

[latest.log](https://github.com/refinedmods/refinedstorage/files/14716883/latest.log)

### How can we reproduce this bug or crash?

It crashes every time I start up within a minute after GUI comes up. (tried disabling GUI and still same crash)

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

47.2.20

### What Refined Storage version is this happening on?

v1.12.4

**Comment by Darkere** [comment]
Try increasing Max-Tick-Time in server.properties. Adding a 0 at the end works

**Comment by IndecisiveZuri** [comment]
@Darkere Yeah that helped thank you so much, honestly sorta surprised that was all it was.
