### ISSUE TITLE
Chunk loader

### ISSUE THREAD

**Issue by BooBooFastCat1** [refinedmods/refinedstorage#3666]
### Describe your enhancement

Network Receivers and Transmitters only work when chunk-loaded and it can be quite inconvenient when covering large distances or to different dimensions

**Comment by raoulvdberge** [comment]
Sorry, out of scope for RS.
https://refinedmods.com/refined-storage/faq.html#_not_including_x_in_refined_storage_makes_this_mod_useless_when_mods_like_y_arent_installed
