### ISSUE TITLE
Sortable priority for crafters

### ISSUE THREAD

**Issue by Nodrance** [refinedmods/refinedstorage#3670]
### Describe your enhancement

When crafting a recipe, search every available pattern according to a user defined priority. Use higher priority crafters until you run out of raw materials to support them, then move on to lower priority ones. For example, you might have a recipe like "crush raw ores if possible, and if there are no raw ores to crush, crush ingots instead" with two different crafters at different priorities.

**Comment by raoulvdberge** [comment]
Crafter priority is already planned for RS 2.
