### ISSUE TITLE
Advanced crafting grid with option to autocraft missing items

### ISSUE THREAD

**Issue by Nodrance** [refinedmods/refinedstorage#3671]
### Describe your enhancement

When you paste a recipe from JEI into an advanced crafting grid:
- Show any items that aren't in storage with a red 0
- - This 0 behaviour should also occur when you run out of an ingredient while crafting
- For any items that are autocraftable, have them with a blue background. Have right clicking remove them, and left clicking open the craft dialogue for that item
- There should also be a "craft missing ingredients" or "craft recipe" button, that opens a crafting dialogue for all of the components of a recipe, or for the recipe as if it had a pattern. 
- It would also be nice if it was possible to automatically add a recipe to an available autocrafter, but I understand that would be pretty difficult

This would significantly speed up the workflow for crafting new things, for example you could set up a recipe for processors and quartz iron, then easily craft most RS things by just using the "craft ingredients" button. For the purposes of code, the grid would act like a crafter, that can make and manage virtual patterns. 

This should require some sort of highly expensive item, such as a nether star or netherite block. The recipe I envisioned was a crafting grid, nether star, 4 crafters, 2 advanced processors, and a pattern.

**Comment by raoulvdberge** [comment]
This already exists?

**Comment by Nodrance** [comment]
Oh, sorry about that. Nothing like that exists in the modpack version I'm playing, you need to make a pattern for every single recipe. Maybe I should see about upgrading

**Comment by raoulvdberge** [comment]
Patterns need to always be created manually, but the JEI integrations you're talking about are already there.

**Comment by Nodrance** [comment]
Maybe my suggestion was unclear. If you press + on a recipe for an iron
shovel, but you don't have sticks, you'll get the recipe for iron nuggets.
I'm suggesting that instead, you get the recipe for a shovel, and you can
press a button to autocraft the missing sticks, if you have a pattern for
them.

**Comment by Darkere** [comment]
Already exists. Check the tooltip when hovering over the + icon.
