### ISSUE TITLE
[1.20.1] Refined Storages crashes server

### ISSUE THREAD

**Issue by NikeSchuh** [refinedmods/refinedstorage#3672]
### Describe the bug

When starting the server it starts totally fine then instantly starts to hang until watchdog closes the server.

### How can we reproduce this bug or crash?

1.Start the server

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.21

### What Refined Storage version is this happening on?

1.12.4

### Relevant log output

```shell
https://hastebin.com/share/ridonewajo.perl
```

**Comment by raoulvdberge** [comment]
Increase the watchdag timeout setting (look up previous issues)
