### ISSUE TITLE
Ability to drag drop fluids from JEI just like you can drag drop items

### ISSUE THREAD

**Issue by mk0003** [refinedmods/refinedstorage#3675]
### Describe your enhancement

You can drag drop items from JEI to exporters, importers, external storages, interfaces etc. But you can't drag drop water, lava or modded fluids to them when they are in fluid mode. You have to have the fluid ready in your inventory always if you are using any fluid regularly. But if you able to drag drop the fluid it would be a lot nicer than clogging your inventory with buckets or tanks.

**Comment by raoulvdberge** [comment]
You can! Which version are you on?

**Comment by mk0003** [comment]
Minecraft 1.20.1 RS 1.12.4 i tried with minimal mods but it wasn't working with fluids.

**Comment by mk0003** [comment]
I just created an instance with only JEI and RS without GregTech and other mods to see if has any effect but it still not working.
Minecraft 1.20.1
JEI version 15.3.0.4
Forge version 47.2.23
RS version 1.12.4
Latest log: [link](https://paste.atlauncher.com/view/905d9332-13a8-43e6-b7ef-5145f02df701)

**Comment by jzburda** [comment]
Can confirm, you CANNOT use buckets while the pattern grid is in fluid mode. It just doesn't work. You CAN however specify the fluids using a crafting recipe.

This hurts in fringe cases like doing Extreme Reactors autocrafting.

**Comment by raoulvdberge** [comment]
This has been fixed for RS 2.
