### ISSUE TITLE
Crafter Manager - Hide Consecutive Empty Rows Option

### ISSUE THREAD

**Issue by Peekofwar** [refinedmods/refinedstorage#3679]
### Describe your enhancement

If you have a lot of crafters, and a lot of empty slots, it would be nice if there was an option to toggle hiding consecutive empty rows in crafter sections in the crafter manager terminal. 

This would display all rows that have items in them, and after the last row containing items it would show only one empty row (if any). All further rows would be hidden.

![image](https://github.com/refinedmods/refinedstorage/assets/10189526/2d40963f-4933-46eb-bbd9-ad7e5e434478)

**Comment by raoulvdberge** [comment]
I think it's good to always give a complete picture of the slots. Filtering them away might become confusing, especially if we dynamically add more of them.

**Comment by Peekofwar** [comment]
> I think it's good to always give a complete picture of the slots. Filtering them away might become confusing, especially if we dynamically add more of them.

To be fair, I was thinking of it being an option the user could toggle. The default view would show all. I just thought it might make it easier to scroll through all of my machines if there was less empty space taking up the UI. _It's my fault for building all those crafters._
