### ISSUE TITLE
Duplication when crafting from Sophisticated Storage

### ISSUE THREAD

**Issue by puggan** [refinedmods/refinedstorage#3682]
### Describe the bug

Item duplication when crafting from item stored in Sophisticated Storage

reproducable in 1.12.4
All Versions: 
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/eddb708b-0e4e-4f0e-8444-98b210a231b9)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/b78a213a-5d22-4a9c-9343-42c9e56b031b)

Also reported to Sophisticated Storage at https://github.com/P3pp3rF1y/SophisticatedStorage/issues/421

### How can we reproduce this bug or crash?

Setup for reproducing:
* Refine Storage Crafting Grid
* Refine Storage Controller (Creative to skip adding powersource)
* Refiine Storage External Storage
* Netherite chest with 2 stack upgrades
* 18 stacks of redstone dust
![2024-05-18_14 41 41](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/06cbd806-76e0-4928-b01f-f86c9c6fde7f)
![2024-05-18_14 41 39](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/649d8712-3244-48bd-9f95-12f04291042e)

Reproduce:
* Use the Crafting Grid to Craft Redstone Blocks, by shift-clicking to make a full stack

Expected:
* 18 stack of redstone -> 2 stack of redstone block

Current Behaviour:
* 18 stack of redstone -> 9 stack of redstone block

![2024-05-18_14 48 19](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/8da7eba4-c65f-4589-8437-83ad0c83653d)

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

 Expected: * 18 stack of redstone -> 2 stack of redstone block

### What Refined Storage version is this happening on?

1.12.4

**Comment by puggan** [comment]
The Stack upgrades, letting you have more then 64 items in the same stack seams to be an important part of the problem.

**Comment by starforcraft** [comment]
https://github.com/refinedmods/refinedstorage/pull/3669

**Comment by puggan** [comment]
Also a problem with Dank. Not as much duplication, but still duplication.
![image](https://github.com/refinedmods/refinedstorage/assets/866668/55efae1a-e7fd-4c68-b8d4-ee216dc2720e)
![2024-05-18_15 20 36](https://github.com/refinedmods/refinedstorage/assets/866668/a16d1d1b-3c71-4665-8d3e-93bff97622f5)
![2024-05-18_15 20 51](https://github.com/refinedmods/refinedstorage/assets/866668/7f49adfe-51bf-47b0-9164-22ef65396906)

**Comment by puggan** [comment]
Duplicate of https://github.com/refinedmods/refinedstorage/issues/3640
