### ISSUE TITLE
External Storage

### ISSUE THREAD

**Issue by Babillabux** [refinedmods/refinedstorage#3689]
### Describe the bug

When i use an external storage that receive a redstone signal and the external storage is configured on "ignore redstone", then i can't take any item in my storage

### How can we reproduce this bug or crash?

I did it with the mod Storage Drawer in 1.20.1 with the Redstone Upgrade, I placed the external storage above the drawer, and the bug is here (the external storage is configured with "ignore redstone signal")

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.0

### What Refined Storage version is this happening on?

1.12.4

### Relevant log output

```shell
that's not create a crash while playing
```

**Comment by Nodrance** [comment]
Can you join the official discord and give more details? Like a screenshot
