### ISSUE TITLE
Crafting preview calculation

### ISSUE THREAD

**Issue by DomitillePottier** [refinedmods/refinedstorage#3690]
### Describe the bug

Hi !

I've got an issue when trying to craft some items that need a lot of sub-crafts. All the patterns needed are given, but when I try to launch the craft, the crafting preview don't show all the items needed.
It's been two hours that we're trying to debug this, but we didn't find any solution.

![image](https://github.com/refinedmods/refinedstorage/assets/55233473/577b5fe4-f132-497e-87c8-6a0c696e752c)
![image](https://github.com/refinedmods/refinedstorage/assets/55233473/a8568330-7183-4dce-b778-5d9b57f9b7ac)

For example, when I try to craft an infinite disk, the crafting preview doesn't show me all the items needed but juste the 16384k storage part, although I have given the corresponding pattern...
I have smelting factories that work fine.

### How can we reproduce this bug or crash?

1. Click on the craft in the crafting grid.
2. Press start

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

47.2.30

### What Refined Storage version is this happening on?

1.12.4

**Comment by raoulvdberge** [comment]
We can't help you with this bug report. It's not detailed enough. Please head to the discord for support questions.
