### ISSUE TITLE
Suggestion: Diagnoser

### ISSUE THREAD

**Issue by Nodrance** [refinedmods/refinedstorage#3691]
### Describe your enhancement

A wrench-like tool crafter from a few processors and stuff. When you right click a block, it tells you why it might not be working. Examples:

- This grid isn't getting enough power, and so you cannot withdraw items from it.
- This grid is showing no items because all of the storages it is attached to are insert only
- This importer isn't running because it's set to need a redstone signal
- This crafter is currently working fine, but recently failed because there was no room in the target block, or the target block doesn't have an input on that side.
- This crafter is trying to use a processing pattern but is facing air. You want the side with the circle to be facing into the factory, It's directional, like a dispenser. 

Essentially, every time a block runs its code and it does anything other than work like a newbie would expect, it will write a human readable message about why to an internal string buffer. If it does work, it won't immediately clear the buffer, but it will log that it's worked since the last error. Then, right clicking with the diagnoser will print that message to chat. 

I think this will make the mod even easier for newbies, while also cutting down on the number of support requests in the discord.

**Comment by raoulvdberge** [comment]
I think such a tool is bad design. The mod should signify the problem in the source block itself, not provide some diagnoser tool that users don't know when to use or when it's going to be relevant ("I have used the tool but it doesn't tell me anything!").
 
> This grid isn't getting enough power, and so you cannot withdraw items from it.

The grid will have an "off" texture.

> This grid is showing no items because all of the storages it is attached to are insert only

Insert-only storages in RS2 now *do* show the items.

> This importer isn't running because it's set to need a redstone signal

You configure this explicitly. The concept of redstone signal is also present in other mods so I don't think we need to make this even clearer.


> This crafter is currently working fine, but recently failed because there was no room in the target block, or the target block doesn't have an input on that side.

This is displayed in the crafting monitor, which is your diagnoser tool for that.

> This crafter is trying to use a processing pattern but is facing air. You want the side with the circle to be facing into the factory, It's directional, like a dispenser.

Same as above.

**Comment by Nodrance** [comment]
These situations are pretty obvious in the game, but we still get lots of people joining the discord to ask about them, and probably a lot more than never think to join. I don't think having an additional idiot's tool would be a bad thing, as long as it doesn't become a crutch to avoid adding other ways of explaining what's wrong.

**Comment by raoulvdberge** [comment]
We should be thinking how to make the current misunderstandings more clear, before thinking about adding a crutch.
