### ISSUE TITLE
Wireless crafting grid voiding items

### ISSUE THREAD

**Issue by 0GuiPereira** [refinedmods/refinedstorage#3694]
### Describe the bug

When using the wireless crafting grid (I tried with all of them), items placed in the 3x3 crafting grid are voided if the inventory is closed, reopening only shows 2 items in the 3x3 grid and 2 items in a 2x1 grid (see screenshots). This leads to the loss of materials, which is not the expected behavior.

Playing on ATM9 0.2.59

### How can we reproduce this bug or crash?

1. 18 blocks of gray concrete powder
![Screenshot (530) 04h-37m-12s 31-05-2024](https://github.com/refinedmods/refinedstorage/assets/90417799/a3bb9c08-eb05-4b3f-9628-5b0f4e699bf1)

2. put 9 in the 3x3 crafting grid
![Screenshot (531) 04h-37m-20s 31-05-2024](https://github.com/refinedmods/refinedstorage/assets/90417799/b74e77f3-b1b6-48b1-8d2f-496e9612368c)

3. closed and reopened the wireless crafting grid
![Screenshot (532) 04h-37m-38s 31-05-2024](https://github.com/refinedmods/refinedstorage/assets/90417799/c7ab19ca-ceab-4c09-b02e-57264c608ab9)

4. 5 blocks of gray concrete powder disappeared after closing and reopening the wireless crafting grid
![Screenshot (533) 04h-37m-44s 31-05-2024](https://github.com/refinedmods/refinedstorage/assets/90417799/977b3b43-79b3-4068-b33c-53a7579fe5a9)

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

forge-1.20.1-47.2.20

### What Refined Storage version is this happening on?

1.12.4

### Relevant log output

```shell
Not Relevant
```

**Comment by Nodrance** [comment]
It's a problem with the 2 slots to the right, under the 4. Remove the mod that adds them, or fill them.

**Comment by starforcraft** [comment]
Update ATM 9 or RS Insert Export Upgrade
