### ISSUE TITLE
search bar when searching for tag alternatives in the pattern grid

### ISSUE THREAD

**Issue by cauamachado51** [refinedmods/refinedstorage#3695]
### Describe your enhancement

I just wanted to make clear my complete dissatisfaction with not having a search bar when searching for alternatives by item tag in the patterns grid. IT TAKES TOO LONG to search through that pile of items/tags, in such a small interface, it should at least cover the screen.

refinedstorage-1.12.4.jar

**Comment by raoulvdberge** [comment]
Hi, thank you for the suggestion. This is a duplicate of https://github.com/refinedmods/refinedstorage/issues/3333 and you can now search for alternatives in RS2. This is how it looks like:

![image](https://github.com/user-attachments/assets/ea7dc838-cba5-4094-a176-d76d986f358d)
