### ISSUE TITLE
(1.20.1) Item Copy When Using Wireless Grid

### ISSUE THREAD

**Issue by LocketGoma** [refinedmods/refinedstorage#3696]
### Describe the bug

* I Useing ATM9 Modpacks, has Refined Strorage / Refined Storage Addons Mod
If use Crafting table in Wireless Crafting Grid, Can Copy Items

![image](https://github.com/refinedmods/refinedstorage/assets/16269328/5c9657db-b2df-4835-83aa-be5bc9ec804e)
![image](https://github.com/refinedmods/refinedstorage/assets/16269328/efb6771e-0278-4901-8c54-504f8e181f29)

### How can we reproduce this bug or crash?

1. Open Wireliss Crafting Grid
2. Set any Item On Crafting Table UI(in Numpad, 7,8)
3. Close HUD (pusy ESC, etc)
4. Re-Open

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.20

### What Refined Storage version is this happening on?

1.12.4 / 0.10.0

**Comment by starforcraft** [comment]
Duplicate https://github.com/refinedmods/refinedstorage/issues/3694 (Update ATM 9 or RS Insert Export Upgrade)
