### ISSUE TITLE
Add button (alt/midle mouse button) to open request window to craft items in Refined Storage monitor (like in ae2)

### ISSUE THREAD

**Issue by max0n4ik** [refinedmods/refinedstorage#3698]
### Describe your enhancement

Add button (alt/midle mouse button) to open request window to craft items in Refined Storage monitor (like in ae2)

when I hold (alt/middle button) down the button by pointing the cursor at an object that I can do with an autocraft,, , the word craft is displayed

**Comment by Nodrance** [comment]
ctrl shift click to craft an item you already have

**Comment by max0n4ik** [comment]
> ctrl shift click to craft an item you already have

why this so secret information. thx a lot
