### ISSUE TITLE
1.20.1 Detector not measuring fluids in the system correctly

### ISSUE THREAD

**Issue by Cragsand** [refinedmods/refinedstorage#3704]
### Describe the bug

1. Place a detector
2. Set the detector to measure fluids
3. Set the detector to emit redstone signal below 50 buckets
4. Redstone signal is not emitted

### How can we reproduce this bug or crash?

There is no crash. Could be because of incompatibility with other mods. I tried disabling one after another but the bug still occurs so was unable to figure out any workaround. Log with all the mods and versions loaded: https://gist.github.com/Cragsand/13b0fb7bd1f5c78586911aa2368257f5

- Emit signal when on the amount = Never outputs any signal
- Emit signal when above the amount = Always outputs a signal
- Emit signal when below the amount = Never outputs any signal

Short GIF video showing the problem:
![ezgif-2-971a4bd680](https://github.com/refinedmods/refinedstorage/assets/49168045/4b56635b-7625-43b9-8ed8-0b25d0103980)

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

NeoForge 47.1.105

### What Refined Storage version is this happening on?

refinedstorage-1.12.4.jar

### Relevant log output

```shell
Log with list of mods being loaded
https://gist.github.com/Cragsand/13b0fb7bd1f5c78586911aa2368257f5
```

**Comment by jonatjano** [comment]
Fluid amount in detectors are expressed in mB, meaning you need to set it 60 000 in order to say 60 buckets

**Comment by Cragsand** [comment]
> Fluid amount in detectors are expressed in mB, meaning you need to set it 60 000 in order to say 60 buckets

Thank you for clarifying! Totally my bad. Closing the issue! 😊
