### ISSUE TITLE
Infinite speed upgrade if you click with the middle mouse wheel on requestify

### ISSUE THREAD

**Issue by giacomocavera** [refinedmods/refinedstorage#3705]
### Describe the bug

If you click with the middle mouse wheel on requestify the pattern inserted is deleted and appear 4 speed upgrade

### How can we reproduce this bug or crash?

1. Click on requestify
2. Click the middle mouse wheel
3. Speed upgrade appear

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.3.2

### What Refined Storage version is this happening on?

1.11.7

**Comment by raoulvdberge** [comment]
wrong repo

**Comment by giacomocavera** [comment]
if you want I can send you a video

**Comment by Nodrance** [comment]
This is not the place for requestify issues, this is the refined storage repo, not the requestify repo. We do not make requestify
