### ISSUE TITLE
Crash: Because 'nbt' is null

### ISSUE THREAD

**Issue by Waterspark63** [refinedmods/refinedstorage#3706]
### Describe the bug

When attempting to open a grid, the client crashes and kicks the player from the server.
There's the latest.log:
[latest.log](https://github.com/user-attachments/files/16057705/latest.log)

It seems the latest.log is missing some logging, so heres the log from the launcher:
https://gist.github.com/Waterspark63/2044556c6d4553884d6176370b1deb95

As well as this is the error on the clients screen that doesn't seem to show in logs:
`Internal Exception: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128425_(String, Int)" because "nbt" is null.`

### How can we reproduce this bug or crash?

1. Create RS System
2. Throw some items with nbt into the grid (not sure what exactly was thrown in as the player doesn't remember)
3. Try to open the grid.
4. Client side crash.

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.30

### What Refined Storage version is this happening on?

1.12.4

**Comment by Nodrance** [comment]
Most likely, you put in some kind of bugged item and that's causing the issues

**Comment by Waterspark63** [comment]
Looked into the refined storage disks.dat, and isolated the item in question, it was a inventory pets chest pet, with items inside it.
The nbt for the chest pet just includes `Damage: 0`, and nothing else. Is that normal?

**Comment by Nodrance** [comment]
Does this always happen when you put in a chest pet?

**Comment by Waterspark63** [comment]
I just played with the chest pet, putting a empty, or a low filled one (just put a torch, and 4 empty 64k disks) into the disk doesn't seem to have any issues. It might be if the chest is absolutely full (possibly with nbt items of its own), it might bug out.

Filled the chest pet entirely with iron, 4 64k disks, and a torch, and it doesn't kick it. Might be a corrupted item, so I'm gonna close this for now.
