### ISSUE TITLE
Wireless Range

### ISSUE THREAD

**Issue by Quest79** [refinedmods/refinedstorage#3710]
### Describe your enhancement

1.20.1+

Im not sure if this is a config I haven't found but its a joke that 48m is the max distance of this thing and if I want more I have to download another mod for infinity. 48m or infinity are the options? Really?

Please allow Range Upgrades to stack inside the Wireless Transmitter. Upto 8 or 64 or a million who cares?. Slap a power cost on it of course per upgrade and please make it configurable so packs can adjust. I personally just need like 300m and wiring down wireless transmitters all over my base defeats the purpose.

**Comment by Darkere** [comment]
can be configured in the serverconfig
