### ISSUE TITLE
CRTL+SHIFT No Item Recipe Indication

### ISSUE THREAD

**Issue by Peekofwar** [refinedmods/refinedstorage#3722]
### Describe your enhancement

I discovered that if I hold down CTRL and SHIFT when clicking on an item in my RS system, it will bring up the crafting menu instead of grabbing the items that are in-stock. 

What I would like to see however, is some kind of indication that an item doesn't have a recipe in the system. In fact, what I think would work is if the item count would change to CRAFT when holding down SHIFT and CTRL, and items that don't have a recipe would be grayed out.

Currently, when holding CTRL and SHIFT, the UI doesn't show any indication that you are able to click to craft on an item that is in-stock. Furthermore, if you click on an in-stock item that doesn't have a recipe while holding down the CRTL and SHIFT keys, it will instead just transfer the item into your inventory rather than showing some kind of "no pattern" error message.

By "in-stock," I am referring to items in an RS system that have a quantity greater than zero.

**Comment by raoulvdberge** [comment]
In RS2, craftable items will get a "crafting" icon next to the item/fluid.
See: https://github.com/refinedmods/refinedstorage2/issues/98
Let me know if this will fix your issue. If not, I'll reopen, and we discuss further.
