### ISSUE TITLE
Filter tab does not appear in the crafting grid

### ISSUE THREAD

**Issue by mbertalan** [refinedmods/refinedstorage#3726]
### Describe the bug

The filter itself works, but for some reason, the tab on top of the grid is not showing up. 

### How can we reproduce this bug or crash?

[Uploading Vault Hunters 3rd Edition-3.15.1.3.zip…]()

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

1.258.0-19849

### What Refined Storage version is this happening on?

1.20.4

**Comment by raoulvdberge** [comment]
Dumping a zip are no reproduction steps.
