### ISSUE TITLE
Item/Fluid mode switch button missing.

### ISSUE THREAD

**Issue by SquidNeko** [refinedmods/refinedstorage#3729]
### Describe the bug

Im playing the modpack atm9 where refined storage is in.
In any of the grids the button is missing.

Its specially critical in the Pattern Grid where the mode switch is missing, as i cannot switch to use the fluids in the recipes thats in my storage.

Atm9 mod dev told me is a bug with this mod and not their modpack.

Also its described here: https://refinedmods.com/refined-storage/autocrafting/fluid-autocrafting.html#_creation_of_the_mixed_pattern

### How can we reproduce this bug or crash?

Open Pattern Grid with items and fluids in storage.
Button for switching item/fluid modes on left side is gone.

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.20

### What Refined Storage version is this happening on?

1.12.4

**Comment by Darkere** [comment]
The button has moved and is now where exact mode is found for crafting grids when switching to processing mode

**Comment by SquidNeko** [comment]
If you mean the fluid checkmark box. It doesnt switch the grid to fluid mode.

**Comment by Darkere** [comment]
The button is just for defining fluids for patterns. There is no and never was a way to see stored fluids in the pattern grid in RS1
