### ISSUE TITLE
Controller only recognizes connected entities in its chunk on load

### ISSUE THREAD

**Issue by mcronald-1** [refinedmods/refinedstorage#3730]
### Describe the bug

When loading into a saved world only the connected entities (cables, importers, exporters, etc.) in the controller's chunk are recognized.

### How can we reproduce this bug or crash?

1. Place a controller
2. Connect entities to controller that are outside the controller's chunk
3. Save world
4. Load world
5. Observe controller and confirm that only entities within its chunk are recognized

Before re-load:

![BeforeSave](https://github.com/user-attachments/assets/00de4afa-01b9-4d94-a16f-e12ee41e2497)

After world load:

![AfterLoad](https://github.com/user-attachments/assets/d2c5761d-94de-49e7-9972-2fac4568ae1c)

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.3.7

### What Refined Storage version is this happening on?

1.12.4

**Comment by Nodrance** [comment]
what modpack is this?

**Comment by mcronald-1** [comment]
> what modpack is this?

It's a custom pack
[Mod list](https://pastebin.com/aFTn6QcE)

**Comment by mcronald-1** [comment]
Was playing again today and suddenly it's working properly again. Not sure what changed, but I'll close this issue as it may not be as repeatable as I thought.
