### ISSUE TITLE
refined storage 

### ISSUE THREAD

**Issue by M0xiito** [refinedmods/refinedstorage#3733]
### Describe your enhancement

Please can you tell me when the update to refined storage version 1.21 will be released?

**Comment by Nodrance** [comment]
When rs2 is done in a few months, it will be on 1.21

**Comment by M0xiito** [comment]
will the textures be changed?

**Comment by Nodrance** [comment]
Join the discord

**Comment by M0xiito** [comment]
Can I have a link?

**Comment by Nodrance** [comment]
https://github.com/refinedmods/refinedstorage

and then scroll down
