### ISSUE TITLE
Autocraft starter

### ISSUE THREAD

**Issue by Nodrance** [refinedmods/refinedstorage#3738]
### Describe your enhancement

A block that, when pulsed (or when a signal is present and no job is in progress), will start an autocrafting job. This would eliminate the need for weird systems with the crafting upgrade on an exporter, and allow you to simply begin an autocrafting job using automation, with whatever complicated conditions you want to wire into your system

**Comment by raoulvdberge** [comment]
It's a good addon idea, perhaps something for RS Requestify? But not for base RS.
