### ISSUE TITLE
Disk drive multiplies items???

### ISSUE THREAD

**Issue by kendragster** [refinedmods/refinedstorage#3742]
### Describe the bug

When i put for example, 320 of charcoal on the grid (i have like 30 disk drives connected together), when i reload the world, the grid shows 50k of charcoal or more man, is hard to explain, there is some pics.

### How can we reproduce this bug or crash?

1. Put atleast 30 disk drives in columns of 3x1 side by side like my screenshot.
2. Fill them with storage disk, mybe 64k will work.
3. try putting 128 diamonds on the grid, and reload the world.
![image_2024-12-22_172715659](https://github.com/user-attachments/assets/45220a06-6f88-4261-ade0-3682e62643e0)

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.3.12

### What Refined Storage version is this happening on?

1.12.4

**Comment by Nodrance** [comment]
Are they "real"? Can you take them all out and hold them all at the same time? 

If yes, this is a bug

If no, you somehow duplicated a disk and now you have the equivalent of looking in the left half of a double chest, looking in the right half, and assuming you have twice as many items. (each duplicated disk points to the same internal inventory, like an ender chest)

**Comment by kendragster** [comment]
Well, its a bug then T-T, you know something about it?

**Comment by Nodrance** [comment]
So you can hold them all in your inventory at once?

That sounds like a bug. I don't know anything about it, I'm not the dev, I just know people sometimes do the second thing and think it's a bug when it's not.

**Comment by kendragster** [comment]
No no sorry, i can't, look at this
![image_2024-12-22_181219731](https://github.com/user-attachments/assets/237e4337-6692-470f-bb74-0ed52550c66f)
Im using a digital miner of another mod and using the transmitter and receiver to transport them, when they arrive, for example 60 emeralds arrive to the disks, when i reload the world, there are like 4k emeralds, but when i click, it only gives me the 60 emeralds i got before, but the grid tells me that 3940 emeralds are still there, but when i try to get them out, i can't, they just stick there, when i retire the emeralds and reload the world, the grid dont shows the bug amount of emeralds, and when i place them again everything is normal, then thing is when i reload thwe world, and the disk drives, because i have a system with storage drawers and that doesn't happen bro

**Comment by Nodrance** [comment]
I think your problem is that instead of crafting a bunch of different disks, you have copies of the same disk. Empty them all (you can do this one at a time), hold them in your hand, shift right click to break them apart, and then craft them again. This should probably fix the issue

**Comment by kendragster** [comment]
![image_2024-12-22_182647115](https://github.com/user-attachments/assets/04108879-0415-4dd6-b78b-824c11f0dfd5)
Mate thank you, and yeah, my disk drives had the same code, i had a lot of the same disks as you said, thank you bro i really apreciate this, i been searching about this for 4 hours, again thank you :3.

**Comment by kendragster** [comment]
![image_2024-12-22_182923098](https://github.com/user-attachments/assets/d1757517-bdab-4be0-968c-19b645f2461f)
That was the disc multiplied in all my drives
