### ISSUE TITLE
Crafter Proxys

### ISSUE THREAD

**Issue by Seanthebaker** [refinedmods/refinedstorage#3744]
### Describe your enhancement

This is for RS2 but adding in something like the Crafter Proxys addon to allow parallel crafting would be helpful for mass crafting

Original mod: https://www.curseforge.com/minecraft/mc-mods/refined-crafter-proxy

As a potential balance, making the primary Crafter be upgraded to a proxy possible one ends up with limited pattern slots, i.e. standard crafter 9 slots, whereas a proxy- possible one only has 3 slots but can spread across multiple machines

**Comment by jonatjano** [comment]
This is already a thing in RS1 and will be kept in RS2, just put the exact same pattern in multiple crafters and the load will be balanced between them

**Comment by raoulvdberge** [comment]
Refined storage already has Crafter chaining
