### ISSUE TITLE
Auto Crafting + Mekanism = Bad juju! (deletion and non removal of items from system)

### ISSUE THREAD

**Issue by dragonpc75** [refinedmods/refinedstorage#938]
#### Issue description:
Item not removable from storage network
item gets deleted
#### What happens:
found out today that auto crafting bins in Refined storage is a bad idea. you can craft it but then it doesn't let you have the item out of the grid, or any other way.. i don't know what is causing this there was no crash report or anything, it just won't let me take it out. i even tried an advanced bin, it is also stuck there now.. lol can't take them out. figured you'd at least want to know.
**Another bug i found, when in the crafting grid of Refined storage, you place a Bin with lets say 2k redstone in it, and shift click it to extract all the items, you get one stack and the bin disappears/disintegrates.. **
i am unsure whether this is on your side or on Refined storage's side, but i will post in both places to be safe.
i am posting here to let you be aware of this issue and hopefully find a resolution that works for both mods.
Here is a link to the Issue on Mekanism's Github.
https://github.com/aidancbrady/Mekanism/issues/4169

#### What you expected to happen:
my stuff not to get deleted especially 2.5k redstone blocks.. that hurt! LOL and to remove items from the storage network after autocrafting,
#### Steps to reproduce:
1.create a refined storage system using disk drives not blocks (not sure if it matters)
2.create crafters and patterns for just about everything that needs auto crafting from Refined storage lol,
3.add patterns for auto crafting Mekanism's Basic and Advanced Bin, and auto craft one, tada no removeiiii!
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:2185
- Refined Storage:1.2.18

Does this issue occur on a server? [yes/no]
Single player [no]
#### If a (crash)log is relevant for this issue, link it here:
no crash log generated, just will not give item no matter how many times i clicky clicky!! ;)
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
I'll look into this, but don't use Mekanism bins. They don't work well with anything, and cause issues with RS as well.

**Comment by thiakil** [comment]
> They don't work well with anything

What exactly do you mean by that? In terms of exposing them to external mods, they implement IItemHandler and should work fine.

**Comment by raoulvdberge** [comment]
They didnt use to.

**Comment by thiakil** [comment]
Not sure when it actually made it to a release, but https://github.com/aidancbrady/Mekanism/commit/536dab7239927d6e38c0918b4f56caa28bdaf46a

**Comment by raoulvdberge** [comment]
Hence my "didn't". You are responding on an issue from january.

**Comment by Mementh** [comment]
issue still happens.. best to use a crafter other than RS to make these.. :/

**Comment by raoulvdberge** [comment]
Works fine for me in 1.5.24; I can autocraft Mekanism bins and get them out.

**Comment by Ant95** [comment]
Fixed (1.12) by https://github.com/aidancbrady/Mekanism/commit/9c7164c0db3877538a6c525700b64d4353d20da5 on Mekanism end
And fixed (1.12) by https://github.com/raoulvdberge/refinedstorage/commit/d1c275d35eb89519e9c537db42851352d3b60146 on Refined Storage end
